SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LesseeNo__c</fullName>
        <description>Realtime update of both SFDC and RADAR whenever this value is changed in either system</description>
        <label>Lessee Number</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RSM_Onboarding__c</fullName>
        <description>Field to Store onboarding status of rydesmart account</description>
        <label>Onboarding</label>
        <picklist>
            <picklistValues>
                <fullName>Initiation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacted and Training Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trained</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Researching</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/RSM_Sales_Qus__c.object
<CustomObject>
    <description>To Store RydeSmart Pre-Launch Customer Information</description>
    <fields>
        <fullName>Account_Number__c</fullName>
        <description>Account Number</description>
        <label>Account Number</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Additional_Customer_RydeSmart_Locations__c</fullName>
        <label>Additional Customer RydeSmart Locations</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Additional_Pertinent_Information__c</fullName>
        <description>Additional, Pertinent Information:</description>
        <label>Additional, Pertinent Information:</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Are_there_any_shop_specific_information__c</fullName>
        <description>Are there any shop specific information you can share regarding this RydeSmart implementation and ongoing support?</description>
        <label>Are there any shop specific information</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CPU_Phone__c</fullName>
        <description>Customer Primary User - Phone</description>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>CPU_Title__c</fullName>
        <description>Customer Primary User - Title</description>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Can_the_RS_Account_Manager_contact_the_c__c</fullName>
        <description>Can the RS Account Manager contact the customer directly or do you require a warm introduction to the customer?</description>
        <label>Can the RS Account Manager contact the c</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>RSM Sales Questionnaires</relationshipLabel>
        <relationshipName>RSM_Sales_Questionnaires</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Industry_Business__c</fullName>
        <label>Customer Industry / Business</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <label>Customer Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>RSM Sales Questionnaires</relationshipLabel>
        <relationshipName>RSM_Sales_Questionnaires</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Customer_Primary_RydeSmart_Location__c</fullName>
        <label>Customer Primary RydeSmart Location:</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Primary_User__c</fullName>
        <label>Customer Primary User</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_RydeSmart_Owner__c</fullName>
        <label>Customer RydeSmart Owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Do_Some_or_All_Drivers_Use_the_Same_Truc__c</fullName>
        <description>Do Some or All Drivers Use the Same Truck Every Day?</description>
        <label>Do Some or All Drivers Use the Same Truc</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Does_the_customer_have_specific_ROI_goal__c</fullName>
        <description>Does the customer have specific ROI goals involving RydeSmart?</description>
        <label>Does the customer have specific ROI goal</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Email_Address__c</fullName>
        <description>Customer RydeSmart Owner - Email Address</description>
        <label>Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Customer Primary User - Email</description>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>How_does_the_customer_intend_to_use_Ryde__c</fullName>
        <description>How does the customer intend to use RydeSmart; will they be using any other logistic tools in conjunction with RydeSmart?</description>
        <label>How does the customer intend to use Ryde</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Long_Haul__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Long Haul</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <description>Sales Persons phone number</description>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>RS Customer Phone</description>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Please_describe_potential_for_additional__c</fullName>
        <description>Please describe potential for additional RydeSmart business, if any</description>
        <label>Please describe potential for additional</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Please_describe_the_customer_previous_Te__c</fullName>
        <description>Please describe the customer previous Telematics experience to include provider, if any</description>
        <label>Please describe the customer previous Te</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Please_describe_the_customer_s_normal_op__c</fullName>
        <description>Please describe the customer’s normal operation of their trucks to include route information, back hauls, etc.</description>
        <label>Please describe the customer’s normal op</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sales_Person_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sales Person Name</description>
        <label>Sales Person Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RSM_Sales_Questionnaires</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Short_Haul__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Short Haul</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Slip_Seating__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Slip Seating</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Team_Drivers__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Team Drivers</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Customer RydeSmart Owner - Title</description>
        <label>Title</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>RSM Sales Questionnaire</label>
    <nameField>
        <label>RSM Sales Qus</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RSM Sales Questionnaires</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/classes/RSMSalesQuestionnaire.cls
Public class RSMSalesQuestionnaire{

    Public RSM_Sales_Qus__c newRSMSQ {get;set;}
    public String accId{get;set;}
    public String taskId{get;set;}
    Account ac;
    public RSMSalesQuestionnaire(ApexPages.StandardController controller) {
        accId=Apexpages.currentpage().getParameters().get('accId');
        taskId=Apexpages.currentpage().getParameters().get('tId');
        
        newRSMSQ = (RSM_Sales_Qus__c)Controller.getrecord();
        if(accId != null){
            ac=[select Id,OwnerId,AccountNumber,LesseeNo__c,Owner.phone, RSM_Onboarding__c from Account where Id=:accId];
            List<RSM_Sales_Qus__c> lQuestion = [Select r.Title__c, r.Team_Drivers__c, r.SystemModstamp, 
                                                r.Slip_Seating__c, r.Short_Haul__c, r.Sales_Person_Name__c, 
                                                r.Please_describe_the_customer_s_normal_op__c, 
                                                r.Please_describe_the_customer_previous_Te__c, 
                                                r.Please_describe_potential_for_additional__c, 
                                                r.Phone__c, r.Phone_Number__c, r.Name, r.Long_Haul__c, 
                                                r.LastModifiedDate, r.LastModifiedById, r.IsDeleted, r.Id, 
                                                r.How_does_the_customer_intend_to_use_Ryde__c, r.Email__c, 
                                                r.Email_Address__c, r.Does_the_customer_have_specific_ROI_goal__c, 
                                                r.Do_Some_or_All_Drivers_Use_the_Same_Truc__c, r.Date__c, 
                                                r.Customer_RydeSmart_Owner__c, r.Customer_Primary_User__c, 
                                                r.Customer_Primary_RydeSmart_Location__c, r.Customer_Name__c, 
                                                r.Customer_Industry_Business__c,
                                                r.Contact__c, 
                                                r.Can_the_RS_Account_Manager_contact_the_c__c, r.CPU_Title__c, 
                                                r.CPU_Phone__c, r.Are_there_any_shop_specific_information__c, 
                                                r.Additional_Pertinent_Information__c, r.Additional_Customer_RydeSmart_Locations__c, 
                                                r.Account_Number__c From RSM_Sales_Qus__c r where Customer_Name__c =: ac.Id];
            if(lQuestion != null && lQuestion.size() > 0)
            {
                newRSMSQ = lQuestion[0];
            }
            else
            {
                //newRSMSQ.Account_Number__c=ac.AccountNumber;
                newRSMSQ.Account_Number__c=ac.LesseeNo__c;
                newRSMSQ.Customer_Name__c=ac.Id;
                newRSMSQ.Sales_Person_Name__c=ac.OwnerId;
                newRSMSQ.Date__c=System.today();
                newRSMSQ.Phone_Number__c=ac.Owner.phone;
            }
        }
        if(Apexpages.currentpage().getParameters().get('Id')!=null){
            newRSMSQ =[select Id,Additional_Customer_RydeSmart_Locations__c,Title__c,CPU_Title__c,Phone__c,CPU_Phone__c,
            Customer_RydeSmart_Owner__c,Customer_Primary_User__c,Customer_Name__c,
            Customer_Primary_RydeSmart_Location__c,
            Account_Number__c,Sales_Person_Name__c,Date__c,Phone_Number__c,
            Email_Address__c,Email__c,Customer_Industry_Business__c,Contact__c,
            Team_Drivers__c,Short_Haul__c,Slip_Seating__c,Long_Haul__c,
            Do_Some_or_All_Drivers_Use_the_Same_Truc__c,Please_describe_potential_for_additional__c,
            Please_describe_the_customer_s_normal_op__c,Can_the_RS_Account_Manager_contact_the_c__c,
            Please_describe_the_customer_previous_Te__c,How_does_the_customer_intend_to_use_Ryde__c,
            Does_the_customer_have_specific_ROI_goal__c,Are_there_any_shop_specific_information__c,
            Additional_Pertinent_Information__c
            
            from RSM_Sales_Qus__c Where Id=:Apexpages.currentpage().getParameters().get('Id')];    
        }
       
        
    }
        
    Public PageReference Save(){
        
        
        upsert newRSMSQ;
        if(taskId!=null){
        Task updateTask=new Task(Id=taskId,Status='Completed');
        update updateTask;
        }
        if(ac != null)
        {
            ac.RSM_Onboarding__c = 'Researching';
            update ac;
        }
        return new PageReference('/apex/RSM_Sales_Questionnaire_View?id='+newRSMSQ);
    }
}