SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LesseeNo__c</fullName>
        <description>Realtime update of both SFDC and RADAR whenever this value is changed in either system</description>
        <label>Lessee Number</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAM_Cust_ID__c</fullName>
        <description>Migrated data from SAM</description>
        <label>SAM_Cust_ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UVS_Type__c</fullName>
        <label>UVS Account Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Customer_Branch__c.object
<CustomObject>
    <description>Customer Branches at Ryder</description>
    <fields>
        <fullName>Customer_Branch_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Branch Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Customer_Branch</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Branch_Status__c</fullName>
        <description>Indicates whether a Customer/Branch has active vehicles.</description>
        <inlineHelpText>Indicates whether a Customer/Branch has active vehicles.</inlineHelpText>
        <label>Customer Branch Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Risk_Status__c</fullName>
        <label>Risk Status</label>
        <picklist>
            <picklistValues>
                <fullName>Growth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>At Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Status</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Ryder_Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field for Customer Branch to Ryder branch</description>
        <label>Ryder Branch</label>
        <referenceTo>Ryder_Branch__c</referenceTo>
        <relationshipLabel>Customer / Branch</relationshipLabel>
        <relationshipName>Customer_Branches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ryder_HQ_Account__c</fullName>
        <description>M/D field between Customer Branch and HQ Accounts</description>
        <label>Ryder HQ Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer / Branch</relationshipLabel>
        <relationshipName>Customer_Branches</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ext_customerbranch_id__c</fullName>
        <externalId>true</externalId>
        <label>Ext Cust Branch Id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Customer / Branch</label>
    <nameField>
        <label>Customer Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer / Branch</pluralLabel>
    <recordTypes>
        <fullName>UVS</fullName>
        <active>true</active>
        <description>Identity</description>
        <label>UVS</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Global_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Global Settings</label>
</CustomObject>

SFDC Automation/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ext_pipeline_id__c</fullName>
        <externalId>true</externalId>
        <label>Opportunity Number</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Ryder_Branch__c.object
<CustomObject>
    <description>Branches at Ryder</description>
    <fields>
        <fullName>Area_Code__c</fullName>
        <label>Area Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Branch_Code__c</fullName>
        <description>external ID</description>
        <externalId>true</externalId>
        <label>Branch Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Ryder Branch</label>
    <nameField>
        <label>Ryder Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ryder Branches</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/objects/UVS_Bill_of_Sale__c.object
<CustomObject>
    <description>Bill of Sale for UVS</description>
    <fields>
        <fullName>OPPORTUNITYID__c</fullName>
        <label>OPPORTUNITY NUMBER</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OPPORTUNITY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OPPORTUNITY ID</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>UVS_Bill_of_Sales</relationshipLabel>
        <relationshipName>UVS_Bill_of_Sales_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PROCESSED__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PROCESSED</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PROCESS_COMMENT__c</fullName>
        <label>PROCESS COMMENT</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SOLD_LOCATION_CODE__c</fullName>
        <label>SOLD_LOCATION_CODE</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UNIT_ID__c</fullName>
        <label>UNIT_ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UNIT_NUMBER__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UNIT NUMBER</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>UVS_Bill_of_Sales</relationshipLabel>
        <relationshipName>UVS_Bill_of_Sales</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bill of Sale</label>
    <nameField>
        <label>BillOfSale Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UVS_Bill_of_Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup on Accounts</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Availability__c</fullName>
        <label>Availability</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_of_Sale__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill of Sale</label>
        <referenceTo>UVS_Bill_of_Sale__c</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Branch_Code__c</fullName>
        <label>Branch Code</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CUSTOMER_BRANCH__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field for Customer Branch</description>
        <label>Customer Branch</label>
        <referenceTo>Customer_Branch__c</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Available_For_Sale__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This flag used to mark available for Used Vehicle Sale</description>
        <label>Is Available For Sale</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sold_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field to indicate whether a vehicle has been sold and not available in the inventory.</description>
        <inlineHelpText>Field to indicate whether a vehicle has been sold and not available in the inventory.</inlineHelpText>
        <label>Sold Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <externalId>true</externalId>
        <label>Unit Number</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <recordTypes>
        <fullName>UVS</fullName>
        <active>true</active>
        <description>Record Type for UVS Vehicles</description>
        <label>UVS</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/UVS_ProcessBillOfSales.cls
global with sharing class UVS_ProcessBillOfSales implements Database.Batchable<SObject>
{
    /*
        Declare a String for Query all the Bill Of Sales object records where Process is false.
        We need to process only those records where Process is false and 
        after process set these records as true so these never comes again
    */
    global String query = 'Select u.UNIT_ID__c, u.UNIT_NUMBER__c, u.OPPORTUNITYID__c, u.Id, '
                        + ' u.SOLD_LOCATION_CODE__c, u.PROCESS_COMMENT__c, u.OPPORTUNITY__c'
                        + ' From UVS_Bill_of_Sale__c u where'
                        + ' PROCESSED__c = false and OPPORTUNITYID__c != null and UNIT_ID__c != null';
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        // retrun the Query locator     
        return Database.getQueryLocator(query);
    }   
    global void execute(Database.BatchableContext BC, List<UVS_Bill_of_Sale__c> lUVS_Bill_of_Sale)
    {
        Boolean IsUpdatable = false;
        Set<String> sOppIds = new Set<String>();
        Set<String> sUnitIds = new Set<String>();
        Set<String> sRyderBranchIds = new Set<String>();
        Map<Id, Account> mAcc = new Map<Id, Account>();
        Map<String, Opportunity> mOpp = new Map<String, Opportunity>();
        Map<String, Vehicle__c> mVehicle = new Map<String, Vehicle__c>();
        Map<String, Ryder_Branch__c> mRyderBranch = new Map<String, Ryder_Branch__c>();
        Map<String, Customer_Branch__c> mCustomerBranch = new Map<String, Customer_Branch__c>();
        List<Opportunity> lOpp = new List<Opportunity>();
        List<Account> lAcc = new List<Account>();
        List<Vehicle__c> lVehicle = new List<Vehicle__c>();
        List<Customer_Branch__c> Customer_BranchUpdate = new List<Customer_Branch__c>();
        
        System.debug('---------lUVS_Bill_of_Sale-33->'+lUVS_Bill_of_Sale);
        // Get the UVS Record Type from Custom Settings for Customer Branch used in Creating Customer Branch
        String CustomerBranchRecordType = '';
        Global_Settings__c CustomerBranchRecordTypes = Global_Settings__c.getValues('11');
        // if the custom settings is not null then get the value from settings and out in a local variable
        if(CustomerBranchRecordTypes != null && CustomerBranchRecordTypes.Value__c != null && CustomerBranchRecordTypes.IsActive__c)
            CustomerBranchRecordType = CustomerBranchRecordTypes.Value__c;        
        System.debug('--------CustomerBranchRecordType-40->'+CustomerBranchRecordType);                
        /*
            Iterate all the Bill Of Sales records and create sets of Oportunity Number, Unit number and Locations
        */
        for(UVS_Bill_of_Sale__c Bill : lUVS_Bill_of_Sale)
        {
            System.debug('----Bill-46->'+Bill.Id);
            if(Bill.OPPORTUNITYID__c != null)
                sOppIds.add(Bill.OPPORTUNITYID__c);
            if(Bill.UNIT_ID__c != null)
                sUnitIds.add(Bill.UNIT_ID__c);
            if(Bill.SOLD_LOCATION_CODE__c != null)
            {
                if(String.valueOf(Bill.SOLD_LOCATION_CODE__c).length() == 4)
                    Bill.SOLD_LOCATION_CODE__c = '0'+Bill.SOLD_LOCATION_CODE__c;
                sRyderBranchIds.add(String.valueOf(Bill.SOLD_LOCATION_CODE__c));
            }
        }
        System.debug('---sRyderBranchIds-58->'+sRyderBranchIds);
        System.debug('---sUnitIds-59->'+sUnitIds);
        System.debug('---sOppIds-60->'+sOppIds);
        if(sOppIds.size() > 0)
        {
            Set<Id> sAccIds = new Set<Id>();
            /*
                Query all the Opportunities which are found in Bill Of Sales
            */
            List<Opportunity> lOppty = [select ext_pipeline_id__c, Id, StageName, AccountId 
                                        from Opportunity where ext_pipeline_id__c in : sOppIds 
                                        and AccountId != null];
            if(lOppty != null && lOppty.size() > 0)
            {
                mOpp = new Map<String, Opportunity>();
                for(Opportunity Opp : lOppty)
                {
                    mOpp.put(Opp.ext_pipeline_id__c, Opp);
                    sAccIds.add(Opp.AccountId);
                }
            }
            /*
                Query Account
            */
            if(sAccIds.size() > 0)
                mAcc = new Map<Id, Account>([Select a.LesseeNo__c, a.OwnerId, a.UVS_Type__c, Id, a.SAM_Cust_ID__c, 
                                            (Select RecordTypeId, Ext_Customerbranch_Id__c, Id, Ryder_Branch__c, Name, Ryder_Branch__r.Name, 
                                            Customer_Branch_Status__c, Ryder_Branch__r.Id, Ryder_Branch__r.Branch_Code__c 
                                            From Customer_Branches__r) 
                                            From Account a where Id IN : sAccIds]);
            /*
                create a collection of Customer Branch
            */
            for(String sAcc : sAccIds)
            {
                List<Customer_Branch__c> lCustomerBranch = mAcc.get(sAcc).Customer_Branches__r;
                for(Customer_Branch__c ObjCustomerBranch : lCustomerBranch)
                {
                    mCustomerBranch.put(ObjCustomerBranch.Ext_Customerbranch_Id__c, ObjCustomerBranch);
                }
            }
        }
        /*
            create a collection of Ryder Branch for creating a new Customer Branch if Customer Branch not found on Account
        */
        if(sRyderBranchIds.size() > 0)
        {
            List<Ryder_Branch__c> lRyderBranch = [Select r.Name, r.Id, r.Branch_Code__c, r.Area_Code__c 
                                                    From Ryder_Branch__c r where Branch_Code__c in : sRyderBranchIds];
            if(lRyderBranch != null && lRyderBranch.size() > 0)
            {
                for(Ryder_Branch__c Obj : lRyderBranch)
                    mRyderBranch.put(Obj.Branch_Code__c, Obj);
            }
        }
        if(sUnitIds.size() > 0)
        {
            mVehicle = new Map<String, Vehicle__c>();
            list<Vehicle__c> lVeh = [select Unit__c, Availability__c, Id, Is_Available_For_Sale__c, Account__c, Sold_Flag__c from Vehicle__c 
                                                where Unit__c IN : sUnitIds];
            if(lVeh != null && lVeh.size() > 0)
            {
                for(Vehicle__c Veh : lVeh)
                    mVehicle.put(Veh.Unit__c, Veh);
            }
        }
        System.debug('---mAcc-124->'+mAcc);
        System.debug('---mOpp-125->'+mOpp);
        System.debug('---mCustomerBranch-126->'+mCustomerBranch);
        System.debug('---mRyderBranch-127->'+mRyderBranch);
        System.debug('---mVehicle-128->'+mVehicle);
        
        Map<String, Customer_Branch__c> mCustomerBranchNew = new Map<String, Customer_Branch__c>();
        List<Customer_Branch__c> lCustomerBranchNew = new List<Customer_Branch__c>();
        List<Customer_Branch__c> lCustomerBranchUpd = new List<Customer_Branch__c>();
        List<UVS_Bill_of_Sale__c> lUVS_Bill_of_SaleRemains = new List<UVS_Bill_of_Sale__c>();
        // Get the UVS record Type id for Customer Branch
        for(UVS_Bill_of_Sale__c Bill : lUVS_Bill_of_Sale)
        {
            // Get the Opportunity and Vehicle records from Map 
            String sError = '';
            Opportunity Opp = mOpp.get(Bill.OPPORTUNITYID__c);
            Vehicle__c Vehicle = mVehicle.get(Bill.UNIT_ID__c);         
            Account Acc = null;
            System.debug('---Opp-142->'+Opp);
            System.debug('---mOpp-143->'+mOpp);
            System.debug('---Vehicle-144->'+Vehicle);
            System.debug('---mVehicle-145->'+mVehicle);
            // if we found the Opportunity and Vehicle then set the values in diff fields
            if(Opp != null && Vehicle != null)
            {
                Bill.OPPORTUNITY__c = Opp.Id;
                Acc = mAcc.get(Opp.AccountId);
                if(Acc.UVS_Type__c != 'Customer')
                {
                    Acc.UVS_Type__c = 'Customer';
                    lAcc.add(Acc);
                }
                if(Opp.StageName != 'Booked')
                {
                    Opp.StageName = 'Booked';
                    lOpp.add(Opp);
                }
                Vehicle.Is_Available_For_Sale__c = false;
                Vehicle.Sold_Flag__c = true;
                Vehicle.Availability__c = '';
                Vehicle.Bill_of_Sale__c = Bill.Id;
                Vehicle.Account__c = Opp.AccountId;
                // Now if in the Bill of Sales the Location Code is not null 
                // than check if this code match in current Customer Branch record or not
                if(Bill.SOLD_LOCATION_CODE__c != null)
                {
                    String sLocation = String.valueOf(Bill.SOLD_LOCATION_CODE__c);
                    Ryder_Branch__c ObjRyderB = mRyderBranch.get(sLocation);
                    //String sCode = Acc.SAM_Cust_ID__c + '-' + ObjRyderB.Branch_Code__c + '-' + ObjRyderB.Name;
                    String sCode = '';
                    if(ObjRyderB != null && ObjRyderB.Branch_Code__c != null)
                    {
                        sCode = (Id)Acc.Id + '_' + ObjRyderB.Branch_Code__c;
                        // If Customer Branch matchs than set the Vehicle to that Branch
                        if(mCustomerBranch.get(sCode) != null)
                        {
                            Customer_Branch__c CustB = mCustomerBranch.get(sCode);
                            Vehicle.Customer_Branch__c = CustB.Id;
                            lVehicle.add(Vehicle);
                            if(CustB.Customer_Branch_Status__c != 'Active')
                            {
                                CustB.Customer_Branch_Status__c = 'Active';
                                lCustomerBranchUpd.add(CustB);
                            }
                            if(CustB.RecordTypeId != CustomerBranchRecordType)
                            {
                            	CustB.RecordTypeId = CustomerBranchRecordType;
                            	Customer_BranchUpdate.add(CustB);
                            }
                        }
                        else // If Customer Branch matchs doesn't found than create a new Customer Branch and add in a collection
                        {
                        	String sName = '';
                        	if(Acc.LesseeNo__c != null)
                        		sName = Acc.LesseeNo__c + ' - ';
                        	if(ObjRyderB.Branch_Code__c != null)
                        		sName += ObjRyderB.Branch_Code__c + ' - ';
                        	sName += ObjRyderB.Name;                        	
                            // Create new Customer Branches
                            Customer_Branch__c Customer_Branch = new Customer_Branch__c();
                            Customer_Branch.Name = sName;
                            Customer_Branch.Ryder_Branch__c = ObjRyderB.Id;
                            Customer_Branch.Ryder_HQ_Account__c = Acc.Id;
                            Customer_Branch.ext_customerbranch_id__c = sCode;
                            Customer_Branch.Risk_Status__c = 'No Status';
                            Customer_Branch.Customer_Branch_Owner__c = Acc.OwnerId;
                            Customer_Branch.RecordTypeId = CustomerBranchRecordType;
                            mCustomerBranchNew.put(sCode, Customer_Branch);
                            lUVS_Bill_of_SaleRemains.add(Bill);
                        }
                        // Set the Bill of Sales Process field to True to avaid this record to process next time
                        // Set the Bill of Sales Process Comment to blank
                        Bill.PROCESSED__c = true;
                        Bill.PROCESS_COMMENT__c = '';
                        Bill.UNIT_NUMBER__c = Vehicle.id;
                    }
                    else
                    {
                        Bill.PROCESS_COMMENT__c = 'Ryder Branch not found!';
                    }
                }
                else
                {
                    Bill.PROCESS_COMMENT__c = 'LOCATION CODE is not found!';
                }
            }
            else
            {
                Bill.PROCESS_COMMENT__c = 'Opportunity ID or Vehicle Ids are not found!';
            }
        }
        
        // If there are records found in the collection for Customer Branch than insert these and align the Vehicle to correct Customer Branch
        if(mCustomerBranchNew.size() > 0)
        {
            insert mCustomerBranchNew.values();
            for(Customer_Branch__c ObjCustomerBranch : mCustomerBranchNew.values())
            {
            	mCustomerBranch.put(ObjCustomerBranch.ext_customerbranch_id__c, ObjCustomerBranch);
            }
            for(UVS_Bill_of_Sale__c Bill : lUVS_Bill_of_SaleRemains)
            {
                Opportunity Opp = mOpp.get(Bill.OPPORTUNITYID__c);
                Vehicle__c Vehicle = mVehicle.get(Bill.UNIT_ID__c);
                Account Acc = null;                
                String sLocation = String.valueOf(Bill.SOLD_LOCATION_CODE__c);
                Ryder_Branch__c ObjRyderB = mRyderBranch.get(sLocation);
                
                if(Opp != null && Vehicle != null && ObjRyderB != null)
                {
                	Vehicle.Is_Available_For_Sale__c = false;
	                Vehicle.Sold_Flag__c = true;
	                Vehicle.Availability__c = '';
	                Vehicle.Account__c = Opp.AccountId;
	                Vehicle.Bill_of_Sale__c = Bill.Id;                
                    Acc = mAcc.get(Opp.AccountId);
                    if(Bill.SOLD_LOCATION_CODE__c != null && Acc != null)
                    {
                        String sCode = (Id)Acc.Id + '_' + ObjRyderB.Branch_Code__c;
                        if(mCustomerBranch.get(sCode) != null)
                        {
                            Vehicle.Customer_Branch__c = mCustomerBranch.get(sCode).Id;
                            lVehicle.add(Vehicle);
                        }
                    }
                }
            }
        }
        
        SavePoint SavePointObj = Database.setSavePoint();
        system.debug('-------lAcc-273->'+lAcc);
        system.debug('-------lOpp-274->'+lOpp);
        system.debug('-------lVehicle-275->'+lVehicle);
        system.debug('-------lCustomerBranchUpd-276->'+lCustomerBranchUpd);
        system.debug('-------lUVS_Bill_of_Sale-277->'+lUVS_Bill_of_Sale);
        system.debug('-------Customer_BranchUpdate-278->'+Customer_BranchUpdate);
        try
        {
            // Update Account, Opportunity, Vehicle and Bill of sales records.
            if(lAcc.size() > 0)
                update lAcc;
            if(lOpp.size() > 0)
                update lOpp;
            if(lVehicle.size() > 0)
                update lVehicle;
            if(lCustomerBranchUpd.size() > 0)
                update lCustomerBranchUpd;
            if(Customer_BranchUpdate.size() > 0)
            	update Customer_BranchUpdate;
            update lUVS_Bill_of_Sale;
        }
        catch(Exception Ex)
        {
            Database.rollback(SavePointObj);
            // get the email address
            String sEmailAddress = '';
            Global_Settings__c EmailAddress = Global_Settings__c.getValues('12');
            // if the custom settings is not null then get the value from settings and out in a local variable
            if(EmailAddress != null && EmailAddress.IsActive__c)
                sEmailAddress = EmailAddress.Value__c;        
            system.debug('-------sEmailAddress-303->'+sEmailAddress);
            if(sEmailAddress != '')
            {
                // Send Email to dev resource if there is any issue.
                Messaging.SingleEmailMessage MailObj = new Messaging.SingleEmailMessage();
                MailObj.setToAddresses(new String[] {sEmailAddress});
                MailObj.setSubject('Exception got in UVS_ProcessBillOfSales Batch');
                MailObj.setPlainTextBody(Ex.getmessage());
                system.debug('-------MailObj-310->'+MailObj);
                Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{MailObj});
            }
        }
    }
    global void finish(Database.BatchableContext BC)
    {
        // there is nothing needs to be done after the process completes
    }
}