SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ADDR_ID__c</fullName>
        <description>Needed for migration purposes.</description>
        <label>Address ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Alias_Name__c</fullName>
        <description>Also know as name for accounts (1 OR More AKAs)</description>
        <label>Other Names</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BAD_ADDRESS_BIT__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bad Address Bit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BAD_ADDR_CD__c</fullName>
        <description>Flag used to mark an address as BAD</description>
        <label>Bad Address CD</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BAD_ADDR_DATE__c</fullName>
        <description>Date when the address was marked bad</description>
        <label>Bad Address Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BAD_ADDR_REASON__c</fullName>
        <description>Reason for marking an address BAD</description>
        <label>Bad Address Reason</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>BUSINESS_STATUS__c</fullName>
        <description>CURRENT OR TARGET BUSINESS (For customers with multiple locations).   Lookup tb_REF_CODE with ref_code_type &apos;LBS&apos; to the corr. reasons.</description>
        <label>Business Status</label>
        <picklist>
            <picklistValues>
                <fullName>Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Target Business</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CO_ANNSRY__c</fullName>
        <description>Company Anniversary</description>
        <label>Inception Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CO_OWNER_ID__c</fullName>
        <label>Co Owner ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CO_RYDER_ANNSRY__c</fullName>
        <description>Ryder Customer Inception Date - ACS Tables</description>
        <label>Company Ryder Anniversary</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CO_SEGMENT__c</fullName>
        <description>RYDER Specific Company Segment, Lookup code from TB_REF_CODE, REF TYPE CODE = CMS.</description>
        <label>Market Segment</label>
        <picklist>
            <picklistValues>
                <fullName>0 - Three trucks or less</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>00 - Three Trucks or Less (Bargain Hunter)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1 - Brgn hunters Med fl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 - Cap builders Med fl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - Time-crit del Med fl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 - Brgn hunters Low den fl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5  - Cap bld Low den fl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6 - Time-crit del Low den fl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7 -  Brgn hunters Lrg fl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8 - Sophisticated 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9 - Sophisticated 2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CUST_REPAIR_LIMIT__c</fullName>
        <description>Customer Repair Limit</description>
        <label>Customer Repair Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Central_Decisionmaking__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Select this if the sales decisions are made at the National / Parent Account level.</inlineHelpText>
        <label>Central Decisionmaking</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CompanyTypeID__c</fullName>
        <label>Company Type</label>
        <picklist>
            <picklistValues>
                <fullName>1 Corporation</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2 Sub S Corp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 Partnership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 Sole Proprietorship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5 Tax Exempt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6 Government Entity</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CustProspectID__c</fullName>
        <description>Customer Prospect ID</description>
        <externalId>true</externalId>
        <label>Customer Prospect ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CustomerTypeID__c</fullName>
        <description>Customer type indicating FMS or RIL. Realtime update of both SFDC and RADAR whenever this value is changed in either system.      Question: Does RADAR care about this or any changes to this field?</description>
        <label>Customer Type</label>
        <picklist>
            <picklistValues>
                <fullName>FMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RIL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FMS Rental</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DB_Loc_Type__c</fullName>
        <description>D&amp;B lassification of customer locations</description>
        <label>D&amp;B Location Type</label>
        <picklist>
            <picklistValues>
                <fullName>Branch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distribution Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Division</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Headquarters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing/Assembly Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single Location</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subsidiary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subsidiary Undefined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transportation Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warehousing Center</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DUNS_HQ__c</fullName>
        <description>DUNS Headquarters Number</description>
        <label>DUNS HQ #</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Domestic_Ultimate_DUNS__c</fullName>
        <description>Domestic Ultimate DUNS Number</description>
        <label>Domestic Ultimate DUNS #</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Equifax_City__c</fullName>
        <label>Equifax City</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Equifax_Country__c</fullName>
        <label>Equifax Country</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Equifax_Email__c</fullName>
        <label>Equifax Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Equifax_Fax__c</fullName>
        <label>Equifax Fax</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Equifax_No__c</fullName>
        <description>To store the EquifaxNo</description>
        <label>Equifax No</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Equifax_Phone__c</fullName>
        <label>Equifax Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Equifax_State__c</fullName>
        <label>Equifax State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Equifax_Street1__c</fullName>
        <label>Equifax Street1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Equifax_Street2__c</fullName>
        <label>Equifax Street2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Equifax_Zip_Postal_Code__c</fullName>
        <label>Equifax Zip/Postal Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FormerCustomer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to indicate customer is current or former</description>
        <label>Former Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Global_Ultimate_DUNS__c</fullName>
        <description>Global Ultimate DUNS NUmber</description>
        <label>Global Ultimate DUNS #</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LOC_ID__c</fullName>
        <description>Needed for migration purposes.</description>
        <label>Location ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legal_Entity_Address_City__c</fullName>
        <label>Legal Entity Address City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legal_Entity_Address_Country__c</fullName>
        <label>Legal Entity Address Country</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legal_Entity_Address_State_Province__c</fullName>
        <label>Legal Entity Address State/Province</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legal_Entity_Address_Street__c</fullName>
        <label>Legal Entity Address Street</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legal_Entity_Address_Zip_Postal_Code__c</fullName>
        <label>Legal Entity Address Zip/Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legal_Equifax_No__c</fullName>
        <label>Legal Equifax No</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legal_Site_Duns__c</fullName>
        <description>Shadow Field for integration to Radar - Can be editable by Admins and Credit</description>
        <label>Legal Site Duns #</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LesseeNo__c</fullName>
        <description>Realtime update of both SFDC and RADAR whenever this value is changed in either system</description>
        <label>Lessee Number</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NATL_RNTL_CUST_ID__c</fullName>
        <description>National Rental Customer Account ID. Pulled from FIS</description>
        <label>National Rental #</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_NUMBER__c</fullName>
        <description>PO Number</description>
        <label>PO Number</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_2__c</fullName>
        <description>Secondary Account Phone number</description>
        <label>Phone 2</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Ryder_Specific_Loc_Type__c</fullName>
        <description>Ryder classification of customer locations</description>
        <label>Ryder Specific Location Type</label>
        <picklist>
            <picklistValues>
                <fullName>Branch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distribution Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Division</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Headquarters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing/Assembly Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subsidiary Undefined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transportation Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warehousing Center</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>STATUS_ACTIVE__c</fullName>
        <description>Customer status to control visibility.</description>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Site_Duns__c</fullName>
        <description>Site Number</description>
        <label>Site Duns #</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Top10Account__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to indicate if it is a top 10 account or not.</description>
        <label>Top 10 Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>addr_verified_date__c</fullName>
        <label>Address Verified Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/classes/insertUpdateCompany.cls
/**
* 
*   insertUpdateCompany trigger class insert/update if the values for the insert/update company has 
*   changed and notifies and updates accounts using webservice
*
*   Author           |Author-Email                      |Date       |Comment
*   -----------------|----------------------------------|-----------|--------------------------------------------------
*   Vishal Patel     |vishal@comitydesigns.com          |11.24.2010 |First draft
*
*/
public with sharing class insertUpdateCompany 
{

    // Insert the companies using future method
    @Future(callout=true)
    public static void insertCompanyOnRyder_future(Set<String> dunsNumbers, Map<String, String> mapParentDuns, String accountId)
    {
        insertCompanyOnRyder(dunsNumbers, mapParentDuns, accountId);        
    }

    // Insert the company on ryder and update the accounts
    public static void insertCompanyOnRyder(Set<String> dunsNumbers, Map<String, String> mapParentDuns, String accountId)
    {
        
        Account account = new Account();
        // Map the accounts 
        Map<String, Account> accounts = new Map<String, Account>();
        // Get the accounts to process 
        Account[] processAccounts = [SELECT a.addr_verified_date__c, a.Website, a.Type, a.Top10Account__c,a.Site_Duns__c, a.ShippingStreet, a.ShippingState, 
                            a.ShippingPostalCode, a.ShippingCountry, a.ShippingCity, a.STATUS_ACTIVE__c, a.Ryder_Specific_Loc_Type__c, a.RecordTypeId, a.Phone_2__c, 
                            a.Phone, a.ParentId, a.PO_NUMBER__c, a.OwnerId, a.NumberOfEmployees, a.Name, a.NATL_RNTL_CUST_ID__c, a.MasterRecordId, a.LesseeNo__c, 
                            a.Legal_Entity_Address_Zip_Postal_Code__c, a.Legal_Entity_Address_Street__c, a.Legal_Entity_Address_State_Province__c, a.Legal_Entity_Address_Country__c, 
                            a.Legal_Entity_Address_City__c, a.LastActivityDate, a.LOC_ID__c, a.Industry, a.Id, a.Global_Ultimate_DUNS__c, a.FormerCustomer__c, a.Fax, 
                            a.Domestic_Ultimate_DUNS__c, a.Description, a.DUNS_HQ__c, a.DB_Loc_Type__c, a.CustomerTypeID__c, a.CustProspectID__c, a.CurrencyIsoCode, 
                            a.Central_Decisionmaking__c, a.CUST_REPAIR_LIMIT__c, a.CO_SEGMENT__c, a.CO_RYDER_ANNSRY__c, a.CO_OWNER_ID__c, a.CO_ANNSRY__c, a.BillingStreet, 
                            a.BillingState, a.BillingPostalCode, a.BillingCountry, a.BillingCity, a.BUSINESS_STATUS__c, a.BAD_ADDR_REASON__c, a.BAD_ADDR_DATE__c, 
                            a.BAD_ADDR_CD__c, a.BAD_ADDRESS_BIT__c, a.AnnualRevenue, a.Alias_Name__c, a.ADDR_ID__c, RecordType.Name, a.SIC,
                            a.CompanyTypeID__c, a.Legal_Site_Duns__c, a.Equifax_No__c, a.Legal_Equifax_No__c, a.Equifax_Street1__c, a.Equifax_Street2__c, a.Equifax_City__c, 
                            a.Equifax_State__c, a.Equifax_Country__c, a.Equifax_Zip_Postal_Code__c, a.Equifax_Phone__c, a.Equifax_Fax__c, a.Equifax_Email__c, a.Equifax_Company_Name__c
                            FROM Account a WHERE a.Site_Duns__c IN: dunsNumbers];
                            
        // Loop through the accounts and call out create company                            
        for (Account acct : processAccounts)
        {
            accounts.put(acct.Site_Duns__c, acct);
            if (acct.Id == accountId)
                account = acct;
        }
        //System.debug('Accounts - '+accounts);
        // Call the common function to create the account on ryder for the primary HQ for the branch
        CommonFunctions commonFunctions = new CommonFunctions();
        boolean usePhysicalAddr = false;
        if (account.id != null) {
            usePhysicalAddr = true;
        }
        Integer companyId = commonFunctions.createAccountsOnRyder(account, usePhysicalAddr, false);
        System.debug('companyId - ' + companyId);
            
        // Check if the record was created on Ryder
        if (companyId != -1)
        {
            System.debug('Accounts to update - '+accounts);

            // Set the parent id for the child and ryder id for the parent
            List<Account> acctsToUpdate = new List<Account>();
            for(Account newAcct : processAccounts)
            {
                System.debug('newAcct - '+newAcct);
                            
                // Check if the site duns and hq duns is the same and presume it is headquarters
                if (newAcct.Site_Duns__c == newAcct.DUNS_HQ__c)
                {
                    if (newAcct.CustProspectID__c != String.valueOf(companyId))
                    {
                        newAcct.CustProspectID__c = String.valueOf(companyId);
                        acctsToUpdate.add(newAcct);
                    }
                }
                else
                {
                    // Check if the parent exist for the child duns
                    if (mapParentDuns.containsKey(newAcct.DUNS_HQ__c))
                    {
                        // Get the parent account and save it in the child record
                        if (accounts.containsKey(mapParentDuns.get(newAcct.DUNS_HQ__c)))
                        {
                            newAcct.ParentId = accounts.get(mapParentDuns.get(newAcct.DUNS_HQ__c)).Id;
                            acctsToUpdate.add(newAcct);
                        }
                    }
                }
            }    
            // Update the account 
            if (acctsToUpdate.size()>0)
            {
                RyderGlobalVariables.UPDATE_ACCOUNT_TRIGGER = false;
                update acctsToUpdate;
            }
        }
    }

    // Update the companies using future method
    @Future(callout=true)
    public static void updateCompanyOnRyder_future(Set<Id> accountIds)
    {
        updateCompanyOnRyder(accountIds);       
    }
    
    // Update Companies
    public static void updateCompanyOnRyder(Set<Id> accountIds)
    {
        // Accounts that we need to update
        Account[] accounts = [SELECT Name, Type, LesseeNo__c, Industry, Site_Duns__c, Legal_Site_Duns__c, DUNS_HQ__c, Domestic_Ultimate_DUNS__c, 
                              Global_Ultimate_DUNS__c, NATL_RNTL_CUST_ID__c, LastModifiedBy.Name, Equifax_No__c, Legal_Equifax_No__c, Equifax_Street1__c, Equifax_Street2__c, Equifax_City__c, Equifax_State__c, Equifax_Country__c, 
        					  Equifax_Zip_Postal_Code__c, Equifax_Phone__c, Equifax_Fax__c, Equifax_Email__c, Equifax_Company_Name__c FROM Account WHERE Id IN :accountIds];
        
        // Create criteria to send request to Ryder WSDL
        updateCompany.CompanyUpdateRequest requestCriteria = new updateCompany.CompanyUpdateRequest();

        // Go through the accounts and update using the soap method
        for (Account account : accounts)
        {
            requestCriteria.CompanyName = account.Name;
            //requestCriteria.CompanyTypeId = dbAccount.Type;
            requestCriteria.LesseNum = account.LesseeNo__c;
            requestCriteria.SiteDuns = account.Legal_Site_Duns__c;
            requestCriteria.HQDuns = account.DUNS_HQ__c;
            requestCriteria.UltimateDuns = account.Domestic_Ultimate_DUNS__c;
            //requestCriteria.IndustryTypeId = dbAccount.Industry;
            requestCriteria.SICCode = account.Industry;
            //requestCriteria.Id = Integer.valueOf(account.CustProspectID__c);
            //requestCriteria.NationalCustFlag = account.NATL_RNTL_CUST_ID__c;
            requestCriteria.LastUpdateUser = account.LastModifiedBy.Name;

			//08/28/2012 Saad - added fields for Equifax            
            requestCriteria.EquifaxNo = account.Equifax_No__c;
            requestCriteria.LegalEquifaxNo = account.Legal_Equifax_No__c;
            requestCriteria.EquifaxStreet1 = account.Equifax_Street1__c;
            requestCriteria.EquifaxStreet2 = account.Equifax_Street2__c;
            requestCriteria.EquifaxState = account.Equifax_State__c;
            requestCriteria.EquifaxCity = account.Equifax_City__c;
            requestCriteria.EquifaxCountry = account.Equifax_Country__c;
            requestCriteria.EquifaxZipCode = account.Equifax_Zip_Postal_Code__c;
            requestCriteria.EquifaxPhone = account.Equifax_Phone__c;
            requestCriteria.EquifaxFax = account.Equifax_Fax__c;
            requestCriteria.EquifaxEmail = account.Equifax_Email__c;
            requestCriteria.EquifaxCompanyName = account.Equifax_Company_Name__c;

            UpdateCompany.UpdateCompanySoap companySoap = new UpdateCompany.UpdateCompanySoap();
            companySoap.timeout_x = RyderGlobalVariables.WS_TIMEOUT;
            companySoap.endpoint_x = RyderGlobalVariables.RYDER_WS_ENDPOINT + RyderGlobalVariables.UPDATE_COMPANIES;
            UpdateCompany.CRMCredential credential = new UpdateCompany.CRMCredential();
            //credential.UserName = UserInfo.getUserName();
            //credential.Password = 'passw0rd';
            //credential.SecurityToken = 'x9hJscMUilGopqHFAZETe0Glm';
            
            system.debug('requestCriteria.LegalEquifaxNo = ' + requestCriteria.LegalEquifaxNo);  
            system.debug('account.Legal_Equifax_No__c = ' + account.Legal_Equifax_No__c);
            
            credential.UserName = '';
            credential.Password = '';
            credential.SecurityToken = '';
            try
            {
                // Make a soap request
                UpdateCompany.DCCompanyUpdate updateCompanyInfo = companySoap.ProcessRequest(credential, requestCriteria);
                
                //Check if there was a success
                if (updateCompanyInfo != null)
                {
                    String companyId = String.valueOf(updateCompanyInfo.ID);        
                }
            }
            catch(Exception ex)
            {
                System.debug('Error while updating the company: ' + ex.getMessage());
            }
        }
                
    }
}