SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LesseeNo__c</fullName>
        <description>Realtime update of both SFDC and RADAR whenever this value is changed in either system</description>
        <label>Lessee Number</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RSM_Billing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Billing</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/RSM_Contract__c.object
<CustomObject>
    <description>Object to store RydeSmart Contract details</description>
    <fields>
        <fullName>Document_Type_Name__c</fullName>
        <label>Document Type Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Lessee_Email__c</fullName>
        <label>Lessee Email</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lessee__c</fullName>
        <label>Lessee</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status_Name__c</fullName>
        <label>Status Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>RSM Contract</label>
    <nameField>
        <label>RSM Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RSM Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC Automation/src/classes/RSM_AccountContractsTest.cls
@isTest
private class RSM_AccountContractsTest {
	
	static testmethod void test_searchAllContracts()
	{
		RSMCreateTestData.GetCustomSettingsRecord();
		
		Account Ac=new Account ();
	    Ac.RSM_Billing__c=true;
	    Ac.Name ='Test';
	    Ac.LesseeNo__c = '0000001';
	    insert Ac;
	    
	    RSM_Contract__c RSM_Con=new RSM_Contract__c();
	    RSM_Con.Name = '123';
	    RSM_Con.Document_Type_Name__c = 'FSL';
	    RSM_Con.Effective_Date__c = date.today();
	    RSM_Con.Lessee__c = '0000001';
	    RSM_Con.Lessee_Email__c = 'test@test.com';
	    RSM_Con.Status_Name__c = 'Approved';
	    insert RSM_Con; 
		
		ApexPages.StandardController stdController = new ApexPages.StandardController(Ac);
		
		RSMAccountContracts rsmAC = new RSMAccountContracts(stdController);
		rsmAC.getPageAllContracts();
		rsmAC.changeOrder();
		rsmAC.sortOrder = 'DESC';
		rsmAC.changeOrder();
	}
	
}