SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>RSM_Account_Status__c</fullName>
        <label>Account Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RSM_Plus1_Total_Unit__c</fullName>
        <label>Plus1 Total Unit</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RSM_Plus_Total_Unit__c</fullName>
        <label>Plus Total Unit</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RSM_STD_Total_Unit__c</fullName>
        <label>STD Total Unit</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup on Accounts</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RSM_Service_Level__c</fullName>
        <description>Displays Service Level of the vehicle</description>
        <label>Service Level</label>
        <picklist>
            <picklistValues>
                <fullName>Plus 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>STD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RSM__c</fullName>
        <description>Displays RydeSmart contract status</description>
        <label>RS Contract Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Printed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to SSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by SSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deleted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/RSM_RollUpSummaryVehicles_Helper.cls
public with sharing class RSM_RollUpSummaryVehicles_Helper
{
	public Static void ProcessVehicleHistory(List<Vehicle__History> scope)
	{
		String sRSMValue = 'Approved';
        Set<String> sAccIds = new Set<String>();
        for(Vehicle__History vehcle : scope)
        {
            sAccIds.add(vehcle.Parent.Account__c);            
        }
        if(Test.isRunningTest())
        {
        	Set<ID> sVehIds = new Set<ID>();
        	for(Vehicle__History vehcle : scope)
        		sVehIds.add(vehcle.ParentId);
        	if(sVehIds.size() > 0)
        	{
        		List<Vehicle__c> lVeh = [Select Account__c from Vehicle__c where Id in: sVehIds];
        		for(Vehicle__c Veh : lVeh)
        			sAccIds.add(Veh.Account__c);  
        	}
        }
        
        if(sAccIds.size() > 0)
        {
            List<Account> lAccount = [select Id, RSM_Plus1_Total_Unit__c, RSM_Plus_Total_Unit__c, RSM_Account_Status__c,  
                                            RSM_STD_Total_Unit__c from Account where Id IN : sAccIds];
            if(lAccount != null && lAccount.size() > 0)
            {
                List<vehicle__c> lVehicle = [select Id, RSM__c, RSM_Service_Level__c, Account__c 
                                                from vehicle__c where RSM__c =: sRSMValue and 
                                                Account__c in : sAccIds];
                for(Account Acc : lAccount)
                {
                    if(lVehicle != null && lVehicle.size() > 0)
                    {                   
                        Boolean IsChanged = false;
                        Integer iPlus1 = 0;
                        Integer iPlus = 0;
                        Integer iStd = 0;
                        for(vehicle__c Vehcle : lVehicle)
                        {
                            if(Acc.Id == Vehcle.Account__c)
                            {
                                if(Vehcle.RSM_Service_Level__c == 'Plus 1')
                                {
                                    iPlus1++;
                                    IsChanged = true;
                                }
                                if(Vehcle.RSM_Service_Level__c == 'Plus')
                                {
                                    IsChanged = true;
                                    iPlus++;
                                }
                                if(Vehcle.RSM_Service_Level__c == 'STD')
                                {
                                    IsChanged = true;
                                    iStd++;
                                }
                            }
                        }
                        Acc.RSM_Plus1_Total_Unit__c = iPlus1;
                        Acc.RSM_Plus_Total_Unit__c = iPlus;
                        Acc.RSM_STD_Total_Unit__c = iStd;
                        if(IsChanged)
                        {
                            Acc.RSM_Account_Status__c = 'Customer';
                        }
                        else
                        {
                        	Acc.RSM_Account_Status__c = 'Prospect';
                        }
                    }
                    else
                        Acc.RSM_Account_Status__c = 'Prospect';
                }       
                update lAccount;    
            }
        } 
	}
}