SFDC Automation/src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Vendor account record type for legal requests</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup on Accounts</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ask_Price__c</fullName>
        <label>Ask Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NBV__c</fullName>
        <label>Book Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>RSM_Demo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Demo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RSM_From__c</fullName>
        <label>From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RSM_To__c</fullName>
        <label>To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RSM__c</fullName>
        <description>Displays RydeSmart contract status</description>
        <label>RS Contract Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Printed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to SSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by SSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deleted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Take_Price__c</fullName>
        <label>Take Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/MiscTest.cls
@isTest(seealldata = true)
private class MiscTest {
    static testMethod void testRyderException(){
        RyderException re = new RyderException('Test Error', 'tst', 'tst', 'tst');
        RDatacom_additionalinformation rai = new RDatacom_additionalinformation();
        rai.name = 'test';
        rai.value = 'test';
        RDatacom_CompanyDUNSResponse rcd = new RDatacom_CompanyDUNSResponse();
        rcd.matchEngine = 'tst';
        rcd.rule = 'tst';
        rcd.size = 0;
        rcd.success = true;
        RDatacom_DUNSMatchRecords rdm = new RDatacom_DUNSMatchRecords();
        rdm.fieldDiffs = new List<RDatacom_fieldDiffs>();
        rdm.matchConfidence = 'test';
        RDatacom_Errors rde = new RDatacom_Errors();
        rde.statuscode = 'test';
        rde.message = 'test';
        System.assert(true);
    }
    
    static testMethod void testCearteTaskIfApprovedAndInDemo() {
        Account acc = TestUtilUVS.createAccount('Vendor', 'FMS', true);
        List<Vehicle__c> listVehicles = new List<Vehicle__c>();
        Vehicle__c veh1 = new Vehicle__c();
        veh1.Name = '1';
        veh1.Account__c = acc.Id;
        veh1.Ask_Price__c = 11;
        veh1.Take_Price__c = 11;
        veh1.NBV__c = 11;
        veh1.RSM_Demo__c = true;
        veh1.RSM_From__c = Date.today();
        veh1.RSM_To__c = Date.today().addDays(5);
        veh1.RSM__c = 'Approved';
        insert veh1;
        listVehicles.add(veh1);
        
        Vehicle__c veh2 = new Vehicle__c();
        veh2.Name = '2';
        veh2.Account__c = acc.Id;
        veh2.Ask_Price__c = 11;
        veh2.Take_Price__c = 11;
        veh2.NBV__c = 11;
        veh2.RSM_Demo__c = null;
        veh2.RSM_From__c = Date.today();
        veh2.RSM_To__c = Date.today().addDays(5);
        veh2.RSM__c = 'Denied';
        
        Map<Id, Vehicle__c> mapVehicles = new Map<Id, Vehicle__c>();
        mapVehicles.put(veh1.Id, veh2);
        RSMManageVehicle_Helper.CearteTaskIfApprovedAndInDemo(listVehicles, mapVehicles);
    }
    
    static testMethod void testUpdateAccount() {
        Account acc = TestUtilUVS.createAccount('Vendor', 'FMS', true);
        List<Vehicle__c> listVehicles = new List<Vehicle__c>();
        Vehicle__c veh1 = new Vehicle__c();
        veh1.Name = '1';
        veh1.Account__c = acc.Id;
        veh1.Ask_Price__c = 11;
        veh1.Take_Price__c = 11;
        veh1.NBV__c = 11;
        veh1.RSM_Demo__c = true;
        veh1.RSM_From__c = Date.today();
        veh1.RSM_To__c = Date.today().addDays(5);
        veh1.RSM__c = 'Approved';
        insert veh1;
        listVehicles.add(veh1);
        
        Vehicle__c veh2 = new Vehicle__c();
        veh2.Name = '2';
        veh2.Account__c = acc.Id;
        veh2.Ask_Price__c = 11;
        veh2.Take_Price__c = 11;
        veh2.NBV__c = 11;
        veh2.RSM_Demo__c = null;
        veh2.RSM_From__c = Date.today();
        veh2.RSM_To__c = Date.today().addDays(5);
        veh2.RSM__c = 'Denied';
        
        Map<Id, Vehicle__c> mapVehicles = new Map<Id, Vehicle__c>();
        mapVehicles.put(veh1.Id, veh2);
        RSMManageVehicle_Helper.UpdateAccount(listVehicles, mapVehicles);
    }
    
    static testMethod void testUpdateAccountOnExpirationDateChange() {
        Account acc = TestUtilUVS.createAccount('Vendor', 'FMS', true);
        List<Vehicle__c> listVehicles = new List<Vehicle__c>();
        Vehicle__c veh1 = new Vehicle__c();
        veh1.Name = '1';
        veh1.Account__c = acc.Id;
        veh1.Ask_Price__c = 11;
        veh1.Take_Price__c = 11;
        veh1.NBV__c = 11;
        veh1.RSM_Demo__c = true;
        veh1.RSM_From__c = Date.today();
        veh1.RSM_To__c = Date.today().addDays(5);
        veh1.RSM__c = 'Approved';
        insert veh1;
        listVehicles.add(veh1);
        
        Vehicle__c veh2 = new Vehicle__c();
        veh2.Name = '2';
        veh2.Account__c = acc.Id;
        veh2.Ask_Price__c = 11;
        veh2.Take_Price__c = 11;
        veh2.NBV__c = 11;
        veh2.RSM_Demo__c = null;
        veh2.RSM_From__c = Date.today();
        veh2.RSM_To__c = Date.today().addDays(5);
        veh2.RSM__c = 'Denied';
        
        Map<Id, Vehicle__c> mapVehicles = new Map<Id, Vehicle__c>();
        mapVehicles.put(veh1.Id, veh2);
        RSMManageVehicle_Helper.UpdateAccountOnExpirationDateChange(listVehicles, mapVehicles);
    }
/*
    static testMethod void testPopulateUnitNumber() {
        Account acc = TestUtilUVS.createAccount('Vendor', 'FMS', true);
        List<Vehicle__c> listVehicles = new List<Vehicle__c>();
        Vehicle__c veh1 = new Vehicle__c();
        veh1.Name = '1';
        veh1.Account__c = acc.Id;
        veh1.Ask_Price__c = 11;
        veh1.Take_Price__c = 11;
        veh1.NBV__c = 11;
        veh1.RSM_Demo__c = true;
        veh1.RSM_From__c = Date.today();
        veh1.RSM_To__c = Date.today().addDays(5);
        veh1.RSM__c = 'Approved';
        insert veh1;
        listVehicles.add(veh1);
        
        
        RSMManageVehicle_Helper.PopulateUnitNumber(listVehicles);
    }
    */       
}