SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CO_SEGMENT__c</fullName>
        <description>RYDER Specific Company Segment, Lookup code from TB_REF_CODE, REF TYPE CODE = CMS.</description>
        <label>Market Segment</label>
        <picklist>
            <picklistValues>
                <fullName>0 - Three trucks or less</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>00 - Three Trucks or Less (Bargain Hunter)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1 - Brgn hunters Med fl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 - Cap builders Med fl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - Time-crit del Med fl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 - Brgn hunters Low den fl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5  - Cap bld Low den fl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6 - Time-crit del Low den fl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7 -  Brgn hunters Lrg fl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8 - Sophisticated 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9 - Sophisticated 2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CompanyTypeID__c</fullName>
        <label>Company Type</label>
        <picklist>
            <picklistValues>
                <fullName>1 Corporation</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2 Sub S Corp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 Partnership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 Sole Proprietorship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5 Tax Exempt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6 Government Entity</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CustomerTypeID__c</fullName>
        <description>Customer type indicating FMS or RIL. Realtime update of both SFDC and RADAR whenever this value is changed in either system.      Question: Does RADAR care about this or any changes to this field?</description>
        <label>Customer Type</label>
        <picklist>
            <picklistValues>
                <fullName>FMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RIL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FMS Rental</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup on Accounts</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RSM_Service_Level__c</fullName>
        <description>Displays Service Level of the vehicle</description>
        <label>Service Level</label>
        <picklist>
            <picklistValues>
                <fullName>Plus 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>STD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RSM__c</fullName>
        <description>Displays RydeSmart contract status</description>
        <label>RS Contract Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Printed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to SSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by SSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deleted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/RSM_rollUpSummaryVehicles_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 * This class contains Test methods for: RSM_rollUpSummaryVehicle and RSM_rollUpSummaryVehicle_Helper
 */
@isTest
private class RSM_rollUpSummaryVehicles_Test {

    static testMethod void myUnitTest()
    {       
        RSMCreateTestData.GetCustomSettingsRecord();
        
        RSM_rollUpSummaryVehicles runLockBatch = new RSM_rollUpSummaryVehicles();
        Database.executeBatch(runLockBatch, 200);
        
        
        // TO DO: implement unit test
        Account parentAcct = new Account(Name='Test Account', ShippingState='LA', ShippingCountry='CA', CustomerTypeID__c='FMS', 
                                            CO_SEGMENT__c='0 - Three trucks or less', CompanyTypeID__c='1 Corporation');  
        insert parentAcct;
        
        // create child account
        Vehicle__c childAccnt1 = new Vehicle__c(Name='Test Vehicle1', Account__c = parentAcct.id, RSM_Service_Level__c='Plus 1',RSM__c = 'Approved');
        insert childAccnt1;
        
        Vehicle__c childAccnt2 = new Vehicle__c(Name='Test Vehicle2', Account__c = parentAcct.id, RSM_Service_Level__c='Plus 1',RSM__c = 'Approved');
        insert childAccnt2;
 
        Vehicle__c childAccnt3 = new Vehicle__c(Name='Test Vehicle3', Account__c = parentAcct.id, RSM_Service_Level__c='STD',RSM__c = 'Approved');
        insert childAccnt3; 
 
        Vehicle__c childAccnt4 = new Vehicle__c(Name='Test Vehicle4', Account__c = parentAcct.id, RSM_Service_Level__c='Plus',RSM__c = 'Approved');
        insert childAccnt4;
 
        Vehicle__History vh = NEW Vehicle__History();
        vh.Field = 'RSM_Service_Level__c';
        vh.ParentId = childAccnt1.Id;
        //vh.Parent.Account__c = parentAcct.Id;
        
        List<Vehicle__History> lVH = new List<Vehicle__History>{};
        lVH.add(vh);
        RSM_RollUpSummaryVehicles_Helper.ProcessVehicleHistory(lVH);
    }
}