SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>STATUS_ACTIVE__c</fullName>
        <description>Customer status to control visibility.</description>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Customer_100_Ownership__c</fullName>
        <label>Customer 100% Ownership</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Close_Date__c</fullName>
        <label>Opportunity Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity_Number__c</fullName>
        <label>Opportunity Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Owner__c</fullName>
        <description>Contains the opportunity owners full name</description>
        <label>Opportunity Owner</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Original_Decision_Maker__c</fullName>
        <label>Original Decision Maker</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>STATUS_ACTIVE__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Status Active</description>
        <label>Status Active</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Actual_Close_Date__c</fullName>
        <description>Populated with the current date when the Opportunity is marked Signed / Booked / Lost</description>
        <label>Actual Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Customer_100_Ownership__c</fullName>
        <description>Select Yes if this company owned their entire fleet when we got them, regardless of who was providing maintenance services, or they went to 100% ownership if we lost them. Select No if this company had any portion of their fleet under a lease contract</description>
        <inlineHelpText>Select Yes if this company owned their entire fleet when we got them, regardless of who was providing maintenance services, or they went to 100% ownership if we lost them. Select No if this company had any portion of their fleet under a lease contract</inlineHelpText>
        <label>Customer 100% Ownership</label>
        <picklist>
            <controllingField>Deal_lost_to_Won_from_whom__c</controllingField>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Original_Decision_Maker__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Original Decision Maker</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>Contact.STATUS_ACTIVE__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>The Contact you are adding as an Original Decision Maker must be an active Contact within the same Account where you are creating the new Opportunity.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ext_pipeline_id__c</fullName>
        <externalId>true</externalId>
        <label>Opportunity Number</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/classes/OpportunityOwnershipValidation.cls
public with sharing class OpportunityOwnershipValidation {

    public static void CreateCasesForValidOwnership(Map<Id, Opportunity> mapOld, Map<Id, Opportunity> mapNew){
        
        for (Opportunity oppty : mapNew.values()){
        
            // Check if any of the below information has changed
            if(oppty.StageName == 'Booked') {
    
                if(oppty.Customer_100_Ownership__c == 'Yes'){
                    
                    try{
                        // Check if a case already exists
                        RecordType recType = [Select Id from RecordType where Name =:'Ownership Validations'];
                        List<Case> cCase = [Select Id from Case where Opportunity_Case__c = :oppty.Id and RecordTypeId =:recType.Id];
                        
                        if(cCase.isEmpty() || cCase.size() == 0){
                            
                            //Get Oppty Owner Name
                            User u = [Select Name from User where Id = :oppty.OwnerId];
                            //Get Queue Id to assign as the Owner of the Case
                            Group queue = [Select Id FROM Group WHERE Name = 'Ownership Validations' AND Type = 'Queue'];
                            
                            //Get Oppty Decision Maker
                            String origDecisionMaker = '';
                            Contact origDecMakerContact = null;
                            
                            //Assign the Original Decision Maker 
                            if(oppty.Original_Decision_Maker__c == null){
                                //Check if there is a Parent Id in Account
                                Account parentAccount = [SELECT ParentId FROM Account WHERE Id = :oppty.AccountId];
                                if(parentAccount.ParentId == null){
                                    //If there is no ParentId then use the oppty AccountId
                                    origDecMakerContact = [SELECT Name FROM Contact WHERE AccountId = :oppty.AccountId AND STATUS_ACTIVE__c = true LIMIT 1];
                                    origDecisionMaker = origDecMakerContact.Name;
                                }else{
                                    origDecMakerContact = [SELECT Name FROM Contact WHERE AccountId = :parentAccount.ParentId AND STATUS_ACTIVE__c = true LIMIT 1];
                                    origDecisionMaker = origDecMakerContact.Name;
                                }
                            }else{
                                //There is an Original Decision Maker in the opportunity
                                origDecMakerContact = [SELECT Name FROM Contact WHERE Id = :oppty.Original_Decision_Maker__c AND STATUS_ACTIVE__c = true LIMIT 1];
                                origDecisionMaker = origDecMakerContact.Name;
                            }
                        
                            //No case exists, create a new one
                            Case newCase = new Case();
                            newCase.AccountId = oppty.AccountId; 
                            newCase.Status = 'New';
                            newCase.Opportunity_Owner__c = u.Name;
                            newCase.Opportunity_Case__c = oppty.Id;
                            newCase.Opportunity_Close_Date__c = oppty.Actual_Close_Date__c;
                            newCase.Opportunity_Number__c = oppty.ext_pipeline_id__c;
                            newCase.RecordTypeId = recType.Id;
                            newCase.OwnerId = queue.Id; //Case is assigned to a Queue
                            newCase.Original_Decision_Maker__c = origDecisionMaker;
                            insert newCase;
                        }
                        
                    }
                    catch (Exception ex){
                        system.debug(LoggingLevel.ERROR, 'aaaaaaaaa Message: ' + ex.getMessage());    
                        system.debug(LoggingLevel.ERROR, 'aaaaaaaaa Cause: ' + ex.getCause());    
                        system.debug(LoggingLevel.ERROR, 'aaaaaaaaa Line number: ' + ex.getLineNumber());
                    }
                }
            }
        }
    }

}