SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Classification__c</fullName>
        <label>Account Classification</label>
        <picklist>
            <picklistValues>
                <fullName>National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coordinated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Coordinated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National - Cash Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local - Cash Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Cash and Non-Cash</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Central_Decisionmaking__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Select this if the sales decisions are made at the National / Parent Account level.</inlineHelpText>
        <label>Central Decisionmaking</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LesseeNo__c</fullName>
        <description>Realtime update of both SFDC and RADAR whenever this value is changed in either system</description>
        <label>Lessee Number</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RSM_CCMs__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to Store RydeSmart&apos;s CCM (Customer Care Manager) owner</description>
        <inlineHelpText>If CCM is changed Manually then check &quot;Do Not Override CCM&quot; field.</inlineHelpText>
        <label>CCM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Source__c</fullName>
        <description>This field tells if the contact is created by lead convesion process or manually by clicking new contact button.</description>
        <label>Contact Source</label>
        <picklist>
            <picklistValues>
                <fullName>Lead Conversion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manual</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Maintenance_Contact_Type__c</fullName>
        <label>Maintenance Contact - All Branches</label>
        <picklist>
            <picklistValues>
                <fullName>Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tertiary</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Primary</fullName>
        <active>true</active>
        <label>Primary</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Customer_Branch__c.object
<CustomObject>
    <description>Customer Branches at Ryder</description>
    <fields>
        <fullName>Ryder_HQ_Account__c</fullName>
        <description>M/D field between Customer Branch and HQ Accounts</description>
        <label>Ryder HQ Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer / Branch</relationshipLabel>
        <relationshipName>Customer_Branches</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Customer / Branch</label>
    <nameField>
        <label>Customer Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer / Branch</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup on Accounts</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CUSTOMER_BRANCH__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field for Customer Branch</description>
        <label>Customer Branch</label>
        <referenceTo>Customer_Branch__c</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RSM_Demo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Demo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RSM_From__c</fullName>
        <label>From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RSM_To__c</fullName>
        <label>To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RSM__c</fullName>
        <description>Displays RydeSmart contract status</description>
        <label>RS Contract Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Printed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to SSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by SSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deleted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/RSMTaskForDemoVehicleEnd_Test.cls
@isTest
private class RSMTaskForDemoVehicleEnd_Test
{
    static testmethod void unitTest()
    {
        Test.startTest();
    
        RSMCreateTestData.GetCustomSettingsRecord();
        
        //RecordType RT = new RecordType(SobjectType = 'Task', Name = 'RydeSmart Task');
        //insert RT; 
        
        Account Acc1 = new Account();
        Acc1.name = 'Test';
        Acc1.account_classification__c = 'Key Account';
        Acc1.central_decisionmaking__c = False;
        Acc1.type = 'Customer';
        Acc1.Account_Classification__c = 'National';
        Acc1.LesseeNo__c = '123123';
        Acc1.RSM_CCMs__c = Userinfo.getUserId();
        insert Acc1;
    
        Customer_Branch__c CustomerBranch = new Customer_Branch__c();
        CustomerBranch.Name = 'Test Customer Branch';
        CustomerBranch.Ryder_HQ_Account__c = Acc1.Id;
        insert CustomerBranch;
      
        Contact Cont1 = new Contact();
        Cont1.AccountId = Acc1.Id;
        Cont1.FirstName = 'Test Contact';
        Cont1.LastName = 'Sample';
        Cont1.Email = 'test8979123@rydertest.com';
        Cont1.Maintenance_Contact_Type__c = 'Primary';
        Cont1.Phone = '(123) 456-8789';
        Cont1.Contact_Source__c = 'Lead Conversion';
        insert Cont1;
    
        Vehicle__c Vehicle = new Vehicle__c();
        Vehicle.Name = '1234';
        Vehicle.CUSTOMER_BRANCH__c = CustomerBranch.Id;
        Vehicle.RSM__c = 'Approved';
        Vehicle.Account__c = Acc1.Id;
        Vehicle.RSM_From__c = System.Today();
        Vehicle.RSM_To__c = System.Today();
        Vehicle.RSM_Demo__c = true;
        insert Vehicle;
      
        RSMTaskForDemoVehicleEnd rcsq = new RSMTaskForDemoVehicleEnd();
        Id BatchprocessId = Database.executeBatch(rcsq);
             
        Test.stopTest();

    }
}