SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LesseeNo__c</fullName>
        <description>Realtime update of both SFDC and RADAR whenever this value is changed in either system</description>
        <label>Lessee Number</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RSM_AC_Classification__c</fullName>
        <description>RydeSmart Account Classification</description>
        <inlineHelpText>If RS Account Classification is changed manually then Check &quot;Do Not Override AC&quot; field.</inlineHelpText>
        <label>RydeSmart Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Key Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Key Account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RSM_Account_Status__c</fullName>
        <label>Account Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RSM_Onboarding__c</fullName>
        <description>Field to Store onboarding status of rydesmart account</description>
        <label>Onboarding</label>
        <picklist>
            <picklistValues>
                <fullName>Initiation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacted and Training Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trained</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Researching</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/RSM_ContractDetail__c.object
<CustomObject>
    <description>The object stores the details of the contract</description>
    <fields>
        <fullName>Action_Name__c</fullName>
        <label>Action Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_sent_to_De_Activate_contract__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field to capture if Email is sent to RSS to De-activation Contract.</description>
        <label>Email sent to De-Activate contract</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Current__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Current</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unit_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Number</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipName>RSContractDetails</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RSM ContractDetail</label>
    <nameField>
        <label>RSM ContractDetailID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RSM ContractDetails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/RSM_VehicleValidationDetails__c.object
<CustomObject>
    <fields>
        <fullName>Unit_Number__c</fullName>
        <label>Unit Number</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>RSM VehicleValidationDetails</relationshipLabel>
        <relationshipName>RSM_VehicleValidationDetails</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Validation_Rule_Id__c</fullName>
        <label>Validation Rule Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>RSM VehicleValidationDetails</label>
    <nameField>
        <label>VehicleValidationDetailsId</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RSM VehicleValidationDetails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/RSM_Schedule_Batch4.cls
global class RSM_Schedule_Batch4 implements Schedulable {
      global void execute(SchedulableContext sc) {
        
        //************Emails************
    //FR010-Batchable to send initial welcome letter to non-key accounts
       RSMInitialWelEmailToNonKeyAc rsiwe= new RSMInitialWelEmailToNonKeyAc (); 
        rsiwe.query='select Id,RSM_AC_Classification__c,RSM_Onboarding__c from Account where RSM_AC_Classification__c=\'Non-Key Account\' and RSM_Onboarding__c=\'Initiation\''; 
        database.executebatch(rsiwe,200);
        
        //FR011-Batch Class to Send Email to Non-Key Ac once installation Process is complete for all the contracted vehicles
        RSMEmailToNonKeyAcAfterInstCompleted rseaic= new RSMEmailToNonKeyAcAfterInstCompleted(); 
        rseaic.query='select Id,RSM_AC_Classification__c from Account where RSM_AC_Classification__c=\'Non-Key Account\' and RSM_Account_Status__c = \'Customer\''; 
        database.executebatch(rseaic,200);
        
        //FR134-Batch Class to Send Email to Non-Key Accounts for cancelation contracts
        RSMCancelEmailtoNonKeyAc rsce= new RSMCancelEmailtoNonKeyAc(); 
        rsce.query='select Id,LesseeNo__c,RSM_AC_Classification__c from Account where RSM_AC_Classification__c=\'Non-Key Account\''; 
        database.executebatch(rsce,200);
        
       //FR033-Generate Email to RSS once unit cancels their contract to request de-activation
        RSMEmailRSSToDeactivateCon rerd= new RSMEmailRSSToDeactivateCon(); 
        rerd.query='select Id,Action_Name__c,Is_Current__c,Email_sent_to_De_Activate_contract__c from RSM_ContractDetail__c where Action_Name__c=\'Cancel\' and Is_Current__c=true and Email_sent_to_De_Activate_contract__c=false'; 
        database.executebatch(rerd,200);
        
        //FR034-Generate an email to RSS to reactivate billing  when FSL is billing, approved contract for RydeSmart exists and RydeSmart is not billing
        RSMEmailRSSToReactivatebilling rerb= new RSMEmailRSSToReactivatebilling(); 
       rerb.query='select Id,Unit_Number__c,Unit_Number__r.Name,Validation_Rule_Id__c from RSM_VehicleValidationDetails__c where Validation_Rule_Id__c=\'11\' OR Validation_Rule_Id__c=\'22\'';
          database.executebatch(rerb,500);
        
      }
}