SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LesseeNo__c</fullName>
        <description>Realtime update of both SFDC and RADAR whenever this value is changed in either system</description>
        <label>Lessee Number</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup on Accounts</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EXPIRATION_DATE__c</fullName>
        <description>Expiration Date</description>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>In_Service_Date__c</fullName>
        <label>In Service Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Out_Service_Date__c</fullName>
        <label>Out Service Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PRODUCT_LINE__c</fullName>
        <description>Product Line</description>
        <label>Product Line</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <description>Used to identify the matching Product for Renewals.</description>
        <formula>PRODUCT_LINE__c &amp; &quot;-&quot; &amp; SAM_CLASS__c &amp; &quot;-&quot; &amp; Renewal_Default_Type__c</formula>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RSM_Service_Level__c</fullName>
        <description>Displays Service Level of the vehicle</description>
        <label>Service Level</label>
        <picklist>
            <picklistValues>
                <fullName>Plus 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>STD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SAM_CLASS__c</fullName>
        <description>Sam Class</description>
        <label>SAM Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <externalId>true</externalId>
        <label>Unit Number</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/RSMAccountVehicle.cls
/****************************************************************************
 *  Date            Name          Description
 * --------   --------------    ----------------
 * 1/24/2014    Saad Wali Jaan    RydeSmart Vehicle Data Visibility on Accounts page        
 ****************************************************************************/


/*
* This class is defined to be a controller to the page RydeSmartVehicles page
*/

public with sharing class RSMAccountVehicle 
{
    //public List<Vehicle__c> accountRelatedVehicle {get;set;}
   
    public Account accountInfo {set; get;}
    
    public String searchCriteriaVehicle{get; set;}
    public String searchCriteriaCompany {get;set;}
    public String vehicleQuery {get;set;}
    
    public String sortOrder {get;set;}
    public String sortField {get;set;}
    
    public ApexPages.StandardSetController stdVehicleController {get;set;}
    
    public List<Vehicle__c> getPageVehicles()
    {
        return stdVehicleController.getRecords();
    }
    
    public RSMAccountVehicle(ApexPages.StandardController stdController) 
    {
        this.accountInfo = (Account)stdController.getRecord(); 
        sortField = 'Name';
        sortOrder = 'ASC';
        init();
    }
    
    public void changeOrder()
    {
        if(sortOrder == 'ASC')
        {
            sortOrder = 'DESC';
        }
        else
        {
            sortOrder = 'ASC';
        }
        init();
    }
    
    public void init()
    {
        if(accountInfo.Id!=null)
        {
            accountInfo = [select id, LesseeNo__c from Account where id=: accountInfo.id ];
            searchCriteriaCompany = accountInfo.id;
        }
        searchVehicles();
    }
    
    public void searchVehicles()
    {
        searchCriteriaVehicle = (searchCriteriaVehicle!=null)?searchCriteriaVehicle:'';
        stdVehicleController = new ApexPages.StandardSetController(new List<Vehicle__c>());
        
        vehicleQuery = 'SELECT id, EXPIRATION_DATE__c, In_Service_Date__c, Name, Out_Service_Date__c, PRODUCT_LINE__c, ';
        vehicleQuery += 'Product_Name__c, SAM_CLASS__c, Unit__c FROM Vehicle__c where Account__c =\''+searchCriteriaCompany+'\'';
        vehicleQuery += ' and RSM_Service_Level__c != \'\'';
        if (searchCriteriaVehicle!='')
        {
            searchCriteriaVehicle = '\''+searchCriteriaVehicle+'\'';
            searchCriteriaVehicle = searchCriteriaVehicle.replace(' ','');
            searchCriteriaVehicle = searchCriteriaVehicle.replace(',','\',\''); 
            vehicleQuery += ' and Unit__c IN (' +searchCriteriaVehicle +')';
            searchCriteriaVehicle = searchCriteriaVehicle.replace('\'','');             
        }
        
        vehicleQuery += ' order by ' + sortField + ' ' + sortOrder;
        stdVehicleController = new ApexPages.StandardSetController(Database.getQueryLocator(vehicleQuery));
        stdVehicleController.setpageSize(10);
    }
}