SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>SAM_Cust_ID__c</fullName>
        <description>Migrated data from SAM</description>
        <label>SAM_Cust_ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <picklist>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wholesale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Export</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Vendor account record type for legal requests</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Customer_Branch__c.object
<CustomObject>
    <description>Customer Branches at Ryder</description>
    <fields>
        <fullName>Ryder_Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field for Customer Branch to Ryder branch</description>
        <label>Ryder Branch</label>
        <referenceTo>Ryder_Branch__c</referenceTo>
        <relationshipLabel>Customer / Branch</relationshipLabel>
        <relationshipName>Customer_Branches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ryder_HQ_Account__c</fullName>
        <description>M/D field between Customer Branch and HQ Accounts</description>
        <label>Ryder HQ Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer / Branch</relationshipLabel>
        <relationshipName>Customer_Branches</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Customer / Branch</label>
    <nameField>
        <label>Customer Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer / Branch</pluralLabel>
    <recordTypes>
        <fullName>UVS</fullName>
        <active>true</active>
        <description>Identity</description>
        <label>UVS</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Pricebook2.object
<CustomObject>
    <recordTypes>
        <fullName>UVS</fullName>
        <active>true</active>
        <description>Used by Used Vehicle Sales Group</description>
        <label>UVS</label>
    </recordTypes>
    <sharingModel>ReadSelect</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>SAM_Class__c</fullName>
        <label>SAM Class</label>
        <picklist>
            <picklistValues>
                <fullName>10 - Panel Van or Pickup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20 - Parcel Van</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21 - Metro Van/Sprinter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30 - Truck &gt;=8K &lt;= 16K GVW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>31 - Reefer Truck &lt;=16K</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40 - Gas Straight Truck</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50 - Truck &gt;16K &lt;=26K GVW &lt;=20 ft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>51 - Truck (No Body) &gt;16K &lt;=26K GVW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60 - Truck &gt;16K &lt;=26K GVW &gt; 20 ft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>61 - Tank Truck &gt;16K &lt;=26K GVW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70 - Reefer Truck &gt;16K &lt;=26K GVW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80 - Truck &gt;26K GVW &lt;= 20 ft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>81 - Truck (No Body) &gt;26K &lt;=33K GVW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>90 - Truck &gt; 26K GVW &gt; 20 ft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>91 - Tank Truck &gt;26K &lt;=33K GVW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>100 - Stake or Flatbed Truck</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>110 - Reefer Truck &gt; 26K GVW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>120 - T/A Big Bore Truck</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>121 - S/A Big Bore Truck</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>122 - Tank Truck &gt;33K GVW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>130 - S/A Tractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>131 - S/A Yard Tractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>132 - S/A Pick-up &amp; Delivery Tractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>140 - T/A Tractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>141 - T/A Yard Tractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>150 - S/A Sleeper Tractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>160 - T/A COE Sleeper Tractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>170 - T/A Conv Sleeper Tractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>180 - Dry Trailer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>181 - Tanker Trailer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

SFDC Automation/src/objects/Quote.object
<CustomObject>
    <recordTypes>
        <fullName>UVS</fullName>
        <active>true</active>
        <description>Used vehicle Sales</description>
        <label>UVS</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Ryder_Branch__c.object
<CustomObject>
    <description>Branches at Ryder</description>
    <fields>
        <fullName>Branch_Code__c</fullName>
        <description>external ID</description>
        <externalId>true</externalId>
        <label>Branch Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Ryder Branch</label>
    <nameField>
        <label>Ryder Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ryder Branches</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/objects/RyderConfig__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Provides configuration information for Ryder</description>
    <label>Ryder Config</label>
</CustomObject>

SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <fields>
        <fullName>Ask_Price__c</fullName>
        <label>Ask Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Branch_Code__c</fullName>
        <label>Branch Code</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CUSTOMER_BRANCH__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field for Customer Branch</description>
        <label>Customer Branch</label>
        <referenceTo>Customer_Branch__c</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Available_For_Sale__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This flag used to mark available for Used Vehicle Sale</description>
        <label>Is Available For Sale</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SAM_CLASS__c</fullName>
        <description>Sam Class</description>
        <label>SAM Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field to indicate whether a vehicle has been sold and not available in the inventory.</description>
        <inlineHelpText>Field to indicate whether a vehicle has been sold and not available in the inventory.</inlineHelpText>
        <label>Sold Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <description>This field will hold the transaction type of the vehicle. Eg: Lease Extension</description>
        <label>Transaction Type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <recordTypes>
        <fullName>UVS</fullName>
        <active>true</active>
        <description>Record Type for UVS Vehicles</description>
        <label>UVS</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/AddProductsCustomControllerTest.cls
/*******************************************************************
Name  : AddProductsCustomControllerTest
Author: Gaurav Gupta (Appirio)
Date  : October 16, 2014
Discription: Test Class for the Helper class AddProductsCustomController
*************************************************************************/
@isTest(seealldata = true)
private class AddProductsCustomControllerTest {
  static testMethod void testAfterUpdate(){
      User sysAdmin = TestUtilUvs.createAdminUser(True);

      System.runAs ( sysAdmin ) {
        //RyderConfig__c rydConf = new RyderConfig__c();
        //rydConf = TestUtilUVS.createRyderConfig(true);
      Account acc =TestUtilUVS.createAccount('Vendor','FMS',false);
      acc.Transaction_Type__c = 'Retail';
      acc.Accountsource = 'Advertisement';
      acc.SAM_Cust_ID__c = 'abc';
      insert acc;
         test.startTest();
      Opportunity opp = TestUtilUVS.createOpportunity('UVS Opportunity',acc , False, null);
      opp.CloseDate = date.today();
      opp.CurrencyISOCode = 'USD';
      insert opp;

            list<Product2> lstProd = new list<Product2>();
            Product2 prod = new Product2();
            prod.Name = 'UVS-DEF-Used';
            prod.CurrencyIsoCode = 'USD';
            lstProd.add(prod);

            Product2 prod1 = new Product2();
            prod1.Name = 'UVS-ABc-Used';
            lstProd.add(prod1);

            Product2 prod3 = new Product2();
            prod3.Name = 'UVS-UVW-Used';
            prod3.CurrencyIsoCode = 'USD';
            lstProd.add(prod3);
            insert lstProd;
        test.stopTest();

        Pricebook2 stdpb = [SELECT Id FROM Pricebook2 WHERE IsStandard = true];
            PriceBookEntry pbe = [SELECT Id
                                FROM PriceBookEntry
                                WHERE Product2Id = :prod.Id
                                LIMIT 1];
              pbe.isActive = true;

            update pbe;

      Ryder_Branch__c rb = new Ryder_Branch__c();
      rb.Branch_Code__c = '123';
      insert rb;
      Customer_Branch__c cstB = new Customer_Branch__c();
      cstB.Ryder_branch__c = rb.id;
      cstB.Ryder_HQ_Account__c = acc.id;
      insert cstB;
          //**************************************************
          // Create a custom price book
          //Pricebook2 customPB = new Pricebook2(Name='UVS', isActive=true);
          PriceBook2 UVSPriceBook = [Select Id from PriceBook2 where Name = 'UVS' limit 1];
         // insert customPB;

       PricebookEntry PBE1 = new PricebookEntry();
       PBE1.Product2Id = prod1.Id;
       PBE1.Pricebook2Id = UVSPriceBook.Id;
       PBE1.UnitPrice = 100.00;
       PBE1.IsActive = true;
      insert PBE1;



      list<Vehicle__c> lstvehicle = new list<Vehicle__c>();
      Vehicle__c v1 = new Vehicle__c(Name='12');
      v1.CUSTOMER_BRANCH__c = cstB.id;
      v1.Is_Available_For_Sale__c = true;
      v1.Sold_Flag__c = false ;
      v1.Sam_Class__c = 'UVW';
      v1.Ask_Price__c = 20000.0;
      lstvehicle.add(v1);
      Vehicle__c v = new Vehicle__c(Name='12');
      v.CUSTOMER_BRANCH__c = cstB.id;
      v.Is_Available_For_Sale__c = true;
      v.Sold_Flag__c = false ;
      v.Sam_Class__c = 'DEF';
      v.Ask_Price__c = 20000.0;
      v.Ask_Price__c = 20000.0;
      lstvehicle.add(v);

      insert lstvehicle;

      //**************************************************


        /*Quote q = TestUtilUVS.createQuote('UVS', false);
        //q.contactId = newCon.id;
        q.OpportunityId = opp.id;
      insert q;*/






      PageReference tpageRef = Page.AddProductsCustom;
      Test.setCurrentPage(tpageRef);

      ApexPages.currentPage().getParameters().put('oppId', opp.Id);
      //ApexPages.currentPage().getParameters().put('quoteId', q.Id);

    AddProductsCustomController apcc = new AddProductsCustomController();
    apcc.unitNumber = '12';

    AddProductsCustomController.getQuery();
    apcc.search();
    List<AddProductsCustomController.VehicleSelection> searchResults_test = new List<AddProductsCustomController.VehicleSelection>();
    searchResults_test = apcc.searchResults;
    boolean selectOne = false;
    For(AddProductsCustomController.VehicleSelection vc : searchResults_test){
      String vehicleSameClass = vc.vehicle.Sam_Class__c;
      if(vehicleSameClass != null && vehicleSameClass.contains('-') ){
         vc.isSelected = true;
      }
    }
    apcc.searchResults[0].isSelected = true;
    //system.assert(false , apcc.searchResults);
    // Set vehicle.isSelected to true
    apcc.selectVehicles();

    apcc.cancel();
    }
  }
static testMethod void ExecutePastClosedOpportunityUseCase(){
      User sysAdmin = TestUtilUvs.createAdminUser(True);

      System.runAs ( sysAdmin ) {
        //RyderConfig__c rydConf = new RyderConfig__c();
        //rydConf = TestUtilUVS.createRyderConfig(true);
      Account acc =TestUtilUVS.createAccount('Vendor','FMS',false);
      acc.Transaction_Type__c = 'Retail';
      acc.Accountsource = 'Advertisement';
      acc.SAM_Cust_ID__c = 'abc';
      insert acc;
         test.startTest();
      Opportunity opp = TestUtilUVS.createOpportunity('UVS Opportunity',acc , False, null);
      // Update the Close date to 2 days early so the Validation Rule can be tested by forcing the Opportunity to be in the past.
      opp.CloseDate = date.today().addDays(-2);
      opp.CurrencyISOCode = 'USD';
      insert opp;

            list<Product2> lstProd = new list<Product2>();
            Product2 prod = new Product2();
            prod.Name = 'UVS-DEF-Used';
            prod.CurrencyIsoCode = 'USD';
            lstProd.add(prod);

            Product2 prod1 = new Product2();
            prod1.Name = 'UVS-ABc-Used';
            lstProd.add(prod1);

            Product2 prod3 = new Product2();
            prod3.Name = 'UVS-UVW-Used';
            prod3.CurrencyIsoCode = 'USD';
            lstProd.add(prod3);
            insert lstProd;
        test.stopTest();

        Pricebook2 stdpb = [SELECT Id FROM Pricebook2 WHERE IsStandard = true];
            PriceBookEntry pbe = [SELECT Id
                                FROM PriceBookEntry
                                WHERE Product2Id = :prod.Id
                                LIMIT 1];
              pbe.isActive = true;

            update pbe;

      Ryder_Branch__c rb = new Ryder_Branch__c();
      rb.Branch_Code__c = '123';
      insert rb;
      Customer_Branch__c cstB = new Customer_Branch__c();
      cstB.Ryder_branch__c = rb.id;
      cstB.Ryder_HQ_Account__c = acc.id;
      insert cstB;
          //**************************************************
          // Create a custom price book
          //Pricebook2 customPB = new Pricebook2(Name='UVS', isActive=true);
          PriceBook2 UVSPriceBook = [Select Id from PriceBook2 where Name = 'UVS' limit 1];
         // insert customPB;

       PricebookEntry PBE1 = new PricebookEntry();
       PBE1.Product2Id = prod1.Id;
       PBE1.Pricebook2Id = UVSPriceBook.Id;
       PBE1.UnitPrice = 100.00;
       PBE1.IsActive = true;
      insert PBE1;



      list<Vehicle__c> lstvehicle = new list<Vehicle__c>();
      Vehicle__c v1 = new Vehicle__c(Name='12');
      v1.CUSTOMER_BRANCH__c = cstB.id;
      v1.Is_Available_For_Sale__c = true;
      v1.Sold_Flag__c = false ;
      v1.Sam_Class__c = 'UVW';
      v1.Ask_Price__c = 20000.0;
      lstvehicle.add(v1);
      Vehicle__c v = new Vehicle__c(Name='12');
      v.CUSTOMER_BRANCH__c = cstB.id;
      v.Is_Available_For_Sale__c = true;
      v.Sold_Flag__c = false ;
      v.Sam_Class__c = 'DEF';
      v.Ask_Price__c = 20000.0;
      v.Ask_Price__c = 20000.0;
      lstvehicle.add(v);

      insert lstvehicle;

      //**************************************************


        /*Quote q = TestUtilUVS.createQuote('UVS', false);
        //q.contactId = newCon.id;
        q.OpportunityId = opp.id;
      insert q;*/






      PageReference tpageRef = Page.AddProductsCustom;
      Test.setCurrentPage(tpageRef);

      ApexPages.currentPage().getParameters().put('oppId', opp.Id);
      //ApexPages.currentPage().getParameters().put('quoteId', q.Id);

    AddProductsCustomController apcc = new AddProductsCustomController();
    apcc.unitNumber = '12';

    AddProductsCustomController.getQuery();
    apcc.search();
    List<AddProductsCustomController.VehicleSelection> searchResults_test = new List<AddProductsCustomController.VehicleSelection>();
    searchResults_test = apcc.searchResults;
    boolean selectOne = false;
    For(AddProductsCustomController.VehicleSelection vc : searchResults_test){
      String vehicleSameClass = vc.vehicle.Sam_Class__c;
      if(vehicleSameClass != null && vehicleSameClass.contains('-') ){
         vc.isSelected = true;
      }
    }
    apcc.searchResults[0].isSelected = true;
    //system.assert(false , apcc.searchResults);
    // Set vehicle.isSelected to true
    apcc.selectVehicles();

    apcc.cancel();
    }
  }
  static testMethod void testAddCustomController(){
      User sysAdmin = TestUtilUvs.createAdminUser(True);

      System.runAs ( sysAdmin ) {
        //RyderConfig__c rydConf = new RyderConfig__c();
        //rydConf = TestUtilUVS.createRyderConfig(true);
      Account acc =TestUtilUVS.createAccount('Vendor','FMS',false);
      acc.Transaction_Type__c = 'Retail';
      acc.Accountsource = 'Advertisement';
      acc.SAM_Cust_ID__c = 'abc';
      insert acc;


      Test.StartTest();
      Opportunity opp = TestUtilUVS.createOpportunity('UVS Opportunity',acc , False, null);
      opp.CloseDate = date.today().addDays(-5);
      opp.CurrencyISOCode = 'USD';
      insert opp;
      Test.StopTest();
        Quote q = TestUtilUVS.createQuote('UVS', false);
        //q.contactId = newCon.id;
        q.OpportunityId = opp.id;
      insert q;

      PageReference tpageRef = Page.AddProductsCustom;
      Test.setCurrentPage(tpageRef);

      //ApexPages.currentPage().getParameters().put('oppId', opp.Id);
      ApexPages.currentPage().getParameters().put('quoteId', q.Id);

      AddProductsCustomController apcc = new AddProductsCustomController();
      AddProductsCustomController.getQuery();
      apcc.search();
      // Set vehicle.isSelected to true
      apcc.selectVehicles();

      apcc.cancel();
  }
  }
  
  
  
  static testMethod void testAddCustomController2(){
    User sysAdmin = TestUtilUvs.createAdminUser(True);
    System.runAs ( sysAdmin ) {
      Account acc =TestUtilUVS.createAccount('Vendor','FMS',false);
      acc.Transaction_Type__c = 'Retail';
      acc.Accountsource = 'Advertisement';
      acc.SAM_Cust_ID__c = 'abc';
      insert acc;

      Test.StartTest();
      Opportunity opp = TestUtilUVS.createOpportunity('UVS Opportunity',acc , False, null);
      opp.CloseDate = date.today().addDays(-5);
      opp.CurrencyISOCode = 'USD';
      insert opp;
      Test.StopTest();
      
      Quote q = TestUtilUVS.createQuote('UVS', false);
      //q.contactId = newCon.id;
      q.OpportunityId = opp.id;
      insert q;
      
      Product2 prod1 = new Product2();
      prod1.Name = 'UVS-UVW-Used';
      prod1.CurrencyIsoCode = 'USD';
      insert prod1;
      
      
      PriceBook2 UVSPriceBook = [Select Id from PriceBook2 where Name = 'UVS' limit 1];
      
      Ryder_Branch__c rb = new Ryder_Branch__c();
      rb.Branch_Code__c = '123';
      insert rb;
      Customer_Branch__c cstB = new Customer_Branch__c();
      cstB.Ryder_branch__c = rb.id;
      cstB.Ryder_HQ_Account__c = acc.id;
      insert cstB;
      
      list<Vehicle__c> lstvehicle = new list<Vehicle__c>();
      Vehicle__c v1 = new Vehicle__c(Name='12');
      v1.CUSTOMER_BRANCH__c = cstB.id;
      v1.Is_Available_For_Sale__c = true;
      v1.Sold_Flag__c = false ;
      v1.Sam_Class__c = 'UVW';
      v1.Ask_Price__c = 20000.0;
      lstvehicle.add(v1);
      Vehicle__c v = new Vehicle__c(Name='12');
      v.CUSTOMER_BRANCH__c = cstB.id;
      v.Is_Available_For_Sale__c = true;
      v.Sold_Flag__c = false ;
      v.Sam_Class__c = 'DEF';
      v.Ask_Price__c = 20000.0;
      v.Ask_Price__c = 20000.0;
      lstvehicle.add(v);

      insert lstvehicle;
      
      PricebookEntry PBE1 = new PricebookEntry();
      PBE1.Product2Id = prod1.Id;
      PBE1.Pricebook2Id = UVSPriceBook.Id;
      PBE1.UnitPrice = 100.00;
      PBE1.IsActive = true;
      PBE1.CurrencyIsoCode = 'USD';
      insert PBE1;

      PageReference tpageRef = Page.AddProductsCustom;
      Test.setCurrentPage(tpageRef);

      //ApexPages.currentPage().getParameters().put('oppId', opp.Id);
      ApexPages.currentPage().getParameters().put('quoteId', q.Id);

      AddProductsCustomController objController = new AddProductsCustomController();
      AddProductsCustomController.getQuery();
      objController.unitNumber = '12';
      objController.search();
      objController.searchResults[0].isSelected = true;
      objController.selectVehicles();
    }
  }
}