SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Classification__c</fullName>
        <label>Account Classification</label>
        <picklist>
            <picklistValues>
                <fullName>National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coordinated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Coordinated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National - Cash Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local - Cash Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Cash and Non-Cash</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BAD_ADDR_DATE__c</fullName>
        <description>Date when the address was marked bad</description>
        <label>Bad Address Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Central_Decisionmaking__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Select this if the sales decisions are made at the National / Parent Account level.</inlineHelpText>
        <label>Central Decisionmaking</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LesseeNo__c</fullName>
        <description>Realtime update of both SFDC and RADAR whenever this value is changed in either system</description>
        <label>Lessee Number</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>addr_verified_date__c</fullName>
        <label>Address Verified Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Customer_Branch__c.object
<CustomObject>
    <description>Customer Branches at Ryder</description>
    <fields>
        <fullName>Ryder_HQ_Account__c</fullName>
        <description>M/D field between Customer Branch and HQ Accounts</description>
        <label>Ryder HQ Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer / Branch</relationshipLabel>
        <relationshipName>Customer_Branches</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Customer / Branch</label>
    <nameField>
        <label>Customer Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer / Branch</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/RSM_Component__c.object
<CustomObject>
    <description>Object to store the RydeSmart Components &amp; installation details</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>This field is Used to pass the AccountId to History Viewer VF page by clicking History Viewer button.</description>
        <formula>Unit_Number__r.Account__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>I_P_Address__c</fullName>
        <label>I.P. Address</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Current__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Current</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unit_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Number</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>RSM Components</relationshipLabel>
        <relationshipName>RSM_Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RSM Component</label>
    <nameField>
        <label>RSM Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RSM Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC Automation/src/objects/RSM_Contract__c.object
<CustomObject>
    <description>Object to store RydeSmart Contract details</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to store the ID of the Account with which the Contract is related. This field will be populated from database based on the Lessee No in the contract</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>RSM Contracts</relationshipLabel>
        <relationshipName>RSM_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Number__c</fullName>
        <externalId>true</externalId>
        <label>Contract Number</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lessee__c</fullName>
        <label>Lessee</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status_Name__c</fullName>
        <label>Status Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>RSM Contract</label>
    <nameField>
        <label>RSM Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RSM Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC Automation/src/objects/RSM_ContractDetail__c.object
<CustomObject>
    <description>The object stores the details of the contract</description>
    <fields>
        <fullName>Action_Name__c</fullName>
        <label>Action Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract_Number__c</fullName>
        <label>Contract Number</label>
        <referenceTo>RSM_Contract__c</referenceTo>
        <relationshipName>ContractNumber</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EffectiveDate__c</fullName>
        <description>Field to store the effective date of the contract</description>
        <label>EffectiveDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Is_Current__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Current</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unit_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Number</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipName>RSContractDetails</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RSM ContractDetail</label>
    <nameField>
        <label>RSM ContractDetailID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RSM ContractDetails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/RSM_PO__c.object
<CustomObject>
    <description>Object to store Purchase Order header data</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>RSM POs</relationshipLabel>
        <relationshipName>RSM_POs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DateOrdered__c</fullName>
        <label>DateOrdered</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DateReceived__c</fullName>
        <label>DateReceived</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Unit_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit #</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>RSM POs</relationshipLabel>
        <relationshipName>RSM_POs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RSM PO</label>
    <nameField>
        <label>Customer Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RSM POs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup on Accounts</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CUSTOMER_BRANCH__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field for Customer Branch</description>
        <label>Customer Branch</label>
        <referenceTo>Customer_Branch__c</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RSM__c</fullName>
        <description>Displays RydeSmart contract status</description>
        <label>RS Contract Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Printed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to SSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by SSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deleted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <externalId>true</externalId>
        <label>Unit Number</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/HistoryViewer_Controller_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class HistoryViewer_Controller_Test {

    static testMethod void UnitTest_ForAll_Errors()
    {
        // TO DO: implement unit test
        RSMCreateTestData.GetCustomSettingsRecord();
    	
    	Test.StartTest();
    	        
		Account Acc1 = new Account();
        Acc1.name = 'Test';
        Acc1.account_classification__c = 'Key Account';
        Acc1.central_decisionmaking__c = False;
        Acc1.type = 'Customer';
        Acc1.Account_Classification__c = 'National';
        Acc1.LesseeNo__c = '0123123';
        insert Acc1;
        Acc1.Account_Classification__c = 'Local';
        update Acc1;
    	
    	ApexPages.StandardController Control = new ApexPages.StandardController(Acc1);
	    HistoryViewer_Controller ClassObj = new HistoryViewer_Controller(Control);
	    // SearchHistory method will return Null as there is an error
	    System.assertEquals(null, ClassObj.SearchHistory());
	    ClassObj.ObjectName = 'Vehicle__c';
	    ClassObj.FieldName = 'CUSTOMER_BRANCH__c';
	    ClassObj.VehicleName = 'None';
	    // SearchHistory method will return Null as there is an error
	    System.assertEquals(null, ClassObj.SearchHistory());
    	
    	Customer_Branch__c CustomerBranch = new Customer_Branch__c();
	    CustomerBranch.Name = 'Test Customer Branch';
	    CustomerBranch.Ryder_HQ_Account__c = Acc1.Id;
	    insert CustomerBranch;
	    
	    Vehicle__c Vehicle = new Vehicle__c(Unit__c = '123456');
	    Vehicle.Name = '1234';
	    Vehicle.CUSTOMER_BRANCH__c = CustomerBranch.Id;
	    Vehicle.RSM__c = 'Approved';
	    Vehicle.Account__c = Acc1.Id;
	    insert Vehicle;
	    	    
	    Control = new ApexPages.StandardController(Acc1);
	    ClassObj = new HistoryViewer_Controller(Control);
	    // SearchHistory method will return Null as there is an error as ObjectName, FieldName is None
	    System.assertEquals(null, ClassObj.SearchHistory());
	    ClassObj.ObjectName = 'Vehicle__c';
	    ClassObj.FieldName = 'CUSTOMER_BRANCH__c';
	    ClassObj.VehicleName = 'None';
	    // SearchHistory method will return Null as there is an error as VehicleName is None
	    System.assertEquals(null, ClassObj.SearchHistory());
	    ClassObj.VehicleName = Vehicle.Id;
	    // Below Account Date fields are used as place holder on the VF page to take user input. Based on these dates history is queried
	    ClassObj.AccDate.addr_verified_date__c = null;
	    // SearchHistory method will return Null as there is an error as date is null
	    System.assertEquals(null, ClassObj.SearchHistory());
	    // Below Account Date fields are used as place holder on the VF page to take user input. Based on these dates history is queried
	    ClassObj.AccDate.addr_verified_date__c = System.today().addDays(-15);
	    ClassObj.AccDate.BAD_ADDR_DATE__c = System.today().addDays(15);
	    ClassObj.SearchHistory();	    	    
	    ClassObj.ReturnBack();
	    Test.StopTest();
    }
    static testMethod void UnitTest_For_AccountHistoryView()
    {
        // TO DO: implement unit test
        RSMCreateTestData.GetCustomSettingsRecord();
    	
    	Test.StartTest();
    	        
		Account Acc1 = new Account();
        Acc1.name = 'Test';
        Acc1.account_classification__c = 'Key Account';
        Acc1.central_decisionmaking__c = False;
        Acc1.Type = 'Customer';
        Acc1.Account_Classification__c = 'National';
        Acc1.LesseeNo__c = '0123123';
        insert Acc1;
        Acc1.Account_Classification__c = 'Local';
        update Acc1;
    	
	    ApexPages.StandardController Control = new ApexPages.StandardController(Acc1);
	    HistoryViewer_Controller ClassObj = new HistoryViewer_Controller(Control);	 
	    ClassObj.getObjectNames();
	    ClassObj.ObjectName = 'Account';
	    ClassObj.getFieldNames();
	    ClassObj.FieldName = 'Account_Classification__c';
	    ClassObj.Action = 'Local';
	    ClassObj.AccDate.addr_verified_date__c = System.today().addDays(-15);
	    // Below Account Date fields are used as place holder on the VF page to take user input. Based on these dates history is queried
	    ClassObj.AccDate.BAD_ADDR_DATE__c = System.today().addDays(15);
	    ClassObj.SearchHistory();
	    // This must return 0 Account History record As in Test method history never populates
	    System.assertEquals(0, ClassObj.InnerClassObj.size());
	    
	    
	    HistoryViewer_Controller.InnerClass InnerC = new HistoryViewer_Controller.InnerClass();
	    InnerC.sDate = system.now().format();
	    InnerC.sUser = 'Test User';
	    InnerC.sOldValue = 'Local';
	    InnerC.sNewValue = 'National';
	    InnerC.sAction = 'Changed Account Classification from Local to National';
	    HistoryViewer_Controller.InnerClass InnerC1 = new HistoryViewer_Controller.InnerClass();
	    InnerC1.sDate = system.now().format();
	    InnerC1.sUser = 'Test User';
	    InnerC1.sOldValue = 'National';
	    InnerC1.sNewValue = 'Local';
	    InnerC1.sAction = 'Changed Account Classification from National to Local';
	    ClassObj.InnerClassObj.add(InnerC);
	    ClassObj.InnerClassObj.add(InnerC1);
	    ClassObj.FilterData();	    	    	    
	    ClassObj.ReturnBack();
	    Test.StopTest();
    }
    static testMethod void UnitTest_For_VehicleHistoryView()
    {
        // TO DO: implement unit test
        RSMCreateTestData.GetCustomSettingsRecord();
    	
    	Test.StartTest();
    	        
		Account Acc1 = new Account();
        Acc1.name = 'Test';
        Acc1.account_classification__c = 'Key Account';
        Acc1.central_decisionmaking__c = False;
        Acc1.Type = 'Customer';
        Acc1.Account_Classification__c = 'National';
        Acc1.LesseeNo__c = '0123123';
        insert Acc1;
        Acc1.Account_Classification__c = 'Local';
        update Acc1;
    	
    	Customer_Branch__c CustomerBranch = new Customer_Branch__c();
	    CustomerBranch.Name = 'Test Customer Branch';
	    CustomerBranch.Ryder_HQ_Account__c = Acc1.Id;
	    insert CustomerBranch;
	    Customer_Branch__c CustomerBranch1 = new Customer_Branch__c();
	    CustomerBranch1.Name = 'Test Customer Branch';
	    CustomerBranch1.Ryder_HQ_Account__c = Acc1.Id;
	    insert CustomerBranch1;
        
    	Vehicle__c Vehicle = new Vehicle__c(Unit__c = '123456');
	    Vehicle.Name = '1234';
	    Vehicle.CUSTOMER_BRANCH__c = CustomerBranch.Id;
	    Vehicle.RSM__c = 'Approved';
	    Vehicle.Account__c = Acc1.Id;
	    insert Vehicle;
	    Vehicle.CUSTOMER_BRANCH__c = CustomerBranch1.Id;
		update Vehicle;
		
		ApexPages.currentPage().getParameters().put('extid', Vehicle.Id);
	    ApexPages.StandardController Control = new ApexPages.StandardController(Acc1);
	    HistoryViewer_Controller ClassObj = new HistoryViewer_Controller(Control);
	    ClassObj.getVehicleNames();
	    ClassObj.ObjectName = 'Vehicle__c';
	    ClassObj.FieldName = 'CUSTOMER_BRANCH__c';
	    ClassObj.VehicleName = Vehicle.Id;
	    // Below Account Date fields are used as place holder on the VF page to take user input. Based on these dates history is queried
	    ClassObj.AccDate.addr_verified_date__c = System.today().addDays(-15);
	    ClassObj.AccDate.BAD_ADDR_DATE__c = System.today().addDays(15);
	    ClassObj.SearchHistory();
	    ClassObj.ObjectSelected();
	    // This must return 0 Vehicle History record As in Test method history never populates
	    System.assertEquals(0, ClassObj.InnerClassObj.size());
	    
	    ClassObj.VehicleName = 'All';
	    // Below Account Date fields are used as place holder on the VF page to take user input. Based on these dates history is queried
	    ClassObj.AccDate.addr_verified_date__c = System.today().addDays(-15);
	    ClassObj.AccDate.BAD_ADDR_DATE__c = System.today().addDays(15);
	    ClassObj.SearchHistory();
	    System.assertEquals(0, ClassObj.InnerClassObj.size());	    	    
	    ClassObj.ReturnBack();
	    
	    Test.StopTest();
    }
    static testMethod void UnitTest_For_ContractHistoryView()
    {
        // TO DO: implement unit test
        RSMCreateTestData.GetCustomSettingsRecord();
    	
    	Test.StartTest();
    	        
		Account Acc1 = new Account();
        Acc1.name = 'Test';
        Acc1.account_classification__c = 'Key Account';
        Acc1.central_decisionmaking__c = False;
        Acc1.Type = 'Customer';
        Acc1.Account_Classification__c = 'National';
        Acc1.LesseeNo__c = '0123123';
        insert Acc1;
        Acc1.Account_Classification__c = 'Local';
        update Acc1;
    	
    	Customer_Branch__c CustomerBranch = new Customer_Branch__c();
	    CustomerBranch.Name = 'Test Customer Branch';
	    CustomerBranch.Ryder_HQ_Account__c = Acc1.Id;
	    insert CustomerBranch;
	    
	    Vehicle__c Vehicle = new Vehicle__c(Unit__c = '123456');
	    Vehicle.Name = '1234';
	    Vehicle.CUSTOMER_BRANCH__c = CustomerBranch.Id;
	    Vehicle.RSM__c = 'Approved';
	    Vehicle.Account__c = Acc1.Id;
	    insert Vehicle;
	    
    	RSM_Contract__c Contrt1 = new RSM_Contract__c(Account__c = Acc1.Id);
	    Contrt1.Lessee__c = Acc1.LesseeNo__c;
	    Contrt1.Contract_Number__c = 2434;
	    Contrt1.Status_Name__c = 'Approved';	    
	    insert Contrt1;
	    
	    RSM_ContractDetail__c Contrt1Detail = new RSM_ContractDetail__c();
	    Contrt1Detail.Contract_Number__c = Contrt1.id;
	    Contrt1Detail.Action_Name__c = 'Cancel';
	    Contrt1Detail.Is_Current__c = True;
	    Contrt1Detail.Unit_Number__c = Vehicle.Id;
	    insert Contrt1Detail;
	    Contrt1Detail.EffectiveDate__c = System.today().addDays(-5);
	    update Contrt1Detail;
	    
	    ApexPages.StandardController Control = new ApexPages.StandardController(Acc1);
	    HistoryViewer_Controller ClassObj = new HistoryViewer_Controller(Control);	    
	    ClassObj.ObjectName = 'RSM_Contract__c';
	    ClassObj.FieldName = 'EffectiveDate__c';
	    ClassObj.VehicleName = Vehicle.Id;
	    // Below Account Date fields are used as place holder on the VF page to take user input. Based on these dates history is queried
	    ClassObj.AccDate.addr_verified_date__c = System.today().addDays(-15);
	    ClassObj.AccDate.BAD_ADDR_DATE__c = System.today().addDays(15);
	    ClassObj.SearchHistory();
	    // This must return 0 Contract History record As in Test method history never populates
	    System.assertEquals(0, ClassObj.InnerClassObj.size());	    	    
	    ClassObj.ReturnBack();
	    
	    Test.StopTest();
    }
    static testMethod void UnitTest_For_ComponentHistoryView()
    {
        // TO DO: implement unit test
        RSMCreateTestData.GetCustomSettingsRecord();
    	
    	Test.StartTest();
    	        
		Account Acc1 = new Account();
        Acc1.name = 'Test';
        Acc1.account_classification__c = 'Key Account';
        Acc1.central_decisionmaking__c = False;
        Acc1.Type = 'Customer';
        Acc1.Account_Classification__c = 'National';
        Acc1.LesseeNo__c = '0123123';
        insert Acc1;
        Acc1.Account_Classification__c = 'Local';
        update Acc1;
    	
    	Customer_Branch__c CustomerBranch = new Customer_Branch__c();
	    CustomerBranch.Name = 'Test Customer Branch';
	    CustomerBranch.Ryder_HQ_Account__c = Acc1.Id;
	    insert CustomerBranch;
	    
    	Vehicle__c Vehicle = new Vehicle__c(Unit__c = '123456');
	    Vehicle.Name = '1234';
	    Vehicle.CUSTOMER_BRANCH__c = CustomerBranch.Id;
	    Vehicle.RSM__c = 'Approved';
	    Vehicle.Account__c = Acc1.Id;
	    insert Vehicle;
	    
	    RSM_Component__c RSMComponent = new RSM_Component__c(Name = 'HistoryViewer Controller Test', 
	    														I_P_Address__c = '120.120.120.1', Unit_Number__c = Vehicle.Id);
	    insert RSMComponent;
	    RSMComponent.I_P_Address__c = '120.120.120.2';
	    update RSMComponent;
	    
	    ApexPages.StandardController Control = new ApexPages.StandardController(Acc1);
	    HistoryViewer_Controller ClassObj = new HistoryViewer_Controller(Control);	    
	    ClassObj.ObjectName = 'RSM_Component__c';
	    ClassObj.FieldName = 'I_P_Address__c';
	    ClassObj.VehicleName = Vehicle.Id;
	    // Below Account Date fields are used as place holder on the VF page to take user input. Based on these dates history is queried
	    ClassObj.AccDate.addr_verified_date__c = System.today().addDays(-15);
	    ClassObj.AccDate.BAD_ADDR_DATE__c = System.today().addDays(15);
	    ClassObj.SearchHistory();
	    // This must return 0 Account History record As in Test method history never populates
	    System.assertEquals(0, ClassObj.InnerClassObj.size());
	    
	    Test.StopTest();
    }
    static testMethod void UnitTest_For_POHistoryView()
    {
        // TO DO: implement unit test
        RSMCreateTestData.GetCustomSettingsRecord();
    	
    	Test.StartTest();
    	        
		Account Acc1 = new Account();
        Acc1.name = 'Test';
        Acc1.account_classification__c = 'Key Account';
        Acc1.central_decisionmaking__c = False;
        Acc1.Type = 'Customer';
        Acc1.Account_Classification__c = 'National';
        Acc1.LesseeNo__c = '0123123';
        insert Acc1;
        Acc1.Account_Classification__c = 'Local';
        update Acc1;
    	
    	Customer_Branch__c CustomerBranch = new Customer_Branch__c();
	    CustomerBranch.Name = 'Test Customer Branch';
	    CustomerBranch.Ryder_HQ_Account__c = Acc1.Id;
	    insert CustomerBranch;
	    
	    Vehicle__c Vehicle = new Vehicle__c(Unit__c = '123456');
	    Vehicle.Name = '1234';
	    Vehicle.CUSTOMER_BRANCH__c = CustomerBranch.Id;
	    Vehicle.RSM__c = 'Approved';
	    Vehicle.Account__c = Acc1.Id;
	    insert Vehicle;
	    
	    RSM_PO__c RSM_PO = new RSM_PO__c(DateOrdered__c = System.today(), 
	    									Name = 'Test PO',
	    									DateReceived__c = System.today(), 
	    									Account__c = Acc1.Id, Unit_Number__c = Vehicle.Id);
	    insert RSM_PO;
	    
	    ApexPages.StandardController Control = new ApexPages.StandardController(Acc1);
	    HistoryViewer_Controller ClassObj = new HistoryViewer_Controller(Control);	    
	    ClassObj.ObjectName = 'RSM_PO__c';
	    ClassObj.FieldName = 'DateReceived__c';
	    ClassObj.VehicleName = Vehicle.Id;
	    // Below Account Date fields are used as place holder on the VF page to take user input. Based on these dates history is queried
	    ClassObj.AccDate.addr_verified_date__c = System.today().addDays(-15);
	    ClassObj.AccDate.BAD_ADDR_DATE__c = System.today().addDays(15);
	    ClassObj.SearchHistory();
	    // This must return 0 Account History record As in Test method history never populates
	    System.assertEquals(0, ClassObj.InnerClassObj.size());
	    
	    Test.StopTest();
    }
}