SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>RSM_AC_Classification__c</fullName>
        <description>RydeSmart Account Classification</description>
        <inlineHelpText>If RS Account Classification is changed manually then Check &quot;Do Not Override AC&quot; field.</inlineHelpText>
        <label>RydeSmart Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Key Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Key Account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RSM_CCM_manual_Update__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field to check if the CCM is Manually Updated</description>
        <label>Do Not Override CCM</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RSM_CCMs__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to Store RydeSmart&apos;s CCM (Customer Care Manager) owner</description>
        <inlineHelpText>If CCM is changed Manually then check &quot;Do Not Override CCM&quot; field.</inlineHelpText>
        <label>CCM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RSM_Onboarding__c</fullName>
        <description>Field to Store onboarding status of rydesmart account</description>
        <label>Onboarding</label>
        <picklist>
            <picklistValues>
                <fullName>Initiation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacted and Training Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trained</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Researching</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/classes/RSMOnboardingFlowBatch_Test.cls
@isTest
private class RSMOnboardingFlowBatch_Test{

    static testmethod void unitTest(){
    Test.startTest();
	RSMCreateTestData.GetCustomSettingsRecord();
    
    Account Ac=new Account ();
    Ac.Name ='Test';
    Ac.RSM_Onboarding__c='Initiation';
    Ac.RSM_AC_Classification__c='Key Account';
    Ac.RSM_CCMs__c=UserInfo.getUserId();
    Ac.RSM_CCM_manual_Update__c=true;
    insert Ac;
    
    RSMOnboardingFlowBatch robf= new RSMOnboardingFlowBatch (); 
    robf.query='select Id from Account where Id=\''+Ac.Id+'\' Limit 1'; 
    database.executebatch(robf);
    
    Test.stopTest();

}
}