SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Classification__c</fullName>
        <label>Account Classification</label>
        <picklist>
            <picklistValues>
                <fullName>National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coordinated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Coordinated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National - Cash Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local - Cash Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Cash and Non-Cash</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_Classification__c</fullName>
        <formula>TEXT( Account.Account_Classification__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Classification</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_100_Ownership__c</fullName>
        <description>Select Yes if this company owned their entire fleet when we got them, regardless of who was providing maintenance services, or they went to 100% ownership if we lost them. Select No if this company had any portion of their fleet under a lease contract</description>
        <inlineHelpText>Select Yes if this company owned their entire fleet when we got them, regardless of who was providing maintenance services, or they went to 100% ownership if we lost them. Select No if this company had any portion of their fleet under a lease contract</inlineHelpText>
        <label>Customer 100% Ownership</label>
        <picklist>
            <controllingField>Deal_lost_to_Won_from_whom__c</controllingField>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Estimated_Proposal_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Estimated Proposed Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Original_Decision_Maker__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Original Decision Maker</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>Contact.STATUS_ACTIVE__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>The Contact you are adding as an Original Decision Maker must be an active Contact within the same Account where you are creating the new Opportunity.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Opportunity_Split__c.object
<CustomObject>
    <description>Used to display the National/Coordinated Account and Local Account splits on an opportunity.  This object will be used to perform pipeline reports.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Opportunity for which the Split is valid</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Splits</relationshipLabel>
        <relationshipName>Opportunity_Splits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sales_Team_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Team Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunity_Splits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Split</label>
    <nameField>
        <displayFormat>SPLIT-{000000}</displayFormat>
        <label>Opportunity Split #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Splits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/classes/test_OpportunityUpdateTrigger.cls
@isTest
private with sharing class test_OpportunityUpdateTrigger {

    private static User createUser(){
        Profile pro = [select id from profile where name = 'standard user'][0];
        User u1 = new user();
        u1.username = 'opptest@ryder.com';
        u1.LastName = 'lastname';
        u1.Email = 'mherlihy@salesforce.com';
        u1.Alias = 'tuser';
        u1.CommunityNickname = 'tnick';
        u1.profileid = pro.id;
        u1.TimeZoneSidKey = 'America/New_York';
        u1.LocaleSidKey = 'en_US';
        u1.EmailEncodingKey = 'ISO-8859-1';
        u1.LanguageLocaleKey = 'en_US';
        insert u1;
        return u1;
    }

    private static Account createAccount(){
        Account a = new Account();
        a.BillingState = 'IL';
        a.BillingCountry = 'US';
        a.BillingPostalCode = RyderGlobalVariables.TEST_POST_CODE;
        a.name = 'test account';
        a.Account_Classification__c = 'Local';
        insert a;
        
        return a;
    }
    
    private static Contact createContact(Account a){
        Contact c = New Contact (); 
        c.FirstName = 'TestFirst'; 
        c.LastName = 'TestLast'; 
        c.email = 'TestContact@test.com';
        c.accountId = a.Id;
        insert c;
        return c;
    }
    
    private static Opportunity createOpportunity(Account a, Contact c){
        Opportunity o = new Opportunity();
        o.AccountId = a.id;
        o.Original_Decision_Maker__c = c.id;
        o.CloseDate = date.today()+2;
        o.StageName = 'Qualifying';
        o.name = 'test opportunity';
        o.Estimated_Proposal_Date__c = System.today() + 1;
        insert o;
        return o;
    }

    static testMethod void test_OpportunityUpdateTrigger(){
        User u = createUser();
        Account a = createAccount();
        Contact c = createContact(a);
        Opportunity o = createOpportunity(a, c);
        //Opportunity_Split__c os = [select id, sales_team_member__c from Opportunity_Split__c where Opportunity__c = :o.id];
        o.OwnerId = u.id;
        update o;
        //Opportunity_Split__c osupdated = [select id, sales_team_member__c from Opportunity_Split__c where Opportunity__c = :o.id];
        //system.assertequals(osupdated.sales_team_member__c, u.id);
    }
    
    static testMethod void test_OpportunityUpdateTrigger_CaseCreate(){
        
        User u = createUser();
        Account a = createAccount();
        Contact c = createContact(a);
        Opportunity oppty = createOpportunity(a, c);
        //Opportunity oppty = new Opportunity();
        oppty.StageName = 'Booked';
        oppty.Customer_100_Ownership__c = 'Yes';
        oppty.OwnerId = u.id;
        update oppty;
    }

}