SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Classification__c</fullName>
        <label>Account Classification</label>
        <picklist>
            <picklistValues>
                <fullName>National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coordinated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Coordinated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National - Cash Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local - Cash Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Cash and Non-Cash</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Central_Decisionmaking__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Select this if the sales decisions are made at the National / Parent Account level.</inlineHelpText>
        <label>Central Decisionmaking</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CustomerTypeID__c</fullName>
        <description>Customer type indicating FMS or RIL. Realtime update of both SFDC and RADAR whenever this value is changed in either system.      Question: Does RADAR care about this or any changes to this field?</description>
        <label>Customer Type</label>
        <picklist>
            <picklistValues>
                <fullName>FMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RIL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FMS Rental</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>LesseeNo__c</fullName>
        <description>Realtime update of both SFDC and RADAR whenever this value is changed in either system</description>
        <label>Lessee Number</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Available_24_7__c</fullName>
        <description>Indicate if this Contact is available to contact at all hours of the day.</description>
        <inlineHelpText>Indicate if this Contact is available to contact at all hours of the day.</inlineHelpText>
        <label>Available 24/7?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact_Source__c</fullName>
        <description>This field tells if the contact is created by lead convesion process or manually by clicking new contact button.</description>
        <label>Contact Source</label>
        <picklist>
            <picklistValues>
                <fullName>Lead Conversion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manual</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <label>Post Sales Contact Role</label>
        <picklist>
            <picklistValues>
                <fullName>After Hours</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P.O. Authorization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RCRC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Target Marketing Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executive Sponsorship Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RydeSmart</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Maintenance_Contact_Type__c</fullName>
        <label>Maintenance Contact - All Branches</label>
        <picklist>
            <picklistValues>
                <fullName>Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tertiary</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Primary</fullName>
        <active>true</active>
        <label>Primary</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Customer_Branch__c.object
<CustomObject>
    <description>Customer Branches at Ryder</description>
    <fields>
        <fullName>Ryder_HQ_Account__c</fullName>
        <description>M/D field between Customer Branch and HQ Accounts</description>
        <label>Ryder HQ Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer / Branch</relationshipLabel>
        <relationshipName>Customer_Branches</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Customer / Branch</label>
    <nameField>
        <label>Customer Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer / Branch</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Global_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Global Settings</label>
</CustomObject>

SFDC Automation/src/objects/Key_Contact__c.object
<CustomObject>
    <description>CSI and Maintenance Contacts</description>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AccountId</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Key Contacts</relationshipLabel>
        <relationshipName>Key_Contacts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Available_24_7__c</fullName>
        <inlineHelpText>Indicate if this Contact is available to contact at all hours of the day.</inlineHelpText>
        <label>Available 24/7?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <inlineHelpText>Select which role this Contact serves for this Customer/Branch.</inlineHelpText>
        <label>Contact Role</label>
        <picklist>
            <picklistValues>
                <fullName>CSI Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maintenance Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RydeSmart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RydeSmart Mktg</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IFT Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <inlineHelpText>Select the Contact Type.  Only one contact can be listed as Primary for a Customer/Branch.</inlineHelpText>
        <label>Contact Type</label>
        <picklist>
            <picklistValues>
                <fullName>Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tertiary</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.STATUS_ACTIVE__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Related Branches</relationshipLabel>
        <relationshipName>Key_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Branch__c</fullName>
        <description>Joiner object used for CSI and Maintenance Contacts</description>
        <label>Customer / Branch</label>
        <referenceTo>Customer_Branch__c</referenceTo>
        <relationshipLabel>Key Contacts</relationshipLabel>
        <relationshipName>Key_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Key Contact</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Key Contact #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Key Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Suspect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <description>The field use for Vehicle Unit sent from Eloqua as UVS Lead and will be used to autopopulate Customer Needs at the time of creation</description>
        <label>Unit #</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup on Accounts</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CUSTOMER_BRANCH__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field for Customer Branch</description>
        <label>Customer Branch</label>
        <referenceTo>Customer_Branch__c</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RSM__c</fullName>
        <description>Displays RydeSmart contract status</description>
        <label>RS Contract Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Printed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to SSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by SSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deleted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <externalId>true</externalId>
        <label>Unit Number</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <recordTypes>
        <fullName>Rental</fullName>
        <active>true</active>
        <description>Record Type for Rental Vehicles</description>
        <label>Rental</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/RSM_NonLeaseContract_Controller_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class RSM_NonLeaseContract_Controller_Test
{
	public static Account InsertAccount(String RecordTypeId)
	{
		Account Acc1 = new Account();
	    Acc1.Name = 'Test';
	    Acc1.account_classification__c = 'Key Account';
	    Acc1.central_decisionmaking__c = False;
	    Acc1.type = 'Customer';
	    Acc1.Account_Classification__c = 'National';
	    Acc1.LesseeNo__c = '0123123';
        Acc1.Type='Customer';
        Acc1.BillingStreet='13335 Seventh Concession';
        Acc1.BillingCity='Miami';
        Acc1.ShippingState='FL';
        Acc1.ShippingCountry='US';
        //Acc1.CustomerTypeID__c=;
        Acc1.BillingPostalCode = '33378';
        Acc1.RecordTypeId = RecordTypeId;
        insert Acc1;
        return Acc1;
    }
	public static Customer_Branch__c InsertCustomerBranch(String AccId)
	{
		Customer_Branch__c CustomerBranch = new Customer_Branch__c();
	    CustomerBranch.Name = 'Test Customer Branch';
	    CustomerBranch.Ryder_HQ_Account__c = AccId;
	    insert CustomerBranch;
	    return CustomerBranch;
	}
	public static Contact InsertContact(String AccId)
	{
		Contact Cont1 = new Contact();
		Cont1.AccountId = AccId;
		Cont1.FirstName = 'Test Contact';
		Cont1.LastName = 'Sample';
		Cont1.Email = 'test8979123@rydertest.com';
		Cont1.Maintenance_Contact_Type__c = 'Primary';
		Cont1.Phone = '(123) 456-8789';
		Cont1.Contact_Source__c = 'Lead Conversion';
		insert Cont1;
	    return Cont1;
	}
	public static Key_Contact__c InsertKeyContact(String AccId, String ContId, String CustomerBranchId)
	{
		Key_Contact__c Key_Contact = new Key_Contact__c(Contact_Role__c = 'RydeSmart',
    													Contact__c = ContId, AccountId__c = AccId, 
    													Customer_Branch__c = CustomerBranchId, Available_24_7__c = 'YES', 
    													Contact_Type__c = 'Primary');
    	insert Key_Contact;
	    return Key_Contact;
	}
	public static Vehicle__c InsertVehicle(String AccId, String CustomerBranchId, String sRecordType, String sNumber)
	{
		
		Vehicle__c Vehicle = new Vehicle__c();
	    Vehicle.Name = '1234';
	    Vehicle.CUSTOMER_BRANCH__c = CustomerBranchId;
	    Vehicle.RSM__c = 'Approved';
	    Vehicle.Account__c = AccId;
	    Vehicle.RecordTypeId = sRecordType;
	    Vehicle.Unit__c = sNumber;
	    insert Vehicle;
	    return Vehicle;
	}
	
    static testMethod void TestCovrage_For_RSM_AutoRegContractDetails()
    {
        // TO DO: implement unit test
        Test.startTest();
	    	RSMCreateTestData.GetCustomSettingsRecord();
	    	String AccRecordTypeId = [select Id from RecordType where SobjectType = 'Account' and Name = 'Ryder FMS Branch Account'].Id;
	    	
			Account Acc1 = InsertAccount(AccRecordTypeId);    	
	    	Customer_Branch__c CustomerBranch = InsertCustomerBranch(Acc1.id);    
			Contact Cont1 = InsertContact(Acc1.Id);    	
	    	Key_Contact__c Key_Contact = InsertKeyContact(Acc1.Id, Cont1.Id, CustomerBranch.Id);    	
	    	List<RecordType> lRecordType = [Select r.SobjectType, r.Name, r.Id From RecordType r 
	    									where SobjectType = 'Vehicle__c' and 
	    									(Name = 'Non Ryder Vehicle (NRV)' OR Name = 'Rental')];
	    	Vehicle__c Vehicle = null;
	    	Vehicle__c Vehicle1 = null;
	    	if(lRecordType.size() > 0)
	    	{
		    	Global_Settings__c CaseProposalRecordType = new Global_Settings__c(Name = '7');
		    	CaseProposalRecordType.IsActive__c = True;
		    	CaseProposalRecordType.Comment__c = 'RecordType';
		    	CaseProposalRecordType.Type__c = 'RecordType';
		    	CaseProposalRecordType.Object_Name__c = 'Vehicle';
		    	CaseProposalRecordType.Value__c = lRecordType[0].ID;
		    	insert CaseProposalRecordType;
		    	Vehicle = InsertVehicle(Acc1.Id, CustomerBranch.Id, lRecordType[0].Id, '700000');
	    	}
	    	if(lRecordType.size() > 1)
	    	{
		    	Global_Settings__c CaseProposalRecordType1 = new Global_Settings__c(Name = '8');
		    	CaseProposalRecordType1.IsActive__c = True;
		    	CaseProposalRecordType1.IsActive__c = True;
		    	CaseProposalRecordType1.Comment__c = 'RecordType';
		    	CaseProposalRecordType1.Type__c = 'RecordType';
		    	CaseProposalRecordType1.Object_Name__c = 'Vehicle';
		    	CaseProposalRecordType1.Value__c = lRecordType[1].ID;
		    	insert CaseProposalRecordType1;
		    	Vehicle1 = InsertVehicle(Acc1.Id, CustomerBranch.Id, lRecordType[1].Id, '700001');
	    	}
	    	
	    	RSM_NonLeaseContract_Controller ClassObj = new RSM_NonLeaseContract_Controller();
	    	ClassObj.RSM_Contract.Account__c = Acc1.Id;
	    	ClassObj.QueryVehicleData();
	    	ApexPages.currentPage().getParameters().put('rowno', '4');
	    	ClassObj.DeleteRow();
	    	ClassObj.ResetData();
	    	ClassObj.SaveData();
	    	for(RSM_NonLeaseContract_Controller.InnerClass Obj : ClassObj.InnerClassObj)
			{
				Obj.Vehicle = Vehicle.Id;				
			}
	    	ClassObj.SaveData();
	    	for(RSM_NonLeaseContract_Controller.InnerClass Obj : ClassObj.InnerClassObj)
			{
				Obj.Vehicle = Vehicle.Id;
				Obj.RSM_ContractDetail.Rate__c = 123;
				Obj.RSM_ContractDetail.EffectiveDate__c = null;
			}
	    	ClassObj.SaveData();
	    	for(RSM_NonLeaseContract_Controller.InnerClass Obj : ClassObj.InnerClassObj)
			{
				Obj.Vehicle = Vehicle.Id;
				Obj.RSM_ContractDetail.Rate__c = 123;
				Obj.RSM_ContractDetail.EffectiveDate__c = System.now();
			}
	    	ClassObj.SaveData();
	    	Integer i = 0;
	    	for(RSM_NonLeaseContract_Controller.InnerClass Obj : ClassObj.InnerClassObj)
			{
				i++;
				Obj.RSM_ContractDetail.Rate__c = 123;
				Obj.RSM_ContractDetail.EffectiveDate__c = System.now();
				Obj.RSM_ContractDetail.Is_Current__c = true;
				if(i == 1)
				{
					Obj.Vehicle = Vehicle.Id;
				}
				else if(i == 2)
				{
					Obj.Vehicle = Vehicle1.Id;
				}
				else
				{
					Obj.Vehicle = '--None--';
					Obj.RSM_ContractDetail.Rate__c = 123;
					Obj.RSM_ContractDetail.EffectiveDate__c = System.now();
				}
			}
			ClassObj.getDocumentTypeNames();
			ClassObj.getStatusNames();
			ClassObj.DocumentTypeName = 'RPM';
			system.debug('--------------------------------->'+ClassObj.InnerClassObj);
	    	ClassObj.SaveData();
	    	system.debug('--------------------------------->'+ApexPages.getMessages());
	    	
        Test.stopTest();
    }
}