SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Company_Lead_Type__c</fullName>
        <label>Company Lead Type</label>
        <picklist>
            <picklistValues>
                <fullName>Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Individual</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CustomerTypeID__c</fullName>
        <description>Customer type indicating FMS or RIL. Realtime update of both SFDC and RADAR whenever this value is changed in either system.      Question: Does RADAR care about this or any changes to this field?</description>
        <label>Customer Type</label>
        <picklist>
            <picklistValues>
                <fullName>FMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RIL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FMS Rental</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Employee_Email__c</fullName>
        <label>Employee Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Employee_Name__c</fullName>
        <label>Employee Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employee_Phone__c</fullName>
        <description>The phone number of the employee that comes from the employee leads</description>
        <label>Employee Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Employee_Zipcode__c</fullName>
        <description>The zip code of the employee that comes from the employee leads.</description>
        <label>Employee Zipcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RyderProbabilityMatch__c</fullName>
        <label>Accuracy Probability</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SapID__c</fullName>
        <description>The Sap ID of the employee that comes from the employee needs.</description>
        <label>SapID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/AccountShareCustom__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AccountId</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Share Custom</relationshipLabel>
        <relationshipName>Account_Share_Custom</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GroupId__c</fullName>
        <label>GroupId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>AccountShareCustom</label>
    <nameField>
        <label>AccountShareCustom Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Share Custom</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Email_Does_Not_Exist_Reason__c</fullName>
        <description>Dependent on Email Does Not Exist Flag</description>
        <inlineHelpText>Select a reason you have not entered an Email Address.</inlineHelpText>
        <label>Email Does Not Exist Reason</label>
        <picklist>
            <controllingField>Email_does_not_exist__c</controllingField>
            <picklistValues>
                <fullName>Contact has no e-mail address</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact doesnt want to share e-mail address</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>I will update later</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invalid Email</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Email_does_not_exist__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Does Email Exist</description>
        <label>Email does not exist</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Customer_Type__c</fullName>
        <label>Customer Type</label>
        <picklist>
            <picklistValues>
                <fullName>FMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RIL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FSL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Email_does_not_exist__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Email does not exist</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Employee_Email__c</fullName>
        <label>Employee Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Employee_Name__c</fullName>
        <label>Employee Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employee_Phone__c</fullName>
        <description>The phone number of the employee for employee leads</description>
        <label>Employee Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Employee_Zipcode__c</fullName>
        <description>The zip code of the employee for employee leads</description>
        <label>Employee Zipcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity_Type__c</fullName>
        <label>Entity Type</label>
        <picklist>
            <picklistValues>
                <fullName>Incorporated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Individual Consumer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Lead_Source_Detail__c</fullName>
        <label>Lead Source Detail</label>
        <picklist>
            <controllingField>LeadSource</controllingField>
            <picklistValues>
                <fullName>Walk-in</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vendor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Word of Mouth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>End of Lease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ryder 800 Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rental Counter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VSM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BDM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CDM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DBD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DNA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supply Chain Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trade Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ryder web site visitor via web search</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Truck Paper</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TruckerAds.com</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trucker.com</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CommercialTruckTrader.com</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transportation Direct Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Red Cross</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>iPad Purl Promotion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food and Beverage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billboard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yellow Pages</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blitz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Seminar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Self-Generated</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>National_Account_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Please indicate if this should be a National Account</inlineHelpText>
        <label>National Account?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SapID__c</fullName>
        <description>This field will be used by web to lead users to get credit for the leads.</description>
        <label>SapID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/classes/test_NewAccountcontact.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes and validating the lead conversion and contact management.
 *
 */
@isTest
private class test_NewAccountcontact
{
    // Create lead to convert
    public static User sysAdmin = TestUtilUvs.createUser(True);
    private static Lead createLead(String country)
    {
        Lead lead = new Lead();
        lead.FirstName = RyderGlobalVariables.TEST_FIRST_NAME;
        lead.LastName = RyderGlobalVariables.TEST_LAST_NAME;
        lead.Company = RyderGlobalVariables.TEST_PRIMARY_NAME;
        lead.Status = RyderGlobalVariables.TEST_STATUS;
        lead.LeadSource = RyderGlobalVariables.TEST_SOURCE;
        lead.LeadSource = 'Employee Referral' ;
        lead.Street = RyderGlobalVariables.TEST_ADDRESS_LINE;
        lead.City = RyderGlobalVariables.TEST_CITY;
        lead.SapID__c = 'test';
        lead.Employee_Zipcode__c = '302019';
        lead.Employee_Phone__c = '(999) 999-9999';
        lead.Employee_Name__c = 'test';
        lead.Employee_Email__c = 'abc@gmail.com';
        lead.Entity_Type__c = 'Individual Consumer';
        lead.phone = '(999) 999-9999';

        lead.LeadSource = 'Inbound';
        lead.Lead_Source_Detail__c = 'Walk-in';
        
        if (country == RyderGlobalVariables.COUNTRIES_USA) {
            lead.State = RyderGlobalVariables.TEST_STATE;
            lead.PostalCode = RyderGlobalVariables.TEST_POST_CODE;
        } else {
            lead.State = RyderGlobalVariables.TEST_STATE_CANADA;
            lead.PostalCode = RyderGlobalVariables.TEST_CANADA_POST_CODE;
        }
        lead.National_Account_Flag__c = true;
        lead.Country = country;
        
        lead.Customer_Type__c = RyderGlobalVariables.CustomerType.FMS.name();
        // lead.Country = 'US';
        insert lead;
        
        return lead;
    }
    
    // Create Account to attach to existing lead convert
    private static Account createAccount(String country)
    {
        
        Account account1 = new Account();
        account1.RyderProbabilityMatch__c = 100.00;
        account1.Name = RyderGlobalVariables.TEST_PRIMARY_NAME;
        account1.phone = '(999) 999-9999';
        account1.ShippingStreet = RyderGlobalVariables.TEST_ADDRESS_LINE;
        account1.ShippingCity = RyderGlobalVariables.TEST_CITY;
        
            account1.ShippingState = RyderGlobalVariables.TEST_STATE;
            account1.ShippingPostalCode = RyderGlobalVariables.TEST_POST_CODE;
            account1.ShippingCountry = RyderGlobalVariables.COUNTRIES_USA;
 
        account1.CustomerTypeID__c = RyderGlobalVariables.CustomerType.FMS.name();
        account1.billingstate = 'IL';
        insert account1;        
        
        
        Account account = new Account();
        account.parentId = account1.id;
        account.RyderProbabilityMatch__c = 100.00;
        account.Name = RyderGlobalVariables.TEST_PRIMARY_NAME;
        account.phone = '(999) 999-9999';
        account.ShippingStreet = RyderGlobalVariables.TEST_ADDRESS_LINE;
        account.ShippingCity = RyderGlobalVariables.TEST_CITY;
        if (country == RyderGlobalVariables.COUNTRIES_USA) {
            account.ShippingState = RyderGlobalVariables.TEST_STATE;
            account.ShippingPostalCode = RyderGlobalVariables.TEST_POST_CODE;
            account.ShippingCountry = RyderGlobalVariables.COUNTRIES_USA;
        } else {
            account.ShippingState = RyderGlobalVariables.TEST_STATE_CANADA;
            account.ShippingPostalCode = RyderGlobalVariables.TEST_CANADA_POST_CODE;
            account.ShippingCountry = RyderGlobalVariables.COUNTRIES_CANADA;
        }

        account.CustomerTypeID__c = RyderGlobalVariables.CustomerType.FMS.name();
        account.billingstate = 'IL';
        insert account;
        
        return account;
    }

    // Create Contact to attach to existing lead convert
    private static Contact createContact(Id acctId)
    {
        Contact contact = new Contact();
        contact.FirstName = RyderGlobalVariables.TEST_FIRST_NAME;
        contact.LastName = RyderGlobalVariables.TEST_LAST_NAME;
        contact.Phone = null;
        contact.Email_does_not_exist__c = true;
        contact.Email_Does_Not_Exist_Reason__c = 'I will update it later';
        contact.AccountId = acctId;
        insert contact;
        
        return contact;
    }
    
    // Basic test checks if the lead is converted with creation of USA account and contact 
    static testMethod void test_NewAccountPageFromLeadUSA() 
    {
       // User sysAdmin = TestUtilUvs.createUser(True);

        System.runAs ( sysAdmin ) {
            
            
        Lead lead = createLead(RyderGlobalVariables.COUNTRIES_USA);
        Account account = createAccount(RyderGlobalVariables.COUNTRIES_USA);
        Contact cntct = createContact(account.Id);
        // Start the test
        Test.startTest();
        account.Company_Lead_Type__c = 'Individual';
        update account;
        RyderGlobalVariables.IS_TEST = true;
        RyderGlobalVariables.UPDATE_ACCOUNT_TRIGGER = false;
        // Set the Page Reference
        PageReference newAccountPage = Page.NewAccount;
        Test.setCurrentPage(newAccountPage);
                    
        // Set the model action
        ApexPages.currentPage().getParameters().put('leadId', lead.Id);
        ApexPages.currentPage().getParameters().put('fromLead', 'true');

        // Create a standard controller 
        ApexPages.Standardcontroller controller = new ApexPages.Standardcontroller(account); 
        
        //create instance of pages controller
        newAccountContactController newAccountContactController = new newAccountContactController(controller);
        
        newAccountContactController.isUVSLead = true;
        newAccountContactController.isIndividualLead = true;
        newAccountContactController.convertIndividualLead();
        // Lookup values
        List<SelectOption> selectCountries = newAccountContactController.getItemsCountries();
        List<DBAccount> dbAccounts = newAccountContactController.getDBAccountToDisplay();
        Account accountRecordOwner = newAccountContactController.getRecordOwner();
        
        newAccountContactController.account = account;
        newAccountContactController.isIndividualLead = false;
        PageReference pageRefSearch = newAccountContactController.doSearch();

        System.debug('Account - '+accountRecordOwner);
        
        // Call the cancel function 
        PageReference pageRefCancel = newAccountContactController.Cancel();
        
        newAccountContactController.accountSelected = RyderGlobalVariables.TEST_DUNS_NUMBER;
        newAccountContactController.assignAccount();
        newAccountContactController.accountSelected = RyderGlobalVariables.TEST_DUNS_NUMBER;
        newAccountContactController.assignAccount();

        newAccountContactController.oldAccountSelected = RyderGlobalVariables.TEST_DUNS_NUMBER;
        newAccountContactController.accountSelected = '098765';
        newAccountContactController.assignAccount();

        newAccountContactController.oldAccountSelected = '';
        newAccountContactController.accountSelected = RyderGlobalVariables.TEST_DUNS_NUMBER;
        newAccountContactController.assignAccount();
        
        newAccountContactController.assignContact();
        SFDCContact afdcContact = newAccountContactController.addSFDCNewContact();

        // Call the convert function and then check the assert
        PageReference pageRef = newAccountContactController.createNewAccount();
        
        Lead leadToCheck = [SELECT Id, ConvertedAccountId, ConvertedContactId FROM Lead WHERE Id =: lead.Id];
        System.debug('leadToCheck - ' + leadToCheck);
        //System.assert(leadToCheck.ConvertedAccountId == null);
        //System.assert(leadToCheck.ConvertedContactId == null);
        // Stop the test
        Test.stopTest();
      } 
    }

    // Basic test checks if the lead is converted with creation of Canada account and contact 
    static testMethod void test_NewAccountPageFromLeadCanada() 
    {
        //User sysAdmin = TestUtilUvs.createUser(True);

        System.runAs ( sysAdmin ) {
            
        
        
        Lead lead = createLead(RyderGlobalVariables.COUNTRIES_CANADA);
        Account account = createAccount(RyderGlobalVariables.COUNTRIES_CANADA);
        Contact cntct = createContact(account.Id);
        // Start the test
        Test.startTest();
                    
        RyderGlobalVariables.IS_TEST = true;
        RyderGlobalVariables.UPDATE_ACCOUNT_TRIGGER = false;
        // Set the Page Reference
        PageReference newAccountPage = Page.NewAccount;
        Test.setCurrentPage(newAccountPage);
                    
        // Set the model action
        ApexPages.currentPage().getParameters().put('leadId', lead.Id);
        ApexPages.currentPage().getParameters().put('fromLead', 'true');

        // Create a standard controller
        ApexPages.Standardcontroller controller = new ApexPages.Standardcontroller(account); 

        //create instance of pages controller
        newAccountContactController newAccountContactController = new newAccountContactController(controller);
        newAccountContactController.isUVSLead = true;
        // Lookup values
        List<SelectOption> selectCountries = newAccountContactController.getItemsCountries();
        List<DBAccount> dbAccounts = newAccountContactController.getDBAccountToDisplay();
        Account accountRecordOwner = newAccountContactController.getRecordOwner();

        PageReference pageRefSearch = newAccountContactController.doSearch();

        System.debug('Account - '+accountRecordOwner);
        
        // Call the cancel function 
        PageReference pageRefCancel = newAccountContactController.Cancel();
        
        newAccountContactController.accountSelected = RyderGlobalVariables.TEST_DUNS_NUMBER;
        newAccountContactController.assignAccount();
        newAccountContactController.accountSelected = RyderGlobalVariables.TEST_DUNS_NUMBER;
        newAccountContactController.assignAccount();

        newAccountContactController.oldAccountSelected = RyderGlobalVariables.TEST_DUNS_NUMBER;
        newAccountContactController.accountSelected = '098765';
        newAccountContactController.assignAccount();
        
        newAccountContactController.oldAccountSelected = '';
        newAccountContactController.accountSelected = RyderGlobalVariables.TEST_DUNS_NUMBER;
        newAccountContactController.assignAccount();
        
        newAccountContactController.assignContact();
        SFDCContact afdcContact = newAccountContactController.addSFDCNewContact();

        // Call the convert function and then check the assert
        PageReference pageRef = newAccountContactController.createNewAccount();
        
        Lead leadToCheck = [SELECT Id, ConvertedAccountId, ConvertedContactId FROM Lead WHERE Id =: lead.Id];
        System.debug('leadToCheck - ' + leadToCheck);
        //System.assert(leadToCheck.ConvertedAccountId == null);
        //System.assert(leadToCheck.ConvertedContactId == null);
        // Stop the test
        Test.stopTest();
        }
    }

    // Basic test checks if the lead is converted with creation of Canada account and contact 
    static testMethod void test_NewAccountPageFromNewAccountCanada() 
    {
       
        //User sysAdmin = TestUtilUvs.createUser(True);

        System.runAs ( sysAdmin ) {
            
       
        // Start the test
        Test.startTest();
        Account account = createAccount(RyderGlobalVariables.COUNTRIES_CANADA);
        Contact cntct = createContact(account.Id);
                    
        RyderGlobalVariables.IS_TEST = true;
        RyderGlobalVariables.UPDATE_ACCOUNT_TRIGGER = false;
        // Set the Page Reference
        PageReference newAccountPage = Page.NewAccount;
        Test.setCurrentPage(newAccountPage);
                    
        // Create a standard controller
        ApexPages.Standardcontroller controller = new ApexPages.Standardcontroller(account); 

        //create instance of pages controller
        newAccountContactController newAccountContactController = new newAccountContactController(controller);
        newAccountContactController.isUVSLead = true;
        newAccountContactController.account = account;
        newAccountContactController.contact = cntct;

        // Lookup values
        List<SelectOption> selectCountries = newAccountContactController.getItemsCountries();
        List<DBAccount> dbAccounts = newAccountContactController.getDBAccountToDisplay();
        Account accountRecordOwner = newAccountContactController.getRecordOwner();

        PageReference pageRefSearch = newAccountContactController.doSearch();

        System.debug('Account - '+accountRecordOwner);
        
        // Call the cancel function 
        PageReference pageRefCancel = newAccountContactController.Cancel();
        
        newAccountContactController.accountSelected = RyderGlobalVariables.TEST_DUNS_NUMBER;
        newAccountContactController.assignAccount();
        newAccountContactController.accountSelected = RyderGlobalVariables.TEST_DUNS_NUMBER;
        newAccountContactController.assignAccount();
        newAccountContactController.oldAccountSelected = '';
        newAccountContactController.accountSelected = RyderGlobalVariables.TEST_DUNS_NUMBER;
        newAccountContactController.assignAccount();
        
        newAccountContactController.assignContact();
        SFDCContact afdcContact = newAccountContactController.addSFDCNewContact();

        // Call the convert function and then check the assert
        PageReference pageRef = newAccountContactController.createNewAccount();
        System.assert(pageRef == null);
        // Stop the test
        Test.stopTest();
        }
    }

    // Basic test checks if the lead is converted with creation of Canada account and contact 
    static testMethod void test_NewAccountPageFromNewAccountUSA() 
    {
       // User sysAdmin = TestUtilUvs.createUser(True);

        System.runAs ( sysAdmin ) {
            
        
        // Start the test
        Test.startTest();
        Account account = createAccount(RyderGlobalVariables.COUNTRIES_USA);
        Contact cntct = createContact(account.Id);
                    
        RyderGlobalVariables.IS_TEST = true;
        RyderGlobalVariables.UPDATE_ACCOUNT_TRIGGER = false;
        // Set the Page Reference
        PageReference newAccountPage = Page.NewAccount;
        Test.setCurrentPage(newAccountPage);
                    
        // Create a standard controller
        ApexPages.Standardcontroller controller = new ApexPages.Standardcontroller(account); 

        //create instance of pages controller
        newAccountContactController newAccountContactController = new newAccountContactController(controller);
        newAccountContactController.isUVSLead = true;
        newAccountContactController.account = account;
        newAccountContactController.contact = cntct;

        // Lookup values
        List<SelectOption> selectCountries = newAccountContactController.getItemsCountries();
        List<DBAccount> dbAccounts = newAccountContactController.getDBAccountToDisplay();
        Account accountRecordOwner = newAccountContactController.getRecordOwner();

        PageReference pageRefSearch = newAccountContactController.doSearch();

        System.debug('Account - '+accountRecordOwner);
        
        // Call the cancel function 
        PageReference pageRefCancel = newAccountContactController.Cancel();
        
        newAccountContactController.accountSelected = RyderGlobalVariables.TEST_DUNS_NUMBER;
        newAccountContactController.assignAccount();
        newAccountContactController.accountSelected = RyderGlobalVariables.TEST_DUNS_NUMBER;
        newAccountContactController.assignAccount();
        newAccountContactController.oldAccountSelected = '';
        newAccountContactController.accountSelected = RyderGlobalVariables.TEST_DUNS_NUMBER;
        newAccountContactController.assignAccount();
        
        newAccountContactController.assignContact();
        SFDCContact afdcContact = newAccountContactController.addSFDCNewContact();

        // Call the convert function and then check the assert
        PageReference pageRef = newAccountContactController.createNewAccount();
        System.assert(pageRef == null);
        // Stop the test
        Test.stopTest();
        }
    }
    
 //AAK //////////////////////
 
     // Create Account to attach to existing lead convert
    private static Account createRentalAccount(String country)
    {
        Account account = new Account();
        account.RyderProbabilityMatch__c = 100.00;
        account.Name = RyderGlobalVariables.TEST_PRIMARY_NAME;
        account.ShippingStreet = RyderGlobalVariables.TEST_ADDRESS_LINE;
        account.ShippingCity = RyderGlobalVariables.TEST_CITY;
        if (country == RyderGlobalVariables.COUNTRIES_USA) {
            account.ShippingState = RyderGlobalVariables.TEST_STATE;
            account.ShippingPostalCode = RyderGlobalVariables.TEST_POST_CODE;
            account.ShippingCountry = RyderGlobalVariables.COUNTRIES_USA;
        } else {
            account.ShippingState = RyderGlobalVariables.TEST_STATE_CANADA;
            account.ShippingPostalCode = RyderGlobalVariables.TEST_CANADA_POST_CODE;
            account.ShippingCountry = RyderGlobalVariables.COUNTRIES_CANADA;
        }

        account.CustomerTypeID__c = 'FMS Rental';
        account.billingstate = 'IL';
        insert account;
        
        return account;
    }

        // Create Contact to attach to existing lead convert
    private static Contact createContactwithEmail(Id acctId)
    {
        Contact contact = new Contact();
        contact.FirstName = RyderGlobalVariables.TEST_FIRST_NAME;
        contact.LastName = RyderGlobalVariables.TEST_LAST_NAME;
        contact.Phone = null;
        contact.Email = 'abc@test.com';
        contact.Email_does_not_exist__c = false;
        contact.Email_Does_Not_Exist_Reason__c = null;
        contact.AccountId = acctId;
        insert contact;
        
        return contact;
    }
 
     //to work with Rental account without lead
     // Basic test checks if the lead is converted with creation of Canada account and contact 
    static testMethod void test_NewAccountPageFromNewAccountCanadaRental() 
    {
       //User sysAdmin = TestUtilUvs.createUser(True);

        System.runAs ( sysAdmin ) {
            
        
        // Start the test
        Test.startTest();
        Account account = createRentalAccount(RyderGlobalVariables.COUNTRIES_CANADA);
        Contact cntct = createContactwithEmail(account.Id);
                    
        RyderGlobalVariables.IS_TEST = true;
        RyderGlobalVariables.UPDATE_ACCOUNT_TRIGGER = false;
        // Set the Page Reference
        PageReference newAccountPage = Page.NewAccount;
        Test.setCurrentPage(newAccountPage);
                    
        // Create a standard controller
        ApexPages.Standardcontroller controller = new ApexPages.Standardcontroller(account); 

        //create instance of pages controller
        newAccountContactController newAccountContactController = new newAccountContactController(controller);
        newAccountContactController.isUVSLead = true;
        newAccountContactController.account = account;
        newAccountContactController.contact = cntct;

        // Lookup values
        List<SelectOption> selectCountries = newAccountContactController.getItemsCountries();
        List<DBAccount> dbAccounts = newAccountContactController.getDBAccountToDisplay();
        Account accountRecordOwner = newAccountContactController.getRecordOwner();

        PageReference pageRefSearch = newAccountContactController.doSearch();

        System.debug('Account - '+accountRecordOwner);
        
        // Call the cancel function 
        PageReference pageRefCancel = newAccountContactController.Cancel();
        
        newAccountContactController.accountSelected = RyderGlobalVariables.TEST_DUNS_NUMBER;
        newAccountContactController.assignAccount();
        newAccountContactController.accountSelected = RyderGlobalVariables.TEST_DUNS_NUMBER;
        newAccountContactController.assignAccount();
        newAccountContactController.oldAccountSelected = '';
        newAccountContactController.accountSelected = RyderGlobalVariables.TEST_DUNS_NUMBER;
        newAccountContactController.assignAccount();
        
        newAccountContactController.assignContact();
        SFDCContact afdcContact = newAccountContactController.addSFDCNewContact();

        // Call the convert function and then check the assert
        PageReference pageRef = newAccountContactController.createNewAccount();
        System.assert(pageRef == null);
        // Stop the test
        Test.stopTest();
        }
    }  

    static testMethod void test_NewAccountPageForAccountShareCustom() 
    {
       // User sysAdmin = TestUtilUvs.createUser(True);
        Profile p = [select p.id from Profile p where p.Name in ('VSM_VSR') LIMIT 1];
        UserRole r = [SELECT Id FROM UserRole WHERE Name LIKE '%VSM%' LIMIT 1];
        //Creating the user
        User u = new User( Username = 'uvs2@rydertest.com',
                                    Alias = 'autclon', FirstName = 'Ryder2', LastName = 'Tester2', Email = 'uvs2@rydertest.com',
                                    EmailEncodingKey = 'UTF-8', LanguageLocaleKey = 'en_US',
                                    LocalesIdKey = 'en_US', ProfileId = p.Id, TimeZonesIdKey = 'America/New_York',
                                    isActive = true, userRoleId = r.Id);
        
        User u3 = new User( Username = 'uvs3@rydertest.com',
                                    Alias = 'autclon', FirstName = 'Ryder3', LastName = 'Tester3', Email = 'uvs3@rydertest.com',
                                    EmailEncodingKey = 'UTF-8', LanguageLocaleKey = 'en_US',
                                    LocalesIdKey = 'en_US', ProfileId = p.Id, TimeZonesIdKey = 'America/New_York',
                                    isActive = true, userRoleId = r.Id);

        
        System.runAs (u) {
            
            
        Lead lead = createLead(RyderGlobalVariables.COUNTRIES_USA);
        Account account = new Account();

        // Start the test
        Test.startTest();

        // Set the Page Reference
        PageReference newAccountPage = Page.NewAccount;
        Test.setCurrentPage(newAccountPage);
                    
        // Set the model action
        ApexPages.currentPage().getParameters().put('leadId', lead.Id);
        ApexPages.currentPage().getParameters().put('fromLead', 'true');

        // Create a standard controller 
        ApexPages.Standardcontroller controller = new ApexPages.Standardcontroller(account); 
        
        //create instance of pages controller
        newAccountContactController newAccountContactController = new newAccountContactController(controller);
        
        // Call the convert function and then check the assert
        PageReference pageRef = newAccountContactController.createNewAccount();
        Account acct = newAccountContactController.account;
        
        acct.Phone = '111-111-1111';
        update acct;
            
        List<AccountShareCustom__c> accsharecust = [SELECT AccountId__c, GroupId__c FROM AccountShareCustom__c where accountId__c =: acct.Id];
        system.debug('Account Share Custom : ' + accsharecust);
        List<AccountShare> accshare = [SELECT AccountId, UserOrGroupId, RowCause FROM AccountShare where AccountId =: acct.Id];            
        system.debug('Account Share : ' + accshare);            

        delete acct;            
            
        // Stop the test
        Test.stopTest();
      } 
    } 

}