SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>RSM_Billing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Billing</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Customer_Branch__c.object
<CustomObject>
    <description>Customer Branches at Ryder</description>
    <fields>
        <fullName>Ryder_HQ_Account__c</fullName>
        <description>M/D field between Customer Branch and HQ Accounts</description>
        <label>Ryder HQ Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer / Branch</relationshipLabel>
        <relationshipName>Customer_Branches</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Customer / Branch</label>
    <nameField>
        <label>Customer Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer / Branch</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup on Accounts</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CUSTOMER_BRANCH__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field for Customer Branch</description>
        <label>Customer Branch</label>
        <referenceTo>Customer_Branch__c</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RSM_Billing_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Billing</label>
        <type>Checkbox</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/RSMUpdateBillingStatusBatch.cls
//Batch class to update billing status in Account if atleast one vehicle is billing
global class RSMUpdateBillingStatusBatch implements Database.Batchable<SObject>{

  public String query;
  global Database.QueryLocator start(Database.BatchableContext BC){
      System.debug('query : '+query);
      return Database.getQueryLocator(query);
   }
   
   global void execute(Database.BatchableContext BC, List<Account> scope){
      Map<Id,Account> accountMap=new Map<Id,Account>();
      Map<Id,Account> updateAccountMap=new Map<Id,Account>();
      Map<Id,List<Vehicle__c>> acctVehiclesListMap=new Map<Id,List<Vehicle__c>>();
      Set<Id> accSet=new Set<Id>();
      
      for(Account ac:scope){
          accountMap.put(ac.Id,ac);    
      } 
      
      for(Customer_Branch__c cb: [select Id,Ryder_HQ_Account__c,(select Id,RSM_Billing_Status__c from Vehicles__r) from Customer_Branch__c where Ryder_HQ_Account__c in:accountMap.keyset()]){
          if(acctVehiclesListMap!=null && acctVehiclesListMap.get(cb.Ryder_HQ_Account__c)!=null){
              acctVehiclesListMap.get(cb.Ryder_HQ_Account__c).addAll(cb.Vehicles__r);
          }else{
              List<Vehicle__c> vList=new List<Vehicle__c>();
              vList.addAll(cb.Vehicles__r);
              acctVehiclesListMap.put(cb.Ryder_HQ_Account__c,vList);    
          }
      }
      for(Account ac:scope){
          Boolean billingFlag=false;
          if(acctVehiclesListMap!=null && acctVehiclesListMap.get(ac.Id)!=null && acctVehiclesListMap.get(ac.Id).size()>0){
              for(Vehicle__c v:acctVehiclesListMap.get(ac.Id)){
                  if(v.RSM_Billing_Status__c==true){        
                      billingFlag=true;
                      break;    
                  }   
              }
          }
          Account acc=new Account(Id=ac.Id,RSM_Billing__c=billingFlag);
          updateAccountMap.put(ac.Id,acc);
      }
      if(updateAccountMap!=null && updateAccountMap.values().size()>0){
          update updateAccountMap.values();
      }
 
   }

   global void finish(Database.BatchableContext BC){
   }
}