SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>STATUS_ACTIVE__c</fullName>
        <description>Customer status to control visibility.</description>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>STATUS_ACTIVE__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Status Active</description>
        <label>Status Active</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Estimated_Proposal_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Estimated Proposed Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Original_Decision_Maker__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Original Decision Maker</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>Contact.STATUS_ACTIVE__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>The Contact you are adding as an Original Decision Maker must be an active Contact within the same Account where you are creating the new Opportunity.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchase_Reason__c</fullName>
        <label>Purchase Reason</label>
        <picklist>
            <picklistValues>
                <fullName>End of Lease Sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Export</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Growing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Replacing Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Salvage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Starting New Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wholesale</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>UVS_Opportunity</fullName>
        <active>true</active>
        <businessProcess>UVS Sales Process</businessProcess>
        <label>UVS Opportunity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Book_Value__c</fullName>
        <formula>Unit_Number__r.NBV__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Book Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <label>Product Line</label>
        <picklist>
            <picklistValues>
                <fullName>FSL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RPM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rydesmart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DCC Light</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fuel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Take_Price2__c</fullName>
        <label>Take Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unit_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Number</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

SFDC Automation/src/objects/Pricebook2.object
<CustomObject>
    <recordTypes>
        <fullName>UVS</fullName>
        <active>true</active>
        <description>Used by Used Vehicle Sales Group</description>
        <label>UVS</label>
    </recordTypes>
    <sharingModel>ReadSelect</sharingModel>
</CustomObject>

SFDC Automation/src/objects/UVS_SheduleA_Request__c.object
<CustomObject>
    <description>UVS SheduleA</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>ScheduleA_Request_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Buy_Out_Approved__c</fullName>
        <label>Buy-Out Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Request</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent to Lease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent to Pricing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User_Pricing_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pricing User  Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ScheduleA_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ScheduleA Request</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>SheduleA Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ScheduleA Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC Automation/src/objects/UVS_Vehicle_Information__c.object
<CustomObject>
    <description>UVS Buy-Out Calculation</description>
    <fields>
        <fullName>Book_Value__c</fullName>
        <label>Book Value</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Buy_Out_Date__c</fullName>
        <label>Buy-Out Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Location_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location Code</label>
        <referenceTo>Customer_Branch__c</referenceTo>
        <relationshipLabel>Vehicles Information</relationshipLabel>
        <relationshipName>Vehicles_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ScheduleA_Request__c</fullName>
        <label>ScheduleA Request</label>
        <referenceTo>UVS_SheduleA_Request__c</referenceTo>
        <relationshipLabel>Vehicle_Information</relationshipLabel>
        <relationshipName>Vehicle_Information</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Vehicle Information</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Vehicle Information</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <fields>
        <fullName>Ask_Price__c</fullName>
        <label>Ask Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NBV__c</fullName>
        <label>Book Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PRODUCT_LINE__c</fullName>
        <description>Product Line</description>
        <label>Product Line</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Take_Price__c</fullName>
        <label>Take Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <recordTypes>
        <fullName>UVS</fullName>
        <active>true</active>
        <description>Record Type for UVS Vehicles</description>
        <label>UVS</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/UVS_CreateOpportunities.cls
global class UVS_CreateOpportunities {

    webservice static String ProcessBuy_Out_Status(String Id)
    { 
        system.debug(LoggingLevel.INFO, '------------>' + Id);
        UVS_SheduleA_Request__c scheduleA = [SELECT Id, Buy_Out_Approved__c, User_Pricing_Name__c 
        									FROM UVS_SheduleA_Request__c 
        									WHERE Id = :Id and User_Pricing_Name__c != null];
		system.debug(LoggingLevel.INFO, '------------>' + scheduleA);
		if(scheduleA != null)
		{
			if(scheduleA.User_Pricing_Name__c != UserInfo.getUserId())
			{
				if(scheduleA.Buy_Out_Approved__c == 'New Request')
				{
					scheduleA.Buy_Out_Approved__c = 'Sent to Pricing';
					update scheduleA;
				}
				else if(scheduleA.Buy_Out_Approved__c != null && scheduleA.Buy_Out_Approved__c == 'Sent to Lease')
				{
					scheduleA.Buy_Out_Approved__c = 'Approved';
					update scheduleA;
					CreateScheduleAOpportunity(scheduleA.Id);
				}
				else
					return 'Request was already processed.';
			}
			else if(scheduleA.User_Pricing_Name__c == UserInfo.getUserId() && 
				scheduleA.Buy_Out_Approved__c != null && 
				scheduleA.Buy_Out_Approved__c == 'Sent to Pricing')
			{
				scheduleA.Buy_Out_Approved__c = 'Sent to Lease';
				update scheduleA;
			}
			else
				return 'Request was already processed.';
			return 'Request Processed!';
		}
		return 'Request Missing User Pricing Name!';
    }
	
    public static void CreateScheduleAOpportunity(String sScheduleAId){
        
        UVS_SheduleA_Request__c scheduleA = [SELECT Id, Account_Name__c, Name, OwnerId FROM UVS_SheduleA_Request__c WHERE Id = : sScheduleAId];
        List<Opportunity> opportunityResultCollection = new List<Opportunity>();
        
        //Get all location codes (grouped) to create opportunities.
        AggregateResult[] lVehicleInfo = [select Location_Code__c, MAX(Buy_Out_Date__c) from UVS_Vehicle_Information__c 
                                                            where ScheduleA_Request__c =: sScheduleAId
                                                            group by Location_Code__c];
                                                            
        system.debug(LoggingLevel.INFO, 'aaaaaaaa lVehicleInfo: ' + lVehicleInfo);
                                                            
        //Set the original decision maker for the opportunities being created. 
        String originalDecisionMaker = getOriginalDecisionMaker(scheduleA.Account_Name__c);
        system.debug(LoggingLevel.INFO, 'aaaaaaaa originalDecisionMaker: ' + originalDecisionMaker);

		//Map<Id, Opportunity> opportunityResult = new Map<Id, Opportunity>();
        //Loop through all location codes to create an opportunity for each location code listed
        integer i = 1;
        for(AggregateResult vehicle : lVehicleInfo){
            
            Opportunity opportunityResult = CreateOpportunity('ScheduleA UVS ' + i + '-' + scheduleA.Name, 'Overcome Concerns', scheduleA.Account_Name__c, scheduleA.OwnerId, originalDecisionMaker, date.today().addMonths(1), Date.valueOf(vehicle.get('expr0')), null); //expr0 is (Buy_Out_Date__c)
            opportunityResultCollection.add(opportunityResult);
            i++;
        }
        system.debug(LoggingLevel.INFO, 'aaaaaaaa opportunityResultCollection: ' + opportunityResultCollection);
        
        // In order to create price book entry for custom price books, first we need to create price book entries for standard price books
        PriceBook2 UVSPriceBook = [Select Id from PriceBook2 where Name = 'UVS' limit 1];
        // list of opportunity line items to be inserted
        List<OpportunityLineItem> listNewOppLineItem = new List<OpportunityLineItem>();
        //Loop through created opportunities (from result) to create line items based off vehicles from location codes. 
        for (Opportunity oppty: opportunityResultCollection) {
        	
        	
            //listNewOppLineItem.add(createOpportunityLineItem(vehicle, pbe.Id,pbe.Product2.Family));
        }
        
    }
   
    public static String getOriginalDecisionMaker(String accountId){

        Contact origDecMakerContact = null;
        String origDecisionMaker = '';
        
        //Check if there is a Parent Id in Account
        Account parentAccount = [SELECT ParentId FROM Account WHERE Id = :accountId];
        
        if(parentAccount.ParentId == null){
            
            //If there is no ParentId then use the oppty AccountId
            origDecMakerContact = [SELECT Id FROM Contact WHERE AccountId = :accountId AND STATUS_ACTIVE__c = true LIMIT 1];
            origDecisionMaker = origDecMakerContact.Id;
            
        }else{
            
            origDecMakerContact = [SELECT Id FROM Contact WHERE AccountId = :parentAccount.ParentId AND STATUS_ACTIVE__c = true LIMIT 1];
            origDecisionMaker = origDecMakerContact.Id;
        }
        return origDecisionMaker;
    }
    
    public static Opportunity CreateOpportunity(String oppName, 
                                                         String stageName, 
                                                         String accountId, 
                                                         String ownerId, 
                                                         String originalDecisionMaker, 
                                                         Date estimatedProposalDate, 
                                                         Date buyoutDate, 
                                                         String purchaseReason
                                                         ) {

        RecordType uvsOpptyRecordTypeId = [SELECT Id FROM RecordType WHERE SobjectType = 'Opportunity' AND DeveloperName = 'UVS_Opportunity'];
        //Map<Id, Opportunity> result = new Map<Id, Opportunity>();
        Opportunity newOpportunity = new Opportunity();
        
        newOpportunity.StageName = stageName;
        newOpportunity.Estimated_Proposal_Date__c = estimatedProposalDate;
        newOpportunity.AccountId = accountId;
        newOpportunity.OwnerId = ownerId;
        newOpportunity.Original_Decision_Maker__c = originalDecisionMaker;
        newOpportunity.Estimated_Proposal_Date__c = estimatedProposalDate;
        newOpportunity.CloseDate = buyoutDate;
        newOpportunity.Purchase_Reason__c = purchaseReason;
        newOpportunity.RecordTypeId = uvsOpptyRecordTypeId.Id; //'UVS Opportunity';
        newOpportunity.Name = oppName;
        insert newOpportunity;
        
        system.debug(LoggingLevel.INFO, 'aaaaaaaa newOpportunity: ' + newOpportunity);
        
        //result.put(newOpportunity.Id, newOpportunity);
        
        return newOpportunity;
    }
    
    // method to create opportunity line item
    // Vehicle : Vehicle Object record
    // pbeId : Id of price book entry record
    private OpportunityLineItem createOpportunityLineItem(String oppId, Vehicle__c vehicle, Id pbeId,String family){
        system.debug('::vehicle::::'+vehicle);
        OpportunityLineItem OLI = new OpportunityLineItem(Quantity=1,
                                                        Unit_Number__c = vehicle.Id,
                                                        Take_Price2__c = vehicle.Take_Price__c,
                                                        //Book_Value__c = vehicle.NBV__c,
                                                        UnitPrice = 0,
                                                        OpportunityId = oppId,
                                                        Product_Line__c  = family,
                                                        PriceBookEntryId = pbeId
                                                        );
        if(Vehicle.Ask_Price__c != null)
            OLI.UnitPrice = Vehicle.Ask_Price__c;    
        return OLI;
    }
    
}