SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>RSM_Revenue__c</fullName>
        <description>Field to display associated RydeSmart revenue of Account</description>
        <label>Monthly Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Customer_Branch__c.object
<CustomObject>
    <description>Customer Branches at Ryder</description>
    <fields>
        <fullName>Ryder_HQ_Account__c</fullName>
        <description>M/D field between Customer Branch and HQ Accounts</description>
        <label>Ryder HQ Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer / Branch</relationshipLabel>
        <relationshipName>Customer_Branches</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Customer / Branch</label>
    <nameField>
        <label>Customer Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer / Branch</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/RSM_ContractDetail__c.object
<CustomObject>
    <description>The object stores the details of the contract</description>
    <fields>
        <fullName>Is_Current__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Current</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unit_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Number</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipName>RSContractDetails</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RSM ContractDetail</label>
    <nameField>
        <label>RSM ContractDetailID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RSM ContractDetails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup on Accounts</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CUSTOMER_BRANCH__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field for Customer Branch</description>
        <label>Customer Branch</label>
        <referenceTo>Customer_Branch__c</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RSM_Billing_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Billing</label>
        <type>Checkbox</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/RSMUpdateAccountRevenueBatch.cls
//Baatch class to update Revenue in the account object from contract object
global class RSMUpdateAccountRevenueBatch implements Database.Batchable<SObject>{

   public String query;
   global Database.QueryLocator start(Database.BatchableContext BC){
      System.debug('query : '+query);
      return Database.getQueryLocator(query);
   } 
   
   global void execute(Database.BatchableContext BC, List<Account> scope){
      Map<Id,Account> accountMap=new Map<Id,Account>();
      List<Account> updateAccLst=new List<Account>();
            
      Map<Id,Double> accVehRevMap=new Map<Id,Double>();
      for(Account ac:scope){
          accountMap.put(ac.Id,ac);    
      } 
      //List<Customer_Branch__c> cbList=[select Id,Ryder_HQ_Account__c,(select Id,RSM_Billing_Status__c from Vehicles__r) from Customer_Branch__c where Ryder_HQ_Account__c in:accountMap.keyset()];    
      Set<Id> vehIds=new Set<Id>();
      
      for(Customer_Branch__c cb: [select Id,Ryder_HQ_Account__c,(select Id,RSM_Billing_Status__c from Vehicles__r) from Customer_Branch__c where Ryder_HQ_Account__c in:accountMap.keyset()]){
          for(Vehicle__c v:cb.Vehicles__r){
             vehIds.add(v.Id); 
          }
      }
      for(RSM_ContractDetail__c rc:[select Id,rate__c,Is_Current__c,Unit_Number__c,Unit_Number__r.Account__c from RSM_ContractDetail__c where Unit_Number__c in :vehIds and Is_Current__c=true]){
          if(accVehRevMap!=null && accVehRevMap.get(rc.Unit_Number__r.Account__c)!=null){
              accVehRevMap.put(rc.Unit_Number__r.Account__c,rc.rate__c+accVehRevMap.get(rc.Unit_Number__r.Account__c));
          }else{
               accVehRevMap.put(rc.Unit_Number__r.Account__c,rc.rate__c);
          }    
      }
      
      for(Id acId:accVehRevMap.keyset()){
          Account ac=new Account(Id=acId,RSM_Revenue__c=accVehRevMap.get(acId));
          updateAccLst.add(ac);    
      }
      if(updateAccLst!=null && updateAccLst.size()>0){
          update updateAccLst;
      }
 
   }

   global void finish(Database.BatchableContext BC){
   }
}