SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LesseeNo__c</fullName>
        <description>Realtime update of both SFDC and RADAR whenever this value is changed in either system</description>
        <label>Lessee Number</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RSM_AC_Classification__c</fullName>
        <description>RydeSmart Account Classification</description>
        <inlineHelpText>If RS Account Classification is changed manually then Check &quot;Do Not Override AC&quot; field.</inlineHelpText>
        <label>RydeSmart Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Key Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Key Account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RSM_CCMs__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to Store RydeSmart&apos;s CCM (Customer Care Manager) owner</description>
        <inlineHelpText>If CCM is changed Manually then check &quot;Do Not Override CCM&quot; field.</inlineHelpText>
        <label>CCM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RSM_Onboarding__c</fullName>
        <description>Field to Store onboarding status of rydesmart account</description>
        <label>Onboarding</label>
        <picklist>
            <picklistValues>
                <fullName>Initiation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacted and Training Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trained</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Researching</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Source__c</fullName>
        <description>This field tells if the contact is created by lead convesion process or manually by clicking new contact button.</description>
        <label>Contact Source</label>
        <picklist>
            <picklistValues>
                <fullName>Lead Conversion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manual</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Original_Decision_Maker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Decision Maker</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Estimated_Proposal_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Estimated Proposed Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Original_Decision_Maker__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Original Decision Maker</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>Contact.STATUS_ACTIVE__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>The Contact you are adding as an Original Decision Maker must be an active Contact within the same Account where you are creating the new Opportunity.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Specialized_Operating_Criteria__c</fullName>
        <label>Specialized Operating Criteria</label>
        <picklist>
            <picklistValues>
                <fullName>HazMat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Natural Gas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Specialized Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parking Agreement</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/classes/SpecializedOperatingCrit_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class SpecializedOperatingCrit_Test
{
  static testMethod void myUnitTest()
    {
      Test.startTest();
        
        RSMCreateTestData.GetCustomSettingsRecord();
        
        Account ac = new Account();
        ac.Name = 'Test1';
        ac.LesseeNo__c = '123';
        ac.RSM_CCMs__c = UserInfo.getUserId();
        ac.RSM_Onboarding__c = '';
        ac.RSM_AC_Classification__c  =  'National';
        insert ac;
    
    Contact c = New Contact (); 
      c.FirstName = 'TestFirst'; 
      c.LastName = 'TestLast'; 
      c.email = 'TestContact@test.com';
      c.accountId = ac.Id;
      c.Contact_Source__c = 'Lead Conversion';
      insert c;
      
        Opportunity o = new Opportunity();
        o.AccountId = ac.id;
        o.Original_Decision_Maker__c = c.id;
        o.CloseDate = date.today()+2;
        o.StageName = 'Qualifying';
        o.name = 'test opportunity';
        o.Estimated_Proposal_Date__c = System.today() + 1;  
        o.Specialized_Operating_Criteria__c = 'Parking Lot;Natural Gas;Test';      
        insert o;
        
        Test.stopTest();
    }
}