SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Classification__c</fullName>
        <label>Account Classification</label>
        <picklist>
            <picklistValues>
                <fullName>National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coordinated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Coordinated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National - Cash Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local - Cash Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Cash and Non-Cash</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Central_Decisionmaking__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Select this if the sales decisions are made at the National / Parent Account level.</inlineHelpText>
        <label>Central Decisionmaking</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LesseeNo__c</fullName>
        <description>Realtime update of both SFDC and RADAR whenever this value is changed in either system</description>
        <label>Lessee Number</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/RSM_Sales_Qus__c.object
<CustomObject>
    <description>To Store RydeSmart Pre-Launch Customer Information</description>
    <fields>
        <fullName>Account_Number__c</fullName>
        <description>Account Number</description>
        <label>Account Number</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <label>Customer Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>RSM Sales Questionnaires</relationshipLabel>
        <relationshipName>RSM_Sales_Questionnaires</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <description>Sales Persons phone number</description>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Sales_Person_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Sales Person Name</description>
        <label>Sales Person Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RSM_Sales_Questionnaires</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RSM Sales Questionnaire</label>
    <nameField>
        <label>RSM Sales Qus</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RSM Sales Questionnaires</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/classes/RSMSalesQuestionnaire_Test.cls
@isTest
private class RSMSalesQuestionnaire_Test{

    static testmethod void unitTest()
    {
	    Test.startTest();
	    
	    RSMCreateTestData.GetCustomSettingsRecord();
	    Account Acc1 = new Account();
        Acc1.name = 'Test';
        Acc1.account_classification__c = 'Key Account';
        Acc1.central_decisionmaking__c = False;
        Acc1.type = 'Customer';
        Acc1.Account_Classification__c = 'National';
        Acc1.LesseeNo__c = '0123123';
        insert Acc1;


	    RSM_Sales_Qus__c rsq = new RSM_Sales_Qus__c ();
	    rsq.Account_Number__c = Acc1.LesseeNo__c;
	    rsq.Customer_Name__c = Acc1.Id;
	    rsq.Sales_Person_Name__c = Acc1.OwnerId;
	    rsq.Date__c = System.today();
	    rsq.Phone_Number__c = Acc1.Owner.phone;
	    Insert rsq;
	    PageReference pr = Page.RSM_Sales_Questionnaire_Task_List;
    
	    Test.setCurrentPage(pr);
	    Apexpages.currentPage().getParameters().put('accId',Acc1.Id);
	    Apexpages.currentPage().getParameters().put('Id',rsq.Id);
	    Apexpages.StandardController ctrl = new Apexpages.StandardController(rsq);
	    RSMSalesQuestionnaire rq = new RSMSalesQuestionnaire(ctrl);
	    rq.save();

    	Test.stopTest();
	}
	static testmethod void unitTest1()
    {
	    Test.startTest();
	    
	    RSMCreateTestData.GetCustomSettingsRecord();
	    Account Acc1 = new Account();
        Acc1.name = 'Test';
        Acc1.account_classification__c = 'Key Account';
        Acc1.central_decisionmaking__c = False;
        Acc1.type = 'Customer';
        Acc1.Account_Classification__c = 'National';
        Acc1.LesseeNo__c = '0123123';
        insert Acc1;
		
		RSM_Sales_Qus__c rsq = new RSM_Sales_Qus__c ();
	    rsq.Account_Number__c = Acc1.LesseeNo__c;
	    rsq.Customer_Name__c = Acc1.Id;
	    rsq.Sales_Person_Name__c = Acc1.OwnerId;
	    rsq.Date__c = System.today();
	    rsq.Phone_Number__c = Acc1.Owner.phone;
	    
		PageReference pr = Page.RSM_Sales_Questionnaire_Task_List;
		Test.setCurrentPage(pr);
	    Apexpages.currentPage().getParameters().put('accId',Acc1.Id);
	    Apexpages.StandardController ctrl = new Apexpages.StandardController(rsq);
	    RSMSalesQuestionnaire rq = new RSMSalesQuestionnaire(ctrl);
	    rq.save();

    	Test.stopTest();
	}
}