SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LesseeNo__c</fullName>
        <description>Realtime update of both SFDC and RADAR whenever this value is changed in either system</description>
        <label>Lessee Number</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/RSM_Contract__c.object
<CustomObject>
    <description>Object to store RydeSmart Contract details</description>
    <fields>
        <fullName>CreatedBy__c</fullName>
        <description>To store the Created by of the Contract in the Telemetry</description>
        <label>CreatedBy</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CreatedDate__c</fullName>
        <description>To store the Created Date of the Contract in the Telemetry</description>
        <label>CreatedDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Document_Type_Name__c</fullName>
        <label>Document Type Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Lessee_Email__c</fullName>
        <label>Lessee Email</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lessee__c</fullName>
        <label>Lessee</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status_Name__c</fullName>
        <label>Status Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>RSM Contract</label>
    <nameField>
        <label>RSM Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RSM Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC Automation/src/classes/RSMAccountContracts.cls
/************************************************************************************
 *  Date            Name          Description
 * --------   --------------    ----------------
 * 1/24/2014    Saad Wali Jaan    RydeSmart Contracts Data Visibility on Accounts page        
 *************************************************************************************/

/*
* This class is defined to be a controller to the page RydeSmartContract page
*/

public with sharing class RSMAccountContracts
{
    public List<RSM_Contract__c> accountRelatedAllContracts {get;set;}
    public Account accountInfo {set; get;}
    
    public String sortOrder {get;set;}
    public String sortField {get;set;}
    
    public ApexPages.StandardSetController stdAllContractController {get;set;}
    
    public List<RSM_Contract__c> getPageAllContracts()
    {
        return stdAllContractController.getRecords();
    }
    
    public RSMAccountContracts(ApexPages.StandardController stdController) 
    {
        this.accountInfo = (Account)stdController.getRecord(); 
        sortField = 'Name';
        sortOrder = 'ASC';
        init();
    }
    
    public void changeOrder()
    {
        if(sortOrder == 'ASC')
        {
            sortOrder = 'DESC';
        }
        else
        {
            sortOrder = 'ASC';
        }
        init();
    }
    
    public void init()
    {
        if(accountInfo.Id!=null)
        {
            accountInfo = [select id, LesseeNo__c from Account where id=: accountInfo.id ];
        }
        searchAllContracts();
    }
    
    public void searchAllContracts()
    {
        accountRelatedAllContracts = new List<RSM_Contract__c>();
        stdAllContractController = new ApexPages.StandardSetController(new List<RSM_Contract__c>());
        stdAllContractController = new ApexPages.StandardSetController(Database.getQueryLocator(
        [Select r.CreatedBy__c, r.CreatedDate__c, r.Document_Type_Name__c, r.Effective_Date__c, r.Id, r.Lessee__c, r.Lessee_Email__c, r.Name, r.Status_Name__c from RSM_Contract__c r WHERE Lessee__c =:accountInfo.LesseeNo__c order by Effective_Date__c desc]));
        stdAllContractController.setpageSize(10);
    }
}