SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Additional_Comments__c</fullName>
        <inlineHelpText>Place additional comments for service handling</inlineHelpText>
        <label>Additional Comments</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Vendor account record type for legal requests</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Additional_Comments__c</fullName>
        <description>field to capture comments at the item of customer needs selection.</description>
        <inlineHelpText>field to capture comments at the item of customer needs selection.</inlineHelpText>
        <label>Additional Comments</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Original_Decision_Maker__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Original Decision Maker</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>Contact.STATUS_ACTIVE__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>The Contact you are adding as an Original Decision Maker must be an active Contact within the same Account where you are creating the new Opportunity.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Ryder_Account_Team_Role_Map__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Ryder Account Team Role Map</label>
</CustomObject>

SFDC Automation/src/objects/RyderConfig__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Provides configuration information for Ryder</description>
    <label>Ryder Config</label>
</CustomObject>

SFDC Automation/src/objects/Vehicle_List__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of vehicles with their types</description>
    <label>Vehicle List</label>
</CustomObject>

SFDC Automation/src/classes/OpptyTypeRouterControllerTest.cls
/**=============================================================================
 * Created By: Nimisha (Appirio, Inc)
 * Created Date: [09/20/2014]
 * Description: Test class for OpptyTypeRouterController Class

==============================================================================*/
@isTest
private class OpptyTypeRouterControllerTest {
  static User uvsUser;
  static Account acc;
  static Contact con;
  static Opportunity opp;
  static list<Vehicle_List__c> vehList;
  static RyderConfig__c rydConf;
  static Ryder_Account_Team_Role_Map__c ryAccTRM;
    static testMethod void myUnitTest() {
      uvsUser = TestUtilUVS.createUser(true);
      system.runAs(uvsUser) {
        vehList=TestUtilUVS.createVehicleList(true);
        rydConf = TestUtilUVS.createRyderConfig(true);
        ryAccTRM = TestUtilUVS.createRyderAccountTeamRoleMap(true);

        acc = TestUtilUVS.createAccount('Vendor','FMS',false);
        insert acc;
        con = TestUtilUVS.createContact(acc.Id, false);
        con.Additional_Comments__c = 'Testing';
        con.OwnerId = UserInfo.getUserId();
        insert con;
        opp = TestUtilUVS.createOpportunity('UVS Opportunity', acc, false, con);
        opp.Original_Decision_Maker__c = con.Id;
        insert opp;
        ApexPages.StandardController sc = new ApexPages.StandardController(opp);
        OpptyTypeRouterController controller = new OpptyTypeRouterController(sc);
        controller.redirectToAddProduct();
        opp.RecordTypeId = [Select Id from RecordType where Name = 'Parent Opportunity' and sObjectType = 'Opportunity' ].get(0).Id;
        update opp;
        sc = new ApexPages.StandardController(opp);
        controller = new OpptyTypeRouterController(sc);
        controller.redirectToAddProduct();

      }
    }
}