SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Last_12_Months_Fixed_Cost__c</fullName>
        <label>Last 12 Months - Fixed Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_12_Months_Rated_Cost__c</fullName>
        <label>Last 12 Months - Rated Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_12_Months_Revenue__c</fullName>
        <label>Last 12 Months - Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LesseeNo__c</fullName>
        <description>Realtime update of both SFDC and RADAR whenever this value is changed in either system</description>
        <label>Lessee Number</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Life_to_Date_Fixed_Cost__c</fullName>
        <label>Life to Date - Fixed Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Life_to_Date_Rated_Cost__c</fullName>
        <label>Life to Date - Rated Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Life_to_Date_Revenue__c</fullName>
        <label>Life to Date - Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RSM_AC_Classification__c</fullName>
        <description>RydeSmart Account Classification</description>
        <inlineHelpText>If RS Account Classification is changed manually then Check &quot;Do Not Override AC&quot; field.</inlineHelpText>
        <label>RydeSmart Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Key Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Key Account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RSM_CCMs__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to Store RydeSmart&apos;s CCM (Customer Care Manager) owner</description>
        <inlineHelpText>If CCM is changed Manually then check &quot;Do Not Override CCM&quot; field.</inlineHelpText>
        <label>CCM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RSM_Onboarding__c</fullName>
        <description>Field to Store onboarding status of rydesmart account</description>
        <label>Onboarding</label>
        <picklist>
            <picklistValues>
                <fullName>Initiation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacted and Training Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trained</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Researching</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UpdatedFSLRPMFields__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to check if this account&apos;s FSL and RPM fields should be recalculated or not!</description>
        <label>UpdatedFSLRPMFields</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup on Accounts</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_12_Months_Fixed_Cost__c</fullName>
        <label>Last 12 Months - Fixed Cost</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_12_Months_Rated_Cost__c</fullName>
        <label>Last 12 Months - Running Cost</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_12_Months_Revenue__c</fullName>
        <label>Last 12 Months - Revenue</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Life_to_Date_Fixed_Cost__c</fullName>
        <label>Life to Date - Fixed Cost</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Life_to_Date_Rated_Cost__c</fullName>
        <label>Life to Date - Running Cost</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Life_to_Date_Revenue__c</fullName>
        <label>Life to Date - Revenue</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PRODUCT_LINE__c</fullName>
        <description>Product Line</description>
        <label>Product Line</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/PerformanceInformationRollupTest.cls
@isTest
public class PerformanceInformationRollupTest
{
	static testmethod void unitTest()
	{
		RSMCreateTestData.GetCustomSettingsRecord();
		Account ac=new Account();
		ac.Name='Test Acc';
		ac.LesseeNo__c = '123';
        ac.RSM_CCMs__c = UserInfo.getUserId();
        ac.RSM_Onboarding__c = '';
        ac.RSM_AC_Classification__c  =  'National';
        ac.UpdatedFSLRPMFields__c = true;
		insert ac;
		
		Vehicle__c v=new Vehicle__c();
		v.Account__c=ac.Id;
		v.Last_12_Months_Fixed_Cost__c=100;
		v.Last_12_Months_Rated_Cost__c=100;
		v.Last_12_Months_Revenue__c=100;
		v.Life_to_Date_Fixed_Cost__c=100;
		v.Life_to_Date_Rated_Cost__c=100;
		v.Life_to_Date_Revenue__c=100;
		insert v;
		
		Vehicle__c v1=new Vehicle__c();
		v1.Account__c=ac.Id;
		v1.Last_12_Months_Fixed_Cost__c=100;
		v1.Last_12_Months_Rated_Cost__c=100;
		v1.Last_12_Months_Revenue__c=100;
		v1.Life_to_Date_Fixed_Cost__c=100;
		v1.Life_to_Date_Rated_Cost__c=100;
		v1.Life_to_Date_Revenue__c=100;
		v1.Product_line__c='FSL';
		insert v1;
		
		Vehicle__c v2=new Vehicle__c();
		v2.Account__c=ac.Id;
		v2.Last_12_Months_Fixed_Cost__c=100;
		v2.Last_12_Months_Rated_Cost__c=100;
		v2.Last_12_Months_Revenue__c=100;
		v2.Life_to_Date_Fixed_Cost__c=100;
		v2.Life_to_Date_Rated_Cost__c=100;
		v2.Life_to_Date_Revenue__c=100;
		v2.Product_line__c='RPM';
		insert v2;
		
		Vehicle__c v3=new Vehicle__c();
		v3.Account__c=ac.Id;
		v3.Last_12_Months_Fixed_Cost__c=100;
		v3.Last_12_Months_Rated_Cost__c=100;
		v3.Last_12_Months_Revenue__c=100;
		v3.Life_to_Date_Fixed_Cost__c=100;
		v3.Life_to_Date_Rated_Cost__c=100;
		v3.Life_to_Date_Revenue__c=100;
		insert v3;
		
		Vehicle__c v4=new Vehicle__c();
		v4.Account__c=ac.Id;
		v4.Last_12_Months_Fixed_Cost__c=100;
		v4.Last_12_Months_Rated_Cost__c=100;
		v4.Last_12_Months_Revenue__c=100;
		v4.Life_to_Date_Fixed_Cost__c=100;
		v4.Life_to_Date_Rated_Cost__c=100;
		v4.Life_to_Date_Revenue__c=100;
		v4.Product_line__c='FSL';
		insert v4;
		
		Vehicle__c v5=new Vehicle__c();
		v5.Account__c=ac.Id;
		v5.Last_12_Months_Fixed_Cost__c=100;
		v5.Last_12_Months_Rated_Cost__c=100;
		v5.Last_12_Months_Revenue__c=100;
		v5.Life_to_Date_Fixed_Cost__c=100;
		v5.Life_to_Date_Rated_Cost__c=100;
		v5.Life_to_Date_Revenue__c=100;
		v5.Product_line__c='RPM';
		insert v5;
		
		
		AccountFSLRPMFieldCalculationBatch AccFSLRPMFieldCalObj = new AccountFSLRPMFieldCalculationBatch(); 
        database.executebatch(AccFSLRPMFieldCalObj,1);
	
	}
}