SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LesseeNo__c</fullName>
        <description>Realtime update of both SFDC and RADAR whenever this value is changed in either system</description>
        <label>Lessee Number</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/RSM_Contract__c.object
<CustomObject>
    <description>Object to store RydeSmart Contract details</description>
    <fields>
        <fullName>Contract_Number__c</fullName>
        <externalId>true</externalId>
        <label>Contract Number</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lessee__c</fullName>
        <label>Lessee</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <label>RSM Contract</label>
    <nameField>
        <label>RSM Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RSM Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC Automation/src/objects/RSM_ContractDetail__c.object
<CustomObject>
    <description>The object stores the details of the contract</description>
    <fields>
        <fullName>Contract_Number__c</fullName>
        <label>Contract Number</label>
        <referenceTo>RSM_Contract__c</referenceTo>
        <relationshipName>ContractNumber</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Unit_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Number</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipName>RSContractDetails</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RSM ContractDetail</label>
    <nameField>
        <label>RSM ContractDetailID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RSM ContractDetails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/RSMCancelEmailtoNonKeyAcCtrl.cls
//Controller for VF Component 'RSMCancelEmailtoNonKeyAc Comp'
global class RSMCancelEmailtoNonKeyAcCtrl {

    global String conId {get;set;}
    global String accountName { get{
    	System.debug('Nitin---conId->'+conId);
    	System.debug('Nitin---conId->'+[select Name,LesseeNo__c from Account]);
        List<RSM_Contract__c> rcList=[select Id,Lessee__c,Name from RSM_Contract__c where Id=:conId];
        System.debug('Nitin---rcList->'+rcList);
        if(rcList!=null && rcList.size()>0){
            Account Acc = [select Name from Account where LesseeNo__c=:rcList[0].Lessee__c];
            if(Acc != null)
            	accountName = Acc.Name;
        }
        return accountName; 
    } set; }
    global String contractNumber{get{
        List<RSM_Contract__c> rcList=[select Id,Lessee__c,Name from RSM_Contract__c where Id=:conId];
        if(rcList!=null && rcList.size()>0){
            contractNumber=rcList[0].Name;
        }
        return contractNumber;
    }set;}
    global String vehList { get{
        
        System.debug('conId : '+conId);
        string vehStr='';//***** 
        List<RSM_Contract__c> rc=[select Id,Lessee__c,Name from RSM_Contract__c where Id=:conId];
        if(rc!=null && rc.size()>0){
            Account Acc = [select Name from Account where LesseeNo__c=:rc[0].Lessee__c];
            if(Acc != null)
            	accountName = Acc.Name;
            contractNumber=rc[0].Name;
           
           for(RSM_ContractDetail__c rcd:[select Unit_Number__c,Unit_Number__r.Name from RSM_ContractDetail__c where Contract_Number__c=:rc[0].Id]){
                     
           if(vehStr==''){
               vehStr=rcd.Unit_Number__r.Name;
           }else{
               vehStr=vehStr+' , '+rcd.Unit_Number__r.Name;
               }
           
            } 
        }    
        return vehStr;
    } set; }
   
}