SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Classification__c</fullName>
        <label>Account Classification</label>
        <picklist>
            <picklistValues>
                <fullName>National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coordinated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Coordinated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National - Cash Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local - Cash Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Cash and Non-Cash</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Central_Decisionmaking__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Select this if the sales decisions are made at the National / Parent Account level.</inlineHelpText>
        <label>Central Decisionmaking</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LesseeNo__c</fullName>
        <description>Realtime update of both SFDC and RADAR whenever this value is changed in either system</description>
        <label>Lessee Number</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAM_Cust_ID__c</fullName>
        <description>Migrated data from SAM</description>
        <label>SAM_Cust_ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Source__c</fullName>
        <description>This field tells if the contact is created by lead convesion process or manually by clicking new contact button.</description>
        <label>Contact Source</label>
        <picklist>
            <picklistValues>
                <fullName>Lead Conversion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manual</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Maintenance_Contact_Type__c</fullName>
        <label>Maintenance Contact - All Branches</label>
        <picklist>
            <picklistValues>
                <fullName>Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tertiary</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Primary</fullName>
        <active>true</active>
        <label>Primary</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Customer_Branch__c.object
<CustomObject>
    <description>Customer Branches at Ryder</description>
    <fields>
        <fullName>Ryder_Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field for Customer Branch to Ryder branch</description>
        <label>Ryder Branch</label>
        <referenceTo>Ryder_Branch__c</referenceTo>
        <relationshipLabel>Customer / Branch</relationshipLabel>
        <relationshipName>Customer_Branches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ryder_HQ_Account__c</fullName>
        <description>M/D field between Customer Branch and HQ Accounts</description>
        <label>Ryder HQ Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer / Branch</relationshipLabel>
        <relationshipName>Customer_Branches</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Customer / Branch</label>
    <nameField>
        <label>Customer Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer / Branch</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Original_Decision_Maker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Decision Maker</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <description>The field use for Vehicle Unit sent from Eloqua as UVS Lead and will be used to autopopulate Customer Needs at the time of creation</description>
        <label>Unit #</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_Classification__c</fullName>
        <formula>TEXT( Account.Account_Classification__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Classification</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Estimated_Proposal_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Estimated Proposed Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Original_Decision_Maker__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Original Decision Maker</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>Contact.STATUS_ACTIVE__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>The Contact you are adding as an Original Decision Maker must be an active Contact within the same Account where you are creating the new Opportunity.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ext_pipeline_id__c</fullName>
        <externalId>true</externalId>
        <label>Opportunity Number</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Ryder_Branch__c.object
<CustomObject>
    <description>Branches at Ryder</description>
    <fields>
        <fullName>Branch_Code__c</fullName>
        <description>external ID</description>
        <externalId>true</externalId>
        <label>Branch Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Ryder Branch</label>
    <nameField>
        <label>Ryder Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ryder Branches</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/objects/UVS_Bill_of_Sale__c.object
<CustomObject>
    <description>Bill of Sale for UVS</description>
    <fields>
        <fullName>OPPORTUNITYID__c</fullName>
        <label>OPPORTUNITY NUMBER</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OPPORTUNITY__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OPPORTUNITY ID</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>UVS_Bill_of_Sales</relationshipLabel>
        <relationshipName>UVS_Bill_of_Sales_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PROCESSED__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PROCESSED</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SOLD_LOCATION_CODE__c</fullName>
        <label>SOLD_LOCATION_CODE</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TOTAL_COST_OF_SALE__c</fullName>
        <label>TOTAL_COST_OF_SALE</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UNIT_ID__c</fullName>
        <label>UNIT_ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UNIT_NUMBER__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UNIT NUMBER</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>UVS_Bill_of_Sales</relationshipLabel>
        <relationshipName>UVS_Bill_of_Sales</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bill of Sale</label>
    <nameField>
        <label>BillOfSale Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UVS_Bill_of_Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup on Accounts</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Branch_Code__c</fullName>
        <label>Branch Code</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CUSTOMER_BRANCH__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field for Customer Branch</description>
        <label>Customer Branch</label>
        <referenceTo>Customer_Branch__c</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RSM__c</fullName>
        <description>Displays RydeSmart contract status</description>
        <label>RS Contract Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Printed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to SSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by SSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deleted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <externalId>true</externalId>
        <label>Unit Number</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/UVS_OpportunityBillOfSaleBatch_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class UVS_OpportunityBillOfSaleBatch_Test {

    static testMethod void SetOpportunityAmountAndCount()
    {
        // TO DO: implement unit test
        Test.startTest();
        
	        RSMCreateTestData.GetCustomSettingsRecord();
	        
	        Account Acc1 = new Account();
	        Acc1.name = 'Test';
	        Acc1.account_classification__c = 'Key Account';
	        Acc1.central_decisionmaking__c = False;
	        Acc1.type = 'Customer';
	        Acc1.Account_Classification__c = 'National';
	        Acc1.LesseeNo__c = '0123123';
	        Acc1.SAM_Cust_ID__c = '12';
	        insert Acc1;
	        system.assertEquals('12', Acc1.SAM_Cust_ID__c);
	        Ryder_Branch__c rb = new Ryder_Branch__c();
			rb.Branch_Code__c = '123';
			rb.name = 'Test';
			insert rb;
			system.assertEquals('123', rb.Branch_Code__c);			
			Customer_Branch__c CustomerBranch = new Customer_Branch__c();
	        CustomerBranch.Ryder_branch__c = rb.id;
	        CustomerBranch.Name = '12 123 Test';
	        CustomerBranch.Ryder_HQ_Account__c = Acc1.Id;
	        insert CustomerBranch;
	    
	        Contact Cont1 = new Contact();
	        Cont1.AccountId = Acc1.Id;
	        Cont1.FirstName = 'Test Contact';
	        Cont1.LastName = 'Sample';
	        Cont1.Email = 'test8979123@rydertest.com';
	        Cont1.Maintenance_Contact_Type__c = 'Primary';
	        Cont1.Phone = '(123) 456-8789';
	        Cont1.Contact_Source__c = 'Lead Conversion';
	        insert Cont1;
	    	system.assertEquals('Sample', Cont1.LastName);
	        Vehicle__c Vehicle = new Vehicle__c();
	        Vehicle.Name = '1234';
	        Vehicle.Unit__c = '1234';
	        Vehicle.CUSTOMER_BRANCH__c = CustomerBranch.Id;
	        Vehicle.RSM__c = 'Approved';
	        Vehicle.Account__c = Acc1.Id;
	        insert Vehicle;	    	
	    	Opportunity Opp = new Opportunity();
	        Opp.AccountId = Acc1.id;
	        Opp.Original_Decision_Maker__c = Cont1.id;
	        Opp.CloseDate = date.today()+2;
	        Opp.StageName = 'Qualifying';
	        Opp.name = 'test opportunity';
	        Opp.Estimated_Proposal_Date__c = System.today() + 1;
	        Opp.ext_pipeline_id__c = '12345';
	        insert Opp;
	    	system.assertEquals('12345', Opp.ext_pipeline_id__c);
	    	UVS_Bill_of_Sale__c ObjBill = new UVS_Bill_of_Sale__c();
	    	ObjBill.UNIT_ID__c = '1234';
	    	ObjBill.OPPORTUNITYID__c = '12345';
	    	ObjBill.PROCESSED__c = false;
	    	ObjBill.TOTAL_COST_OF_SALE__c = 1000;
	    	ObjBill.SOLD_LOCATION_CODE__c = '123';
	    	ObjBill.OPPORTUNITY__c = Opp.Id;
	    	ObjBill.UNIT_NUMBER__c = Vehicle.Id;
	    	insert ObjBill;
	    	system.assertEquals(false, ObjBill.PROCESSED__c);	    	
	    	ObjBill.PROCESSED__c = true;	    	
	    	update ObjBill;
	    	system.assertEquals(true, ObjBill.PROCESSED__c);
	    	UVS_OpportunityBillOfSaleBatch UVS_OppBillOfSaleBatchObj = new UVS_OpportunityBillOfSaleBatch(); 
	        database.executebatch(UVS_OppBillOfSaleBatchObj,200);
	        UVS_OppBillOfSaleBatchObj.CalculateOpportunityAmount(new Set<String>{Opp.Id});
	        
        Test.stopTest();
    }
}