SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>RSM_AC_Classification__c</fullName>
        <description>RydeSmart Account Classification</description>
        <inlineHelpText>If RS Account Classification is changed manually then Check &quot;Do Not Override AC&quot; field.</inlineHelpText>
        <label>RydeSmart Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Key Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Key Account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RSM_Account_Status__c</fullName>
        <label>Account Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RSM_Billing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Billing</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/RSM_Contract__c.object
<CustomObject>
    <description>Object to store RydeSmart Contract details</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to store the ID of the Account with which the Contract is related. This field will be populated from database based on the Lessee No in the contract</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>RSM Contracts</relationshipLabel>
        <relationshipName>RSM_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Number__c</fullName>
        <externalId>true</externalId>
        <label>Contract Number</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>RSM Contract</label>
    <nameField>
        <label>RSM Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RSM Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC Automation/src/objects/RSM_ContractDetail__c.object
<CustomObject>
    <description>The object stores the details of the contract</description>
    <fields>
        <fullName>Action_Name__c</fullName>
        <label>Action Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract_Number__c</fullName>
        <label>Contract Number</label>
        <referenceTo>RSM_Contract__c</referenceTo>
        <relationshipName>ContractNumber</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Current__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Current</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unit_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Number</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipName>RSContractDetails</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RSM ContractDetail</label>
    <nameField>
        <label>RSM ContractDetailID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RSM ContractDetails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup on Accounts</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RSM_Add_Service_current_count__c</fullName>
        <formula>IF(INCLUDES(RSM_Additional_Services__c , &apos;Business Intelligence&apos;),1,0 )+ IF(INCLUDES(RSM_Additional_Services__c, &apos;Safety Analytics&apos;),1,0 ) + IF(INCLUDES(RSM_Additional_Services__c, &apos;Navigation&apos;),1,0 )+ IF(INCLUDES(RSM_Additional_Services__c, &apos;Speed gauge&apos;),1,0 )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RSM Add Service current count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RSM_Addition_Service_prior_count__c</fullName>
        <label>RSM Addition Service prior count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RSM_Service_Level_Prior_value__c</fullName>
        <label>RSM Service Level Prior value</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RSM_Service_Level__c</fullName>
        <description>Displays Service Level of the vehicle</description>
        <label>Service Level</label>
        <picklist>
            <picklistValues>
                <fullName>Plus 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>STD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RSM__c</fullName>
        <description>Displays RydeSmart contract status</description>
        <label>RS Contract Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Printed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to SSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by SSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deleted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/RSM_Schedule_Batch3.cls
global class RSM_Schedule_Batch3 implements Schedulable {
      global void execute(SchedulableContext sc) {
         
      //Batchable class to update billing Status in Account Object
      RSMUpdateBillingStatusBatch rsubs= new RSMUpdateBillingStatusBatch ();
      rsubs.query='select Id,RSM_Billing__c from Account where RSM_Account_Status__c = \'Customer\''; 
      database.executebatch(rsubs,200);
      
      //Batchable class to update RydeSmart Revenue in Account Object
      RSMUpdateAccountRevenueBatch rsuar= new RSMUpdateAccountRevenueBatch ();
      rsuar.query='select Id from Account where RSM_Account_Status__c = \'Customer\'';
      database.executebatch(rsuar,200);
      
      //Batchable class to Initiate Installation2 to send email to activate billing and update RSM Billing Status=Sent to billing
      RSMInstallationFlowBatch2 rsif2= new RSMInstallationFlowBatch2 ();
      rsif2.query='select Id from Account where RSM_Account_Status__c = \'Customer\''; 
      database.executebatch(rsif2,200);
      
      //Batchable to initiate onboarding flow to create Task for CCMs to schedule Training
      RSMOnboardingFlowBatch rsobf= new RSMOnboardingFlowBatch (); 
      rsobf.query='select Id from Account where RSM_AC_Classification__c=\'Key Account\' and RSM_Account_Status__c=\'Customer\''; 
      database.executebatch(rsobf,200);
      
      //Batch class to calculate the vehicle is Upgraded or Downgraded based on the Service level change and Additional service level
      //This batch to be scheduled after 'RSMUpdateVehicleBatch' is completed
      RSMServiceLevelChangeStatus rssls= new RSMServiceLevelChangeStatus(); 
      //rssls.query='select Id,RSM__c,RSM_Add_Service_current_count__c,RSM_Addition_Service_prior_count__c,RSM_Service_Level__c,RSM_Service_Level_Prior_value__c from Vehicle__c where RSM__c=\'Approved\''; 
      rssls.query='select r.Unit_Number__r.RSM__c, r.Action_Name__c, r.Unit_Number__r.RSM_Add_Service_current_count__c, r.Unit_Number__r.RSM_Addition_Service_prior_count__c, r.Unit_Number__r.RSM_Service_Level__c, r.Unit_Number__r.RSM_Service_Level_Prior_value__c, r.Contract_Number__r.Account__c, r.Unit_Number__c, r.Unit_Number__r.Account__c from RSM_ContractDetail__c r where r.Is_Current__c=true and r.Unit_Number__r.RSM__c=\'Approved\'';
      database.executebatch(rssls,200);
    
      }
}