SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Additional_Comments__c</fullName>
        <inlineHelpText>Place additional comments for service handling</inlineHelpText>
        <label>Additional Comments</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Employee_Email__c</fullName>
        <label>Employee Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>SAM_Cust_ID__c</fullName>
        <description>Migrated data from SAM</description>
        <label>SAM_Cust_ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <picklist>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wholesale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Export</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Vendor account record type for legal requests</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Additional_Comments__c</fullName>
        <description>field to capture comments at the item of customer needs selection.</description>
        <inlineHelpText>field to capture comments at the item of customer needs selection.</inlineHelpText>
        <label>Additional Comments</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Customer_Branch__c.object
<CustomObject>
    <description>Customer Branches at Ryder</description>
    <fields>
        <fullName>Additional_Comments__c</fullName>
        <inlineHelpText>Place additional comments for service handling

SMO Field: Text in this field and Other Misc. Billing Information field make up the Comments field in SMO</inlineHelpText>
        <label>Additional Comments</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ryder_Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field for Customer Branch to Ryder branch</description>
        <label>Ryder Branch</label>
        <referenceTo>Ryder_Branch__c</referenceTo>
        <relationshipLabel>Customer / Branch</relationshipLabel>
        <relationshipName>Customer_Branches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ryder_HQ_Account__c</fullName>
        <description>M/D field between Customer Branch and HQ Accounts</description>
        <label>Ryder HQ Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer / Branch</relationshipLabel>
        <relationshipName>Customer_Branches</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Customer / Branch</label>
    <nameField>
        <label>Customer Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer / Branch</pluralLabel>
    <recordTypes>
        <fullName>UVS</fullName>
        <active>true</active>
        <description>Identity</description>
        <label>UVS</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Employee_Email__c</fullName>
        <label>Employee Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Original_Decision_Maker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Decision Maker</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PRODUCT_LINE__c</fullName>
        <label>Product Line</label>
        <picklist>
            <picklistValues>
                <fullName>FSL VOSA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FSL Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FSL Choice Lease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FSL Flex Lease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FSL Fast Track</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RPM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RydeSmart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MMS On Demand</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Original_Decision_Maker__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Original Decision Maker</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>Contact.STATUS_ACTIVE__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>The Contact you are adding as an Original Decision Maker must be an active Contact within the same Account where you are creating the new Opportunity.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Customer_Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer / Branch</label>
        <referenceTo>Customer_Branch__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Detail__c</fullName>
        <label>Product Detail</label>
        <picklist>
            <controllingField>Product_Line__c</controllingField>
            <picklistValues>
                <fullName>VOSA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Choice Lease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flex</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fast Track</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plus One</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physical Damage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haz-mat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OPIS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <label>Product Line</label>
        <picklist>
            <picklistValues>
                <fullName>FSL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RPM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rydesmart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DCC Light</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fuel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Ryder_Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ryder Branch</label>
        <referenceTo>Ryder_Branch__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <picklist>
            <picklistValues>
                <fullName>New Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Location</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fleet Add</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Replacement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Term Extension</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rate Change</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Unit_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Number</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

SFDC Automation/src/objects/Ryder_Account_Team_Role_Map__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Ryder Account Team Role Map</label>
</CustomObject>

SFDC Automation/src/objects/Ryder_Branch__c.object
<CustomObject>
    <description>Branches at Ryder</description>
    <fields>
        <fullName>Branch_Code__c</fullName>
        <description>external ID</description>
        <externalId>true</externalId>
        <label>Branch Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Ryder Branch</label>
    <nameField>
        <label>Ryder Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ryder Branches</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/objects/RyderConfig__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Provides configuration information for Ryder</description>
    <label>Ryder Config</label>
</CustomObject>

SFDC Automation/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>UTC__c</fullName>
        <description>This field will capture the location code for the user.</description>
        <label>UTC</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/objects/UVS_Profiles__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>UVS Profiles</label>
</CustomObject>

SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <fields>
        <fullName>Ask_Price__c</fullName>
        <label>Ask Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Branch_Code__c</fullName>
        <label>Branch Code</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CUSTOMER_BRANCH__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field for Customer Branch</description>
        <label>Customer Branch</label>
        <referenceTo>Customer_Branch__c</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PRODUCT_LINE__c</fullName>
        <description>Product Line</description>
        <label>Product Line</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Detail__c</fullName>
        <description>Product Detail as indicated in the contract package</description>
        <label>Product Detail</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field to indicate whether a vehicle has been sold and not available in the inventory.</description>
        <inlineHelpText>Field to indicate whether a vehicle has been sold and not available in the inventory.</inlineHelpText>
        <label>Sold Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <description>This field will hold the transaction type of the vehicle. Eg: Lease Extension</description>
        <label>Transaction Type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <recordTypes>
        <fullName>Rental</fullName>
        <active>true</active>
        <description>Record Type for Rental Vehicles</description>
        <label>Rental</label>
    </recordTypes>
    <recordTypes>
        <fullName>UVS</fullName>
        <active>true</active>
        <description>Record Type for UVS Vehicles</description>
        <label>UVS</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/OpportunityTriggerHelperTest.cls
/*******************************************************************
Name  : OpportunityTriggerHelperTest
Author: Samarth (Appirio)
Date  : October 9, 2014
Discription: Test Class for the Helper class OpportunityTriggerHelper
*************************************************************************/

@isTest(SeeAllData=true)
private class OpportunityTriggerHelperTest { 
//test.starttest(); 
  static testMethod void validateOpportunityClosed(){
    //First check : if Opportunity Closed, All vehicles set to sold.
    Ryder_Branch__c ryderBranch = TestUtilUVS.createRyderBranch();
    User adminUser = TestUtilUVS.createUser(false);
    adminUser.UTC__c = ryderBranch.Branch_Code__c;
    ID profileID = adminUser.ProfileId;
    insert adminUser;
    System.runAs(adminUser){

        RyderConfig__c rdc = RyderConfig__c.getOrgDefaults();
        if(rdc == null){
            rdc = TestUtilUVS.createRyderConfig(true);
        }
        Ryder_Account_Team_Role_Map__c rmap = Ryder_Account_Team_Role_Map__c.getValues('Default');
        
        if(rmap == null){
            TestUtilUVS.createRyderAccountTeamRoleMap(true);
        }
        Account a = TestUtilUVS.createAccount('Ryder FMS Parent Account', 'FMS Rental', true);// Confirm Created Account fine?

        list<Vehicle__c> vehilist = TestUtilUVS.createVehList(true);

        list<OpportunityLineItem> opplilist = TestUtilUVS.createOpportunityLineItemList(a,vehilist,true);


        //Get the Opportunity Ids associated to the items in OpportunityLineItem
        Set<Id> Oppids = new Set<Id>();
        for(OpportunityLineItem oli : [Select OpportunityId from OpportunityLineItem where id in :opplilist]){
            Oppids.add(oli.Opportunityid);          
        }

        test.starttest();
        Contact newCon = TestUtilUVS.createContact(a.Id,false);
        newCon.Additional_Comments__c = 'Test1';
        newCon.Email = 'test1@rydertest.com';
        newCon.OwnerId = UserInfo.getUserId();
        newCon.fax = '123456789';
        insert newCon;
        
        Lead l = TestUtilUVS.createLead(false);
        l.Email = 'ggupta@appirio.com';
        l.Employee_Email__c = 'abc@xyz.com';
        l.status = 'Accepted';
        l.Original_Decision_Maker__c = newCon.id;
        insert l;
        //}

        UVS_Profiles__c settings11 = UVS_Profiles__c.getOrgDefaults();
        system.debug('settings11::::::::::::::::::'+settings11);
        Database.LeadConvert lc = new database.LeadConvert();
        lc.setLeadId(l.id);
        lc.setConvertedStatus('Qualified');
        //lc.setAccountId(a.id);
        //lc.setAccountId(newCon.id);


        Database.LeadConvertResult lcr = Database.convertLead(lc);

        l = [select id , ConvertedOpportunityId from Lead  where id = :l.id];


         Id recordTypeId = Schema.sObjectType.Opportunity.getRecordTypeInfosByName().get('UVS Opportunity').getRecordTypeId();
        Opportunity o = [select id , isclosed from Opportunity where id = :l.ConvertedOpportunityId];

        o.recordtypeid = recordTypeId;
        //o.stagename = 'Booked'; AAK - throwing error while deployment due to validation rule
        o.stagename = 'Signed';
        update o;
        test.stoptest();

        Map<Id, List<OpportunityLineItem>> mapOpp = new Map<Id, List<OpportunityLineItem>>();
        mapOpp.put(o.id, opplilist);
        OpportunityTriggerHelper.createTask(mapOpp.keySet(), mapOpp);
        OpportunityTriggerHelper.postChatterFeed(Oppids);
        
        list<Opportunity> ols = new list<Opportunity>();
        ols.add(o);
        OpportunityTriggerHelper.updateUTC(ols);

   }
  }

  static testMethod void validateSomeVehicleSold(){
System.runAs(TestUtilUVS.createAdminUser(true)){
        RyderConfig__c rdc = RyderConfig__c.getOrgDefaults();
        if(rdc == null){
            rdc = TestUtilUVS.createRyderConfig(true);
        }
        
            Account acc =TestUtilUVS.createAccount('Vendor','FMS',false);
            acc.Transaction_Type__c = 'Retail';
            acc.Accountsource = 'Advertisement';
            acc.SAM_Cust_ID__c = 'abc';
            insert acc;

            Ryder_Branch__c rb = new Ryder_Branch__c();
            rb.Branch_Code__c = '123';
            insert rb;
            Customer_Branch__c cstB = new Customer_Branch__c();
            cstB.Ryder_branch__c = rb.id;
            cstB.Ryder_HQ_Account__c = acc.id;
            insert cstB;
                Vehicle__c v = new Vehicle__c(Name='1');
                v.CUSTOMER_BRANCH__c = cstB.id;
                v.Sold_Flag__c = false;
                v.Ask_Price__c = 20000.0;
                insert v;
                list<Vehicle__c> lstV = new list<Vehicle__c>();
                lstV.add(v);
                test.startTest();
                /*list<opportunity> lstopp = new list<opportunity>();
                Opportunity opp = TestUtilUVS.createOpportunity('UVS Opportunity',acc , false, null);
                lstopp.add(opp);
                Opportunity opp1 = TestUtilUVS.createOpportunity('UVS Opportunity',acc , false, null);
                lstopp.add(opp1);
                insert lstopp;
                Product2 prod = new Product2();
                prod.Name = 'Standard Price Book UVS';
                prod.CurrencyIsoCode = 'CAD';
                insert prod;
                Opportunity oppUpdated = [select id,Pricebook2Id from Opportunity where ID=: opp.ID];
                Opportunity opp1Updated = [select id,Pricebook2Id from Opportunity where ID=: opp1.ID];
                
                PriceBookEntry pbe = [SELECT Id
                                  FROM PriceBookEntry
                                  WHERE Pricebook2Id = :oppUpdated.Pricebook2Id 
                                  LIMIT 1];
                pbe.isActive = true;
                update pbe;
                PriceBookEntry pbe1 = [SELECT Id
                                  FROM PriceBookEntry
                                  WHERE Pricebook2Id = :opp1Updated.Pricebook2Id 
                                  LIMIT 1];
                pbe1.isActive = true;
                update pbe1;

            list<OpportunityLineItem> lstOppLineItems = new list<OpportunityLineItem>();
            OpportunityLineItem oppLI1 = new OpportunityLineItem();
            oppLI1.PricebookEntryId = pbe.Id;
            oppLI1.OpportunityId = opp.id;
            oppLI1.Unit_Number__c = v.id;
            oppLI1.Quantity = 1;
            oppLI1.UnitPrice = 123;
            oppLI1.Transaction_Type__c = 'Term Extension';
            oppLI1.Product_Line__c = 'Insurance';
            oppLI1.Product_Detail__c = 'Physical Damage';
            lstOppLineItems.add(oppLI1);
            insert oppLI1;
            OpportunityLineItem oppLI2 = new OpportunityLineItem();
            oppLI2.PricebookEntryId = pbe1.Id;
            oppLI2.OpportunityId = opp1.id;
            oppLI2.Unit_Number__c = v.id;
            oppLI2.Quantity = 1;
            oppLI2.UnitPrice = 123;
            oppLI2.Transaction_Type__c = 'Term Extension';
            oppLI2.Product_Line__c = 'Insurance'; 
            oppLI2.Product_Detail__c = 'Physical Damage';
            lstOppLineItems.add(oppLI2);
            insert oppLI2;
            //insert    lstOppLineItems;*/
            list<OpportunityLineItem> opplilist = TestUtilUVS.createOpportunityLineItemList(acc,lstV,true);
            test.stopTest();
            Opportunity opp = new Opportunity(ID=opplilist[0].OpportunityId);
            Id uvsOppRT = UVS_Util.UVSRecordType_Opp;
            //opp.stagename = 'Booked'; AAK - throwing error while deployment due to validation rule
            opp.stagename = 'Booked';
            
            opp.recordtypeid = uvsOppRT;
            update opp;
  //List<Task> lstTask = [select id from Task];
  //system.assert(lstTask.size()>0);

   }
  }


}