SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Additional_Comments__c</fullName>
        <inlineHelpText>Place additional comments for service handling</inlineHelpText>
        <label>Additional Comments</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Vendor account record type for legal requests</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Additional_Comments__c</fullName>
        <description>field to capture comments at the item of customer needs selection.</description>
        <inlineHelpText>field to capture comments at the item of customer needs selection.</inlineHelpText>
        <label>Additional Comments</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Original_Decision_Maker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Decision Maker</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Profile_Default_Products__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Default_Product__c</fullName>
        <label>Default Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Profile Default Products</label>
</CustomObject>

SFDC Automation/src/objects/Ryder_Account_Team_Role_Map__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Ryder Account Team Role Map</label>
</CustomObject>

SFDC Automation/src/objects/RyderConfig__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Provides configuration information for Ryder</description>
    <label>Ryder Config</label>
</CustomObject>

SFDC Automation/src/objects/UVS_Profiles__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Profile_Name__c</fullName>
        <label>Profile Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>UVS Profiles</label>
</CustomObject>

SFDC Automation/src/classes/LeadConversionResultTest.cls
@isTest(SeeAllData=true)
public with sharing class LeadConversionResultTest
{
	static User uvsUser;

	static testMethod void myUnitTest()
	{
		uvsUser = TestUtilUVS.createUser(true);
		system.runAs(uvsUser)
		{			
			RyderConfig__c rdc =  RyderConfig__c.getOrgDefaults();
			if(rdc == null){
				rdc = TestUtilUVS.createRyderConfig(true);
			}
			Ryder_Account_Team_Role_Map__c ryAccTRM = Ryder_Account_Team_Role_Map__c.getValues('Default'); 
			if(ryAccTRM == null){
				ryAccTRM = TestUtilUVS.createRyderAccountTeamRoleMap(true);
			}
			string strCurrentUserProfileName = [SELECT Id, Name
								FROM Profile
								WHERE Id = : userInfo.getProfileId()].get(0).Name;
			Profile_Default_Products__c custSetting = Profile_Default_Products__c.getValues(strCurrentUserProfileName); 
			if(custSetting == null){
				custSetting = new Profile_Default_Products__c();
				custSetting.Name = strCurrentUserProfileName;
				custSetting.Default_Product__c = 'Used Vehicles';
				insert custSetting;
			}




			Account a = TestUtilUVS.createAccount('Vendor', 'FMS', true); // Confirm Created Account fine?
			Contact newCon = TestUtilUVS.createContact(a.Id, false);
			newCon.Additional_Comments__c = 'Test1';
			newCon.Email = 'test1@rydertest.com';
			newCon.OwnerId = UserInfo.getUserId();
			newCon.fax = '123456789';
			insert newCon;



			Test.startTest();
			UVS_Profiles__c settings = UVS_Profiles__c.getOrgDefaults();
			if(settings.Profile_Name__c == null) {
				settings = new UVS_Profiles__c();
				settings.SetupOwnerId = UserInfo.GetOrganizationId();
				settings.Profile_Name__c = 'VP Asset Management;FAM;DAM;VSM_VSR;UVS Business Admin;UVS VP Assistant;System Administrator';
				insert settings;
				system.debug('settings:::::::Profile_Name__c::::22222::::::'+settings.Profile_Name__c);
			} 
			Lead myLead = TestUtilUVS.createLead(false);
			myLead.status = 'Accepted';
			myLead.email = 'testRyeder@gmail.com';
			myLead.Original_Decision_Maker__c = newCon.id;
			insert myLead;

			Database.LeadConvert lc = new Database.LeadConvert();
			lc.setLeadId(myLead.id);

			LeadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted = true LIMIT 1];
			lc.setConvertedStatus(convertStatus.MasterLabel);

			Database.LeadConvertResult lcr = Database.convertLead(lc);
			System.assert(lcr.isSuccess());
			Test.stopTest();
			PageReference pageRef = Page.LeadConversionResult;
			Test.setCurrentPage(pageRef);
			// Add parameters to page URL
			ApexPages.currentPage().getParameters().put('id', myLead.id);
			LeadConversionResult result = new LeadConversionResult();
		}

	}
}