SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LesseeNo__c</fullName>
        <description>Realtime update of both SFDC and RADAR whenever this value is changed in either system</description>
        <label>Lessee Number</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RSM_AC_Classification__c</fullName>
        <description>RydeSmart Account Classification</description>
        <inlineHelpText>If RS Account Classification is changed manually then Check &quot;Do Not Override AC&quot; field.</inlineHelpText>
        <label>RydeSmart Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Key Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Key Account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RSM_Onboarding__c</fullName>
        <description>Field to Store onboarding status of rydesmart account</description>
        <label>Onboarding</label>
        <picklist>
            <picklistValues>
                <fullName>Initiation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacted and Training Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trained</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Researching</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RSM_PLC_FLag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>RSM PLC FLag</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/RSM_Contract__c.object
<CustomObject>
    <description>Object to store RydeSmart Contract details</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to store the ID of the Account with which the Contract is related. This field will be populated from database based on the Lessee No in the contract</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>RSM Contracts</relationshipLabel>
        <relationshipName>RSM_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Number__c</fullName>
        <externalId>true</externalId>
        <label>Contract Number</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status_Name__c</fullName>
        <label>Status Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>RSM Contract</label>
    <nameField>
        <label>RSM Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RSM Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC Automation/src/objects/RSM_ContractDetail__c.object
<CustomObject>
    <description>The object stores the details of the contract</description>
    <fields>
        <fullName>Action_Name__c</fullName>
        <label>Action Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract_Number__c</fullName>
        <label>Contract Number</label>
        <referenceTo>RSM_Contract__c</referenceTo>
        <relationshipName>ContractNumber</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EffectiveDate__c</fullName>
        <description>Field to store the effective date of the contract</description>
        <label>EffectiveDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Is_Current__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Current</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Name__c</fullName>
        <label>Service Name</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Number</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipName>RSContractDetails</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Valid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Valid</label>
        <type>Checkbox</type>
    </fields>
    <label>RSM ContractDetail</label>
    <nameField>
        <label>RSM ContractDetailID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RSM ContractDetails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/RSM_PO__c.object
<CustomObject>
    <description>Object to store Purchase Order header data</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>RSM POs</relationshipLabel>
        <relationshipName>RSM_POs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DateOrdered__c</fullName>
        <label>DateOrdered</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DateReceived__c</fullName>
        <label>DateReceived</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DateShipped__c</fullName>
        <label>DateShipped</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Unit_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit #</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>RSM POs</relationshipLabel>
        <relationshipName>RSM_POs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RSM PO</label>
    <nameField>
        <label>Customer Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RSM POs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup on Accounts</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RSM_Billing_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Billing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RSM_Device_Status__c</fullName>
        <label>Device Status</label>
        <picklist>
            <picklistValues>
                <fullName>Removed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deactivated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installed with Repairs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ordered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Device</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RSM_Health_Status__c</fullName>
        <label>Health Status</label>
        <picklist>
            <picklistValues>
                <fullName>Requires Shop Repair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Has Ticket(s) Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Reporting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No issues reported</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Device</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RSM_Request_for_Billing__c</fullName>
        <label>Request for Billing</label>
        <picklist>
            <picklistValues>
                <fullName>Send to Activate Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent to Activate Billing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RSM__c</fullName>
        <description>Displays RydeSmart contract status</description>
        <label>RS Contract Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Printed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to SSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by SSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deleted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/RSM_Schedule_Batch1.cls
global class RSM_Schedule_Batch1 implements Schedulable {
        global void execute(SchedulableContext sc) {
                
        //Batchable class to update contract status and service level in vehicle 
        RSMUpdateVehicleBatch rsuvb = new RSMUpdateVehicleBatch (); 
        //rsuvb.query='select Id,Unit_Number__c,Service_Name__c,Contract_Number__r.Status_Name__c,Action_Name__c from RSM_ContractDetail__c';
        rsuvb.query='select Id,Unit_Number__c,Unit_Number__r.Account__c,Service_Name__c,Action_Name__c,Contract_Number__r.Status_Name__c,Contract_Number__r.Account__c,Is_Current__c,Valid__c from RSM_ContractDetail__c where Contract_Number__r.Account__c <> NULL order by EffectiveDate__c';
        database.executebatch(rsuvb,50);
 
        //Batchable class to create pre-launch checklist once the contract approves
        RSMCreatePreLaunchCheckList rspcl= new RSMCreatePreLaunchCheckList(); 
        rspcl.query='select Id,LesseeNo__c,RSM_PLC_Flag__c from Account where RSM_PLC_Flag__c = false and RSM_AC_Classification__c=\'Key Account\''; 
        database.executebatch(rspcl,5);
               
        //Batchable class to create RS sales questionnaire task 
        RSMCreateSalesQuestionaairTask rssqt= new RSMCreateSalesQuestionaairTask(); 
        rssqt.query='select Id from Account where RSM_Onboarding__c=\'\''; 
        database.executebatch(rssqt,20);
        
        //Batchable class to update Order Status in vehicle Object
        RSMUpdateOrderStatusBatch  rsosu= new RSMUpdateOrderStatusBatch ();
        rsosu.query='select Id,Unit_Number__c,DateReceived__c,DateShipped__c,DateOrdered__c from RSM_PO__c where LastModifiedDate=LAST_N_DAYS:0'; 
        database.executebatch(rsosu,200);      
        
        //Batchable class to Initiate Installation to update RSM Billing Status=Send to billing
        RSMInstallationFlowBatch rsif= new RSMInstallationFlowBatch ();
        rsif.query='select Id,RSM_Device_Status__c,RSM_Request_for_Billing__c,RSM_Health_Status__c,RSM_Billing_Status__c from vehicle__c where RSM__c=\'Approved\' and RSM_Device_Status__c=\'Installed\' and RSM_Health_Status__c=\'No issues reported\' and RSM_Request_for_Billing__c!=\'Sent to Activate Billing\' and RSM_Billing_Status__c=false'; 
        database.executebatch(rsif,200);
 
      }
}