SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Classification__c</fullName>
        <label>Account Classification</label>
        <picklist>
            <picklistValues>
                <fullName>National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coordinated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Coordinated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National - Cash Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local - Cash Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Cash and Non-Cash</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CO_SEGMENT__c</fullName>
        <description>RYDER Specific Company Segment, Lookup code from TB_REF_CODE, REF TYPE CODE = CMS.</description>
        <label>Market Segment</label>
        <picklist>
            <picklistValues>
                <fullName>0 - Three trucks or less</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>00 - Three Trucks or Less (Bargain Hunter)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1 - Brgn hunters Med fl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 - Cap builders Med fl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - Time-crit del Med fl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 - Brgn hunters Low den fl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5  - Cap bld Low den fl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6 - Time-crit del Low den fl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7 -  Brgn hunters Lrg fl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8 - Sophisticated 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9 - Sophisticated 2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CompanyTypeID__c</fullName>
        <label>Company Type</label>
        <picklist>
            <picklistValues>
                <fullName>1 Corporation</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2 Sub S Corp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 Partnership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 Sole Proprietorship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5 Tax Exempt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6 Government Entity</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CustProspectID__c</fullName>
        <description>Customer Prospect ID</description>
        <externalId>true</externalId>
        <label>Customer Prospect ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CustomerTypeID__c</fullName>
        <description>Customer type indicating FMS or RIL. Realtime update of both SFDC and RADAR whenever this value is changed in either system.      Question: Does RADAR care about this or any changes to this field?</description>
        <label>Customer Type</label>
        <picklist>
            <picklistValues>
                <fullName>FMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RIL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FMS Rental</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DUNS_HQ__c</fullName>
        <description>DUNS Headquarters Number</description>
        <label>DUNS HQ #</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Domestic_Ultimate_DUNS__c</fullName>
        <description>Domestic Ultimate DUNS Number</description>
        <label>Domestic Ultimate DUNS #</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Equifax_City__c</fullName>
        <label>Equifax City</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Equifax_Company_Name__c</fullName>
        <label>Equifax Company Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Equifax_Country__c</fullName>
        <label>Equifax Country</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Equifax_Email__c</fullName>
        <label>Equifax Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Equifax_Fax__c</fullName>
        <label>Equifax Fax</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Equifax_No__c</fullName>
        <description>To store the EquifaxNo</description>
        <label>Equifax No</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Equifax_Phone__c</fullName>
        <label>Equifax Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Equifax_State__c</fullName>
        <label>Equifax State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Equifax_Street1__c</fullName>
        <label>Equifax Street1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Equifax_Street2__c</fullName>
        <label>Equifax Street2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Equifax_Zip_Postal_Code__c</fullName>
        <label>Equifax Zip/Postal Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Global_Ultimate_DUNS__c</fullName>
        <description>Global Ultimate DUNS NUmber</description>
        <label>Global Ultimate DUNS #</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legal_Equifax_No__c</fullName>
        <label>Legal Equifax No</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legal_Site_Duns__c</fullName>
        <description>Shadow Field for integration to Radar - Can be editable by Admins and Credit</description>
        <label>Legal Site Duns #</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LesseeNo__c</fullName>
        <description>Realtime update of both SFDC and RADAR whenever this value is changed in either system</description>
        <label>Lessee Number</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NationalCustFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>National Customer Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SIC_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SIC Code</label>
        <referenceTo>SIC_Code__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site_Duns__c</fullName>
        <description>Site Number</description>
        <label>Site Duns #</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/SIC_Code__c.object
<CustomObject>
    <description>Table to display Codes + Descriptions</description>
    <label>SIC Code</label>
    <nameField>
        <label>SIC Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SIC Codes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/updateCompanyFuture.cls
/**
* 
*   updateCompanyFuture trigger class update if the values for the company has 
*   changed and notifies and updates accounts using webservice
*
*   Author           |Author-Email                      |Date       |Comment
*   -----------------|----------------------------------|-----------|--------------------------------------------------
*   Vishal Patel     |vishal@comitydesigns.com          |12.17.2010 |First draft
*
*/
public with sharing class updateCompanyFuture 
{
    // Update the companies using future method
    @Future(callout=true)
    public static void updateCompanyOnRyder_future(Set<Id> accountIds)
    {
        updateCompanyOnRyder(accountIds);
    }
    
    // Update Companies
    public static void updateCompanyOnRyder(Set<Id> accountIds)
    {
        // Accounts that we need to update
        Account[] accounts = [SELECT Name, Type, LesseeNo__c, Industry, CompanyTypeID__c, CustomerTypeID__c, CustProspectID__c, Legal_Site_Duns__c, Site_Duns__c, SIC, DUNS_HQ__c, Domestic_Ultimate_DUNS__c, Global_Ultimate_DUNS__c, 
        					  NationalCustFlag__c, Account_Classification__c,CO_SEGMENT__c, Equifax_No__c, Legal_Equifax_No__c, Equifax_Street1__c, Equifax_Street2__c, Equifax_City__c, Equifax_State__c, Equifax_Country__c, 
        					  Equifax_Zip_Postal_Code__c, Equifax_Phone__c, Equifax_Fax__c, Equifax_Email__c, Equifax_Company_Name__c, LastModifiedBy.Ride_ID__c, SIC_Code__r.Name FROM Account WHERE Id IN :accountIds];
        
        // Create criteria to send request to Ryder WSDL
        updateCompany.CompanyUpdateRequest requestCriteria = new updateCompany.CompanyUpdateRequest();

        // Go through the accounts and update using the soap method
        for (Account account : accounts)
        {
            requestCriteria.CompanyName = account.Name;
            requestCriteria.CompanyType = account.CompanyTypeID__c;
            requestCriteria.LesseNum = account.LesseeNo__c;
            //Saad Wali Jaan changed 02/07/2012 - Use Legal Site Duns as Legal Site Duns & Site Duns as Site Duns
            //Julio Gonzalez changed 02/04/2011 - Use Legal Site Duns as Site Duns
            requestCriteria.LegalSiteDuns = account.Legal_Site_Duns__c;
            requestCriteria.SiteDuns = account.Site_Duns__c;
            requestCriteria.HQDuns = account.DUNS_HQ__c;
            requestCriteria.UltimateDuns = account.Domestic_Ultimate_DUNS__c;
            requestCriteria.IndustryType = account.Industry;
            requestCriteria.CustomerType = account.CustomerTypeID__c;
            // 12/22/2011- Neelima- replaced sic with SIC_Code__r.Name
            requestCriteria.SICCode = account.SIC_Code__r.Name;
            requestCriteria.CompanySegment = account.CO_SEGMENT__c;
            if (account.CustProspectID__c != null)
                requestCriteria.Id = Integer.valueOf(account.CustProspectID__c);
           // requestCriteria.NationalCustFlag = account.NationalCustFlag__c;
           // 03/18 , Neelima-- replaced NationalCustFlag with account classification
           requestCriteria.NationalCustFlag = account.Account_Classification__c=='National' ? true:false;
            
            //MPH changed 1/20/2011 - requested by Neelima
            //requestCriteria.LastUpdateUser = account.LastModifiedBy.Name;
            requestCriteria.LastUpdateUser = account.LastModifiedBy.Ride_ID__c;
            
            //Added By Saad Wali Jaan. 07/11/2012- Changes for Equifax fields
            requestCriteria.EquifaxNo = account.Equifax_No__c;
            requestCriteria.LegalEquifaxNo = account.Legal_Equifax_No__c;
            requestCriteria.EquifaxStreet1 = account.Equifax_Street1__c;
            requestCriteria.EquifaxStreet2 = account.Equifax_Street2__c;
            requestCriteria.EquifaxCity = account.Equifax_City__c;
            requestCriteria.EquifaxState = account.Equifax_State__c;
            requestCriteria.EquifaxCountry = account.Equifax_Country__c;
            requestCriteria.EquifaxZipCode = account.Equifax_Zip_Postal_Code__c;
            requestCriteria.EquifaxPhone = account.Equifax_Phone__c;
            requestCriteria.EquifaxFax = account.Equifax_Fax__c;
            requestCriteria.EquifaxEmail = account.Equifax_Email__c;
            requestCriteria.EquifaxCompanyName = account.Equifax_Company_Name__c;

            UpdateCompany.UpdateCompanySoap companySoap = new UpdateCompany.UpdateCompanySoap();
            UpdateCompany.CRMCredential credential = new UpdateCompany.CRMCredential();
            //credential.UserName = UserInfo.getUserName();
            //credential.Password = 'passw0rd';
            //credential.SecurityToken = 'x9hJscMUilGopqHFAZETe0Glm';
            
            system.debug('requestCriteria.LegalEquifaxNo = ' + requestCriteria.LegalEquifaxNo);  
            system.debug('account.Legal_Equifax_No__c = ' + account.Legal_Equifax_No__c);
            
            credential.UserName = '';
            credential.Password = '';
            credential.SecurityToken = '';
            try
            {
                
                // Make a soap request
                UpdateCompany.DCCompanyUpdate updateCompanyInfo;
                
                if (RyderGlobalVariables.IS_TEST==false)
                {
                    System.debug('++++++++requestCriteria: '+ requestCriteria);
                    updateCompanyInfo = companySoap.ProcessRequest(credential, requestCriteria);
                    System.debug('+++++++++updateCompanyInfo: ' + updateCompanyInfo);
                    //Check if there was a success
                    if (updateCompanyInfo != null)
                    {
                        String companyId = String.valueOf(updateCompanyInfo.ID);        
                    }
                }
            }
            catch(Exception ex)
            {
                System.debug('Error while updating the company: ' + ex.getMessage());
            }
        }
                
    }

}