SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LesseeNo__c</fullName>
        <description>Realtime update of both SFDC and RADAR whenever this value is changed in either system</description>
        <label>Lessee Number</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RSM_CCMs__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to Store RydeSmart&apos;s CCM (Customer Care Manager) owner</description>
        <inlineHelpText>If CCM is changed Manually then check &quot;Do Not Override CCM&quot; field.</inlineHelpText>
        <label>CCM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RSM_Onboarding__c</fullName>
        <description>Field to Store onboarding status of rydesmart account</description>
        <label>Onboarding</label>
        <picklist>
            <picklistValues>
                <fullName>Initiation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacted and Training Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trained</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Researching</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Customer_Branch__c.object
<CustomObject>
    <description>Customer Branches at Ryder</description>
    <fields>
        <fullName>Ryder_HQ_Account__c</fullName>
        <description>M/D field between Customer Branch and HQ Accounts</description>
        <label>Ryder HQ Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer / Branch</relationshipLabel>
        <relationshipName>Customer_Branches</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Customer / Branch</label>
    <nameField>
        <label>Customer Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer / Branch</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>RydeSmart_Task</fullName>
        <active>true</active>
        <description>This Record type is used for RydeSmart Task</description>
        <label>RydeSmart Task</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <fields>
        <fullName>CUSTOMER_BRANCH__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field for Customer Branch</description>
        <label>Customer Branch</label>
        <referenceTo>Customer_Branch__c</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RSM__c</fullName>
        <description>Displays RydeSmart contract status</description>
        <label>RS Contract Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Printed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to SSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by SSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deleted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/RSMCreateSalesQuestionaairTask_Test.cls
@isTest
private class RSMCreateSalesQuestionaairTask_Test{

static testmethod void unitTest(){
    RSMCreateTestData.GetCustomSettingsRecord();
    
    Account ac=new Account();
    ac.Name='Test1';
    ac.LesseeNo__c='123';
    ac.RSM_CCMs__c=UserInfo.getUserId();
    ac.RSM_Onboarding__c='';
    insert ac;
    
    Customer_Branch__c cb=new Customer_Branch__c();
    cb.Name='Test Customer Branch';
    cb.Ryder_HQ_Account__c=ac.Id;
    insert cb;
    Vehicle__c v=new Vehicle__c();
    v.Name='1234';
    v.CUSTOMER_BRANCH__c=cb.Id;
    v.RSM__c='Approved';
    insert v;
    
    Account ac1=new Account();
    ac1.Name='Test12';
    ac1.LesseeNo__c='1234';
    ac1.RSM_CCMs__c=UserInfo.getUserId();
    ac1.RSM_Onboarding__c='';
    insert ac1;
    RecordType rt=[select Id from RecordType where sobjecttype='Task' and DeveloperName='RydeSmart_Task'];
    Task t1=new Task();
    t1.Subject='Sales Questionaair';
    t1.whatId=ac1.Id;
    t1.RecordtypeId=rt.Id;
    insert t1;
    
    Test.startTest();
    
    RSMCreateSalesQuestionaairTask rcsq=new RSMCreateSalesQuestionaairTask ();
    rcsq.query='select Id from Account where RSM_Onboarding__c=\'\' and Id in ('+'\''+ac.Id+'\',\''+ac1.Id+'\') limit 2 '; 
    Database.executeBatch(rcsq);
    
    Test.stopTest();

}
}