SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Classification__c</fullName>
        <label>Account Classification</label>
        <picklist>
            <picklistValues>
                <fullName>National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coordinated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Coordinated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National - Cash Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local - Cash Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Cash and Non-Cash</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Central_Decisionmaking__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Select this if the sales decisions are made at the National / Parent Account level.</inlineHelpText>
        <label>Central Decisionmaking</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LesseeNo__c</fullName>
        <description>Realtime update of both SFDC and RADAR whenever this value is changed in either system</description>
        <label>Lessee Number</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RSM_AC_Classification__c</fullName>
        <description>RydeSmart Account Classification</description>
        <inlineHelpText>If RS Account Classification is changed manually then Check &quot;Do Not Override AC&quot; field.</inlineHelpText>
        <label>RydeSmart Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Key Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Key Account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Available_24_7__c</fullName>
        <description>Indicate if this Contact is available to contact at all hours of the day.</description>
        <inlineHelpText>Indicate if this Contact is available to contact at all hours of the day.</inlineHelpText>
        <label>Available 24/7?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact_Source__c</fullName>
        <description>This field tells if the contact is created by lead convesion process or manually by clicking new contact button.</description>
        <label>Contact Source</label>
        <picklist>
            <picklistValues>
                <fullName>Lead Conversion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manual</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <label>Post Sales Contact Role</label>
        <picklist>
            <picklistValues>
                <fullName>After Hours</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P.O. Authorization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RCRC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Target Marketing Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executive Sponsorship Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RydeSmart</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Maintenance_Contact_Type__c</fullName>
        <label>Maintenance Contact - All Branches</label>
        <picklist>
            <picklistValues>
                <fullName>Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tertiary</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Primary</fullName>
        <active>true</active>
        <label>Primary</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Customer_Branch__c.object
<CustomObject>
    <description>Customer Branches at Ryder</description>
    <fields>
        <fullName>Ryder_HQ_Account__c</fullName>
        <description>M/D field between Customer Branch and HQ Accounts</description>
        <label>Ryder HQ Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer / Branch</relationshipLabel>
        <relationshipName>Customer_Branches</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Customer / Branch</label>
    <nameField>
        <label>Customer Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer / Branch</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Key_Contact__c.object
<CustomObject>
    <description>CSI and Maintenance Contacts</description>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AccountId</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Key Contacts</relationshipLabel>
        <relationshipName>Key_Contacts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Available_24_7__c</fullName>
        <inlineHelpText>Indicate if this Contact is available to contact at all hours of the day.</inlineHelpText>
        <label>Available 24/7?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <inlineHelpText>Select which role this Contact serves for this Customer/Branch.</inlineHelpText>
        <label>Contact Role</label>
        <picklist>
            <picklistValues>
                <fullName>CSI Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maintenance Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RydeSmart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RydeSmart Mktg</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IFT Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <inlineHelpText>Select the Contact Type.  Only one contact can be listed as Primary for a Customer/Branch.</inlineHelpText>
        <label>Contact Type</label>
        <picklist>
            <picklistValues>
                <fullName>Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tertiary</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.STATUS_ACTIVE__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Related Branches</relationshipLabel>
        <relationshipName>Key_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Branch__c</fullName>
        <description>Joiner object used for CSI and Maintenance Contacts</description>
        <label>Customer / Branch</label>
        <referenceTo>Customer_Branch__c</referenceTo>
        <relationshipLabel>Key Contacts</relationshipLabel>
        <relationshipName>Key_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Key Contact</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Key Contact #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Key Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/RSM_Contract__c.object
<CustomObject>
    <description>Object to store RydeSmart Contract details</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to store the ID of the Account with which the Contract is related. This field will be populated from database based on the Lessee No in the contract</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>RSM Contracts</relationshipLabel>
        <relationshipName>RSM_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Number__c</fullName>
        <externalId>true</externalId>
        <label>Contract Number</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lessee__c</fullName>
        <label>Lessee</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status_Name__c</fullName>
        <label>Status Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>RSM Contract</label>
    <nameField>
        <label>RSM Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RSM Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC Automation/src/objects/RSM_ContractDetail__c.object
<CustomObject>
    <description>The object stores the details of the contract</description>
    <fields>
        <fullName>Action_Name__c</fullName>
        <label>Action Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract_Number__c</fullName>
        <label>Contract Number</label>
        <referenceTo>RSM_Contract__c</referenceTo>
        <relationshipName>ContractNumber</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Current__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Current</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unit_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Number</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipName>RSContractDetails</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RSM ContractDetail</label>
    <nameField>
        <label>RSM ContractDetailID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RSM ContractDetails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup on Accounts</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CUSTOMER_BRANCH__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field for Customer Branch</description>
        <label>Customer Branch</label>
        <referenceTo>Customer_Branch__c</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RSM__c</fullName>
        <description>Displays RydeSmart contract status</description>
        <label>RS Contract Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Printed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to SSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by SSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deleted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/RSMCancelEmailtoNonKeyAc_Test.cls
@isTest
private class RSMCancelEmailtoNonKeyAc_Test{

    static testmethod void unitTest()
    {
    	Test.startTest();
    	RSMCreateTestData.GetCustomSettingsRecord();
    	
		Account Acc1 = new Account();
        Acc1.name = 'Test';
        Acc1.account_classification__c = 'Key Account';
        Acc1.central_decisionmaking__c = False;
        Acc1.type = 'Customer';
        Acc1.Account_Classification__c = 'National';
        Acc1.LesseeNo__c = '0123123';
        insert Acc1;
    	
    	Customer_Branch__c CustomerBranch = new Customer_Branch__c();
	    CustomerBranch.Name = 'Test Customer Branch';
	    CustomerBranch.Ryder_HQ_Account__c = Acc1.Id;
	    insert CustomerBranch;
    
		Contact Cont1 = new Contact();
		Cont1.AccountId = Acc1.Id;
		Cont1.FirstName = 'Test Contact';
		Cont1.LastName = 'Sample';
		Cont1.Email = 'test8979123@rydertest.com';
		Cont1.Maintenance_Contact_Type__c = 'Primary';
		Cont1.Phone = '(123) 456-8789';
		Cont1.Contact_Source__c = 'Lead Conversion';
		insert Cont1;
    	
    	Key_Contact__c Key_Contact = new Key_Contact__c(Contact_Role__c = 'RydeSmart',
    													Contact__c = Cont1.Id, AccountId__c = Acc1.Id, 
    													Customer_Branch__c = CustomerBranch.Id, Available_24_7__c = 'YES', 
    													Contact_Type__c = 'Primary');
    	insert Key_Contact;
    	
    	Vehicle__c Vehicle = new Vehicle__c();
	    Vehicle.Name = '1234';
	    Vehicle.CUSTOMER_BRANCH__c = CustomerBranch.Id;
	    Vehicle.RSM__c = 'Approved';
	    Vehicle.Account__c = Acc1.Id;
	    insert Vehicle;
	
    	RSM_Contract__c Contrt1 = new RSM_Contract__c();
	    Contrt1.Lessee__c = Acc1.LesseeNo__c;
	    Contrt1.Contract_Number__c = 2434;
	    Contrt1.Status_Name__c = 'Approved';	    
	    insert Contrt1;
	    
	    RSM_ContractDetail__c Contrt1Detail = new RSM_ContractDetail__c();
	    Contrt1Detail.Contract_Number__c = Contrt1.id;
	    Contrt1Detail.Action_Name__c = 'Cancel';
	    Contrt1Detail.Is_Current__c = True;
	    Contrt1Detail.Unit_Number__c = Vehicle.Id;
	    insert Contrt1Detail;
	    
	    RSM_ContractDetail__c Contrt1Detail1 = new RSM_ContractDetail__c();
	    Contrt1Detail1.Contract_Number__c = Contrt1.id;
	    Contrt1Detail1.Action_Name__c = 'Cancel';
	    Contrt1Detail1.Is_Current__c = True;
	    Contrt1Detail.Unit_Number__c = Vehicle.Id;
	    insert Contrt1Detail1;
	    
    	RSMCancelEmailtoNonKeyAc rscenk= new RSMCancelEmailtoNonKeyAc(); 
   		rscenk.query='select Id,LesseeNo__c,RSM_AC_Classification__c from Account where RSM_AC_Classification__c=\'Non-Key Account\' LIMIT 2'; 
    	database.executebatch(rscenk);
    	
   		rscenk= new RSMCancelEmailtoNonKeyAc(); 
   		rscenk.query='select Id,LesseeNo__c,RSM_AC_Classification__c from Account where RSM_AC_Classification__c=\'Non-Key Account\' LIMIT 2'; 
    	database.executebatch(rscenk);
    	
    	Test.stopTest();

	}
}