SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ADDR_ID__c</fullName>
        <description>Needed for migration purposes.</description>
        <label>Address ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Alias_Name__c</fullName>
        <description>Also know as name for accounts (1 OR More AKAs)</description>
        <label>Other Names</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BAD_ADDRESS_BIT__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bad Address Bit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BAD_ADDR_CD__c</fullName>
        <description>Flag used to mark an address as BAD</description>
        <label>Bad Address CD</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BAD_ADDR_DATE__c</fullName>
        <description>Date when the address was marked bad</description>
        <label>Bad Address Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BAD_ADDR_REASON__c</fullName>
        <description>Reason for marking an address BAD</description>
        <label>Bad Address Reason</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>BUSINESS_STATUS__c</fullName>
        <description>CURRENT OR TARGET BUSINESS (For customers with multiple locations).   Lookup tb_REF_CODE with ref_code_type &apos;LBS&apos; to the corr. reasons.</description>
        <label>Business Status</label>
        <picklist>
            <picklistValues>
                <fullName>Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Target Business</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CO_ANNSRY__c</fullName>
        <description>Company Anniversary</description>
        <label>Inception Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CO_OWNER_ID__c</fullName>
        <label>Co Owner ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CO_RYDER_ANNSRY__c</fullName>
        <description>Ryder Customer Inception Date - ACS Tables</description>
        <label>Company Ryder Anniversary</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CO_SEGMENT__c</fullName>
        <description>RYDER Specific Company Segment, Lookup code from TB_REF_CODE, REF TYPE CODE = CMS.</description>
        <label>Market Segment</label>
        <picklist>
            <picklistValues>
                <fullName>0 - Three trucks or less</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>00 - Three Trucks or Less (Bargain Hunter)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1 - Brgn hunters Med fl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 - Cap builders Med fl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - Time-crit del Med fl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 - Brgn hunters Low den fl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5  - Cap bld Low den fl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6 - Time-crit del Low den fl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7 -  Brgn hunters Lrg fl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8 - Sophisticated 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9 - Sophisticated 2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CUST_REPAIR_LIMIT__c</fullName>
        <description>Customer Repair Limit</description>
        <label>Customer Repair Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Central_Decisionmaking__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Select this if the sales decisions are made at the National / Parent Account level.</inlineHelpText>
        <label>Central Decisionmaking</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CustProspectID__c</fullName>
        <description>Customer Prospect ID</description>
        <externalId>true</externalId>
        <label>Customer Prospect ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CustomerTypeID__c</fullName>
        <description>Customer type indicating FMS or RIL. Realtime update of both SFDC and RADAR whenever this value is changed in either system.      Question: Does RADAR care about this or any changes to this field?</description>
        <label>Customer Type</label>
        <picklist>
            <picklistValues>
                <fullName>FMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RIL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FMS Rental</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DB_Loc_Type__c</fullName>
        <description>D&amp;B lassification of customer locations</description>
        <label>D&amp;B Location Type</label>
        <picklist>
            <picklistValues>
                <fullName>Branch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distribution Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Division</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Headquarters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing/Assembly Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single Location</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subsidiary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subsidiary Undefined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transportation Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warehousing Center</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DUNS_HQ__c</fullName>
        <description>DUNS Headquarters Number</description>
        <label>DUNS HQ #</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Domestic_Ultimate_DUNS__c</fullName>
        <description>Domestic Ultimate DUNS Number</description>
        <label>Domestic Ultimate DUNS #</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FormerCustomer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to indicate customer is current or former</description>
        <label>Former Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Global_Ultimate_DUNS__c</fullName>
        <description>Global Ultimate DUNS NUmber</description>
        <label>Global Ultimate DUNS #</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LOC_ID__c</fullName>
        <description>Needed for migration purposes.</description>
        <label>Location ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legal_Entity_Address_City__c</fullName>
        <label>Legal Entity Address City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legal_Entity_Address_Country__c</fullName>
        <label>Legal Entity Address Country</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legal_Entity_Address_State_Province__c</fullName>
        <label>Legal Entity Address State/Province</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legal_Entity_Address_Street__c</fullName>
        <label>Legal Entity Address Street</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legal_Entity_Address_Zip_Postal_Code__c</fullName>
        <label>Legal Entity Address Zip/Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LesseeNo__c</fullName>
        <description>Realtime update of both SFDC and RADAR whenever this value is changed in either system</description>
        <label>Lessee Number</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NATL_RNTL_CUST_ID__c</fullName>
        <description>National Rental Customer Account ID. Pulled from FIS</description>
        <label>National Rental #</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PO_NUMBER__c</fullName>
        <description>PO Number</description>
        <label>PO Number</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_2__c</fullName>
        <description>Secondary Account Phone number</description>
        <label>Phone 2</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Ryder_Specific_Loc_Type__c</fullName>
        <description>Ryder classification of customer locations</description>
        <label>Ryder Specific Location Type</label>
        <picklist>
            <picklistValues>
                <fullName>Branch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distribution Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Division</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Headquarters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing/Assembly Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subsidiary Undefined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transportation Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warehousing Center</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>STATUS_ACTIVE__c</fullName>
        <description>Customer status to control visibility.</description>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Site_Duns__c</fullName>
        <description>Site Number</description>
        <label>Site Duns #</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Top10Account__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to indicate if it is a top 10 account or not.</description>
        <label>Top 10 Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>addr_verified_date__c</fullName>
        <label>Address Verified Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/classes/test_insertUpdateCompany.cls
@isTest
private class test_insertUpdateCompany {

	private static String GENERIC_COMPANY_NAME = 'Generic Company Name';
	private static String GENERIC_COMPANY_DUNS = '123456789';
	private static String GENERIC_COMPANY_BILLING_STATE = 'IL';

	private static Account createAccount()
	{
		Account account = new Account();
		account.Name = GENERIC_COMPANY_NAME;
		account.Site_Duns__c = GENERIC_COMPANY_DUNS;
		account.BillingState = GENERIC_COMPANY_BILLING_STATE;
		insert account;
		
		return account;
	}

	static testMethod void test_updateCompanyOnRyder_future(){
		Account a = createAccount();
		Set<Id> acctset = new Set<Id>();
		acctset.add(a.id);
		insertUpdateCompany.updateCompanyOnRyder_future(acctset);
	}


	static testMethod void test_insertCompanyOnRyder_future(){
		Account a = createAccount();
		Set<String> dunsset = new Set<String>();
		dunsset.add(a.site_duns__c);
		Map<String, String> pmap = new Map<String, String>();
		
		try{
			insertUpdateCompany.insertCompanyOnRyder_future(dunsset,pmap,a.id);
		}catch(Exception e){
			
		}
		//insertCompanyOnRyder_future(Set<String> dunsNumbers, Map<String, String> mapParentDuns, String accountId)
		/*
			SELECT a.addr_verified_date__c, a.Website, a.Type, a.Top10Account__c,a.Site_Duns__c, a.ShippingStreet, a.ShippingState, 
							a.ShippingPostalCode, a.ShippingCountry, a.ShippingCity, a.STATUS_ACTIVE__c, a.Ryder_Specific_Loc_Type__c, a.RecordTypeId, a.Phone_2__c, 
							a.Phone, a.ParentId, a.PO_NUMBER__c, a.OwnerId, a.NumberOfEmployees, a.Name, a.NATL_RNTL_CUST_ID__c, a.MasterRecordId, a.LesseeNo__c, 
							a.Legal_Entity_Address_Zip_Postal_Code__c, a.Legal_Entity_Address_Street__c, a.Legal_Entity_Address_State_Province__c, a.Legal_Entity_Address_Country__c, 
							a.Legal_Entity_Address_City__c, a.LastActivityDate, a.LOC_ID__c, a.Industry, a.Id, a.Global_Ultimate_DUNS__c, a.FormerCustomer__c, a.Fax, 
							a.Domestic_Ultimate_DUNS__c, a.Description, a.DUNS_HQ__c, a.DB_Loc_Type__c, a.CustomerTypeID__c, a.CustProspectID__c, a.CurrencyIsoCode, 
							a.Central_Decisionmaking__c, a.CUST_REPAIR_LIMIT__c, a.CO_SEGMENT__c, a.CO_RYDER_ANNSRY__c, a.CO_OWNER_ID__c, a.CO_ANNSRY__c, a.BillingStreet, 
							a.BillingState, a.BillingPostalCode, a.BillingCountry, a.BillingCity, a.BUSINESS_STATUS__c, a.BAD_ADDR_REASON__c, a.BAD_ADDR_DATE__c, 
							a.BAD_ADDR_CD__c, a.BAD_ADDRESS_BIT__c, a.AnnualRevenue, a.Alias_Name__c, a.ADDR_ID__c, RecordType.Name, a.SIC
							FROM Account a WHERE a.Site_Duns__c IN: dunsNumbers];
		*/
	}

}