SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>SAM_Cust_ID__c</fullName>
        <description>Migrated data from SAM</description>
        <label>SAM_Cust_ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <picklist>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wholesale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Export</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Vendor account record type for legal requests</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/BTR_Stats__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Current_Inventory__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Current Inventory</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Make__c</fullName>
        <label>Make</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAM_Class__c</fullName>
        <label>SAM Class</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Selling_Age__c</fullName>
        <label>Selling Age</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>BTR Stats</label>
    <nameField>
        <displayFormat>BTRS-{00000000}</displayFormat>
        <label>BTR Stats Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BTR Stats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Customer_Branch__c.object
<CustomObject>
    <description>Customer Branches at Ryder</description>
    <fields>
        <fullName>Ryder_Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field for Customer Branch to Ryder branch</description>
        <label>Ryder Branch</label>
        <referenceTo>Ryder_Branch__c</referenceTo>
        <relationshipLabel>Customer / Branch</relationshipLabel>
        <relationshipName>Customer_Branches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ryder_HQ_Account__c</fullName>
        <description>M/D field between Customer Branch and HQ Accounts</description>
        <label>Ryder HQ Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer / Branch</relationshipLabel>
        <relationshipName>Customer_Branches</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Customer / Branch</label>
    <nameField>
        <label>Customer Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer / Branch</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Ryder_Branch__c.object
<CustomObject>
    <description>Branches at Ryder</description>
    <fields>
        <fullName>Branch_Code__c</fullName>
        <description>external ID</description>
        <externalId>true</externalId>
        <label>Branch Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Name__c</fullName>
        <label>Country</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Ryder Branch</label>
    <nameField>
        <label>Ryder Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ryder Branches</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/objects/RyderConfig__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Provides configuration information for Ryder</description>
    <label>Ryder Config</label>
</CustomObject>

SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <fields>
        <fullName>Branch_Code__c</fullName>
        <label>Branch Code</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CUSTOMER_BRANCH__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field for Customer Branch</description>
        <label>Customer Branch</label>
        <referenceTo>Customer_Branch__c</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Days_At_UTC__c</fullName>
        <label>Days At UTC</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Model_Year__c</fullName>
        <description>Year of the vehicle</description>
        <label>Model Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAM_CLASS__c</fullName>
        <description>Sam Class</description>
        <label>SAM Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <description>This field will hold the transaction type of the vehicle. Eg: Lease Extension</description>
        <label>Transaction Type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/UVS_VehicleStatsControllerTest.cls
/**=============================================================================
 * Created By: Gaurav Gupta (Appirio, Inc)
 * Created Date: [16/10/2014]
 * Description: Test class for UVS_VehicleStatsController

==============================================================================*/
@isTest
private class UVS_VehicleStatsControllerTest {

    static testMethod void myUnitTest() {
    	
    	User sysAdmin = TestUtilUvs.createAdminUser(True);
    	
    	System.runAs ( sysAdmin ) {
    	  RyderConfig__c rydConf = new RyderConfig__c();
    	  rydConf = TestUtilUVS.createRyderConfig(true);
    	  
			Account acc =TestUtilUVS.createAccount('Vendor','FMS',false);
			acc.Transaction_Type__c = 'Retail';
			acc.Accountsource = 'Advertisement';
			acc.SAM_Cust_ID__c = 'abc';
			insert acc;
			    	  
			Ryder_Branch__c rb = new Ryder_Branch__c();
			rb.Branch_Code__c = '123';
			rb.Country_Name__c = 'India';
			insert rb;
			Customer_Branch__c cstB = new Customer_Branch__c();
			cstB.Ryder_branch__c = rb.id;
			cstB.Ryder_HQ_Account__c = acc.id;
			insert cstB;       	  
    	  
    	  
    	  List<vehicle__c>  lstVehicles= TestUtilUVS.createVehList(false);	
    	  lstVehicles[0].Days_At_UTC__c = 150;
    	  lstVehicles[0].SAM_Class__c = 'ABC-CDE';
    	  lstVehicles[0].Model_Year__c =1989;
    	  lstVehicles[0].CUSTOMER_BRANCH__c = cstB.id;
    	  insert lstVehicles[0];
    	  
    	  BTR_Stats__c btrStats = new BTR_Stats__c();
    	  btrStats.Sam_Class__c = 'ABC-CDE';
    	  btrStats.Year__c = '1989';
    	  btrStats.Is_Current_Inventory__c=true;
    	  btrStats.Country__c = 'India';
    	  btrStats.Make__c = 'Test';
    	  btrStats.Model__c = 'Test';
    	  btrStats.Selling_Age__c = 18;
    	  insert btrStats;
    	  
    	  BTR_Stats__c btrStats1 = new BTR_Stats__c();
    	  btrStats1.Sam_Class__c = 'ABC-CDE';
    	  btrStats1.Year__c = '1989';
    	  btrStats1.Is_Current_Inventory__c= false;
    	  btrStats1.Country__c = 'India';
    	  btrStats1.Make__c = 'Test';
    	  btrStats1.Model__c = 'Test';
    	  btrStats1.Selling_Age__c = 18;
    	  insert btrStats1;
    	  
    	      	  
   		  PageReference tpageRef = Page.UVS_VehicleStats;
		  Test.setCurrentPage(tpageRef);
		
		  ApexPages.currentPage().getParameters().put('id',lstVehicles[0].id);
		  
		  UVS_VehicleStatsController uvsStatsCtrl = new UVS_VehicleStatsController();
		  uvsStatsCtrl.getListSAMClass();
		  system.assertequals(uvsStatsCtrl.country , 'India');
		  //system.assertequals(uvsStatsCtrl.sellingage , '0 - 180 days');
		  
    	}
    }
}