SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LesseeNo__c</fullName>
        <description>Realtime update of both SFDC and RADAR whenever this value is changed in either system</description>
        <label>Lessee Number</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RSM_Billing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Billing</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/classes/RSMAccountVehicleTest.cls
@isTest
public with sharing class RSMAccountVehicleTest {
    
    static testmethod void test_searchVehicles()
    {
        RSMCreateTestData.GetCustomSettingsRecord();
        Account Ac=new Account ();
        Ac.RSM_Billing__c=true;
        Ac.Name ='Test';
        Ac.LesseeNo__c = '0000001';
        insert Ac;
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(Ac);
        
        RSMAccountVehicle rsmVeh = new RSMAccountVehicle(stdController);
        rsmVeh.getPageVehicles();
        rsmVeh.changeOrder();
        rsmVeh.sortOrder = 'DESC';
        rsmVeh.changeOrder();
        
    }
    
}