SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Classification__c</fullName>
        <label>Account Classification</label>
        <picklist>
            <picklistValues>
                <fullName>National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coordinated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Coordinated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National - Cash Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local - Cash Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Cash and Non-Cash</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Central_Decisionmaking__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Select this if the sales decisions are made at the National / Parent Account level.</inlineHelpText>
        <label>Central Decisionmaking</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LesseeNo__c</fullName>
        <description>Realtime update of both SFDC and RADAR whenever this value is changed in either system</description>
        <label>Lessee Number</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/BTR__c.object
<CustomObject>
    <description>Linked to the quote object as 1:1 relationship and used to drive the approval process for the quotes</description>
    <fields>
        <fullName>First_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>First Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>BTRs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The quote record to which this BTR approval process is linked to.</description>
        <inlineHelpText>The quote record to which this BTR approval process is linked to.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>BTRs</relationshipLabel>
        <relationshipName>BTRs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requester_Comments__c</fullName>
        <label>BTR Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Second_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Second Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>BTRs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the BTR approval process for a given quote.</description>
        <inlineHelpText>The status of the BTR approval process for a given quote.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Submitted - With FAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted - With DAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted - With VP AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Third_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Third Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>BTRs2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BTR</label>
    <nameField>
        <displayFormat>BTR-{0000000}</displayFormat>
        <label>BTR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BTRs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Customer_Branch__c.object
<CustomObject>
    <description>Customer Branches at Ryder</description>
    <fields>
        <fullName>Ryder_HQ_Account__c</fullName>
        <description>M/D field between Customer Branch and HQ Accounts</description>
        <label>Ryder HQ Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer / Branch</relationshipLabel>
        <relationshipName>Customer_Branches</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Customer / Branch</label>
    <nameField>
        <label>Customer Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer / Branch</pluralLabel>
    <recordTypes>
        <fullName>UVS</fullName>
        <active>true</active>
        <description>Identity</description>
        <label>UVS</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Requester_Comments__c</fullName>
        <label>BTR Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <recordTypes>
        <fullName>UVS</fullName>
        <active>true</active>
        <description>Used vehicle Sales</description>
        <label>UVS</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Approval_Level__c</fullName>
        <description>0 (No approval required), 1 (FAM), 2 (DAM) and 3 (VP AM )</description>
        <label>Approval Level</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Take_Price2__c</fullName>
        <label>Take Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/UVS_Approval_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Role_Names__c</fullName>
        <inlineHelpText>Roles which require 2 level approvals only</inlineHelpText>
        <label>Role Names</label>
        <type>TextArea</type>
    </fields>
    <label>UVS Approval Setting</label>
</CustomObject>

SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup on Accounts</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CUSTOMER_BRANCH__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field for Customer Branch</description>
        <label>Customer Branch</label>
        <referenceTo>Customer_Branch__c</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Days_At_UTC__c</fullName>
        <label>Days At UTC</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RSM__c</fullName>
        <description>Displays RydeSmart contract status</description>
        <label>RS Contract Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Printed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to SSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by SSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deleted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <externalId>true</externalId>
        <label>Unit Number</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <recordTypes>
        <fullName>UVS</fullName>
        <active>true</active>
        <description>Record Type for UVS Vehicles</description>
        <label>UVS</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/SubmitBTRServiceTest.cls
@isTest(seeAlldata = true)
public with sharing class SubmitBTRServiceTest
{
	static User uvsUser;
	static testMethod void submitBTRTest()
	{
 		UserRole userRoleId_fam = [select Id from UserRole where name = 'VSM/VSR Calgary'];

        User sysAdmin_fam = TestUtilUvs.createAdminUser(false);
        sysAdmin_fam.UserRoleId = userRoleId_fam.id;
        sysAdmin_fam.Username = 'uvs@rydertest_fam.com';                        
        insert sysAdmin_fam;

		UserRole userRoleId_dam = [select Id from UserRole where name = 'DAM Canada'];
        User sysAdmin_dam = TestUtilUvs.createAdminUser(false);
        sysAdmin_dam.UserRoleId = userRoleId_dam.id;
        sysAdmin_dam.Username = 'uvs@rydertest_dam.com';
        insert sysAdmin_dam;            
            
        UserRole userRoleId_vam = [select Id from UserRole where name = 'VP Asset Management'];
        User sysAdmin_vam = TestUtilUvs.createAdminUser(false);
        sysAdmin_vam.UserRoleId = userRoleId_vam.id;
        sysAdmin_vam.Username = 'uvs@rydertest_vam.com';
        insert sysAdmin_vam;
        
		//uvsUser = TestUtilUVS.createUser(true);
  		system.runAs(sysAdmin_fam)
  		{			
	    	Product2 prod = new Product2();
	      	prod.Name = 'Standard Price Book UVS'; 
	      	prod.CurrencyIsoCode = 'CAD';
	      	insert prod;
	            
	    	PriceBookEntry pbe = [SELECT Id, Pricebook2Id FROM PriceBookEntry WHERE Product2Id = :prod.Id LIMIT 1];
	      	pbe.isActive = true;
	      	update pbe;   
	    
	    	Quote q = TestUtilUVS.createQuote('UVS',false);
	    	q.Pricebook2Id = pbe.Pricebook2Id;
	    	q.Requester_Comments__c = 'test' ;
	    	insert q;
	    
	        BTR__c btr = new BTR__c();
	        btr.Status__c = 'Submitted - With FAM';
	        btr.quote__c = q.id;
	        btr.Third_Approver__c = sysAdmin_vam.id;
	        btr.First_Approver__c= sysAdmin_fam.id;
	        btr.Second_Approver__c= sysAdmin_dam.id;
	        insert btr;
	                
	    	test.starttest();            
	    	QuoteLineItem qLI = new QuoteLineItem();
	    	qli.Approval_Level__c=2;
	    	qLi.QuoteId = q.Id;
	    	qLi.PricebookEntryId = pbe.Id;
	    	qLi.Product2Id = prod.id;
	    	qLi.Quantity = 123;
	    	qLi.UnitPrice = 100; 
	   	 	insert qLI;
	    	SubmitBTRService.checkAlreadySubmitted(q.id);
	    	SubmitBTRService.CheckIfQLIHasZeroSalesPrice(q.id);
	    	 
	    	if (UVS_Approval_Setting__c.getInstance() == null)
	    	{
	      		insert new UVS_Approval_Setting__c(Role_Names__c = 'VSM/VSR Calgary;VSM/VSR Dartmouth;VSM/VSR London;VSM/VSR Montreal;VSM/VSR Toronto;VSM/VSR Vancouver;VSM/VSR Export;DAM Canada;DAM Export');
	    	}
	    	SubmitBTRService.submitBTR(q.id);
	    
	    	
	    	qli.Approval_Level__c=3;
	   	 	update qli;
	    	SubmitBTRService.submitBTR(q.id);       
	    
	    	q.Requester_Comments__c = '' ;
	    	update q;
	    	SubmitBTRService.submitBTR(q.id) ;
	    
	    	btr.Status__c = 'Approved';
	    	update btr;
	    	SubmitBTRService.checkAlreadySubmitted(q.id); 
	    	SubmitBTRService.checkAlreadySubmitted('test'); 
	    	SubmitBTRService.submitBTR(q.id);
	    
	    	q.status = 'Denied';
	    	update q;
	    	qli.Approval_Level__c=0;
	    	update qli;
	    	SubmitBTRService.submitBTR(q.id);
	    
	    	qli.UnitPrice = 0;
	    	update qli;
	    	SubmitBTRService.CheckIfQLIHasZeroSalesPrice(q.id);
	     
	    	test.stoptest(); 
	  	}   
 	}
 	static testMethod void Test_SubmitBTRifBTRExistWithSubmitStatus()
 	{
		UserRole userRoleId_fam = [select Id from UserRole where name = 'VSM/VSR Calgary'];

        User sysAdmin_fam = TestUtilUvs.createAdminUser(false);
        sysAdmin_fam.UserRoleId = userRoleId_fam.id;
        sysAdmin_fam.Username = 'uvs@rydertest_fam.com';                        
        insert sysAdmin_fam;

		UserRole userRoleId_dam = [select Id from UserRole where name = 'DAM Canada'];
        User sysAdmin_dam = TestUtilUvs.createAdminUser(false);
        sysAdmin_dam.UserRoleId = userRoleId_dam.id;
        sysAdmin_dam.Username = 'uvs@rydertest_dam.com';
        insert sysAdmin_dam;            
            
        UserRole userRoleId_vam = [select Id from UserRole where name = 'VP Asset Management'];
        User sysAdmin_vam = TestUtilUvs.createAdminUser(false);
        sysAdmin_vam.UserRoleId = userRoleId_vam.id;
        sysAdmin_vam.Username = 'uvs@rydertest_vam.com';
        insert sysAdmin_vam;
        
        Account Acc1 = new Account();
        Acc1.name = 'Test';
        Acc1.account_classification__c = 'Key Account';
        Acc1.central_decisionmaking__c = False;
        Acc1.Type = 'Customer';
        Acc1.Account_Classification__c = 'National';
        Acc1.LesseeNo__c = '0123123';
        insert Acc1;
        Acc1.Account_Classification__c = 'Local';
        update Acc1;
    	
    	Customer_Branch__c CustomerBranch = new Customer_Branch__c();
	    CustomerBranch.Name = 'Test Customer Branch';
	    CustomerBranch.Ryder_HQ_Account__c = Acc1.Id;
	    insert CustomerBranch;
	    
    	Vehicle__c Vehicle = new Vehicle__c(Unit__c = '123456');
	    Vehicle.Name = '1234';
	    Vehicle.CUSTOMER_BRANCH__c = CustomerBranch.Id;
	    Vehicle.RSM__c = 'Approved';
	    Vehicle.Account__c = Acc1.Id;
	    insert Vehicle;
	    Vehicle.CUSTOMER_BRANCH__c = CustomerBranch.Id;
	    Vehicle.Days_At_UTC__c = 110;
		update Vehicle;
		
		//uvsUser = TestUtilUVS.createUser(true);
  		system.runAs(sysAdmin_fam)
  		{
	    	Product2 prod = new Product2();
	      	prod.Name = 'Standard Price Book UVS'; 
	      	prod.CurrencyIsoCode = 'CAD';
	      	insert prod;
	            
	    	PriceBookEntry pbe = [SELECT Id, Pricebook2Id FROM PriceBookEntry WHERE Product2Id = :prod.Id LIMIT 1];
	      	pbe.isActive = true;
	      	update pbe;   
	    
	    	Quote q = TestUtilUVS.createQuote('UVS',false);
	    	q.Pricebook2Id = pbe.Pricebook2Id;
	    	q.Requester_Comments__c = 'test' ;
	    	insert q;
	    	
	        BTR__c btr = new BTR__c();
	        btr.Status__c = 'Submitted - With FAM';
	        btr.quote__c = q.id;
	        btr.Third_Approver__c = sysAdmin_vam.id;
	        btr.First_Approver__c= sysAdmin_fam.id;
	        btr.Second_Approver__c= sysAdmin_dam.id;
	        insert btr;
	                
	    	test.starttest();
	    	
		    	QuoteLineItem qLI = new QuoteLineItem();
		    	qli.Approval_Level__c = 1;
		    	qLi.QuoteId = q.Id;
		    	qLi.PricebookEntryId = pbe.Id;
		    	qLi.Product2Id = prod.id;
		    	qLi.Quantity = 1;
		    	qLi.UnitPrice = 10; 
		    	qLi.Take_Price2__c = 2;
		    	qLI.Vehicle__c = Vehicle.Id;		    	
		   	 	insert qLI;
		   	 	
		    	if (UVS_Approval_Setting__c.getInstance() == null)
		    	{
		      		insert new UVS_Approval_Setting__c(Role_Names__c = 'VSM/VSR Calgary;VSM/VSR Dartmouth;VSM/VSR London;VSM/VSR Montreal;VSM/VSR Toronto;VSM/VSR Vancouver;VSM/VSR Export;DAM Canada;DAM Export');
		    	}
		    	// There is already a existing submitted BTR now if the user submit a new BTR the previous one should become Rejected
		    	String sMSG = SubmitBTRService.submitBTR(q.id);
		    	system.debug('---------sMSG->'+sMSG);
				List<BTR__c> lBTR = [select Id, Status__c from BTR__c where Id =: btr.Id];
				
				if(lBTR != null && lBTR.size() > 0)
					System.assertEquals('Rejected', lBTR[0].Status__c);
	     
	    	test.stoptest(); 
	  	}
	}
}