SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <picklist>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wholesale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Export</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Interest_Rate__c</fullName>
        <label>Interest Rate</label>
        <picklist>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16.5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Original_Decision_Maker__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Original Decision Maker</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>Contact.STATUS_ACTIVE__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>The Contact you are adding as an Original Decision Maker must be an active Contact within the same Account where you are creating the new Opportunity.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <label>Term</label>
        <picklist>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>36</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>42</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>48</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>54</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Interest_Rate__c</fullName>
        <label>Interest Rate</label>
        <picklist>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16.5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Detail__c</fullName>
        <label>Product Detail</label>
        <picklist>
            <controllingField>Product_Line__c</controllingField>
            <picklistValues>
                <fullName>VOSA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Choice Lease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flex</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fast Track</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plus One</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physical Damage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haz-mat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OPIS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <label>Product Line</label>
        <picklist>
            <picklistValues>
                <fullName>FSL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RPM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rydesmart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DCC Light</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fuel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <label>Term</label>
        <picklist>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>36</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>42</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>48</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>54</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <picklist>
            <picklistValues>
                <fullName>New Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Location</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fleet Add</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Replacement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Term Extension</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rate Change</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Unit_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Number</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

SFDC Automation/src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Interest_Rate__c</fullName>
        <label>Interest Rate</label>
        <picklist>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5.5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup on Accounts</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ask_Price__c</fullName>
        <label>Ask Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NBV__c</fullName>
        <label>Book Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PRODUCT_LINE__c</fullName>
        <description>Product Line</description>
        <label>Product Line</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Detail__c</fullName>
        <description>Product Detail as indicated in the contract package</description>
        <label>Product Detail</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Take_Price__c</fullName>
        <label>Take Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <description>This field will hold the transaction type of the vehicle. Eg: Lease Extension</description>
        <label>Transaction Type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <recordTypes>
        <fullName>UVS</fullName>
        <active>true</active>
        <description>Record Type for UVS Vehicles</description>
        <label>UVS</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/QLIOLISyncManagerTest.cls
/*************************************************************************************************
Created By:    Jyotirmaya Rath
Date:          October 14, 2014
Description  : Test class for QLIOLISyncManager class
**************************************************************************************************/
@isTest(seeAllData = true)
private class QLIOLISyncManagerTest
{
    static User uvsAdminUser ;
    
    static testMethod void TestOpportunitySyncMultipleUnits()
    {
        uvsAdminUser = TestUtilUVS.createAdminUser(true);
        system.runAs(uvsAdminUser)
        {
        	test.startTest();
        	
        	list<QuoteLineItem> quotelineItemList = new list<QuoteLineItem>();
            Account acc = TestUtilUVS.createAccount('Ryder FMS Parent Account', 'FMS', true);
            Contact con = TestUtilUVS.createContact(acc.Id,True);
                        
            Product2 prod = new Product2();
	        prod.Name = 'Standard Price Book UVS';
	        prod.CurrencyIsoCode = 'CAD';
	        prod.family = 'FSL';
	        insert prod;
	       	
	       	PriceBookEntry pbe = [Select Name ,Product2.Family,Product2.Id, Pricebook2Id , Pricebook2.name , CurrencyIsoCode From PricebookEntry where Pricebook2.name= 'UVS' LIMIT 1];
            pbe.isActive = true;
            update pbe;
            
            String productFamily = pbe.Product2.Family;
            Opportunity opp = TestUtilUVS.createOpportunity('UVS Opportunity', acc, false, con);
            opp.Original_Decision_Maker__c = con.Id;
            opp.Pricebook2Id = pbe.Pricebook2Id;
            opp.CurrencyIsoCode = pbe.CurrencyIsoCode;            
            insert opp;
			
			Quote quote = new Quote();
            quote.Name = 'test-Quote UVS';
            quote.OpportunityId = opp.Id;
            quote.Pricebook2Id = pbe.Pricebook2Id;
            insert quote;
			test.stopTest();
			
			opp = [Select Id, SyncedQuoteId from Opportunity where id= : opp.id limit 1];
            opp.SyncedQuoteId =  Quote.id;
			update opp;
			
			List<QuoteLineItem> lquotelineItem = [Select Id from QuoteLineItem where QuoteId = : quote.Id];
			System.debug('----------QLI Size--1.0->' + lquotelineItem.size());
						
            Vehicle__c veh = new Vehicle__c();
            veh.Name = 'test1';
            veh.Account__c = acc.Id;
            veh.Take_Price__c = 11;
            veh.NBV__c = 11;
            veh.Ask_Price__c = 20000.0;
            insert Veh;
            
            Vehicle__c veh1 = new Vehicle__c();
            veh1.Name = 'test2';
            veh1.Account__c = acc.Id;
            veh1.Take_Price__c = 11;
            veh1.NBV__c = 11;
            veh1.Ask_Price__c = 20000.0;
            insert veh1;
						
            OpportunityLineItem oLI = new OpportunityLineItem();
            oLI.OpportunityId=opp.Id;
            oLI.Unit_Number__c=veh.Id;
            oLI.PricebookEntryId=pbe.Id;
            oLI.Quantity=1;
            oLI.UnitPrice=123;
            oLI.Transaction_Type__c='NewCustomer';
            oLI.Product_Line__c= productFamily;
            oLI.Product_Detail__c='VOSA';
            insert oLI;
            lquotelineItem = [Select Id from QuoteLineItem where QuoteId = : quote.Id];
			System.debug('----------QLI Size--1.1->' + lquotelineItem.size());
			
            OpportunityLineItem oLI1 = new OpportunityLineItem();
            oLI1.OpportunityId=opp.Id;
            oLI1.Unit_Number__c=veh1.Id;
            oLI1.PricebookEntryId=pbe.Id;
            oLI1.Quantity=1;
            oLI1.UnitPrice=123;
            oLI1.Transaction_Type__c='NewCustomer';
            oLI1.Product_Line__c= productFamily;
            oLI1.Product_Detail__c='VOSA';
            insert oLI1;
            
			lquotelineItem = [Select Id from QuoteLineItem where QuoteId = : quote.Id];
			System.debug('----------QLI Size--1.2->' + lquotelineItem.size());
			System.assertEquals(2, lquotelineItem.size());			
		}
    }
    
    
    static testMethod void testSyncQLIOLISyncManager()
    {
        uvsAdminUser = TestUtilUVS.createAdminUser(true);
        system.runAs(uvsAdminUser)
        {
        	test.startTest();
        	list<QuoteLineItem> quotelineItemList = new list<QuoteLineItem>();
            Account acc = TestUtilUVS.createAccount('Ryder FMS Parent Account', 'FMS', true);
            Contact con = TestUtilUVS.createContact(acc.Id,True);
                        
            Product2 prod = new Product2();
	        prod.Name = 'Standard Price Book UVS';
	        prod.CurrencyIsoCode = 'CAD';
	        prod.family = 'FSL';
	        insert prod;
	       	
	       	PriceBookEntry pbe = [Select Name ,Product2.Family,Product2.Id, Pricebook2Id , Pricebook2.name , CurrencyIsoCode From PricebookEntry where Pricebook2.name= 'UVS' LIMIT 1];
            pbe.isActive = true;
            update pbe;
            
            String productFamily = pbe.Product2.Family;
            Opportunity opp = TestUtilUVS.createOpportunity('UVS Opportunity', acc, false, con);
            opp.Original_Decision_Maker__c = con.Id;
            opp.Pricebook2Id = pbe.Pricebook2Id;
            opp.CurrencyIsoCode = pbe.CurrencyIsoCode;            
            insert opp;
			
			Quote quote = new Quote();
            quote.Name = 'test-Quote UVS';
            quote.OpportunityId = opp.Id;
            quote.Pricebook2Id = pbe.Pricebook2Id;
            insert quote;
            
            opp = [Select id,SyncedQuoteId from Opportunity where id=:opp.id limit 1];
            opp.SyncedQuoteId =  Quote.id;
			update opp;

            Vehicle__c veh = new Vehicle__c();
            veh.Name = 'test1';
            veh.Account__c = acc.Id;
            veh.Ask_Price__c = 11;
            veh.Take_Price__c = 11;
            veh.NBV__c = 11;
            veh.Ask_Price__c = 20000.0;
            insert Veh;
            
            Vehicle__c veh1 = new Vehicle__c();
            veh1.Name = 'test1';
            veh1.Account__c = acc.Id;
            veh1.Ask_Price__c = 11;
            veh1.Take_Price__c = 11;
            veh1.NBV__c = 11;
            veh1.Ask_Price__c = 20000.0;
            insert veh1;
			test.stopTest();
            OpportunityLineItem oLI = new OpportunityLineItem();
            oLI.OpportunityId=opp.Id;
            oLI.Unit_Number__c=veh.Id;
            oLI.PricebookEntryId=pbe.Id;
            oLI.Quantity=1;
            oLI.UnitPrice=123;
            oLI.Transaction_Type__c='NewCustomer';
            oLI.Product_Line__c= productFamily;
            oLI.Product_Detail__c='VOSA';
            insert oLI;
            
            OpportunityLineItem oLI1 = new OpportunityLineItem();
            oLI1.OpportunityId=opp.Id;
            oLI1.Unit_Number__c=veh1.Id;
            oLI1.PricebookEntryId=pbe.Id;
            oLI1.Quantity=1;
            oLI1.UnitPrice=123;
            oLI1.Transaction_Type__c='NewCustomer';
            oLI1.Product_Line__c= productFamily;
            oLI1.Product_Detail__c='VOSA';
            insert oLI1;
			
            QuoteLineItem quoteLI =new QuoteLineItem();
            quoteLI.PriceBookEntryId=pbe.Id;
            quoteLI.Quantity=1;
            quoteLI.Quantity__c=1;
            quoteLI.UnitPrice=123;
            quoteLI.Vehicle__c = veh.Id;
            quoteLI.QuoteId=quote.Id;
			quoteLI.Interest_Rate__c = '12';
			quoteLI.Term__c = '12';
            quotelineItemList.add(quoteLI);
			
			QuoteLineItem quoteLI1 =new QuoteLineItem();
            quoteLI1.PriceBookEntryId=pbe.Id;
            quoteLI1.Quantity=1;
            quoteLI1.Quantity__c=1;
            quoteLI1.UnitPrice=123;
            quoteLI1.Vehicle__c = veh1.Id;
            quoteLI1.QuoteId = quote.Id;
			quoteLI1.Interest_Rate__c = '12';
			quoteLI1.Term__c = '12';
            quotelineItemList.add(quoteLI1);
            
            
            try
            {
	        	if(!quotelineItemList.isEmpty())
	        	{
	            	insert quotelineItemList;
	        	}
            }
            catch(Exception ex)
            {
            	system.debug('::test Exception :::'+ex);
            }    
            quoteLI.Quantity=2;
            quoteLI.Quantity__c=2;
            quoteLI.UnitPrice=124;
            try
            {
                Update quoteLI;
            }
            catch(exception e)
            {
              system.debug('=============EXCEPTION===========' + e.getMessage());
            }
            
			Map<Id, OpportunityLineItem> mOLI = new Map<Id, OpportunityLineItem>();
			mOLI.put(oLI.Id, oLI);
			QLIOLISyncManager.syncQuoteLineItems(mOLI, mOLI);
			
			System.assertequals(oLI.Description, quoteLI.Description);
      }

    }
    
   static testMethod void testSyncOLIQLISyncManager() {
       uvsAdminUser = TestUtilUVS.createAdminUser(true);
       system.runAs(uvsAdminUser) {
    Vehicle__c veh = new Vehicle__c();
    list<QuoteLineItem> quotelineItemList = new list<QuoteLineItem>();
            
            Account acc = TestUtilUVS.createAccount('Ryder FMS Parent Account', 'FMS', true);
            Contact con = TestUtilUVS.createContact(acc.Id,True);
            
            Product2 prod = new Product2();
            prod.Name = 'testUVS123';
            prod.CurrencyIsoCode = 'USD';
            prod.IsActive = true;
            prod.family = 'FSL';
            insert prod;


        	 PriceBookEntry pbe = [Select Name ,Product2.Family,Product2.Id, Pricebook2Id , Pricebook2.name , CurrencyIsoCode From PricebookEntry where Pricebook2.name= 'UVS' LIMIT 1];
            pbe.isActive = true;
            update pbe;
            
            system.debug('::PBE :::'+pbe);
            String productFamily = pbe.Product2.Family;
test.startTest();
            Opportunity opp = TestUtilUVS.createOpportunity('UVS Opportunity', acc, false, con);
            opp.Original_Decision_Maker__c = con.Id;
            opp.Pricebook2Id = pbe.Pricebook2Id;
            opp.CurrencyIsoCode = pbe.CurrencyIsoCode;
            insert opp;
            Test.stopTest();
            Quote quote = new Quote();
            quote.Name = 'test-Quote UVS';
            quote.OpportunityId = opp.Id;
            quote.Pricebook2Id = pbe.Pricebook2Id;

          //quote.IsSyncing = true;
            insert quote;

            //opp.SyncedQuoteId = quote.Id;
            //update opp;
            //System.assert([select IsSyncing from Quote where id =:quote.id].IsSyncing);


            veh.Name = 'test1';
            veh.Account__c = acc.Id;
            veh.Ask_Price__c = 11;
            veh.Take_Price__c = 11;
            veh.NBV__c = 11;
            insert Veh ;
         //   veh = TestUtilUVS.createUVSVehicle(acc, true);
			
            OpportunityLineItem oLI = new OpportunityLineItem();
            oLI.OpportunityId=opp.Id;
            oLI.Unit_Number__c=veh.Id;
            oLI.PricebookEntryId=pbe.Id;
            oLI.Quantity=1;
            oLI.UnitPrice=123;
            oLI.Transaction_Type__c='NewCustomer';
            oLI.Product_Line__c= productFamily;
            oLI.Product_Detail__c='VOSA';
            //oLi.IsTestRunning__c = true;
            insert oLI;
			
            QuoteLineItem quoteLI =new QuoteLineItem();
            quoteLI.PriceBookEntryId=pbe.Id;
            quoteLI.Quantity=1;
            quoteLI.Quantity__c=1;
            quoteLI.UnitPrice=123;
            quoteLI.Vehicle__c = veh.Id;
            quoteLI.QuoteId=quote.Id;
            quoteLI.Interest_Rate__c = '12';
			quoteLI.Term__c = '12';


            quotelineItemList.add(quoteLI);

            try{
	            if(!quotelineItemList.isEmpty()) {
	                insert quotelineItemList;
	            }
            }catch(Exception ex){
            	system.debug('::Exception ex ::'+ex);
            }

            OpportunityLineItem SyncOLI = [select  id,
                                                    Transaction_Type__c,
                                                    Quantity,
                                                    UnitPrice,
                                                    Unit_Number__c
                                            from OpportunityLineItem
                                            WHERE id =: OLI.id ];
           SyncOLI.Quantity  = 2;
           SyncOLI.Quantity__C = 2;
            SyncOLI.UnitPrice = 124 ;
           // SyncOLI.IsTestRunning__c = true;
            Try {
                Update SyncOLI;
             }
             Catch (Exception e){
                system.debug('::Exception :::'+e);
             }
        }

    }
    
   static testMethod void testSyncQuoteLineItemsOnInsert() {
   	  User uvsUser;
	  Account acc;
	  Contact con;
	  Vehicle__c veh;
	  Product2 prod;
	  Opportunity opp;
	  OpportunityLineItem oli;
	  Quote quote;
	  list<QuoteLineItem> qliList = new list<QuoteLineItem>();
    uvsUser = TestUtilUVS.createUser(true);
    system.runAs(uvsUser) {
    	test.startTest();
    	acc = TestUtilUVS.createAccount('Ryder FMS Parent Account', 'FMS', true);
    	con = TestUtilUVS.createContact(acc.Id,false);
      con.Additional_Comments__c = 'Test1';
      con.Email = 'test2@rydertest.com';
      con.OwnerId = UserInfo.getUserId();
      insert con;
      Test.stopTest();
      prod = new Product2();
	    prod.Name = 'testUVS123';
	    prod.CurrencyIsoCode = 'USD';
	    prod.IsActive = true;

	    insert prod;

	  

		PriceBookEntry pbe = [Select Name , Pricebook2Id , Pricebook2.name , CurrencyIsoCode From PricebookEntry where Pricebook2.name= 'UVS' LIMIT 1];
        pbe.isActive = true;
        update pbe;
      opp = TestUtilUVS.createOpportunity('UVS Opportunity', acc, false, con);
      opp.Original_Decision_Maker__c = con.Id;
      opp.Pricebook2Id = pbe.Pricebook2Id;
      opp.CurrencyIsoCode = pbe.CurrencyIsoCode;
      insert opp;
      veh = TestUtilUVS.createUVSVehicle(acc, true);

      quote = new Quote();
      quote.Name = 'test-Quote UVS';
      quote.OpportunityId = opp.Id;
      quote.Pricebook2Id = pbe.Pricebook2Id;
      //quote.IsSyncing = true;
      insert quote;

      oLI = new OpportunityLineItem();
      oLI.OpportunityId = opp.Id;
      oLI.Unit_Number__c = veh.Id;
      oLI.PricebookEntryId = pbe.Id;
      oLI.Quantity = 1;
      oLI.UnitPrice = 123;
      //oLI.Take_Price__c = 12;
      oLI.Transaction_Type__c = 'New Location';
      oLI.Product_Line__c = 'FSL';
      oLI.Product_Detail__c = 'VOSA';

      
      //insert oLI;


      QuoteLineItem qLI = new QuoteLineItem();
      qLI.PriceBookEntryId = pbe.Id;
      qLI.Quantity = 1;
      qLI.UnitPrice = 123;
      qLI.Vehicle__c = veh.Id;
      qLI.QuoteId = quote.Id;
	  qLI.Interest_Rate__c = '12';
	  qLI.Term__c = '12';
      qliList.add(qLI);

      if(!qliList.isEmpty()) {
      	insert qliList;
      }

      //opp = [Select Id, SyncedQuoteId from Opportunity where Id = :opp.Id limit 1];
      //opp.SyncedQuoteId = quote.Id;

      //update opp;



      //qLI = [select Id, UnitPrice from QuoteLineItem where Id in :qliList].get(0);

      qLI.Approved_Price__c = 1234;
      qLI.Interest_Rate__c = '12';
	  qLI.Term__c = '12';
	  qLI.UnitPrice = 12;
      update qLI;



    }
  }
}