SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>UTC_Assigned__c</fullName>
        <label>UTC Assigned</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/BTR__c.object
<CustomObject>
    <description>Linked to the quote object as 1:1 relationship and used to drive the approval process for the quotes</description>
    <fields>
        <fullName>Is_Conditional_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Conditional Approval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The quote record to which this BTR approval process is linked to.</description>
        <inlineHelpText>The quote record to which this BTR approval process is linked to.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>BTRs</relationshipLabel>
        <relationshipName>BTRs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requester_Comments__c</fullName>
        <label>BTR Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ryder_Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is a lookup to Ryder Branch object.</description>
        <inlineHelpText>Points to the branch of the user who created the BTR.</inlineHelpText>
        <label>Ryder Branch</label>
        <referenceTo>Ryder_Branch__c</referenceTo>
        <relationshipLabel>BTRs</relationshipLabel>
        <relationshipName>BTRs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the BTR approval process for a given quote.</description>
        <inlineHelpText>The status of the BTR approval process for a given quote.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Submitted - With FAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted - With DAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted - With VP AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BTR</label>
    <nameField>
        <displayFormat>BTR-{0000000}</displayFormat>
        <label>BTR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BTRs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/BTR_History__c.object
<CustomObject>
    <fields>
        <fullName>Approved_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Approved Price</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>As_Is_Vehicle__c</fullName>
        <defaultValue>false</defaultValue>
        <label>As Is Vehicle</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BTR_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BTR Number</label>
        <referenceTo>BTR__c</referenceTo>
        <relationshipLabel>BTR Histories</relationshipLabel>
        <relationshipName>BTR_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Book_Value__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Book Value</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gain_Loss__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Gain (Loss)</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Is_Conditional_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the BTR is approved conditionally.</description>
        <label>Is Conditional Approval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Make_Model__c</fullName>
        <label>Make Model</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NVI_Percent__c</fullName>
        <label>NVI(%)</label>
        <precision>17</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Quote_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Number</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>BTR Histories</relationshipLabel>
        <relationshipName>BTR_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requester_Comments__c</fullName>
        <label>BTR Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SAM_Class__c</fullName>
        <label>SAM Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Take_Price_percent__c</fullName>
        <label>Take Price (%)</label>
        <precision>17</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>UTC__c</fullName>
        <label>UTC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VOSA__c</fullName>
        <defaultValue>false</defaultValue>
        <label>VOSA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <description>This field holds the model year (this is defined as text to suppress the &apos;,&apos; in the UI).</description>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>BTR History</label>
    <nameField>
        <label>BTR History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BTR Histories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>UTC_Assigned__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to Ryder Branch in order to know the location</description>
        <inlineHelpText>Look up to Ryder Branch in order to know the location</inlineHelpText>
        <label>UTC Assigned</label>
        <referenceTo>Ryder_Branch__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Requester_Comments__c</fullName>
        <label>BTR Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>UTC_Assigned__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to Ryder Branch in order to know the location</description>
        <inlineHelpText>Look up to Ryder Branch in order to know the location</inlineHelpText>
        <label>UTC Assigned</label>
        <referenceTo>Ryder_Branch__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UTC__c</fullName>
        <formula>$User.UTC__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UTC</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Approved_Price__c</fullName>
        <label>Approved Price</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>As_Is_Vehicle__c</fullName>
        <description>Vehicle&apos;s AsIs field value</description>
        <formula>Vehicle__r.AS_IS_Vehicle__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>As Is Vehicle</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Book_Value__c</fullName>
        <formula>Vehicle__r.NBV__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Book Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Customer_Offer_Price__c</fullName>
        <label>Customer Offer Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Days_held__c</fullName>
        <formula>Vehicle__r.Days_At_UTC__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days held</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Eng_Mdl__c</fullName>
        <description>Vehicle Engine Model</description>
        <formula>Vehicle__r.ENG_MDL__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Engine Model</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gain_Loss__c</fullName>
        <formula>UnitPrice - Book_Value__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Gain (Loss)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Make_Model__c</fullName>
        <description>Concatenation of Vehicle.Manufacturer__c and Vehicle.Model__c</description>
        <formula>Vehicle__r.Manufacturer__c &amp; &apos; &apos; &amp; Vehicle__r.Model__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Make/Model</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Miles__c</fullName>
        <description>Vehicle Miles</description>
        <formula>Vehicle__r.MILES__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mileage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Model_Year__c</fullName>
        <formula>TEXT(Vehicle__r.Model_Year__c)</formula>
        <label>Model Year</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NVI_Percent__c</fullName>
        <description>NVI Percentage</description>
        <formula>(UnitPrice* 10000) / Vehicle__r.NVI__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NVI %</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>SAM_Class__c</fullName>
        <formula>Vehicle__r.SAM_CLASS__c &amp; &apos; &apos; &amp; Vehicle__r.VEH_CLS_SAM_DS__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SAM Class</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Take_Price2__c</fullName>
        <label>Take Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Take_Price_percent__c</fullName>
        <formula>UnitPrice/Take_Price2__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Take Price (%)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vosa__c</fullName>
        <formula>Vehicle__r.VOSA__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vosa</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>UTC__c</fullName>
        <description>This field will capture the location code for the user.</description>
        <label>UTC</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <fields>
        <fullName>AS_IS_Vehicle__c</fullName>
        <defaultValue>false</defaultValue>
        <label>AS IS Vehicle</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Approved_Price__c</fullName>
        <label>Approved Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ENG_MDL__c</fullName>
        <label>Engine Model</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gain_Loss__c</fullName>
        <label>Gain Loss</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MILES__c</fullName>
        <label>Miles</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Model_Year__c</fullName>
        <description>Year of the vehicle</description>
        <label>Model Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SAM_CLASS__c</fullName>
        <description>Sam Class</description>
        <label>SAM Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Take_Price_Percent__c</fullName>
        <formula>IF(Ask_Price__c &gt; 0, Take_Price__c / Ask_Price__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Take Price (%)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>VOSA__c</fullName>
        <defaultValue>false</defaultValue>
        <label>VOSA</label>
        <type>Checkbox</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/BTRTriggerHandler.cls
/**=====================================================================
 * Appirio, Inc
 * Name: BTRTriggerHandler
 * Created Date: 9-25-2014
 * Created By: Sunil (Appirio)
 =====================================================================*/
public without sharing class BTRTriggerHandler {
  // update Quote Satus To Approved
  public static void updateQuoteSatusToApproved(Map<Id, BTR__c> mapOld, Map<Id, BTR__c> mapNew) {
    Set<Id> setQuotes = new Set<Id>();
    Set<Id> setEligibleIds = new Set<Id>();
    Set<Id> ownerIds = new Set<Id>();
    for(BTR__c b :mapNew.values()){
        if(mapOld.get(b.Id).Status__c != b.Status__c && b.Status__c == 'Approved'){
        setQuotes.add(b.Quote__c);
        setEligibleIds.add(b.Id);
        ownerIds.add(b.OwnerId);
      }
    }
    System.debug('@@@' + setQuotes);
    
    Map<Id, BTR__c> mapBTR = new Map<Id, BTR__c>([SELECT Id, Quote__c,CreatedDate, Is_Conditional_Approval__c, Name, 
                     Status__c, Owner.Name, Requester_Comments__c, 
                     OwnerId, Ryder_Branch__r.Name FROM BTR__c WHERE Id IN :setEligibleIds]);
    
    // Update Related Quote Status
    List<Quote> lstQuotes = new List<Quote>();
    for(Quote q :[SELECT Id, Status FROM Quote WHERE Id IN :setQuotes]){
      q.Status = 'BTR Approved';
      lstQuotes.add(q);
    }
    System.debug('@@@' + lstQuotes);
    update lstQuotes;
    
    Map<Id, User> mapOwners = new Map<Id, User>([SELECT Id, UTC__c FROM User WHERE Id IN :ownerIds]);
    System.debug('@@@' + mapOwners);
        
    // Insert BTR History record.
    Set<Id> quotesIdSet = new Set<Id>();
    map<Id,BTR__c> quoteToBTRMap = new map<Id,BTR__c>();
    for(BTR__c b :mapNew.values()){
      if(setEligibleIds.contains(b.Id)){
        quotesIdSet.add(b.Quote__c);
        BTR__c objBTR = mapBTR.get(b.Id);
        quoteToBTRMap.put(b.Quote__c, objBTR);
      }
    }
    
    System.debug('Map New:'+mapNew.keySet());
    System.debug('Eligible ids:'+setEligibleIds);
    
    List<Quote> quotesList = [Select Id, Opportunity.Account.Name, (Select Id,SAM_Class__c, UnitPrice, Model_Year__c,Make_Model__c,Eng_Mdl__c,Miles__c,
                                       NVI_Percent__c,Take_Price_percent__c, Book_Value__c,Take_Price2__c,Customer_Offer_Price__c,Gain_Loss__c,As_Is_Vehicle__c,
                                        Vosa__c,Approved_Price__c,Vehicle__r.Name, CreatedBy.Name, CreatedDate, Days_Held__c
                                FROM QuoteLineItems), UTC_Assigned__c 
                                FROM Quote WHERE Id in:quotesIdSet];
    List<QuoteLineItem> lineItems;
    List<BTR_History__c> lstHistory = new List<BTR_History__c>();
    BTR_History__c objHistory ;
    //map<Id,List<QuoteLineItem>> quoteLineItemsMap = new map<Id,List<QuoteLineItem>>([Select Id,(Select Id From QuoteLineItems) from Quote where Id in:quotesIdSet]);
    for(Quote quo : quotesList){
        lineItems = quo.QuoteLineItems;
        if(lineItems!=null && !lineItems.isEmpty()){
            for(QuoteLineItem qli : lineItems){
                objHistory = new BTR_History__c();
                objHistory.BTR_Number__c = quoteToBTRMap.get(quo.Id).Id;
                objHistory.Requester_Comments__c = quoteToBTRMap.get(quo.Id).Requester_Comments__c;
                objHistory.Quote_Number__c = quoteToBTRMap.get(quo.Id).Quote__c;
                objHistory.BTR_Status__c = quoteToBTRMap.get(quo.Id).Status__c;
                objHistory.Vehicle_Number__c = qli.Vehicle__r.Name;
                objHistory.SAM_Class__c = qli.SAM_Class__c;
                objHistory.Year__c = qli.Model_Year__c;
                objHistory.Make_Model__c = qli.Make_Model__c;
                objHistory.Days_At_UTC__c = qli.Days_Held__c;
                objHistory.NVI_Percent__c = qli.NVI_Percent__c;
                objHistory.Take_Price_percent__c = qli.Take_Price_percent__c;
                objHistory.Engine_Make_Model__c = qli.Eng_Mdl__c;
                objHistory.Mileage__c = qli.Miles__c;
                objHistory.Book_Value__c = qli.Book_Value__c;
                objHistory.Take_Price__c = qli.Take_Price2__c;
                objHistory.Offer_Price_Sale_Price__c = qli.UnitPrice;//qli.Customer_Offer_Price__c;
                objHistory.Gain_Loss__c = qli.Gain_Loss__c;
                objHistory.As_Is_Vehicle__c = qli.As_Is_Vehicle__c;
                objHistory.VOSA__c = qli.Vosa__c;
                objHistory.Approved_Price__c = qli.Approved_Price__c;
                objHistory.Customer_Name__c = quo.Opportunity.Account.Name;
                objHistory.Requestor__c = quoteToBTRMap.get(quo.Id).Owner.Name;
                objHistory.Is_Conditional_Approval__c = quoteToBTRMap.get(quo.Id).Is_Conditional_Approval__c;
                objHistory.Request_Date__c = quoteToBTRMap.get(quo.Id).CreatedDate;
                objHistory.UTC__c = quoteToBTRMap.get(quo.Id).Ryder_Branch__r.Name;//mapOwners.get(quoteToBTRMap.get(quo.Id).OwnerId).UTC__c;
                lstHistory.add(objHistory);
            }
        }
    }
    System.debug('List history:'+lstHistory);
 
    /*for(Id quoteId : quotesIdSet){
        if(quoteLineItemsMap.containsKey(quoteId)){
            for(QuoteLineItem qli: quoteLineItemsMap.get(quoteId)){
                objHistory = new BTR_History__c();
                objHistory.BTR_Number__c = b.Id;
                objHistory.Quote_Number__c = b.Quote__c;
                objHistory.BTR_Status__c = b.Status__c;
                objHistory.Vehicle_Number__c = b.Name;
                objHistory.SAM_Class__c = b.SAM_Class__c;
                objHistory.Year__c = b.Year__c;
                objHistory.Make_Model__c = b.Make_Model__c;
                objHistory.Location__c = b.Location__c;
                objHistory.Days_At_UTC__c = b.Days_At_UTC__c;
                objHistory.Engine_Make_Model__c = b.Engine_Make_Model__c;
                objHistory.Mileage__c = b.Mileage__c;
                objHistory.Book_Value__c = b.Book_Value__c;
                objHistory.Take_Price__c = b.Take_Price2__c;
                objHistory.Offer_Price_Sale_Price__c = b.Offer_Price_Sale_Price__c;
                objHistory.Gain_Loss__c = b.Gain_Loss__c;
                objHistory.As_Is_Vehicle__c = b.As_Is_Vehicle__c;
                objHistory.VOSA__c = b.VOSA__c;
                objHistory.Approved_Price__c = b.Approved_Price__c;
                objHistory.Customer_Name__c ='';
                objHistory.Requestor__c ='';
                objHistory.Request_Date__c  = '';
                objHistory.UTC__c = '';
                
                lstHistory.add(objHistory);
            }
        }
    }*/
    if(!lstHistory.isEmpty())
        insert lstHistory;
  }
}