SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LesseeNo__c</fullName>
        <description>Realtime update of both SFDC and RADAR whenever this value is changed in either system</description>
        <label>Lessee Number</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RSM_AC_Classification__c</fullName>
        <description>RydeSmart Account Classification</description>
        <inlineHelpText>If RS Account Classification is changed manually then Check &quot;Do Not Override AC&quot; field.</inlineHelpText>
        <label>RydeSmart Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Key Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Key Account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RSM_Manual_Update__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field to check if RydeSmart Account is Manually Updated</description>
        <label>Do Not Override RC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RSM_PLC_FLag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>RSM PLC FLag</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/RSM_Contract__c.object
<CustomObject>
    <description>Object to store RydeSmart Contract details</description>
    <fields>
        <fullName>CreatedDate__c</fullName>
        <description>To store the Created Date of the Contract in the Telemetry</description>
        <label>CreatedDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Lessee__c</fullName>
        <label>Lessee</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status_Name__c</fullName>
        <label>Status Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>RSM Contract</label>
    <nameField>
        <label>RSM Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RSM Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC Automation/src/classes/RSMCreatePreLaunchCheckList_Test.cls
@isTest
private class RSMCreatePreLaunchCheckList_Test
{
	static testmethod void unitTest()
	{
		Test.startTest();
		RSMCreateTestData.GetCustomSettingsRecord();
        
        Account ac = new Account();
        ac.Name = 'Test Accounts';
        ac.LesseeNo__c ='1234567';
        ac.RSM_AC_Classification__c = 'Key Account';
        ac.RSM_Manual_Update__c = true;
        insert ac;
        
        RSM_Contract__c rCon1=new RSM_Contract__c();    
        rCon1.Name='123';
        rCon1.Lessee__c='1234567';
        rCon1.Status_Name__c = 'Approved';
        rCon1.CreatedDate__c = System.now();
        insert rCon1;
        
        RSM_Contract__c rCon2=new RSM_Contract__c();    
        rCon2.Name='1234';
        rCon2.Lessee__c='1234567';
        rCon2.Status_Name__c = 'Approved';        
        rCon2.CreatedDate__c = System.now();     
        insert rCon2; 
        
        RSMCreatePreLaunchCheckList rcpc = new RSMCreatePreLaunchCheckList();
        //rcpc.query='select Id,Lessee__c,CreatedDate__c from RSM_Contract__c where Id in(\''+rCon1.Id+'\')'; 
        rcpc.query='select Id,LesseeNo__c,RSM_PLC_Flag__c from Account where Id in(\''+ac.Id+'\')';
        Database.executeBatch(rcpc);
        
        Test.stopTest();
    }
}