SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Classification__c</fullName>
        <label>Account Classification</label>
        <picklist>
            <picklistValues>
                <fullName>National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coordinated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Coordinated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National - Cash Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local - Cash Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Cash and Non-Cash</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NCA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NCA</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>That person does not have an NCA profile</errorMessage>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>NCA</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>AccountsForNCA</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_Classification__c</fullName>
        <formula>TEXT( Account.Account_Classification__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Classification</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Original_Decision_Maker__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Original Decision Maker</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>Contact.STATUS_ACTIVE__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>The Contact you are adding as an Original Decision Maker must be an active Contact within the same Account where you are creating the new Opportunity.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate_Sheet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rate Sheet</label>
        <referenceTo>Rate_Sheet__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/PartialWinRateSheet__c.object
<CustomObject>
    <description>Contains the list of Rate Sheets which were not booked</description>
    <fields>
        <fullName>IsTaskCreated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Determines if a task has been created to this Partial Win</description>
        <label>IsTaskCreated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>PartialWinRateSheets</relationshipLabel>
        <relationshipName>PartialWinRateSheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Original_Decision_Maker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Decision Maker</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>PartialWinRateSheets</relationshipLabel>
        <relationshipName>PartialWinRateSheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate_Sheet__c</fullName>
        <description>Contains the Rate Sheet # (ext_ratesheet_id__c from the Rate_Sheet__c object)</description>
        <label>Rate Sheet #</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>PartialWinRateSheet</label>
    <nameField>
        <label>PartialWinRateSheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PartialWinRateSheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Rate_Sheet__c.object
<CustomObject>
    <description>Will be populated with data from Radar</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Rate Sheets</relationshipLabel>
        <relationshipName>Rate_Sheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Rate Sheet</label>
    <nameField>
        <label>Rate Sheet #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Sheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/classes/test_CreateTaskPartialWin.cls
@isTest
private class test_CreateTaskPartialWin {

    static testMethod void test_getOppToCreateTasks() {
        
        Account account = new Account();
        account.Name = 'blah';
        account.NCA__c = '00560000001NgUNAA0'; 
        account.Account_Classification__c = 'National';
        insert account;
        
        Opportunity oppty = new Opportunity();
        oppty.Name = 'Test';
        oppty.AccountId = account.Id;
        oppty.Original_Decision_Maker__c = '0036000001gvtuZAAQ';
        oppty.CloseDate = Date.Today();
        oppty.StageName = 'Solution Hypothesis';
        insert oppty;
        
        PartialWinRateSheet__c pw = new PartialWinRateSheet__c();
        pw.Opportunity__c = oppty.Id;
        pw.Rate_Sheet__c = '123456';
        pw.IsTaskCreated__c = false;
        insert pw;
        
        Test.startTest();
        CreateTaskPartialWin.getOppToCreateTasks();
        Test.stopTest();
    }
    
    static testMethod void test_PartialWinTask(){
        
        Account account = new Account();
        account.Name = 'blah';
        account.NCA__c = '00560000001NgUNAA0'; 
        account.Account_Classification__c = 'National';
        insert account;
        
        Opportunity oppty = new Opportunity();
        oppty.Name = 'Test';
        //oppty.AccountId = account.Id;
        oppty.Original_Decision_Maker__c = '0036000001gvtuZAAQ';
        oppty.CloseDate = Date.Today();
        oppty.StageName = 'Solution Hypothesis';
        insert oppty;
        
        List<ID> lOppIds = new List<ID>();
        lOppIds.add(String.valueOf(oppty.Id));
        
        PartialWinRateSheet__c pw = new PartialWinRateSheet__c();
        pw.Opportunity__c = oppty.Id;
        pw.Rate_Sheet__c = '123456';
        insert pw;
        
        Test.startTest();
        CreateTaskPartialWin.PartialWinTask(lOppIds);
        Test.stopTest();
    }
    

    static testMethod void test_ClosePartialWinTask() {
        
        Opportunity oppty = new Opportunity();
        oppty.Name = 'Test';
        oppty.Original_Decision_Maker__c = '0036000001gvtuZAAQ';
        oppty.CloseDate = Date.Today();
        oppty.StageName = 'Solution Hypothesis';
        insert oppty;
        
        Task T = new Task();
        T.WhatId = oppty.Id;
        T.Type = 'Partial Win';
        insert T;
        
        Test.startTest();
        CreateTaskPartialWin.ClosePartialWinTask(String.valueOf(oppty.Id));
        Test.stopTest();
        
    }
    
}