SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>RSM_CCMs__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to Store RydeSmart&apos;s CCM (Customer Care Manager) owner</description>
        <inlineHelpText>If CCM is changed Manually then check &quot;Do Not Override CCM&quot; field.</inlineHelpText>
        <label>CCM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Global_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Global Settings</label>
</CustomObject>

SFDC Automation/src/objects/RSM_VehicleValidationDetails__c.object
<CustomObject>
    <fields>
        <fullName>Rule_Description__c</fullName>
        <label>Rule Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status_Date__c</fullName>
        <label>Status Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Unit_Number__c</fullName>
        <label>Unit Number</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>RSM VehicleValidationDetails</relationshipLabel>
        <relationshipName>RSM_VehicleValidationDetails</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Validation_Rule_Id__c</fullName>
        <label>Validation Rule Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>RSM VehicleValidationDetails</label>
    <nameField>
        <label>VehicleValidationDetailsId</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RSM VehicleValidationDetails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup on Accounts</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <externalId>true</externalId>
        <label>Unit Number</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/RSM_OrderReportWOContractGT30FR085_Batch.cls
global with sharing class RSM_OrderReportWOContractGT30FR085_Batch implements Database.Batchable<SObject>
{
	/* 
		Query the RSM_VehicleValidationDetails__c object where the Validation Id is: 
		As this Id is always there which is matching the FR087 condition
	*/ 
	public String query = 'Select r.Validation_Rule_Id__c, r.Unit_Number__c, r.Status_Date__c, '
							+'r.Rule_Description__c, r.Name, r.Id, r.Unit_Number__r.Account__c, r.Unit_Number__r.Account__r.OwnerId '
							+'From RSM_VehicleValidationDetails__c r where Validation_Rule_Id__c = \'38\'';
	global Database.QueryLocator start(Database.BatchableContext BC)
	{
		/* 
			Return the Query Data
		*/		
		return Database.getQueryLocator(query);
	}
	
	global void execute(Database.BatchableContext BC, List<RSM_VehicleValidationDetails__c> lVehicleValidate)
	{
		/* 
			Get the Task RydeSmart Record Type Id from Custom Settings
		*/
		String sTaskRecordTypeId = '';
		Global_Settings__c TaskRydeSmartRecordType = Global_Settings__c.getValues('6');
		// if the custom settings is not null then get the value from settings and out in a local variable
		if(TaskRydeSmartRecordType != null && TaskRydeSmartRecordType.IsActive__c)
			sTaskRecordTypeId = TaskRydeSmartRecordType.Value__c;
		Set<String> sVehicleIds = new Set<String>();
		Set<String> sAccIds = new Set<String>();
		Set<String> sVehicleExistIds = new Set<String>();
		/* 
			Iterate the Data and collect the Vehicle Ids
		*/ 
		for(RSM_VehicleValidationDetails__c VehicleValidate : lVehicleValidate)
		{   
			sVehicleIds.add(VehicleValidate.Unit_Number__c);
		}
		/* 
			Query the Existing Task
		*/		
		if(sVehicleIds.size() > 0)
		{
			List<Task> lTaskExist = [Select t.WhatId, t.Subject, t.RecordTypeId 
									From Task t where RecordTypeId =: sTaskRecordTypeId and 
									Subject like '%is Reporting with no Contract for more than 30 Days' and 
									Subject like 'Unit No.%' and WhatId in : sVehicleIds];// Add logic for Account here with: sAccIds
			for(Task TaskO : lTaskExist)
			{
				sVehicleExistIds.add(TaskO.WhatId);
			}
		}
		/* 
			Remove the Vehicle Id where the Task has already been created
		*/		
		sVehicleIds.removeall(sVehicleExistIds);
		if(sVehicleIds.size() > 0)
		{
			List<Vehicle__c> lVehicle = [Select v.Unit__c, v.Id, 
											v.Account__r.RSM_CCMs__c, v.Account__c 
											From Vehicle__c v where 
											Id in : sVehicleIds and 
											Account__r.RSM_CCMs__c != null];
			List<Task> lTask = new List<Task>();
			/* 
				Iterate the Vehicle List and Create the Task
			*/
			for(Vehicle__c Vehicle : lVehicle)
			{    
		    	Task TaskObj = new Task(RecordTypeId = sTaskRecordTypeId, Type = 'Action from RydeSmart');
		    	TaskObj.Subject = 'Unit No. ' + Vehicle.Unit__c + ' is Reporting with no Contract for more than 30 Days';
		    	TaskObj.Description = 'Create Contract for Account';
		    	TaskObj.ActivityDate = System.today().addDays(15);
		    	TaskObj.Type = 'Action from RydeSmart';
		    	TaskObj.WhatId = Vehicle.Id;
		    	TaskObj.OwnerId = Vehicle.Account__r.RSM_CCMs__c;		    	
		    	lTask.add(TaskObj);
		    }
		    if(lTask.size() > 0)
		    	insert lTask;
		}
	}
	global void finish(Database.BatchableContext BC){
	}
}