SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <picklist>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wholesale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Export</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Product_Detail__c</fullName>
        <label>Product Detail</label>
        <picklist>
            <controllingField>Product_Line__c</controllingField>
            <picklistValues>
                <fullName>VOSA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Choice Lease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flex</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fast Track</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plus One</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physical Damage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haz-mat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OPIS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <label>Product Line</label>
        <picklist>
            <picklistValues>
                <fullName>FSL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RPM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rydesmart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DCC Light</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fuel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SAM_Class__c</fullName>
        <formula>Unit_Number__r.SAM_CLASS__c &amp; &apos; &apos; &amp; Unit_Number__r.VEH_CLS_SAM_DS__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SAM Class</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <picklist>
            <picklistValues>
                <fullName>New Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Location</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fleet Add</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Replacement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Term Extension</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rate Change</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

SFDC Automation/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>SAM_Class__c</fullName>
        <label>SAM Class</label>
        <picklist>
            <picklistValues>
                <fullName>10 - Panel Van or Pickup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20 - Parcel Van</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21 - Metro Van/Sprinter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30 - Truck &gt;=8K &lt;= 16K GVW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>31 - Reefer Truck &lt;=16K</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40 - Gas Straight Truck</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50 - Truck &gt;16K &lt;=26K GVW &lt;=20 ft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>51 - Truck (No Body) &gt;16K &lt;=26K GVW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60 - Truck &gt;16K &lt;=26K GVW &gt; 20 ft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>61 - Tank Truck &gt;16K &lt;=26K GVW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70 - Reefer Truck &gt;16K &lt;=26K GVW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80 - Truck &gt;26K GVW &lt;= 20 ft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>81 - Truck (No Body) &gt;26K &lt;=33K GVW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>90 - Truck &gt; 26K GVW &gt; 20 ft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>91 - Tank Truck &gt;26K &lt;=33K GVW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>100 - Stake or Flatbed Truck</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>110 - Reefer Truck &gt; 26K GVW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>120 - T/A Big Bore Truck</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>121 - S/A Big Bore Truck</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>122 - Tank Truck &gt;33K GVW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>130 - S/A Tractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>131 - S/A Yard Tractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>132 - S/A Pick-up &amp; Delivery Tractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>140 - T/A Tractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>141 - T/A Yard Tractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>150 - S/A Sleeper Tractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>160 - T/A COE Sleeper Tractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>170 - T/A Conv Sleeper Tractor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>180 - Dry Trailer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>181 - Tanker Trailer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>VHC_TYPE__c</fullName>
        <label>Vehicle Type</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Used</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Takeover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refrigerated Truck</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi-Cab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Truck</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

SFDC Automation/src/classes/test_EditProductRelayController.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class test_EditProductRelayController {

     static testMethod void myUnitTest() {
        Account a = TestUtil.createAccount('Ryder FMS Parent Account', 'FMS');
        a.billingstate = 'IL';
        a.BillingPostalCode = '12347';
        a.BillingCountry = 'US';
        insert a;
        
        Contact c = New Contact (FirstName = 'TestFirst', LastName = 'TestLast', email = 'TestContact@test.com', accountId = a.Id);
    	insert c;
    	
        List<Opportunity> opptyList = new List<Opportunity>();
        Opportunity o = TestUtil.createOppty(a, c, 'Standard Opportunity');
        insert o;
        
        List<OpportunityContactRole> allContactRoles = [Select opp.ContactId, opp.Id, opp.IsPrimary, opp.OpportunityId, opp.Role from OpportunityContactRole opp where OpportunityId =: o.Id];
    
	    for (OpportunityContactRole ocr :allContactRoles)
	    {
	    	System.AssertEquals(ocr.ContactId, c.id);
	    	System.AssertEquals(ocr.Role, 'Decision Maker');
	    	System.AssertEquals(ocr.IsPrimary, true);
	    }
	    
        PriceBook2  stdPriceBook = [Select p.Name, p.Id From Pricebook2 p where p.Name = 'Standard Price Book' and p.IsActive = true LIMIT 1];
        
        // Select p.VHC_TYPE__c, p.SAM_Class__c, p.ProductCode, p.Name, p.Family From Product2 p
        Product2 tempProduct = new Product2();
        tempProduct.ProductCode = 'Test Product2';
        tempProduct.Name = 'Test Product2';
        tempProduct.Family = 'Test Family';
        tempProduct.VHC_TYPE__c = 'New';
        tempProduct.SAM_Class__c = '10 - Panel Van or Pickup';
        insert tempProduct;
        
        //Select p.Product2Id, p.Pricebook2Id, p.Name, p.Id From PricebookEntry p
        PricebookEntry pbe = new PricebookEntry();
        pbe.Pricebook2Id = stdPriceBook.Id;
        pbe.Product2Id = tempProduct.Id;
        pbe.UnitPrice = 1.00;
        pbe.IsActive = true;
        pbe.CurrencyIsoCode = 'USD';
        pbe.UseStandardPrice = false;
        insert pbe;
        
        //Select o.Transaction_Type__c, o.Quantity, o.Product_Line__c, o.Product_Detail__c, o.PricebookEntryId, o.OpportunityId, o.Id From OpportunityLineItem o
        OpportunityLineItem oli = new OpportunityLineItem();
        oli.quantity = 1;
        oli.PricebookEntryId = pbe.Id;
        oli.OpportunityId = o.Id;
        oli.Product_Line__c = 'Insurance';
        oli.Product_Detail__c = 'GAP';
        oli.Transaction_Type__c = 'Replacement';
        oli.TotalPrice = 129.00;
        insert oli;
        
        // Start the test
        Test.startTest();
                    
        // Set the Page Reference
        PageReference productRelayPage = Page.EditProductRelay;
        Test.setCurrentPage(productRelayPage);
                    
        // Set the model action
        ApexPages.currentPage().getParameters().put('id', oli.Id);

        // Create a standard controller 
        ApexPages.Standardcontroller stdcontroller = new ApexPages.Standardcontroller(oli); 
        
        //create instance of pages controller
        EditProductRelayController controller = new EditProductRelayController(stdcontroller);
        PageReference ref1 = controller.init();
        PageReference ref2 = controller.backToOpportunity();
        Test.stopTest();

    }
    
    static testMethod void myUnitTest2() {
        Account a = TestUtil.createAccount('Ryder FMS Parent Account', 'FMS');
        a.billingstate = 'IL';
        a.BillingPostalCode = '12347';
        a.BillingCountry = 'US';
        insert a;
        
        Contact c = New Contact (FirstName = 'TestFirst', LastName = 'TestLast', email = 'TestContact@test.com', accountId = a.Id);
    	insert c;
    	
        List<Opportunity> opptyList = new List<Opportunity>();
        Opportunity o = TestUtil.createOppty(a, c, 'Standard Opportunity');
        insert o;
        
        List<OpportunityContactRole> allContactRoles = [Select opp.ContactId, opp.Id, opp.IsPrimary, opp.OpportunityId, opp.Role from OpportunityContactRole opp where OpportunityId =: o.Id];
    
	    for (OpportunityContactRole ocr :allContactRoles)
	    {
	    	System.AssertEquals(ocr.ContactId, c.id);
	    	System.AssertEquals(ocr.Role, 'Decision Maker');
	    	System.AssertEquals(ocr.IsPrimary, true);
	    }
	    
        PriceBook2  stdPriceBook = [Select p.Name, p.Id From Pricebook2 p where p.Name = 'Standard Price Book' and p.IsActive = true LIMIT 1];
        
        // Select p.VHC_TYPE__c, p.SAM_Class__c, p.ProductCode, p.Name, p.Family From Product2 p
        Product2 tempProduct = new Product2();
        tempProduct.ProductCode = 'Test Product2';
        tempProduct.Name = 'Test Product2';
        tempProduct.Family = 'Test Family';
        tempProduct.VHC_TYPE__c = 'New';
        tempProduct.SAM_Class__c = '10 - Panel Van or Pickup';
        insert tempProduct;
        
        //Select p.Product2Id, p.Pricebook2Id, p.Name, p.Id From PricebookEntry p
        PricebookEntry pbe = new PricebookEntry();
        pbe.Pricebook2Id = stdPriceBook.Id;
        pbe.Product2Id = tempProduct.Id;
        pbe.UnitPrice = 1.00;
        pbe.IsActive = true;
        pbe.CurrencyIsoCode = 'USD';
        pbe.UseStandardPrice = false;
        insert pbe;
        
        //Select o.Transaction_Type__c, o.Quantity, o.Product_Line__c, o.Product_Detail__c, o.PricebookEntryId, o.OpportunityId, o.Id From OpportunityLineItem o
        OpportunityLineItem oli = new OpportunityLineItem();
        oli.quantity = 1;
        oli.PricebookEntryId = pbe.Id;
        oli.OpportunityId = o.Id;
        oli.Product_Line__c = 'Insurance';
        oli.Product_Detail__c = 'GAP';
        oli.Transaction_Type__c = 'Replacement';
        oli.TotalPrice = 129.00;
        insert oli;
        // Start the test
        Test.startTest();
                    
        // Set the Page Reference
        PageReference productRelayPage = Page.EditProductRelay;
        Test.setCurrentPage(productRelayPage);
        
        // Create a standard controller 
        ApexPages.Standardcontroller stdcontroller = new ApexPages.Standardcontroller(oli);
                            
        // Set the model action
        ApexPages.currentPage().getParameters().put('id', o.Id);
        ApexPages.currentPage().getParameters().put('multiItemEdit', '1');

        //create instance of pages controller
        EditProductRelayController controller = new EditProductRelayController(stdcontroller);
        PageReference ref1 = controller.init();
        PageReference ref2 = controller.backToOpportunity();
        Test.stopTest();

    }
}