SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LesseeNo__c</fullName>
        <description>Realtime update of both SFDC and RADAR whenever this value is changed in either system</description>
        <label>Lessee Number</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RSM_AC_Classification__c</fullName>
        <description>RydeSmart Account Classification</description>
        <inlineHelpText>If RS Account Classification is changed manually then Check &quot;Do Not Override AC&quot; field.</inlineHelpText>
        <label>RydeSmart Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Key Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Key Account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RSM_PLC_FLag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>RSM PLC FLag</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/RSM_Contract__c.object
<CustomObject>
    <description>Object to store RydeSmart Contract details</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to store the ID of the Account with which the Contract is related. This field will be populated from database based on the Lessee No in the contract</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>RSM Contracts</relationshipLabel>
        <relationshipName>RSM_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CreatedDate__c</fullName>
        <description>To store the Created Date of the Contract in the Telemetry</description>
        <label>CreatedDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lessee__c</fullName>
        <label>Lessee</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status_Name__c</fullName>
        <label>Status Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>RSM Contract</label>
    <nameField>
        <label>RSM Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RSM Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC Automation/src/objects/RSM_Pre_Launch_Checklist__c.object
<CustomObject>
    <description>This object stores the values for the pre launch checklist.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>RSM Pre Launch Checklists</relationshipLabel>
        <relationshipName>RSM_Pre_Launch_Checklists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Start Date of the checklist</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>RSM Pre Launch Checklist</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>RSM Pre Launch Checklist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RSM Pre Launch Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC Automation/src/classes/RSMCreatePreLaunchCheckList.cls
//Batch Class to create 11 records in Pre-Launch checklist object and to populate start and End dates. 
global class RSMCreatePreLaunchCheckList implements Database.Batchable<SObject>{

  public String query;
  global Database.QueryLocator start(Database.BatchableContext BC){
      return Database.getQueryLocator(query);
   }

   global void execute(Database.BatchableContext BC, List<Account> scope){
       Set<String> LesseeSet=new Set<String>();
       for(Account acc :scope)
       {
            System.debug('Nitin---acc->'+acc);
            LesseeSet.add(acc.LesseeNo__c);       
       }
       
       Map<String,List<RSM_Contract__c>> rsmCoMap = new Map<String,List<RSM_Contract__c>>();
       List<RSM_Contract__c> rsCoList=[select Id,Lessee__c,CreatedDate__c from RSM_Contract__c where Lessee__c in:LesseeSet and Status_Name__c = 'Approved' order by Lessee__c]; 
       for(RSM_Contract__c rc: rsCoList){
           if(rsmCoMap!=null && rsmCoMap.get(rc.Lessee__c)==null){
               rsmCoMap.put(rc.Lessee__c,new List<RSM_Contract__c>{rc});    
           }else{
               rsmCoMap.get(rc.Lessee__c).add(rc);
           }
       }
       Set<String> LesseeNo =new Set<String>();
       for(String str: rsmCoMap.keyset()){
           if(rsmCoMap.get(str).size() > 0)
           {
               LesseeNo.add(str);
           }        
       }
       System.debug('Nitin---LesseeNo->'+LesseeNo);
    /*   System.debug('Nitin---Account->'+[select Id,LesseeNo__c,RSM_AC_Classification__c from Account]);*/
       List<RSM_Pre_Launch_Checklist__c> preCheckList=new List<RSM_Pre_Launch_Checklist__c>();
       List<Account> listAccounts = [select Id,LesseeNo__c from Account where LesseeNo__c in :LesseeNo and RSM_AC_Classification__c='Key Account'];
       System.debug('Nitin---listAccounts->'+listAccounts);
       for(Account acc: listAccounts){
        acc.RSM_PLC_Flag__c = true;
           for(integer i=0;i<12;i++){
               RSM_Pre_Launch_Checklist__c plc=new RSM_Pre_Launch_Checklist__c();
               plc.Account__c =acc.Id;
               if(i==0){
                   plc.Description__c='Contact Ryder Service Managers for installation prep / Create Install Schedule'; 
                   plc.Start_Date__c= rsmCoMap.get(acc.LesseeNo__c)[0].CreatedDate__c.date();
                   plc.End_Date__c=rsmCoMap.get(acc.LesseeNo__c)[0].CreatedDate__c.date().addDays(5);
               }else if(i==1){
                   plc.Description__c='Finalize custom configurations'; 
                   plc.Start_Date__c=rsmCoMap.get(acc.LesseeNo__c)[0].CreatedDate__c.date().addDays(10);
                   plc.End_Date__c=rsmCoMap.get(acc.LesseeNo__c)[0].CreatedDate__c.date().addDays(15);
               }else if(i==2){
                   plc.Description__c='Schedule initial training'; 
                   plc.Start_Date__c=rsmCoMap.get(acc.LesseeNo__c)[0].CreatedDate__c.date().addDays(15);
                   plc.End_Date__c=rsmCoMap.get(acc.LesseeNo__c)[0].CreatedDate__c.date().addDays(15);
               }else if(i==3){
                   plc.Description__c='Installations  begin – Should be automated'; 
                   plc.Start_Date__c=rsmCoMap.get(acc.LesseeNo__c)[0].CreatedDate__c.date().addDays(30);
                   plc.End_Date__c=rsmCoMap.get(acc.LesseeNo__c)[0].CreatedDate__c.date().addDays(30);
               }else if(i==4){
                   plc.Description__c='Create Master Admin Login for Customer "Super User"'; 
                   plc.Start_Date__c=rsmCoMap.get(acc.LesseeNo__c)[0].CreatedDate__c.date().addDays(30);
                   plc.End_Date__c=rsmCoMap.get(acc.LesseeNo__c)[0].CreatedDate__c.date().addDays(45);
               }else if(i==5){
                   plc.Description__c='Assist Customer in Creating Driver IDs per best Practice'; 
                   plc.Start_Date__c=rsmCoMap.get(acc.LesseeNo__c)[0].CreatedDate__c.date().addDays(30);
                   plc.End_Date__c=rsmCoMap.get(acc.LesseeNo__c)[0].CreatedDate__c.date().addDays(45);
               }else if(i==6){
                   plc.Description__c='Finish installations – Should be automated'; 
                   plc.Start_Date__c=rsmCoMap.get(acc.LesseeNo__c)[0].CreatedDate__c.date().addDays(45);
                   plc.End_Date__c=rsmCoMap.get(acc.LesseeNo__c)[0].CreatedDate__c.date().addDays(45);
               }else if(i==7){
                   plc.Description__c='Schedule weekly status meeting'; 
                   plc.Start_Date__c=rsmCoMap.get(acc.LesseeNo__c)[0].CreatedDate__c.date().addDays(52);
                   plc.End_Date__c=rsmCoMap.get(acc.LesseeNo__c)[0].CreatedDate__c.date().addDays(52);
               }else if(i==8){
                   plc.Description__c='Complete training'; 
                   plc.Start_Date__c=rsmCoMap.get(acc.LesseeNo__c)[0].CreatedDate__c.date().addDays(52);
                   plc.End_Date__c=rsmCoMap.get(acc.LesseeNo__c)[0].CreatedDate__c.date().addDays(52);
               }else if(i==9){
                   plc.Description__c='Move to Paperless Only Driver Logs or conduct supplemental driver training'; 
                   plc.Start_Date__c=rsmCoMap.get(acc.LesseeNo__c)[0].CreatedDate__c.date().addDays(66);
                   plc.End_Date__c=rsmCoMap.get(acc.LesseeNo__c)[0].CreatedDate__c.date().addDays(66);
               }else if(i==10){
                   plc.Description__c='Move to paperless Trip Records'; 
                   plc.Start_Date__c=rsmCoMap.get(acc.LesseeNo__c)[0].CreatedDate__c.date().addDays(66);
                   plc.End_Date__c=rsmCoMap.get(acc.LesseeNo__c)[0].CreatedDate__c.date().addDays(90);
               }else if(i==11){
                   plc.Description__c='Transition Account to steady state Operations'; 
                   plc.Start_Date__c=rsmCoMap.get(acc.LesseeNo__c)[0].CreatedDate__c.date().addDays(90);
                   plc.End_Date__c=rsmCoMap.get(acc.LesseeNo__c)[0].CreatedDate__c.date().addDays(90);
               }
               preCheckList.add(plc);
           }                
       }
       insert preCheckList;
       update listAccounts;
   }

   global void finish(Database.BatchableContext BC){
   }
}