SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Additional_Comments__c</fullName>
        <inlineHelpText>Place additional comments for service handling</inlineHelpText>
        <label>Additional Comments</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SAM_Account_Source__c</fullName>
        <label>SAM Account Source</label>
        <picklist>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yellow Pages</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Truck Paper</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Truck Trader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Truck Buyers Guide</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Blast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exp. With Ryder/Prev. customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Word of mouth/Business assoc</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Salesforce called/visited</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ryder Website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internet – Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Walk in/Drive By</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Mail</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SAM_Cust_ID__c</fullName>
        <description>Migrated data from SAM</description>
        <label>SAM_Cust_ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <picklist>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wholesale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Export</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Vendor account record type for legal requests</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Additional_Comments__c</fullName>
        <description>field to capture comments at the item of customer needs selection.</description>
        <inlineHelpText>field to capture comments at the item of customer needs selection.</inlineHelpText>
        <label>Additional Comments</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Customer_Branch__c.object
<CustomObject>
    <description>Customer Branches at Ryder</description>
    <fields>
        <fullName>Additional_Comments__c</fullName>
        <inlineHelpText>Place additional comments for service handling

SMO Field: Text in this field and Other Misc. Billing Information field make up the Comments field in SMO</inlineHelpText>
        <label>Additional Comments</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ryder_Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field for Customer Branch to Ryder branch</description>
        <label>Ryder Branch</label>
        <referenceTo>Ryder_Branch__c</referenceTo>
        <relationshipLabel>Customer / Branch</relationshipLabel>
        <relationshipName>Customer_Branches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ryder_HQ_Account__c</fullName>
        <description>M/D field between Customer Branch and HQ Accounts</description>
        <label>Ryder HQ Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer / Branch</relationshipLabel>
        <relationshipName>Customer_Branches</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Customer / Branch</label>
    <nameField>
        <label>Customer Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer / Branch</pluralLabel>
    <recordTypes>
        <fullName>UVS</fullName>
        <active>true</active>
        <description>Identity</description>
        <label>UVS</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Customer_Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer / Branch</label>
        <referenceTo>Customer_Branch__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Detail__c</fullName>
        <label>Product Detail</label>
        <picklist>
            <controllingField>Product_Line__c</controllingField>
            <picklistValues>
                <fullName>VOSA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Choice Lease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flex</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fast Track</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plus One</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physical Damage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haz-mat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OPIS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <label>Product Line</label>
        <picklist>
            <picklistValues>
                <fullName>FSL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RPM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rydesmart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DCC Light</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fuel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Ryder_Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ryder Branch</label>
        <referenceTo>Ryder_Branch__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <picklist>
            <picklistValues>
                <fullName>New Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Location</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fleet Add</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Replacement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Term Extension</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rate Change</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Unit_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Number</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

SFDC Automation/src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>UTC__c</fullName>
        <formula>$User.UTC__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UTC</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>UVS</fullName>
        <active>true</active>
        <description>Used vehicle Sales</description>
        <label>UVS</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Ryder_Branch__c.object
<CustomObject>
    <description>Branches at Ryder</description>
    <fields>
        <fullName>Branch_Code__c</fullName>
        <description>external ID</description>
        <externalId>true</externalId>
        <label>Branch Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Ryder Branch</label>
    <nameField>
        <label>Ryder Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ryder Branches</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/objects/RyderConfig__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Provides configuration information for Ryder</description>
    <label>Ryder Config</label>
</CustomObject>

SFDC Automation/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>UTC__c</fullName>
        <description>This field will capture the location code for the user.</description>
        <label>UTC</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/objects/UVS_SAM_Sales_Source__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>SAM Sales Source</description>
    <label>UVS SAM Sales Source</label>
</CustomObject>

SFDC Automation/src/objects/UVS_SAM_Sales_Type__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Sales Types in SAM</description>
    <label>UVS SAM Sales Type</label>
</CustomObject>

SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <fields>
        <fullName>Ask_Price__c</fullName>
        <label>Ask Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Branch_Code__c</fullName>
        <label>Branch Code</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CUSTOMER_BRANCH__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field for Customer Branch</description>
        <label>Customer Branch</label>
        <referenceTo>Customer_Branch__c</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PRODUCT_LINE__c</fullName>
        <description>Product Line</description>
        <label>Product Line</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Detail__c</fullName>
        <description>Product Detail as indicated in the contract package</description>
        <label>Product Detail</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <description>This field will hold the transaction type of the vehicle. Eg: Lease Extension</description>
        <label>Transaction Type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <recordTypes>
        <fullName>UVS</fullName>
        <active>true</active>
        <description>Record Type for UVS Vehicles</description>
        <label>UVS</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/SyncOpWithSAMControllerTest.cls
/**=============================================================================
 * Created By: Gaurav Gupta (Appirio, Inc)
 * Created Date: [15/10/2014]
 * Description: Test class for SyncOpWithSAMController

==============================================================================*/
@isTest
private class SyncOpWithSAMControllerTest {

    static testMethod void myUnitTest() {
        Ryder_Branch__c rb = TestUtilUvs.createRyderBranch();
        User sysAdmin = TestUtilUvs.createAdminUser(false);
        sysAdmin.UTC__c = rb.Branch_Code__c;
        insert sysAdmin; 

        System.runAs ( sysAdmin ) {
            RyderConfig__c rydConf = new RyderConfig__c();
            rydConf = TestUtilUVS.createRyderConfig(true);

            UVS_SAM_Sales_Type__c stCs = new UVS_SAM_Sales_Type__c();
            stCs.name = 'Retail';
            insert stCs;

            UVS_SAM_Sales_Source__c ssCs = new UVS_SAM_Sales_Source__c();
            ssCs.name = 'Advertisement';
            insert ssCs;

            Account acc =TestUtilUVS.createAccount('Vendor','FMS',false);
            acc.Transaction_Type__c = 'Retail';
            acc.SAM_Account_Source__c = 'Other';
            acc.Accountsource = 'Advertisement';
            acc.SAM_Cust_ID__c = 'abc';
            acc.Phone = '12345678900';
            insert acc;
            test.startTest();
            /*
            Ryder_Branch__c rb = new Ryder_Branch__c();
            rb.Branch_Code__c = '123';
            insert rb;
            */
            Customer_Branch__c cstB = new Customer_Branch__c();
            cstB.Ryder_branch__c = rb.id;
            cstB.Ryder_HQ_Account__c = acc.id;
            insert cstB;
                Vehicle__c v = new Vehicle__c(Name='1');
                v.CUSTOMER_BRANCH__c = cstB.id;
                v.Ask_Price__c = 20000.0;
                insert v;
                Opportunity opp = TestUtilUVS.createOpportunity('UVS Opportunity',acc , True, null);

                OpportunityLineItem oppLI1 = new OpportunityLineItem();
                Product2 prod = new Product2();
                prod.Name = 'Standard Price Book UVS';
                prod.CurrencyIsoCode = 'CAD';
                insert prod;

                PriceBookEntry pbe = [SELECT Id
                                  FROM PriceBookEntry
                                  WHERE Product2Id = :prod.Id
                                  LIMIT 1];
                pbe.isActive = true;
                update pbe;


            oppLI1.PricebookEntryId = pbe.Id;
            oppLI1.OpportunityId = opp.id;
            oppLI1.Unit_Number__c = v.id;
            oppLI1.Quantity = 1;
            oppLI1.UnitPrice = 123;
            oppLI1.Transaction_Type__c = 'Term Extension';
            oppLI1.Product_Line__c = 'Insurance';
            oppLI1.Product_Detail__c = 'Physical Damage';
            insert oppLI1;
            //
            list<Vehicle__c> vehilist = [Select id from Vehicle__c where Name < '10'];

            Contact newCon = TestUtilUVS.createContact(acc.Id,false);
            newCon.Additional_Comments__c = 'Test1';
            newCon.Email = 'test1@rydertest.com';
            newCon.OwnerId = UserInfo.getUserId();
            newCon.fax = '1234567890';
            insert newCon;
            test.stopTest();


            Quote q = TestUtilUVS.createQuote('UVS', false);
            q.contactId = newCon.id;
            q.OpportunityId = opp.id;
            //q.AccountId = acc.Id;
            insert q;
            ApexPages.StandardController sc = new ApexPages.standardController(q);

            SyncOpWithSAMController syncOpWithController = new SyncOpWithSAMController(sc);

            syncOpWithController.selectAccount();
            syncOpWithController.isForceInsert = True;
            syncOpWithController.callWS();
            system.assertequals(syncOpWithController.getHasPageMessage() , true);
            system.assertequals(syncOpWithController.isError , True);
            system.assertequals(syncOpWithController.quote.Opportunity.AccountId , acc.id);

        }
    }
}