SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Classification__c</fullName>
        <label>Account Classification</label>
        <picklist>
            <picklistValues>
                <fullName>National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coordinated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Coordinated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National - Cash Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local - Cash Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Cash and Non-Cash</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Central_Decisionmaking__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Select this if the sales decisions are made at the National / Parent Account level.</inlineHelpText>
        <label>Central Decisionmaking</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LesseeNo__c</fullName>
        <description>Realtime update of both SFDC and RADAR whenever this value is changed in either system</description>
        <label>Lessee Number</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Account_Classification__c</fullName>
        <formula>TEXT(Account.Account_Classification__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Classification</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <label>Contact Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer / Branch</label>
        <referenceTo>Customer_Branch__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ryder_Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ryder Branch</label>
        <referenceTo>Ryder_Branch__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle #</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Cases (Vehicle)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Source__c</fullName>
        <description>This field tells if the contact is created by lead convesion process or manually by clicking new contact button.</description>
        <label>Contact Source</label>
        <picklist>
            <picklistValues>
                <fullName>Lead Conversion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manual</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Maintenance_Contact_Type__c</fullName>
        <label>Maintenance Contact - All Branches</label>
        <picklist>
            <picklistValues>
                <fullName>Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tertiary</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Primary</fullName>
        <active>true</active>
        <label>Primary</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Customer_Branch__c.object
<CustomObject>
    <description>Customer Branches at Ryder</description>
    <fields>
        <fullName>Ryder_Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field for Customer Branch to Ryder branch</description>
        <label>Ryder Branch</label>
        <referenceTo>Ryder_Branch__c</referenceTo>
        <relationshipLabel>Customer / Branch</relationshipLabel>
        <relationshipName>Customer_Branches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ryder_HQ_Account__c</fullName>
        <description>M/D field between Customer Branch and HQ Accounts</description>
        <label>Ryder HQ Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer / Branch</relationshipLabel>
        <relationshipName>Customer_Branches</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Customer / Branch</label>
    <nameField>
        <label>Customer Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer / Branch</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Postal_Code__c.object
<CustomObject>
    <description>Holds the mapping between zip code and timezone. Source data is PostalCodes table in AMDATA.</description>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DOS__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DOS</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Postal_Codes_DOS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <externalId>true</externalId>
        <label>Postal Code</label>
        <length>7</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>State_Name__c</fullName>
        <label>State Name</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UVS_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UVS Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Postal_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Postal Code</label>
    <nameField>
        <label>Postal Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Postal Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Ryder_Branch__c.object
<CustomObject>
    <description>Branches at Ryder</description>
    <fields>
        <fullName>Branch_Code__c</fullName>
        <description>external ID</description>
        <externalId>true</externalId>
        <label>Branch Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Name__c</fullName>
        <label>State Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <label>Ryder Branch</label>
    <nameField>
        <label>Ryder Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ryder Branches</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/objects/UVS_SheduleA_Request__c.object
<CustomObject>
    <description>UVS SheduleA</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>ScheduleA_Request_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Buy_Out_Approved__c</fullName>
        <label>Buy-Out Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Request</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent to Lease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent to Pricing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Account_Name__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>ScheduleA Request</relationshipLabel>
        <relationshipName>ScheduleA_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <label>Request Type</label>
        <picklist>
            <picklistValues>
                <fullName>ScheduleA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>End of Lease</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SalesTax_Exempt__c</fullName>
        <label>SalesTax Exempt</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User_Pricing_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pricing User  Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ScheduleA_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ScheduleA Request</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>SheduleA Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ScheduleA Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC Automation/src/objects/UVS_Vehicle_Information__c.object
<CustomObject>
    <description>UVS Buy-Out Calculation</description>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <formula>Vehicle_Number__r.CUSTOMER_BRANCH__r.Ryder_Branch__r.Zip_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Postal Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle Number</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Vehicles Information</relationshipLabel>
        <relationshipName>Vehicles_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vehicle Information</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Vehicle Information</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup on Accounts</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Branch_Code__c</fullName>
        <label>Branch Code</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CUSTOMER_BRANCH__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field for Customer Branch</description>
        <label>Customer Branch</label>
        <referenceTo>Customer_Branch__c</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RSM__c</fullName>
        <description>Displays RydeSmart contract status</description>
        <label>RS Contract Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Printed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to SSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by SSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deleted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/VehicleInformationManagement_Helper_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class VehicleInformationManagement_Helper_Test {

    static testMethod void UnitTest_SheduleA_InsertUpdate()
    {
        // TO DO: implement unit test
        Test.startTest();
        
        RSMCreateTestData.GetCustomSettingsRecord();
        
        Account Acc1 = new Account();
        Acc1.name = 'Test';
        Acc1.account_classification__c = 'Key Account';
        Acc1.central_decisionmaking__c = False;
        Acc1.type = 'Customer';
        Acc1.Account_Classification__c = 'National';
        Acc1.LesseeNo__c = '0123123';
        insert Acc1;
        
        Ryder_Branch__c rb = new Ryder_Branch__c();
		rb.Branch_Code__c = '33178';
		rb.name = 'Test';
		insert rb;
			
        Customer_Branch__c CustomerBranch = new Customer_Branch__c();
        CustomerBranch.Ryder_Branch__c = rb.id;
        CustomerBranch.Name = 'Test Customer Branch';
        CustomerBranch.Ryder_HQ_Account__c = Acc1.Id;
        insert CustomerBranch;
    
        Contact Cont1 = new Contact();
        Cont1.AccountId = Acc1.Id;
        Cont1.FirstName = 'Test Contact';
        Cont1.LastName = 'Sample';
        Cont1.Email = 'test8979123@rydertest.com';
        Cont1.Maintenance_Contact_Type__c = 'Primary';
        Cont1.Phone = '(123) 456-8789';
        Cont1.Contact_Source__c = 'Lead Conversion';
        insert Cont1;
    
		// Executing the ScheduleARequestManagement trigger on ScheduleA Request Object
		UVS_SheduleA_Request__c SheduleARequest = new UVS_SheduleA_Request__c(Account_Name__c = Acc1.Id, 
																			Request_Type__c = 'ScheduleA', 
																			Buy_Out_Approved__c = 'New Request', 
																			SalesTax_Exempt__c = 'No', 
																			Contact_Name__c = Cont1.Id);
		insert SheduleARequest;
		
		// Execution of After Insert trigger on SheduleA Request Object where it set the Default User Price Name
		SheduleARequest = [select Request_Type__c, User_Pricing_Name__c, Id from UVS_SheduleA_Request__c where Id = : SheduleARequest.Id];
		System.assertEquals(LABEL.UVS_SA_Pricing_User, SheduleARequest.User_Pricing_Name__c);
		
		// Execute after Udpate and set the Default User Price Name as there is no Vehicle Information record as of now 
		SheduleARequest.Request_Type__c = 'End of Lease';
		update SheduleARequest;
		
		// Execute after Udpate and set the Default User Price Name as Request Type is ScheduleA
		SheduleARequest.Request_Type__c = 'ScheduleA';
		update SheduleARequest;
		
		Test.stopTest();
    }
    static testMethod void UnitTest_SheduleA_Update()
    {
        // TO DO: implement unit test
        Test.startTest();
        
        RSMCreateTestData.GetCustomSettingsRecord();
        
        Account Acc1 = new Account();
        Acc1.name = 'Test';
        Acc1.account_classification__c = 'Key Account';
        Acc1.central_decisionmaking__c = False;
        Acc1.type = 'Customer';
        Acc1.Account_Classification__c = 'National';
        Acc1.LesseeNo__c = '0123123';
        insert Acc1;
        
        Ryder_Branch__c rb = new Ryder_Branch__c();
		rb.Branch_Code__c = 'Test';
		rb.name = 'Test';
		rb.Zip_Code__c = '33178';
		insert rb;
			
        Customer_Branch__c CustomerBranch = new Customer_Branch__c();
        CustomerBranch.Ryder_Branch__c = rb.id;
        CustomerBranch.Name = 'Test Customer Branch';
        CustomerBranch.Ryder_HQ_Account__c = Acc1.Id;
        insert CustomerBranch;
    
        Contact Cont1 = new Contact();
        Cont1.AccountId = Acc1.Id;
        Cont1.FirstName = 'Test Contact';
        Cont1.LastName = 'Sample';
        Cont1.Email = 'test8979123@rydertest.com';
        Cont1.Maintenance_Contact_Type__c = 'Primary';
        Cont1.Phone = '(123) 456-8789';
        Cont1.Contact_Source__c = 'Lead Conversion';
        insert Cont1;
    
        Vehicle__c Vehicle = new Vehicle__c();
        Vehicle.Name = '1234';
        Vehicle.CUSTOMER_BRANCH__c = CustomerBranch.Id;
        Vehicle.RSM__c = 'Approved';
        Vehicle.Account__c = Acc1.Id;
        insert Vehicle;
        
        User uvsUser = TestUtilUVS.createUser(true);        
		Postal_Code__c Postal_Code = new Postal_Code__c(Name = '33178', Postal_Code__c = '33178', DOS__c = uvsUser.Id, 
                            							City__c = 'Medlay', State__c = 'FL', 
                            							State_Name__c = 'Florida', Country__c = 'US', 
                            							UVS_Assignee__c = uvsUser.Id);
		
      	insert Postal_Code;
		
		// Executing the ScheduleARequestManagement trigger on ScheduleA Request Object
		UVS_SheduleA_Request__c SheduleARequest = new UVS_SheduleA_Request__c(Account_Name__c = Acc1.Id, 
																			Request_Type__c = 'ScheduleA', 
																			Buy_Out_Approved__c = 'New Request', 
																			SalesTax_Exempt__c = 'No', 
																			Contact_Name__c = Cont1.Id);
		insert SheduleARequest;
		
		// Execution of After Insert trigger on SheduleA Request Object where it set the Default User Price Name
		// User_Pricing_Name must be the same as Custom Label User
		SheduleARequest = [select User_Pricing_Name__c, Id from UVS_SheduleA_Request__c where Id = : SheduleARequest.Id];
		System.assertEquals(LABEL.UVS_SA_Pricing_User, SheduleARequest.User_Pricing_Name__c);
		
		// Executing the VehicleInformationManagement trigger on Vehicle Information Object and 
		// validating the use case where where Request_Type__c = 'ScheduleA' and  aVehicle Information record is added
		//SheduleARequest.User_Pricing_Name__c = null;
		SheduleARequest.Request_Type__c = 'End of Lease';
		update SheduleARequest;
		
		// Execution of After Insert trigger on Vehicle Information Object where
        // it set the User Price Name based on Vehicle Information Postal Code field
		UVS_Vehicle_Information__c VehicleInformation = new UVS_Vehicle_Information__c
															(Vehicle_Number__c = Vehicle.id, 
															Anniversary_Date__c = system.today().addDays(50), 
															Buy_Out_Date__c = system.today().addDays(50), 
															ScheduleA_Original_Value__c = 50, 
															ScheduleA_Monthly_Depreciation__c = 1000, 
															ScheduleA_Monthly_Fixed_Rate__c = 800, 
															Comments__c = 'Test', Lease_Term__c = '12', 
															Book_Value__c = 1000, Pre_Paid_Interest__c = 100, 
															Sales_Tax__c = 10, ScheduleA_Request__c = SheduleARequest.Id);
        insert VehicleInformation;
        SheduleARequest = [select User_Pricing_Name__c, Id from UVS_SheduleA_Request__c where Id = : SheduleARequest.Id];
		// User_Pricing_Name must be the same as in postal Code record
		System.assertEquals(uvsUser.Id, SheduleARequest.User_Pricing_Name__c);
		
        Test.stopTest();
    }
}