SFDC Automation/src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Vendor account record type for legal requests</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Pricebook2.object
<CustomObject>
    <recordTypes>
        <fullName>UVS</fullName>
        <active>true</active>
        <description>Used by Used Vehicle Sales Group</description>
        <label>UVS</label>
    </recordTypes>
    <sharingModel>ReadSelect</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Quote.object
<CustomObject>
    <recordTypes>
        <fullName>UVS</fullName>
        <active>true</active>
        <description>Used vehicle Sales</description>
        <label>UVS</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Approval_Level__c</fullName>
        <description>0 (No approval required), 1 (FAM), 2 (DAM) and 3 (VP AM )</description>
        <label>Approval Level</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Interest_Rate__c</fullName>
        <label>Interest Rate</label>
        <picklist>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5.5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Take_Price2__c</fullName>
        <label>Take Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <label>Term</label>
        <picklist>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>36</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>42</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>48</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>54</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/RyderConfig__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Provides configuration information for Ryder</description>
    <label>Ryder Config</label>
</CustomObject>

SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <recordTypes>
        <fullName>UVS</fullName>
        <active>true</active>
        <description>Record Type for UVS Vehicles</description>
        <label>UVS</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/QuoteExtensions_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class QuoteExtensions_Test {

    static testMethod void myUnitTest() {
    	
		   User sysAdmin = TestUtilUVS.createAdminUser(true);
		    System.runAs(sysAdmin){
		    
		      RyderConfig__c rdc = TestUtilUVS.createRyderConfig(true);
		      
		      Product2 prod = new Product2();
		      prod.Name = 'Standard Price Book UVS';
		      prod.CurrencyIsoCode = 'CAD';
		      insert prod;
		      
		      Pricebook2 pb = new pricebook2(name='test');
		      insert pb;
		
		      PricebookEntry pbe = new PricebookEntry(pricebook2id=pb.id, product2id=prod.id,unitprice=1.0, isActive=true);
		      insert pbe;
		      
		      Account acc = TestUtilUVS.createAccount('Vendor', 'FMS', true);
		      Vehicle__c veh = TestUtilUVS.createUVSVehicle(acc, true);
		      
		      Quote q1 = TestUtilUVS.createQuote('UVS',true);
		      q1.pricebook2id=pb.id;
		      q1.status = 'Needs Review';
		      update q1;
		      
		      list <QuoteLineItem> lstQuoteLineItem = new List< QuoteLineItem>();
		      lstQuoteLineItem.add(new QuoteLineItem( Quantity = 1.0 ,Vehicle__c = veh.id,  quoteid= q1.id,
		                                            UnitPrice = 21951.0 , Take_Price2__c = 18951.0,Approval_Level__c= 2,PricebookEntryId=pbe.id,
		                                            Interest_Rate__c = '12',
													Term__c = '12'
		                                            ));
		      insert lstQuoteLineItem;   
        
  
        			
			QuoteExtensions controller = new QuoteExtensions(new ApexPages.Standardcontroller(q1));
			system.assertequals(False , controller.showMessage);

    }
    }
}