SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>RSM_CCMs__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to Store RydeSmart&apos;s CCM (Customer Care Manager) owner</description>
        <inlineHelpText>If CCM is changed Manually then check &quot;Do Not Override CCM&quot; field.</inlineHelpText>
        <label>CCM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Update_Revenue__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Update Revenue</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Customer_Branch__c.object
<CustomObject>
    <description>Customer Branches at Ryder</description>
    <fields>
        <fullName>Ryder_Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field for Customer Branch to Ryder branch</description>
        <label>Ryder Branch</label>
        <referenceTo>Ryder_Branch__c</referenceTo>
        <relationshipLabel>Customer / Branch</relationshipLabel>
        <relationshipName>Customer_Branches</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer / Branch</label>
    <nameField>
        <label>Customer Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer / Branch</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/RSM_Component__c.object
<CustomObject>
    <description>Object to store the RydeSmart Components &amp; installation details</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>This field is Used to pass the AccountId to History Viewer VF page by clicking History Viewer button.</description>
        <formula>Unit_Number__r.Account__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Equipment_Type__c</fullName>
        <label>Equipment Type</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Current__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Current</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unit_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Number</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>RSM Components</relationshipLabel>
        <relationshipName>RSM_Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RSM Component</label>
    <nameField>
        <label>RSM Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RSM Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC Automation/src/objects/RSM_Contract__c.object
<CustomObject>
    <description>Object to store RydeSmart Contract details</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to store the ID of the Account with which the Contract is related. This field will be populated from database based on the Lessee No in the contract</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>RSM Contracts</relationshipLabel>
        <relationshipName>RSM_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Number__c</fullName>
        <externalId>true</externalId>
        <label>Contract Number</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status_Name__c</fullName>
        <label>Status Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>RSM Contract</label>
    <nameField>
        <label>RSM Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RSM Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC Automation/src/objects/RSM_ContractDetail__c.object
<CustomObject>
    <description>The object stores the details of the contract</description>
    <fields>
        <fullName>Contract_Number__c</fullName>
        <label>Contract Number</label>
        <referenceTo>RSM_Contract__c</referenceTo>
        <relationshipName>ContractNumber</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Current__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Current</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unit_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Number</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipName>RSContractDetails</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Valid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Valid</label>
        <type>Checkbox</type>
    </fields>
    <label>RSM ContractDetail</label>
    <nameField>
        <label>RSM ContractDetailID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RSM ContractDetails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Ryder_Branch__c.object
<CustomObject>
    <description>Branches at Ryder</description>
    <label>Ryder Branch</label>
    <nameField>
        <label>Ryder Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ryder Branches</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup on Accounts</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CUSTOMER_BRANCH__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field for Customer Branch</description>
        <label>Customer Branch</label>
        <referenceTo>Customer_Branch__c</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RSM_Service_Level__c</fullName>
        <description>Displays Service Level of the vehicle</description>
        <label>Service Level</label>
        <picklist>
            <picklistValues>
                <fullName>Plus 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>STD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/RSMManageContracts.cls
public class RSMManageContracts
{
    public static void ManageEqipmentRequisition(List<RSM_Contract__c> listContract, Map<Id, RSM_Contract__c> MapContract)  
    {
        Map<Id, list<RSM_ContractDetail__c>> mapcontractdetails = new Map<Id, list<RSM_ContractDetail__c>>();
        Set<ID> setCont = new Set<ID>();
        Set<ID> setvehicle = new Set<ID>();
        Set<ID> sAccIds = new Set<ID>();
        List<RSM_Contract__c> listContracttoprocess = new List<RSM_Contract__c>();
        for(RSM_Contract__c contr : listContract)
        {
            if(contr.Status_Name__c == 'Approved' && (MapContract == null || 
                    (MapContract.get(contr.Id).Status_Name__c != null && 
                    MapContract.get(contr.Id).Status_Name__c != 'Approved')))
            {
                setCont.add(contr.Id);
                listContracttoprocess.add(contr);
                if(contr.Account__c != null)
                    sAccIds.add(contr.Account__c);
            }
        }
        if(setCont.size() > 0)
        {
            
            Map<Id, RSM_ContractDetail__c> mapcontdetails = new Map<Id, RSM_ContractDetail__c>([Select r.Valid__c, r.Unit_Number__c, 
                                                                r.Name, r.Id, r.Contract_Number__c From RSM_ContractDetail__c r where 
                                                                Contract_Number__c in : setCont]);
            for(RSM_Contract__c contr : listContracttoprocess)
            {
                List<RSM_ContractDetail__c> listdetails = new List<RSM_ContractDetail__c>();
                for(RSM_ContractDetail__c contractdetail : mapcontdetails.values())
                {
                    if(contractdetail.Contract_Number__c == contr.Id)
                    {
                        //listdetails.add(contractdetail);
                        setvehicle.add(contractdetail.Unit_Number__c);
                    }
                }
                if(listdetails.size() > 0)
                    mapcontractdetails.put(contr.Id, listdetails);
            }
        }
        System.debug('--34----------mapcontractdetails-----'+mapcontractdetails);
        if(setvehicle.size() > 0)
        {
            Map<ID, List<Vehicle__c>> mapVelicle = new Map<ID, List<Vehicle__c>>();
            Map<Id, Vehicle__c> mapVehicle = new Map<Id, Vehicle__c>([Select v.CUSTOMER_BRANCH__r.Ryder_Branch__c, 
                                                                        v.CUSTOMER_BRANCH__c, v.Account__c, v.RSM_Service_Level__c 
                                                                        From Vehicle__c v where id in : setvehicle and 
                                                                        RSM_Service_Level__c != null]);
            Set<ID> setAccount = new Set<ID>();
            for(Vehicle__c Vehicle : mapVehicle.values())
            {
                setAccount.add(Vehicle.Account__c);
            }
            for(ID accId : setAccount)
            {
                List<Vehicle__c> listVehicle = new List<Vehicle__c>();
                for(Vehicle__c Vehicle : mapVehicle.values())
                {
                    if(accId == Vehicle.Account__c)
                        listVehicle.add(Vehicle);
                }
                if(listVehicle.size() > 0)
                    mapVelicle.put(accId, listVehicle);
            }
            
            Map<ID, List<RSM_Component__c>> mapvehComp = new Map<ID, List<RSM_Component__c>>();
            
            Map<Id, RSM_Component__c> mapComponent = new Map<Id, RSM_Component__c>([Select r.Unit_Number__c, r.Is_Current__c, r.Id, 
                                                        r.Equipment_Type__c From RSM_Component__c r where 
                                                        Unit_Number__c in : mapVehicle.keySet() 
                                                        and Is_Current__c = true]);
            for(ID vehicleid : setvehicle)
            {
                List<RSM_Component__c> listComponent = new List<RSM_Component__c>();
                for(RSM_Component__c Component : mapComponent.values())
                {
                    if(Component.Unit_Number__c == vehicleid)
                        listComponent.add(Component);
                }
                if(listComponent.size() > 0)
                    mapvehComp.put(vehicleid, listComponent);
            }
            
            
        }
        if(sAccIds.size() > 0)
        {
            updateAccount(sAccIds);
        }
    }
    @future
    public static void updateAccount(Set<ID> sAccIds)
    {
        List<Account> lAcc = new List<Account>();
        for(ID AccId : sAccIds)
        {
            Account Acc = new Account(Id = AccId, Update_Revenue__c = true);
            lAcc.add(Acc);
        }
        if(lAcc.size() > 0)
        {
            update lAcc;
        }
    }
    public static void AccountSendEmail(List<RSM_Contract__c> listContract)  
    {
        
        Set<ID> setaccountid = new Set<ID>();
        for(RSM_Contract__c RSM_Contract : listContract)
        {
            if(RSM_Contract.Account__c != null)
                setaccountid.add(RSM_Contract.Account__c);
        }
        if(setaccountid.size() > 0)
        {
            List<AggregateResult> ContractAgg = [SELECT Count(Id) CountId, Account__c Acc FROM RSM_Contract__c WHERE 
                                                    Account__c in: setaccountid  
                                                    Group by Account__c];
            setaccountid = new Set<ID>();
            for(AggregateResult AggResult : ContractAgg)
            {
                Integer iContractCount = ((integer)AggResult.get('CountId'));
                if(iContractCount == 1)
                {
                    setaccountid.add(((Id)AggResult.get('Acc')));
                }
            }
        }
        if(setaccountid.size() > 0)
        {
            List<Account> accforemail = [select Id, RSM_CCMs__c from Account where Id in : setaccountid];
            List<Messaging.SingleEmailMessage> lstSendEmail = new List<Messaging.SingleEmailMessage>();
            List<EmailTemplate> lstemailtemplate = [Select Id from EmailTemplate where DeveloperName = 'First_Contract_Email_CCM'];
            
            if(lstemailtemplate.size() > 0)
            {
                for(Account a : accforemail)
                {
                    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                    mail.setTargetObjectId(a.RSM_CCMs__c);                 
                    mail.setTemplateId(lstemailtemplate[0].Id);
                    mail.setSaveAsActivity(false);
                    lstSendEmail.add(mail);
                }
            }
            if(lstSendEmail.size() > 0)
                Messaging.sendEmail(lstSendEmail);              
        }
    }
}