SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>LesseeNo__c</fullName>
        <description>Realtime update of both SFDC and RADAR whenever this value is changed in either system</description>
        <label>Lessee Number</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Key_Contact__c.object
<CustomObject>
    <description>CSI and Maintenance Contacts</description>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AccountId</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Key Contacts</relationshipLabel>
        <relationshipName>Key_Contacts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <inlineHelpText>Select which role this Contact serves for this Customer/Branch.</inlineHelpText>
        <label>Contact Role</label>
        <picklist>
            <picklistValues>
                <fullName>CSI Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maintenance Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RydeSmart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RydeSmart Mktg</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IFT Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.STATUS_ACTIVE__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Related Branches</relationshipLabel>
        <relationshipName>Key_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Key Contact</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Key Contact #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Key Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/RSM_Contract__c.object
<CustomObject>
    <description>Object to store RydeSmart Contract details</description>
    <fields>
        <fullName>Cancelled_Contract_details__c</fullName>
        <label>Cancelled Contract details</label>
        <summaryFilterItems>
            <field>RSM_ContractDetail__c.Action_Name__c</field>
            <operation>equals</operation>
            <value>Cancel</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>RSM_ContractDetail__c.Is_Current__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>RSM_ContractDetail__c.Contract_Number__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Contract_Number__c</fullName>
        <externalId>true</externalId>
        <label>Contract Number</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lessee__c</fullName>
        <label>Lessee</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status_Name__c</fullName>
        <label>Status Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Contract_Detail__c</fullName>
        <label>Total Contract Detail</label>
        <summaryFilterItems>
            <field>RSM_ContractDetail__c.Is_Current__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>RSM_ContractDetail__c.Contract_Number__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>RSM Contract</label>
    <nameField>
        <label>RSM Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RSM Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC Automation/src/classes/RSMCancelEmailtoNonKeyAc.cls
//FR134-Cancellation Email to Non-Key Accounts once contract cancels
//when all the units have cancelled the contract
global class RSMCancelEmailtoNonKeyAc implements Database.Batchable<SObject>{
    
    public String query;
    global Database.QueryLocator start(Database.BatchableContext BC){
          System.debug('query : '+query);
          return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Account> scope){
        List<Messaging.SingleEmailMessage> EmailList=new List<Messaging.SingleEmailMessage>();
        Set<string> LesseeNoSet=new Set<String>(); 
        Set<Id> accountIdSet=new Set<Id>();
        Set<Id> conIds=new Set<Id>();
        Set<Id> conIdsToEmail=new Set<Id>(); 
        Set<Id>  taskExistConIdsSet=new Set<Id>();          
        for(Account acc:scope){
            LesseeNoSet.add(acc.LesseeNo__c);
        }

    Map<String,String> keyContactEmailMap=new Map<String,String>();
        for(Key_Contact__c kc:[select Id,Contact__r.Email,AccountId__r.LesseeNo__c from Key_Contact__c where Contact_Role__c='RydeSmart' and AccountId__r.LesseeNo__c in :LesseeNoSet]){
            keyContactEmailMap.put(kc.AccountId__r.LesseeNo__c,kc.Contact__c);
        }
        
    for(RSM_Contract__c c:[select Id,Lessee__c,Contract_Number__c, Cancelled_Contract_details__c,Total_Contract_Detail__c from RSM_Contract__c where Lessee__c in :LesseeNoSet and Status_Name__c='Approved']){
        if(c.Cancelled_Contract_details__c > 0 && c.Total_Contract_Detail__c>0 && c.Total_Contract_Detail__c==c.Cancelled_Contract_details__c){
            conIdsToEmail.add(c.Id);
        }
    }
       
    for(Task t:[select Id,whatId from Task where subject='Email: RydeSmart Cancellation' and whatId in:conIdsToEmail]){
        taskExistConIdsSet.add(t.whatId);
    } 
    conIdsToEmail.removeAll(taskExistConIdsSet);
    String etId=[select Id from EmailTemplate where developerName='RSMCancelEmailtoNonKeyAc'].Id;       
    System.debug('Saad etId = ' + etId);
    for(RSM_Contract__c c:[select Id,Lessee__c,Contract_Number__c, Cancelled_Contract_details__c,Total_Contract_Detail__c from RSM_Contract__c where Id in:conIdsToEmail]){
       System.debug('Saad c = ' + c);        
       if(keyContactEmailMap.get(c.Lessee__c)!=null){    
            System.debug('Saad c.Lessee__c = ' + c.Lessee__c);      
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setTargetObjectId(keyContactEmailMap.get(c.Lessee__c));                 
            mail.setTemplateId(etId);
            mail.setBccSender(true);
            mail.setUseSignature(false);
            mail.setSaveAsActivity(true);
            mail.setWhatId(c.Id);
            EmailList.add(mail);   
            System.debug('Saad EmailList = ' + EmailList);
        }  
    } 
    if(EmailList!=null && EmailList.size()>0 && !Test.isRunningTest()){
        System.debug('EmailList : '+EmailList);
        Messaging.sendEmail(EmailList);
    } 
    }

    global void finish(Database.BatchableContext BC){
    }
}