SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CustProspectID__c</fullName>
        <description>Customer Prospect ID</description>
        <externalId>true</externalId>
        <label>Customer Prospect ID</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CustomerTypeID__c</fullName>
        <description>Customer type indicating FMS or RIL. Realtime update of both SFDC and RADAR whenever this value is changed in either system.      Question: Does RADAR care about this or any changes to this field?</description>
        <label>Customer Type</label>
        <picklist>
            <picklistValues>
                <fullName>FMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RIL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FMS Rental</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/classes/test_UpdateCompanyTrigger.cls
/**
 * This class tests the affect of trigger for updateCompany trigger.
 */
@isTest
private class test_UpdateCompanyTrigger 
{
	
	// Create Account to attach to existing lead convert 
	private static Account createAccount(String country)
	{
		Account account = new Account();
		account.Name = RyderGlobalVariables.TEST_PRIMARY_NAME;
		account.ShippingStreet = RyderGlobalVariables.TEST_ADDRESS_LINE;
		account.ShippingCity = RyderGlobalVariables.TEST_CITY;
		if (country == RyderGlobalVariables.COUNTRIES_USA)
			account.ShippingState = RyderGlobalVariables.TEST_STATE;
		else
			account.ShippingState = RyderGlobalVariables.TEST_STATE_CANADA;
		
		account.ShippingCountry = RyderGlobalVariables.COUNTRIES_USA;
		account.ShippingPostalCode = RyderGlobalVariables.TEST_POST_CODE;
		account.CustomerTypeID__c = RyderGlobalVariables.CustomerType.FMS.name();
		account.Type = RyderGlobalVariables.TEST_TYPE_PROSPECT;
		account.BillingState = 'IL';
		account.CustProspectID__c = '8764356';
		
		insert account;
		
		return account;
	}
	
    static testMethod void test_UpdateCompany() 
    {
    	RyderGlobalVariables.IS_TEST = true;
    	RyderGlobalVariables.UPDATE_ACCOUNT_TRIGGER = true;
    	Account account = createAccount(RyderGlobalVariables.COUNTRIES_CANADA_TEXT);
    	account.CustomerTypeID__c = RyderGlobalVariables.CustomerType.RIL.name();
    	update account;
    	Set<Id> accountIds = new Set<Id>();
    	accountIds.add(account.Id); 
    	updateCompanyFuture.updateCompanyOnRyder(accountIds);
    	
    }
}