SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CustomerTypeID__c</fullName>
        <description>Customer type indicating FMS or RIL. Realtime update of both SFDC and RADAR whenever this value is changed in either system.      Question: Does RADAR care about this or any changes to this field?</description>
        <label>Customer Type</label>
        <picklist>
            <picklistValues>
                <fullName>FMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RIL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FMS Rental</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Major_Category__c</fullName>
        <label>Major Category</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>A/P:1099 Transfer x6628</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/P:Check Clear Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/P:Check Copy/Remittance Info</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/P:Chimes-Vendor Referred to VS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/P:Invoice Mailing Address</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/P:Location Charged Questions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/P:Location Invoice Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/P:Payment Status - vendors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/P:RCRC Invoice Copy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/P:RCRC P.O. Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/P:Utilities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/P:Vendor Information Sheet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/P:Vendor Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/P:W-9 Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/P 1099</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/P Admin Vendor (SSC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/P Canadian Invoices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/P Checks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/P - Comdata Fuel Cards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/P - Comdata Mastercard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/P Credit Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/P Drafts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/P Expense Reports - GERS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/P Expense Reports - Manual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/P FIS/Shop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/P Fixed Assets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/P Invoices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/P RCRC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/P Research (WNS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/P Utilities</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subcategory__c</fullName>
        <label>Subcategory</label>
        <picklist>
            <controllingField>Major_Category__c</controllingField>
            <picklistValues>
                <fullName>1099 Correction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1099 Not Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1099 Questions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>120-day Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30-day Letter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>45-day Threat to Bill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60-day Process Bill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>90-day Cancellation Notice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/P:1099 Transfer x6628</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/P:Check Clear Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/P:Check Copy/Remittance Info</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/P:Chimes-Vendor Referred to VS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/P:Invoice Mailing Address</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/P:Location Charged Questions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/P:Location Invoice Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/P:Payment Status - vendors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/P:RCRC Invoice Copy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/P:RCRC P.O. Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/P:Utilities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/P:Vendor Information Sheet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/P:Vendor Setup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/P:W-9 Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/P Admin Vendor (SSC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/P Credit Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/P Invoices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/R:Credit Card Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/R:Credit Status</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/R:Lock box address</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/R:Open Items Info</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A/R:Payment Inquiry</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Duplicate</fullName>
        <active>true</active>
        <label>Duplicate</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/classes/test_FirstCallResolutionTrigger.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 
 
 @isTest(SeeAllData=true)
private class test_FirstCallResolutionTrigger {

    static testMethod void sendEmailForDuplicateCase() 
    {
        Case newCase = new Case();
        Account acct = TestUtil.createAccount('Ryder FMS Parent Account', 'Customer');
        insert acct;
        Contact cont = TestUtil.createContact(acct.Id);
        insert cont;
        newCase.AccountId =acct.Id;
        newCase.ContactId =cont.Id;
        newCase.RecordTypeId=[Select Id from RecordType where name=: 'Case for Known Account' and SobjectType =: 'Case'].Id;
      //  newCase.AccountId = '0016000000YgUyv';
       // newCase.ContactId ='00360000017VQnK';
        //newCase.CreatedById = '005W0000000dpfnIAA';
        //newCase.LastModifiedById = '005W0000000dpfnIAA';
        //newCase.OwnerId='005W0000000dpfnIAA';
       // newCase.RecordTypeId ='01260000000UDIRAA4';
        //newCase.Account.Name = 'WENNER BREAD PRODUCTS, INC.';
        newCase.Major_Category__c = 'A/P 1099';
        newCase.Subcategory__c = '1099 Correction';
        insert(newCase);
    }
}
*/
@isTest(SeeAllData=true)
private class test_FirstCallResolutionTrigger {

    static testMethod void sendEmailForDuplicateCase() 
    {
        Account acnt = createAccount();
        Case newCase = new Case();
        Contact cont= createContact(acnt.Id);
        newCase.RecordTypeId=[Select Id from RecordType where name=: 'Case for Known Account' and SobjectType =: 'Case'].Id;
        newCase.AccountId = acnt.Id;
        newCase.ContactId = cont.Id;
        newCase.OwnerId = Userinfo.getUserId();
        newCase.Major_Category__c = 'A/P 1099';
        newCase.Subcategory__c = '1099 Correction';
        insert(newCase);
        for(integer i=0;i< 3; i++)
        {
            CreateDuplicateCases(acnt.Id,cont.Id);
        }
    }
    private static void CreateDuplicateCases(Id acctId, Id contId)
    {
        Case newCase2 = new Case();
        newCase2.AccountId = acctId;
        newCase2.ContactId = contId;
        newCase2.OwnerId = Userinfo.getUserId();
        newCase2.Major_Category__c = 'A/P 1099';
        newCase2.Subcategory__c = '1099 Correction';
        insert(newCase2); 
    }
    private static Account createAccount()
    {
        Account pAccount = new Account();
        pAccount.Name = 'Company for Duplicate case Testing.';
        pAccount.ShippingStreet = 'Address Line 1';
        pAccount.ShippingCity = 'Test City 1';
        pAccount.ShippingState = 'FL';
        pAccount.ShippingPostalCode = '12345';
        pAccount.ShippingCountry = RyderGlobalVariables.COUNTRIES_USA;
        pAccount.CustomerTypeID__c = RyderGlobalVariables.CustomerType.FMS.name();
        pAccount.billingstate = 'IL';
        insert pAccount;
        
        return pAccount;
    }
    private static Contact createContact(Id acctId)
    {
        Contact contact1 = new Contact();
        contact1.FirstName = 'Contact One First Name';
        contact1.LastName = 'Contact One Last Name';
        contact1.Phone = null;
        contact1.Email = 'DupCase@xyz.com';
        contact1.AccountId = acctId;
        insert contact1;
        
        return contact1;
    }
}