SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Additional_Comments__c</fullName>
        <inlineHelpText>Place additional comments for service handling</inlineHelpText>
        <label>Additional Comments</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <picklist>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wholesale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Export</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Vendor account record type for legal requests</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Additional_Comments__c</fullName>
        <description>field to capture comments at the item of customer needs selection.</description>
        <inlineHelpText>field to capture comments at the item of customer needs selection.</inlineHelpText>
        <label>Additional Comments</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Original_Decision_Maker__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Original Decision Maker</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>Contact.STATUS_ACTIVE__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>The Contact you are adding as an Original Decision Maker must be an active Contact within the same Account where you are creating the new Opportunity.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Product_Detail__c</fullName>
        <label>Product Detail</label>
        <picklist>
            <controllingField>Product_Line__c</controllingField>
            <picklistValues>
                <fullName>VOSA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Choice Lease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flex</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fast Track</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plus One</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physical Damage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haz-mat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Level 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OPIS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <label>Product Line</label>
        <picklist>
            <picklistValues>
                <fullName>FSL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RPM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rydesmart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DCC Light</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fuel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <picklist>
            <picklistValues>
                <fullName>New Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Location</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fleet Add</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Replacement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Term Extension</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rate Change</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Unit_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Number</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

SFDC Automation/src/objects/Pricebook2.object
<CustomObject>
    <recordTypes>
        <fullName>UVS</fullName>
        <active>true</active>
        <description>Used by Used Vehicle Sales Group</description>
        <label>UVS</label>
    </recordTypes>
    <sharingModel>ReadSelect</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Ryder_Account_Team_Role_Map__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Ryder Account Team Role Map</label>
</CustomObject>

SFDC Automation/src/objects/RyderConfig__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Provides configuration information for Ryder</description>
    <label>Ryder Config</label>
</CustomObject>

SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <fields>
        <fullName>Ask_Price__c</fullName>
        <label>Ask Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NBV__c</fullName>
        <label>Book Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PRODUCT_LINE__c</fullName>
        <description>Product Line</description>
        <label>Product Line</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Detail__c</fullName>
        <description>Product Detail as indicated in the contract package</description>
        <label>Product Detail</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Take_Price__c</fullName>
        <label>Take Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <description>This field will hold the transaction type of the vehicle. Eg: Lease Extension</description>
        <label>Transaction Type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <recordTypes>
        <fullName>UVS</fullName>
        <active>true</active>
        <description>Record Type for UVS Vehicles</description>
        <label>UVS</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Vehicle_List__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of vehicles with their types</description>
    <label>Vehicle List</label>
</CustomObject>

SFDC Automation/src/classes/VehicleTriggerHandlerTest.cls
/*************************************************************************************************
Created By:     Nimisha Prashant
Date:           September 22, 2014
Description  :  Test Class for Handler class for Vehicle Trigger
Updated By:     Sunny Gill
Date:           September 22, 2014
**************************************************************************************************/
@isTest(seeAllData = true)
private class VehicleTriggerHandlerTest {
    static User uvsUser;
    static Account acc;
    static Opportunity opp;
    static List<Vehicle__c> oldVehList = new List<Vehicle__c>();
    static List<Vehicle__c> newVehList = new List<Vehicle__c>();
    static testMethod void testUpdateOppChatter() {
      uvsUser = TestUtilUVS.createUser(true);
      system.runAs(uvsUser) {
//        list<Vehicle_List__c> vehListconfig = TestUtilUVS.createVehicleList(true);
//        RyderConfig__c rydConf = TestUtilUVS.createRyderConfig(true);
//        Ryder_Account_Team_Role_Map__c ryAccTRM = TestUtilUVS.createRyderAccountTeamRoleMap(true);

        acc = TestUtilUVS.createAccount('Vendor', 'FMS', true);
        Contact newCon = TestUtilUVS.createContact(acc.Id,false);
        newCon.Additional_Comments__c = 'Test1';
        newCon.Email = 'test2@rydertest.com';
        newCon.OwnerId = UserInfo.getUserId();
        insert newCon;

        opp = TestUtilUVS.createOpportunity('UVS Opportunity', acc, false, newCon);
        opp.Original_Decision_Maker__c = newCon.Id;
        //test.starttest();
        insert opp;
        test.starttest();
        //test.stoptest();
        List<Vehicle__c> vehicleList = TestUtilUVS.createVehList(true);

        //List<OpportunityLineItem> oppLIList = TestUtilUVS.createOpportunityLineItemList(acc, vehicleList, true);

        oldVehList = [SELECT Id,Ask_Price__c,Take_Price__c,NBV__c FROM Vehicle__c where id in :vehicleList];
        Map<Id, Vehicle__c> oldmap = new Map<Id, Vehicle__c>();
        for(Vehicle__c v : oldVehList) {
            oldmap.put(v.id, v);
        }
        newVehList = [SELECT Id,Ask_Price__c,Take_Price__c,NBV__c FROM Vehicle__c  where id in :vehicleList];
        newVehList.get(0).Ask_Price__c = 12;
        newVehList.get(1).Take_Price__c = 12;
        newVehList.get(2).NBV__c = 12;
        Map<Id, Vehicle__c> newmap = new Map<Id, Vehicle__c>();
        for(Vehicle__c v : newVehList) {
            newmap.put(v.id, v);
        }
        System.debug(oldVehList);
        System.debug(newVehList);
        
        // Create OppLine Items 
        for(Id vhId:newmap.keySet()){
        	
        	 Product2 prod = new Product2();
	        prod.Name = 'Standard Price Book UVS';
	        prod.CurrencyIsoCode = 'CAD';
	        prod.family = 'FSL';
	        insert prod;
	       /* PriceBookEntry pbe = [SELECT Id , Pricebook2Id
	                              FROM PriceBookEntry
	                              WHERE Product2Id = :prod.Id
	                              LIMIT 1];*/
	        PriceBookEntry pbe = [Select Name ,Product2.Family,Product2.Id, Pricebook2Id , Pricebook2.name , CurrencyIsoCode From PricebookEntry where Pricebook2.name= 'UVS' LIMIT 1];
            pbe.isActive = true;
            update pbe;
            
            system.debug('::PBE :::'+pbe);
            String productFamily = pbe.Product2.Family;
            
            opp = TestUtilUVS.createOpportunity('UVS Opportunity', acc, false, newCon);
            opp.Original_Decision_Maker__c = newCon.Id;
            opp.Pricebook2Id = pbe.Pricebook2Id;
            opp.CurrencyIsoCode = pbe.CurrencyIsoCode;
            
            insert opp;

           
            //   veh = TestUtilUVS.createUVSVehicle(acc, true);
			//test.starttest();
            OpportunityLineItem oLI = new OpportunityLineItem();
            oLI.OpportunityId=opp.Id;
            oLI.Unit_Number__c=vhId;
            oLI.PricebookEntryId=pbe.Id;

            oLI.Quantity=1;
            oLI.UnitPrice=123;
            //oLI.Take_Price__c=12;
            oLI.Transaction_Type__c='NewCustomer';
            oLI.Product_Line__c= productFamily;
            oLI.Product_Detail__c='VOSA';
            oLI.Unit_Number__c = vhId;
            //oLi.IsTestRunning__c = true;
            insert oLI;
            break;
        }
        
        VehicleTriggerHandler.updateOppChatter(oldMap, newMap);
        test.stoptest();
      }
    }

}