SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Additional_Comments__c</fullName>
        <inlineHelpText>Place additional comments for service handling</inlineHelpText>
        <label>Additional Comments</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Components_Not_Included__c</fullName>
        <inlineHelpText>Describe any components not included in Service</inlineHelpText>
        <label>Components Not Included</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Other_Instructions__c</fullName>
        <inlineHelpText>Please specify Subs for PM&apos;s</inlineHelpText>
        <label>Other Instructions</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Other_Misc_Billing_Information__c</fullName>
        <inlineHelpText>This information will not be displayed in SHOP.</inlineHelpText>
        <label>Other Misc. Billing Information</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Speed_Changes__c</fullName>
        <inlineHelpText>Are speed changes authorized and by whom</inlineHelpText>
        <label>Speed Changes</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Additional_Comments__c</fullName>
        <description>field to capture comments at the item of customer needs selection.</description>
        <inlineHelpText>field to capture comments at the item of customer needs selection.</inlineHelpText>
        <label>Additional Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CSI_Contact_Type__c</fullName>
        <label>CSI Contact - All Branches</label>
        <picklist>
            <picklistValues>
                <fullName>Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tertiary</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <label>Post Sales Contact Role</label>
        <picklist>
            <picklistValues>
                <fullName>After Hours</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P.O. Authorization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RCRC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Target Marketing Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executive Sponsorship Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RydeSmart</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>HQ_Account_Id_18__c</fullName>
        <formula>HQ_Account_ID__c 
&amp; MID(&quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ012345&quot;,( 
IF(FIND(MID(Id,1,1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;)&gt;0,1,0) 
+IF(FIND(MID(HQ_Account_ID__c,2,1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;)&gt;0,2,0) 
+IF(FIND(MID(HQ_Account_ID__c,3,1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;)&gt;0,4,0) 
+IF(FIND(MID(HQ_Account_ID__c,4,1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;)&gt;0,8,0) 
+IF(FIND(MID(HQ_Account_ID__c,5,1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;)&gt;0,16,0) 
)+1,1) 
&amp; MID(&quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ012345&quot;,( 
IF(FIND(MID(HQ_Account_ID__c,6,1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;)&gt;0,1,0) 
+IF(FIND(MID(HQ_Account_ID__c,7,1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;)&gt;0,2,0) 
+IF(FIND(MID(HQ_Account_ID__c,8,1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;)&gt;0,4,0) 
+IF(FIND(MID(HQ_Account_ID__c,9,1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;)&gt;0,8,0) 
+IF(FIND(MID(HQ_Account_ID__c,10,1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;)&gt;0,16,0) 
)+1,1) 
&amp; MID(&quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ012345&quot;,( 
IF(FIND(MID(HQ_Account_ID__c,11,1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;)&gt;0,1,0) 
+IF(FIND(MID(HQ_Account_ID__c,12,1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;)&gt;0,2,0) 
+IF(FIND(MID(HQ_Account_ID__c,13,1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;)&gt;0,4,0) 
+IF(FIND(MID(HQ_Account_ID__c,14,1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;)&gt;0,8,0) 
+IF(FIND(MID(HQ_Account_ID__c,15,1), &quot;ABCDEFGHIJKLMNOPQRSTUVWXYZ&quot;)&gt;0,16,0) 
)+1,1)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>HQ Account Id 18</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Maintenance_Contact_Type__c</fullName>
        <label>Maintenance Contact - All Branches</label>
        <picklist>
            <picklistValues>
                <fullName>Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tertiary</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Primary</fullName>
        <active>true</active>
        <label>Primary</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Customer_Branch__c.object
<CustomObject>
    <description>Customer Branches at Ryder</description>
    <fields>
        <fullName>Additional_Comments__c</fullName>
        <inlineHelpText>Place additional comments for service handling

SMO Field: Text in this field and Other Misc. Billing Information field make up the Comments field in SMO</inlineHelpText>
        <label>Additional Comments</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Blanket_PO_Number__c</fullName>
        <label>Blanket PO Number</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Components_Not_Included__c</fullName>
        <inlineHelpText>Describe any components not included in Service

SMO Field: Component Not Included in Maintenance Plan</inlineHelpText>
        <label>Components Not Included</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Customer_Branch_Status__c</fullName>
        <description>Indicates whether a Customer/Branch has active vehicles.</description>
        <inlineHelpText>Indicates whether a Customer/Branch has active vehicles.</inlineHelpText>
        <label>Customer Branch Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Customer_Requires_PO__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Customer Requires PO</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Other_Instructions__c</fullName>
        <inlineHelpText>Please specify Subs for PM&apos;s

SMO Field: Other Instructions</inlineHelpText>
        <label>Other Instructions</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Other_Misc_Billing_Information__c</fullName>
        <inlineHelpText>Enter billing information details

SMO Field: Text in this field and Additional Comments field make up the Comments field in SMO</inlineHelpText>
        <label>Other Misc. Billing Information</label>
        <length>6500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Pre_authorized_Repair_Amount__c</fullName>
        <inlineHelpText>SMO Field: Approval or PO if exceeds</inlineHelpText>
        <label>Pre-authorized Repair Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pre_authorized_Repairs__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If Checked, the Customer has pre-authorized repairs. 

SMO Field: Customer PO Required</inlineHelpText>
        <label>Pre-authorized Repairs</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary_Account_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Account Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Customer / Branch</relationshipLabel>
        <relationshipName>Customer_Branch1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Contact_Count__c</fullName>
        <description>Used to count the # of Primary Contacts users are trying to add</description>
        <label>Primary Contact Count</label>
        <summaryFilterItems>
            <field>Key_Contact__c.Contact_Type__c</field>
            <operation>equals</operation>
            <value>Primary</value>
        </summaryFilterItems>
        <summaryForeignKey>Key_Contact__c.Customer_Branch__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Risk_Status__c</fullName>
        <label>Risk Status</label>
        <picklist>
            <picklistValues>
                <fullName>Growth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>At Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Status</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Ryder_Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field for Customer Branch to Ryder branch</description>
        <label>Ryder Branch</label>
        <referenceTo>Ryder_Branch__c</referenceTo>
        <relationshipLabel>Customer / Branch</relationshipLabel>
        <relationshipName>Customer_Branches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ryder_HQ_Account__c</fullName>
        <description>M/D field between Customer Branch and HQ Accounts</description>
        <label>Ryder HQ Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer / Branch</relationshipLabel>
        <relationshipName>Customer_Branches</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Speed_Changes__c</fullName>
        <inlineHelpText>Are speed changes authorized and by whom

SMO Field: Are speed changes authorized and by whom</inlineHelpText>
        <label>Speed Changes</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>VEH_COUNT__c</fullName>
        <label>Vehicle Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ext_customerbranch_id__c</fullName>
        <externalId>true</externalId>
        <label>Ext Cust Branch Id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Customer / Branch</label>
    <nameField>
        <label>Customer Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer / Branch</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Key_Contact__c.object
<CustomObject>
    <description>CSI and Maintenance Contacts</description>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <inlineHelpText>Select which role this Contact serves for this Customer/Branch.</inlineHelpText>
        <label>Contact Role</label>
        <picklist>
            <picklistValues>
                <fullName>CSI Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maintenance Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RydeSmart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RydeSmart Mktg</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IFT Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <inlineHelpText>Select the Contact Type.  Only one contact can be listed as Primary for a Customer/Branch.</inlineHelpText>
        <label>Contact Type</label>
        <picklist>
            <picklistValues>
                <fullName>Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tertiary</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.STATUS_ACTIVE__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Related Branches</relationshipLabel>
        <relationshipName>Key_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Branch__c</fullName>
        <description>Joiner object used for CSI and Maintenance Contacts</description>
        <label>Customer / Branch</label>
        <referenceTo>Customer_Branch__c</referenceTo>
        <relationshipLabel>Key Contacts</relationshipLabel>
        <relationshipName>Key_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Key Contact</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Key Contact #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Key Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/classes/CustomerBranchKeyContact.cls
public without sharing class CustomerBranchKeyContact {
	
	public Customer_Branch__c customerBranch{get; set;}
    
    public List<Key_Contact__c> keyContacts {set; get;}
    
    public List<KeyContactVO> keyContactList {set; get;}
    
    public boolean displayMoreLink {set; get;}
    
    public String addNewKeyContact {get; set;}  
    
    public String customerBranchToContactRLID {get; set;}
    
     
     public CustomerBranchKeyContact(ApexPages.StandardController stdController) {
        
        this.customerBranch = (Customer_Branch__c)stdController.getRecord();
        this.customerBranch = [Select c.ext_customerbranch_id__c, c.VEH_COUNT__c, c.SystemModstamp, c.Speed_Changes__c, 
            c.Ryder_HQ_Account__c, c.Ryder_Branch__c, c.Risk_Status__c, c.Primary_Contact_Count__c, c.Primary_Account_Contact__c, 
            c.Pre_authorized_Repairs__c, c.Pre_authorized_Repair_Amount__c, c.Other_Misc_Billing_Information__c, 
            c.Other_Instructions__c, c.Name, c.LastModifiedDate, c.LastModifiedById, c.IsDeleted, c.Id, 
            c.Customer_Requires_PO__c, c.CurrencyIsoCode, c.CreatedDate, c.CreatedById, c.Components_Not_Included__c, 
            c.Customer_Branch_Status__c, c.Blanket_PO_Number__c, c.Additional_Comments__c From Customer_Branch__c c 
            where c.Id =: this.customerBranch.Id LIMIT 1];
        init();
    }
    
    private void init() {
      
        this.displayMoreLink = false;
        this.customerBranchToContactRLID = RyderGlobalVariables.CUSTOMER_BRANCH_TO_CONTACT_RLID;    
        this.keyContactList = new List<KeyContactVO>();
        String accountId = this.customerBranch.Ryder_HQ_Account__c;
        Integer i = 0;
         //  neelima boppana- commented for key contact rewrite 06/29/11
         /*
        //Get primary CSI contacts
        System.debug(LoggingLevel.INFO, '########################### accountId:'+ accountId);
        List<contact> primaryContactList = [select c.id, c.name,c.CSI_Contact_Type__c, c.Maintenance_Contact_Type__c from Contact c where c.HQ_Account_Id_18__c =: accountId and c.CSI_Contact_Type__c != null];
        System.debug('############## primaryContactList:' + primaryContactList);
        if (primaryContactList != null) {
            for (Contact tempContact: primaryContactList) {
	            keyContactList.add(getKeyContactVO(tempContact, RyderGlobalVariables.PrimaryContactRole.CSI));
	            i++;
            }
        }
        system.debug(LoggingLevel.INFO, 'keyContactList size after CSI: ' + keyContactList.size());
        //Get primary maintenance contacts
        
        List<contact> primaryMaintContactList = [select c.id, c.name,c.CSI_Contact_Type__c, c.Maintenance_Contact_Type__c from Contact c where c.HQ_Account_Id_18__c =: accountId and c.Maintenance_Contact_Type__c != null];
        
        if (primaryMaintContactList != null) {
            for (Contact tempContact: primaryMaintContactList) {
                keyContactList.add(getKeyContactVO(tempContact, RyderGlobalVariables.PrimaryContactRole.Maintenance));
                i++;
            }
        } */
        // neelima boppana- soql updated for key contact rewrite 06/29/11
        if (displayMoreLink == false) {
	        this.keyContacts = [Select k.Id, k.Name, k.Customer_Branch__r.Name, k.Customer_Branch__r.Id, k.Contact__r.Name, k.Contact__r.Id, k.Contact_Type__c, k.Contact_Role__c, 
	                k.Available_To__c, k.Available_From__c, k.Available_24_7__c, k.All_Branch_Contact__c, Contact__r.STATUS_ACTIVE__c, Contact__r.DoNotCall, Contact__r.HasOptedOutofSurvey__c  From Key_Contact__c k where k.Customer_Branch__c =: this.customerBranch.Id LIMIT 6];
	        
	        system.debug(LoggingLevel.INFO, 'keyContactList size after maintenance: ' + keyContactList.size());
	        if (this.keyContacts != null) {
	            for(Key_Contact__c keyContact: this.keyContacts) {
	            	KeyContactVO keyContactVO = new KeyContactVO();
	            	keyContactVO.available247 = keyContact.Available_24_7__c;
	            	keyContactVO.availableFrom = keyContact.Available_From__c;
	            	keyContactVO.availableTo = keyContact.Available_To__c;
	            	keyContactVO.contactName = keyContact.Contact__r.Name;
	            	keyContactVO.contactId = keyContact.Contact__r.Id;
	            	keyContactVO.contactRole = keyContact.Contact_Role__c;
	            	keyContactVO.contactType = keyContact.Contact_Type__c;
	            	keyContactVO.customerBranch = keyContact.Customer_Branch__r.Name;
	            	keyContactVO.customerBranchId = keyContact.Customer_Branch__r.Id;
	            	keyContactVO.id = keyContact.Id;
	            	keyContactVO.Name = keyContact.Name;
	            	 // neelima boppana- added for key contact rewrite 06/29/11
	            	keyContactVO.allBranch=keyContact.All_Branch_Contact__c;
	            	keyContactVO.contactStatus = keyContact.Contact__r.STATUS_ACTIVE__c;
	            	keyContactVO.contactDoNotCall = keyContact.Contact__r.DoNotCall;
	            	keyContactVO.contactSurveyOptOut = keyContact.Contact__r.HasOptedOutofSurvey__c;
	            	keyContactList.add(keyContactVO);
	            	i++;
	            	if (i >= 5) {
	            		displayMoreLink = true;
	            		break;
	            	}
	            }	
	        }
        }
        this.addNewKeyContact = addNewKeyContact();
        system.debug(LoggingLevel.INFO, 'keyContactList size: ' + keyContactList.size());
        system.debug(LoggingLevel.INFO, 'keyContactList : ' + keyContactList);
    }
    
    private KeyContactVO getKeyContactVO(Contact tempContact, RyderGlobalVariables.PrimaryContactRole contactRole) {
    	KeyContactVO keyContactVO = new KeyContactVO();
        keyContactVO.available247 = '';
        keyContactVO.availableFrom = '';
        keyContactVO.availableTo = '';
        keyContactVO.contactName = tempContact.Name;
        keyContactVO.contactId = tempContact.Id;
        if (tempContact.CSI_Contact_Type__c != null && contactRole == RyderGlobalVariables.PrimaryContactRole.CSI) {
           keyContactVO.contactRole = RyderGlobalVariables.CSI_ROLE_TEXT;
           keyContactVO.contactType = tempContact.CSI_Contact_Type__c;
        } 
        if (tempContact.Maintenance_Contact_Type__c != null && contactRole == RyderGlobalVariables.PrimaryContactRole.Maintenance) {
           keyContactVO.contactRole = RyderGlobalVariables.MAINTENANCE_ROLE_TEXT;
           keyContactVO.contactType = tempContact.Maintenance_Contact_Type__c;
        }
        
        keyContactVO.customerBranch = 'All';
        keyContactVO.id = null;
        keyContactVO.Name = '';
        return keyContactVO;
    }

    public String addNewKeyContact() {
    	//Get a reference to the Custom Object and gets its Key
        Schema.DescribeSObjectResult result = Key_Contact__c.sObjectType.getDescribe();
    	//navigate to Add new Page
        PageReference pageRef = New PageReference('/' + result.getKeyPrefix() + '/e?' + RyderGlobalVariables.CUSTOMER_BRANCK_HTML_ID + '=' + System.Encodingutil.urlEncode(this.customerBranch.Name, 'UTF-8') + '&' + RyderGlobalVariables.CUSTOMER_BRANCK_HTML_LK_ID + '=' + this.customerBranch.Id + '&retURL=/' + this.customerBranch.Id);
    	return pageRef.getUrl();
    }
    
     // neelima boppana- added for key contact rewrite 06/29/11
     public static void InsertKeyContactsByCustomerBranch(Map<Id, Customer_Branch__c> newMap)
     {
     	Map<Id,String> branchHqAccounts= new Map<Id,String>();
     	Map<Id,String> contactHqAccounts= new Map<Id,String>();
     	List<Key_Contact__c> keyContactsToInsert=new List<Key_Contact__c>();
     	contactUtil.keyContactRecordTypes=CommonFunctions.getRecordTypeMap('Key_Contact__c');
     	
     	// get the hq accounts on the customers branches.
     	for(Customer_Branch__c cb : newMap.values())
     	{
     		if(cb.Customer_Branch_Status__c=='Active')
     	      branchHqAccounts.put(cb.Id,cb.Ryder_HQ_Account__c );
     	}
     	// get all the customer branches for the  hq account id on the contact. 
        List<Contact>allBranchContacts=[Select c.AccountId, c.Available_24_7__c, c.Available_From__c, c.Available_To__c, c.CSI_Contact_Type__c, HQ_Account_Id_18__c,c.Id, c.Maintenance_Contact_Type__c, c.Original_Account__c,c.Contact_Trigger_Toggle__c from Contact c where c.HQ_Account_Id_18__c in :branchHqAccounts.values() and ((c.CSI_Contact_Type__c!=null)or (c.Maintenance_Contact_Type__c!=null))];
        
    	for(Customer_Branch__c branch: newMap.values())
    	{
    		for(Contact c : allBranchContacts)
    		{
    			if(branch.Ryder_HQ_Account__c==c.HQ_Account_Id_18__c)
    			  {
    			     if (c.CSI_Contact_Type__c!=null) keyContactsToInsert.add(ContactUtil.CreateNewKeyContact(c,branch,RyderGlobalVariables.CSI_ROLE_TEXT,true));
    			     if(c.Maintenance_Contact_Type__c!=null)keyContactsToInsert.add(ContactUtil.CreateNewKeyContact(c,branch,RyderGlobalVariables.MAINTENANCE_ROLE_TEXT,true));
    			  }
    		}
    	}
    	System.debug(LoggingLevel.INFO, '+++++++++++++ keyContactsToInsert:' + keyContactsToInsert);
    	insert keyContactsToInsert;     	
     }
     
      // neelima boppana- added for key contact rewrite 06/29/11
      public static void DeleteKeyContactsByCustomerBranch(Map<Id, Customer_Branch__c> newMap, boolean allBranchOnly)
      {
      	List<Key_Contact__c> keyContactsToDelete=null;
      	if(allBranchOnly)
      	{
        keyContactsToDelete=[Select  k.All_Branch_Contact__c,k.Available_From__c, k.Available_To__c, k.Contact__c, k.Contact_Role__c, k.Contact_Type__c, k.Customer_Branch__c, k.HQ_Account_ID__c, k.Id from Key_Contact__c k where k.Customer_Branch__c in :newMap.keySet() and k.All_Branch_Contact__c=true];
        ContactUtil.isDeleteFromTrigger=true;
      	}
     	//get all the key contacts for the deleted branches 
     	else keyContactsToDelete=[Select  k.All_Branch_Contact__c,k.Available_From__c, k.Available_To__c, k.Contact__c, k.Contact_Role__c, k.Contact_Type__c, k.Customer_Branch__c, k.HQ_Account_ID__c, k.Id from Key_Contact__c k where k.Customer_Branch__c in :newMap.keySet()];
     	System.debug(LoggingLevel.INFO, '+++++++++++++ keyContacts To delete:' + keyContactsToDelete);
     	delete keyContactsToDelete;     	
      }
      
    // This method was added to delete all key contacts from a Customer Branch.  
    public void DeleteAllKEyContactsFromCustomerBranch(){
        List<Key_Contact__c> keyContactsToDelete = new List<Key_Contact__c> ();
        keyContactsToDelete=[Select k.All_Branch_Contact__c,k.Available_From__c, k.Available_To__c, k.Contact__c, k.Contact_Role__c, k.Contact_Type__c, k.Customer_Branch__c, k.HQ_Account_ID__c, k.Id from Key_Contact__c k where k.Customer_Branch__c =:  this.customerBranch.Id];
        if (keyContactsToDelete != null && keyContactsToDelete.size()!=0){
            delete keyContactsToDelete;
            init();
        }  
    }  

}