SFDC Automation/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Additional_Comments__c</fullName>
        <inlineHelpText>Place additional comments for service handling</inlineHelpText>
        <label>Additional Comments</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Vendor account record type for legal requests</description>
        <label>Vendor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Additional_Comments__c</fullName>
        <description>field to capture comments at the item of customer needs selection.</description>
        <inlineHelpText>field to capture comments at the item of customer needs selection.</inlineHelpText>
        <label>Additional Comments</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Original_Decision_Maker__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Original Decision Maker</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <filterItems>
                <field>Contact.STATUS_ACTIVE__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>The Contact you are adding as an Original Decision Maker must be an active Contact within the same Account where you are creating the new Opportunity.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <recordTypes>
        <fullName>UVS</fullName>
        <active>true</active>
        <description>Record Type for UVS Vehicles</description>
        <label>UVS</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/UVS_OLIRelatedListTest.cls
/*************************************************************************************************
Created By:     Nimisha Prashant
Date:           September 22, 2014
Description  :  Test Class for UVS_OLIRelatedList Controller Class

**************************************************************************************************/
@isTest(seeAllData = true)
private class UVS_OLIRelatedListTest {
  static User uvsUser;
  static Account acc;
  static Opportunity opp;
  static List<Vehicle__c> vehList;
  static testMethod void myUnitTest() {
    uvsUser = TestUtilUVS.createUser(true);
    system.runAs(uvsUser) {

	test.starttest();
    acc = TestUtilUVS.createAccount('Vendor', 'FMS', true);

	  Contact newCon = TestUtilUVS.createContact(acc.Id,false);
      newCon.Additional_Comments__c = 'Test1';
      newCon.Email = 'test2@rydertest.com';
      newCon.OwnerId = UserInfo.getUserId();
      insert newCon;

      opp = TestUtilUVS.createOpportunity('UVS Opportunity', acc, false, newCon);
      opp.Original_Decision_Maker__c = newCon.Id;

      insert opp;

      //List<Vehicle__c> vehicleList = TestUtilUVS.createVehList(true);

      //List<OpportunityLineItem> oppLIList = TestUtilUVS.createOpportunityLineItemList(acc, vehicleList, true);
		test.stoptest();
      ApexPages.StandardController sc = new ApexPages.StandardController(opp);
      UVS_OLIRelatedList controller = new UVS_OLIRelatedList(sc);
      //controller.deleteRecordId = oppLIList.get(0).Id;
      controller.deleteRecord();

      System.assertEquals(0,[Select Id from OpportunityLineItem where OpportunityId = :opp.Id].size());
    }
  }
}