SFDC Automation/src/objects/BTR__c.object
<CustomObject>
    <description>Linked to the quote object as 1:1 relationship and used to drive the approval process for the quotes</description>
    <fields>
        <fullName>Is_Conditional_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Conditional Approval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The quote record to which this BTR approval process is linked to.</description>
        <inlineHelpText>The quote record to which this BTR approval process is linked to.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>BTRs</relationshipLabel>
        <relationshipName>BTRs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the BTR approval process for a given quote.</description>
        <inlineHelpText>The status of the BTR approval process for a given quote.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Submitted - With FAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted - With DAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted - With VP AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BTR</label>
    <nameField>
        <displayFormat>BTR-{0000000}</displayFormat>
        <label>BTR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BTRs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Quote.object
<CustomObject>
    <recordTypes>
        <fullName>UVS</fullName>
        <active>true</active>
        <description>Used vehicle Sales</description>
        <label>UVS</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/classes/BTRViewControllerTest.cls
/*************************************************************************************************
Created By:    Jyotirmaya.Rath
Date:          October 14, 2014
Description  : Test class for BTRViewController class
**************************************************************************************************/
@isTest(seeAllData = true)
private class BTRViewControllerTest {
    static User uvsUser;
    Static BTRViewController BTRView ;
    Static Quote NewQuote ;
    Static list< BTR__C> BTRList;
     static testMethod void testBTRViewControllerAsVSR() {
       //Creating the VSR user
        uvsUser = TestUtilUVS.createUser(true);
        System.runAs(uvsUser ){
             InsertBTR()   ;
            BTRView = new  BTRViewController ();
            System.assert(BTRView.getItems() != null);
            BTRView.selectView();
        }
     }
      // FAM User
    static testMethod void TestBTRViewControllerAsFAM() {
         uvsUser = TestUtilUVS.createUser(true);
         Profile fAMProfile = [select p.id from Profile p where p.Name in ('FAM') LIMIT 1];
        uvsUser.profileid = FamProfile .id;
        update uvsUser ;


        System.runAs(uvsUser ){


            BTRView = new  BTRViewController ();
            InsertBTR();
            //System.assert(BTRView.isApprovers);
            BTRView.currentUserType = 'FAM';
            Test.startTest();
            BTRView.selectView();
            System.assert(BTRView.getItems() != null);
            BTRView.currentUserType = 'DAM';
            System.assert(BTRView.getItems() != null);

            BTRView.selectView();
            BTRView.currentUserType = 'VP';
            System.assert(BTRView.getItems() != null);

            BTRView.selectView();
            Test.stopTest();
        }
     }
     // ADmin User
     static testMethod void TestBTRViewControllerAsAdmin() {
        uvsUser = TestUtilUVS.createUser(true);
        Profile AdminProfile = [select p.id from Profile p where p.Name in ('System Administrator') LIMIT 1];
        uvsUser.profileid = AdminProfile .id;
        update uvsUser ;

        System.runAs(uvsUser ){
            Test.startTest();
            BTRView = new  BTRViewController ();
            InsertBTR();
        //  System.assert(BTRView.isApprovers);
            BTRView.selectView();
            Test.stopTest();
        }
     }
     private static Void InsertBTR(){
         NewQuote = TestUtilUVS.createQuote( 'UVS', True);
        BTRList = new List<BTR__c>();
        BTRList.add(new BTR__c(Is_Conditional_Approval__c = false,Quote__c =NewQuote.id,Status__c = 'Submitted - With FAM')) ;
        BTRList.add( new BTR__c(Is_Conditional_Approval__c = false,Quote__c =NewQuote.id,Status__c = 'Submitted - With DAM'));
        BTRList.add(new BTR__c(Is_Conditional_Approval__c = false,Quote__c =NewQuote.id,Status__c = 'Submitted - With VP AM'));

        Insert BTRList;
     }
}