SFDC Automation/src/objects/BTR__c.object
<CustomObject>
    <description>Linked to the quote object as 1:1 relationship and used to drive the approval process for the quotes</description>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <formula>Quote__r.Opportunity.Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Conditional_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Conditional Approval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The quote record to which this BTR approval process is linked to.</description>
        <inlineHelpText>The quote record to which this BTR approval process is linked to.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>BTRs</relationshipLabel>
        <relationshipName>BTRs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requester_Comments__c</fullName>
        <label>BTR Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Ryder_Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is a lookup to Ryder Branch object.</description>
        <inlineHelpText>Points to the branch of the user who created the BTR.</inlineHelpText>
        <label>Ryder Branch</label>
        <referenceTo>Ryder_Branch__c</referenceTo>
        <relationshipLabel>BTRs</relationshipLabel>
        <relationshipName>BTRs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the BTR approval process for a given quote.</description>
        <inlineHelpText>The status of the BTR approval process for a given quote.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Submitted - With FAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted - With DAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted - With VP AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BTR</label>
    <nameField>
        <displayFormat>BTR-{0000000}</displayFormat>
        <label>BTR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BTRs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/BTR_History__c.object
<CustomObject>
    <fields>
        <fullName>Approved_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Approved Price</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BTR_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BTR Number</label>
        <referenceTo>BTR__c</referenceTo>
        <relationshipLabel>BTR Histories</relationshipLabel>
        <relationshipName>BTR_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BTR_Status__c</fullName>
        <label>BTR Status</label>
        <picklist>
            <picklistValues>
                <fullName>Submitted - With FAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted - With DAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted - With VP AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <description>Name of the customer</description>
        <label>Customer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Conditional_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the BTR is approved conditionally.</description>
        <label>Is Conditional Approval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Offer_Price_Sale_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Offer Price/Sale Price</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quote_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Number</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>BTR Histories</relationshipLabel>
        <relationshipName>BTR_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Date__c</fullName>
        <label>Request Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Requester_Comments__c</fullName>
        <label>BTR Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Requestor__c</fullName>
        <label>Requestor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UTC__c</fullName>
        <label>UTC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle_Number__c</fullName>
        <label>Vehicle Number</label>
        <length>124</length>
        <type>Text</type>
    </fields>
    <label>BTR History</label>
    <nameField>
        <label>BTR History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BTR Histories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Requester_Comments__c</fullName>
        <label>BTR Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>UTC__c</fullName>
        <formula>$User.UTC__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UTC</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Approved_Price__c</fullName>
        <label>Approved Price</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Customer_Offer_Price__c</fullName>
        <label>Customer Offer Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Ryder_Branch__c.object
<CustomObject>
    <description>Branches at Ryder</description>
    <label>Ryder Branch</label>
    <nameField>
        <label>Ryder Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ryder Branches</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>UTC__c</fullName>
        <description>This field will capture the location code for the user.</description>
        <label>UTC</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <fields>
        <fullName>Approved_Price__c</fullName>
        <label>Approved Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/BTRVehicleHistoryController.cls
/**=====================================================================
 * Appirio, Inc
 * Name: BTR_List
 * Description: T-324750: Create New VF Page to Display Previous BTR List for a Given Vehicle
 * Created Date: 08/10/2014
 * Created By: [Rahul Agrawal] (Appirio)
 *
 * Date Modified                Modified By                  Description of the update
 * [MON DD, YYYY]               [FirstName LastName]         [Short description for changes]
 =====================================================================*/
public with sharing class BTRVehicleHistoryController{
  // Public Valriables
  public string vehNumber {get;set;}
  public string btrId{get;set;}
  public List<BTRWrapper> wrapperList {get;set;}

  // HK (02/24/2015): The 'showBackToBTR' variable will control whether to show the 'Back to BTR' button or now.
  public boolean showBackToBTR { get; set; }
  
  // Constructor
  public BTRVehicleHistoryController(){
    vehNumber = ApexPages.currentPage().getParameters().get('vehNumber');
    btrId = ApexPages.currentPage().getParameters().get('BTRId');
    // HK (02/24/2015): if btrid is null, then the user is accessing the vehicle history directly from the tab, instead from 'Prev BTR'; hence no need to show the 'Back to BTR button.
    if(btrId != null)
        showBackToBTR = true;
    else
        showBackToBTR = false;
    
    populateBTRList();
  }
  
  // Method to fetch list of BTR History based on vehicle number.
  public void populateBTRList(){
    if(vehNumber != null){
      wrapperList = new List<BTRWrapper>();
      
      // Fetch records from BTR History to display historical data.
      List<BTR_History__c> lstBTRList = [SELECT Id, Customer_Name__c,Requestor__c,Request_Date__c,UTC__c, BTR_Status__c,Approved_Price__c, 
                    Offer_Price_Sale_Price__c, BTR_Number__c, BTR_Number__r.Name, Quote_Number__c
                    FROM BTR_History__c
                    WHERE Vehicle_Number__c = :vehNumber];
      
      
      for(BTR_History__c obj :lstBTRList){
        BTRWrapper objWrapper = new BTRWrapper();
        objWrapper.btrId = obj.BTR_Number__c;
        objWrapper.btrNumber = obj.BTR_Number__r.Name;
        objWrapper.customerName = obj.Customer_Name__c;
        objWrapper.requestor = obj.Requestor__c;
        objWrapper.requestDate = obj.Request_Date__c.format('MM/dd/yyyy');
        objWrapper.utc = obj.Utc__c;
        objWrapper.status = 'Approved';
        objWrapper.offerPrice = obj.Offer_Price_Sale_Price__c;
        objWrapper.approvedPrice = obj.Approved_Price__c;
        wrapperList.add(objWrapper);
      }
      
      // Fetch records from Quote Line Item History for current BTR's
      Map<Id, List<QuoteLineItem>> mapQuoteLineItems = new Map<Id, List<QuoteLineItem>>();
      BTRVehicleHistoryInnerClass ObjInnerClass = new BTRVehicleHistoryInnerClass();
      for(QuoteLineItem qli : ObjInnerClass.QueryQuoteLineItem(vehNumber))
      {
        if(mapQuoteLineItems.containsKey(qli.QuoteId) == false){
            mapQuoteLineItems.put(qli.QuoteId, new List<QuoteLineItem>());
        }
        mapQuoteLineItems.get(qli.QuoteId).add(qli);    
      }
      System.debug('@@@' + mapQuoteLineItems);
      
      // Find related Quote's BTR's from above result and display information from both BTR and QLI.
      List<BTR__c> lstBTR = [SELECT Ryder_Branch__r.Name, Owner.Name, CreatedDate, Status__c, Requester_Comments__c, Quote__c, OwnerId, Name, LastModifiedDate, LastModifiedById, 
                             Is_Conditional_Approval__c, Id, Customer_Name__c 
                             FROM BTR__c b WHERE Quote__c = :mapQuoteLineItems.keySet()
                             AND Status__c != 'Approved'];
      
      System.debug('@@@' + lstBTR);
      for(BTR__c objBTR :lstBTR){
        for(QuoteLineItem qli :mapQuoteLineItems.get(objBTR.Quote__c)){
          BTRWrapper objWrapper = new BTRWrapper();
          objWrapper.btrId = objBTR.Id;
          objWrapper.btrNumber = objBTR.Name;
          objWrapper.approvedPrice = qli.Approved_Price__c;
          objWrapper.offerPrice = qli.Customer_Offer_Price__c;
          objWrapper.utc = objBTR.Ryder_Branch__r.Name;
          objWrapper.status = objBTR.Status__c;
          objWrapper.requestDate = objBTR.CreatedDate.format('MM/dd/yyyy');
          objWrapper.requestor = objBTR.Owner.Name;
          objWrapper.customerName = qli.Quote.Opportunity.Account.Name;
          wrapperList.add(objWrapper);
        }
      }
      System.debug('@@@' + wrapperList);
      
      if(wrapperList.size() == 0){
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'No BTR Record is found.'));
      }
    }
  }

  // Method to initiate search for BTR history record based on vehicle number entered by User and clicked on Go button
  public void searchBTRList(){
    populateBTRList();
  }
  
  // Wrapper class for displaying final results on UI
  public class BTRWrapper{
    public String btrNumber {get; set;}
    public String customerName {get;set;}
    public String requestor {get;set;}
    public String requestDate {get;set;}
    public String utc {get;set;}
    public String status {get;set;}
    public Id btrId {get;set;}
    public Decimal offerPrice{get;set;} 
    public Decimal approvedPrice{get;set;}
  }
  public without sharing class BTRVehicleHistoryInnerClass
  {
		public List<QuoteLineItem> QueryQuoteLineItem(String vehNumber)
		{
			List<QuoteLineItem> lQuoteLineItem = [SELECT Id, QuoteId, Quote.Opportunity.Account.Name, 
													Customer_Offer_Price__c, Approved_Price__c 
													FROM QuoteLineItem WHERE Vehicle__r.Name = :vehNumber];
			return lQuoteLineItem;
		}
  }
}