SFDC Automation/src/objects/BTR__c.object
<CustomObject>
    <description>Linked to the quote object as 1:1 relationship and used to drive the approval process for the quotes</description>
    <fields>
        <fullName>Is_Conditional_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Conditional Approval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The quote record to which this BTR approval process is linked to.</description>
        <inlineHelpText>The quote record to which this BTR approval process is linked to.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>Quote</referenceTo>
        <relationshipLabel>BTRs</relationshipLabel>
        <relationshipName>BTRs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the BTR approval process for a given quote.</description>
        <inlineHelpText>The status of the BTR approval process for a given quote.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Submitted - With FAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted - With DAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted - With VP AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>BTR</label>
    <nameField>
        <displayFormat>BTR-{0000000}</displayFormat>
        <label>BTR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BTRs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Quote.object
<CustomObject>
    <recordTypes>
        <fullName>UVS</fullName>
        <active>true</active>
        <description>Used vehicle Sales</description>
        <label>UVS</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Interest_Rate__c</fullName>
        <label>Interest Rate</label>
        <picklist>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5.5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Take_Price2__c</fullName>
        <label>Take Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <label>Term</label>
        <picklist>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>36</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>42</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>48</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>54</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <recordTypes>
        <fullName>UVS</fullName>
        <active>true</active>
        <description>Record Type for UVS Vehicles</description>
        <label>UVS</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/BTRTriggerHandlerTest.cls
/**=====================================================================
 * Appirio, Inc
 * Name: BTRTriggerHandlerTest
 * Created Date: 10-15-2014
 * Created By: Jyotirmaya Rath
 =====================================================================*/
 @isTest(seeAllData = true)
private class BTRTriggerHandlerTest{

    Static BTR__c BTR ;
    static User uvsUser;
    Static Quote NewQuote = new Quote();
    static testMethod void testBTRTriggerHandler() {
        uvsUser = TestUtilUVS.createAdminUser(true);
        system.runAs(uvsUser) {
        	Test.startTest();
            // Insert New Quote
            NewQuote = TestUtilUVS.createQuote( 'UVS', True);
            // New QLI
            Product2 prod = new Product2();
            prod.Name = 'Standard Price Book UVS';
            prod.CurrencyIsoCode = 'USD';
            insert prod;
            PriceBookEntry pbe = [SELECT Id,Pricebook2Id
                                    FROM PriceBookEntry
                                    WHERE Product2Id = :prod.Id
                                    LIMIT 1];
            pbe.isActive = true;
            update pbe;
            NewQuote.Pricebook2Id = pbe.Pricebook2Id;
            Update NewQuote ;
            List<Vehicle__c> veh = TestUtilUVS.createVehList(true);

            list<QuoteLineItem> lstQuoteLineItem = new List <QuoteLineItem>();
            lstQuoteLineItem.add(new QuoteLineItem( Quantity = 1 ,PriceBookEntryId = pbe.Id, UnitPrice = 21951.0 , Vehicle__c = veh[0].Id,
                                                    QuoteId = newQuote.id,
                                                    Take_Price2__c = 18951 ,
                                                    Interest_Rate__c = '12',
													Term__c = '12'
                                                    ));


            if(lstQuoteLineItem <> NULL){
              insert lstQuoteLineItem;
            }
          //  NewQuote =
          	Test.stopTest();

			//Test.startTest();
            BTR = new BTR__c();
            BTR.Is_Conditional_Approval__c = false ;
            BTR.Quote__c = NewQuote.id;
            BTR.Status__c = 'Submitted - With VP AM';
            Insert BTR;

            BTR = [select Status__c from BTR__c where id = : BTR.id];
            BTR.Status__c = 'Approved';
            Update BTR;
			//Test.stopTest();

            Quote UpdatedQuote = [select id,status from Quote where id =: newQuote.id];
            System.assertequals( UpdatedQuote.status,'BTR Approved');



         }
    }

}