SFDC Automation/src/objects/BTR_History__c.object
<CustomObject>
    <fields>
        <fullName>Approved_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Approved Price</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Approved_to_take__c</fullName>
        <label>Approved % to take</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>As_Is_Vehicle__c</fullName>
        <defaultValue>false</defaultValue>
        <label>As Is Vehicle</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Book_Value__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Book Value</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Days_At_UTC__c</fullName>
        <label>Days At UTC</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Engine_Make_Model__c</fullName>
        <label>Engine Make/Model</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gain_Loss__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Gain (Loss)</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Make_Model__c</fullName>
        <label>Make Model</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mileage__c</fullName>
        <label>Mileage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NVI_Percent__c</fullName>
        <label>NVI(%)</label>
        <precision>17</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Offer_Price_Sale_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Offer Price/Sale Price</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SAM_Class__c</fullName>
        <label>SAM Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Take_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Take Price</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Take_Price_percent__c</fullName>
        <label>Take Price (%)</label>
        <precision>17</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>UTC__c</fullName>
        <label>UTC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VOSA__c</fullName>
        <defaultValue>false</defaultValue>
        <label>VOSA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vehicle_Number__c</fullName>
        <label>Vehicle Number</label>
        <length>124</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <description>This field holds the model year (this is defined as text to suppress the &apos;,&apos; in the UI).</description>
        <label>Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>BTR History</label>
    <nameField>
        <label>BTR History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BTR Histories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>UTC__c</fullName>
        <formula>$User.UTC__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UTC</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Approved_Price__c</fullName>
        <label>Approved Price</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Approved_to_take__c</fullName>
        <formula>Approved_Price__c/Take_Price2__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Approved % to take</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>As_Is_Vehicle__c</fullName>
        <description>Vehicle&apos;s AsIs field value</description>
        <formula>Vehicle__r.AS_IS_Vehicle__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>As Is Vehicle</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Book_Value__c</fullName>
        <formula>Vehicle__r.NBV__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Book Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gain_Loss__c</fullName>
        <formula>UnitPrice - Book_Value__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Gain (Loss)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Make_Model__c</fullName>
        <description>Concatenation of Vehicle.Manufacturer__c and Vehicle.Model__c</description>
        <formula>Vehicle__r.Manufacturer__c &amp; &apos; &apos; &amp; Vehicle__r.Model__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Make/Model</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NVI_Percent__c</fullName>
        <description>NVI Percentage</description>
        <formula>(UnitPrice* 10000) / Vehicle__r.NVI__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NVI %</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>SAM_Class__c</fullName>
        <formula>Vehicle__r.SAM_CLASS__c &amp; &apos; &apos; &amp; Vehicle__r.VEH_CLS_SAM_DS__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SAM Class</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Take_Price_percent__c</fullName>
        <formula>UnitPrice/Take_Price2__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Take Price (%)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vosa__c</fullName>
        <formula>Vehicle__r.VOSA__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vosa</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/QuoteLineItemHistory__c.object
<CustomObject>
    <fields>
        <fullName>BTR_History__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BTR History</label>
        <referenceTo>BTR_History__c</referenceTo>
        <relationshipLabel>QuoteLineItemHistorys</relationshipLabel>
        <relationshipName>QuoteLineItemHistorys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Line Item</label>
        <referenceTo>QuoteLineItem</referenceTo>
        <relationshipLabel>Quote Line Item History</relationshipLabel>
        <relationshipName>QuoteLineItemHistorys</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>QuoteLineItemHistory</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>QuoteLineItemHistory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QuoteLineItemHistorys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <fields>
        <fullName>AS_IS_Vehicle__c</fullName>
        <defaultValue>false</defaultValue>
        <label>AS IS Vehicle</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Approved_Price__c</fullName>
        <label>Approved Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Days_At_UTC__c</fullName>
        <label>Days At UTC</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Gain_Loss__c</fullName>
        <label>Gain Loss</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SAM_CLASS__c</fullName>
        <description>Sam Class</description>
        <label>SAM Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Take_Price_Percent__c</fullName>
        <formula>IF(Ask_Price__c &gt; 0, Take_Price__c / Ask_Price__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Take Price (%)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Take_Price__c</fullName>
        <label>Take Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>VOSA__c</fullName>
        <defaultValue>false</defaultValue>
        <label>VOSA</label>
        <type>Checkbox</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/BTRCustomerHistoryController.cls
/**=====================================================================
 * Appirio, Inc
 * Name: BTR_List
 * Description: T-324750: Create New VF Page to Display Specific Previous BTR for Customer Name
 * Created Date: 09/10/2014
 * Created By: [Rahul Aeran] (Appirio)
 *
 * Date Modified                Modified By                  Description of the update
 * [MON DD, YYYY]               [FirstName LastName]         [Short description for changes]
 =====================================================================*/
public without sharing class BTRCustomerHistoryController{

    // Public Valriables
    public string vehNumber {get;set;}
    public string customerName {get;set;}
    public string btrId {get;set;}
    public List<QuoteLineItemHistory__c> quoteLIHistoryList{get;set;}
    public list<BTR_History__c> lstBTRList {get;set;}

    // Constructor
    public BTRCustomerHistoryController(){
        vehNumber = ApexPages.currentPage().getParameters().get('vehNumber');
        customerName  = ApexPages.currentPage().getParameters().get('customerName');
        btrId = ApexPages.currentPage().getParameters().get('btrId');
        populateBTRList();
    }

   // Method to fetch list of BTR History based on vehicle number.
    public void populateBTRList(){
        if(vehNumber != null){
            
            lstBTRList = [SELECT Vehicle_Number__c,SAM_Class__c,Year__c,Make_Model__c,Location__c,Days_At_UTC__c,Engine_Make_Model__c,Mileage__c,NVI_Percent__c
                                        ,Book_Value__c,Take_Price__c,Offer_Price_Sale_Price__c,Take_Price_percent__c,Gain_Loss__c,As_Is_Vehicle__c,
                                        VOSA__c,Approved_Price__c,Approved_to_take__c, UTC__c 
                                        FROM BTR_History__c
                                        WHERE Vehicle_Number__c = :vehNumber];
            // Get Quote Line Items Record based on vehicle
            Set<Id> quoteLineItemIds = new Set<Id>();
            for(QuoteLineItem qli :[Select Id
                        From QuoteLineItem
                        where Vehicle__r.Name = :vehNumber ]){
                quoteLineItemIds.add(qli.Id);
            }
            quoteLIHistoryList = [SELECT Name,LastModifiedDate,LastModifiedBy.Name
                                    FROM QuoteLineItemHistory__c
                                    WHERE Quote_Line_Item__c IN: quoteLineItemIds];
           
           
        }else{
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Invalid Vehicle Number.'));
        }
    }

    

   
}