SFDC Automation/src/objects/BTR_Stats__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Current_Inventory__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Current Inventory</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Make__c</fullName>
        <label>Make</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mileage_Tier__c</fullName>
        <label>Mileage Tier</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAM_Class__c</fullName>
        <label>SAM Class</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Proceeds__c</fullName>
        <label>Sales Proceeds</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Selling_Age__c</fullName>
        <label>Selling Age</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Unit Count</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>BTR Stats</label>
    <nameField>
        <displayFormat>BTRS-{00000000}</displayFormat>
        <label>BTR Stats Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BTR Stats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Customer_Branch__c.object
<CustomObject>
    <description>Customer Branches at Ryder</description>
    <fields>
        <fullName>Ryder_Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field for Customer Branch to Ryder branch</description>
        <label>Ryder Branch</label>
        <referenceTo>Ryder_Branch__c</referenceTo>
        <relationshipLabel>Customer / Branch</relationshipLabel>
        <relationshipName>Customer_Branches</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Customer / Branch</label>
    <nameField>
        <label>Customer Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer / Branch</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Ryder_Branch__c.object
<CustomObject>
    <description>Branches at Ryder</description>
    <fields>
        <fullName>Country_Name__c</fullName>
        <label>Country</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Ryder Branch</label>
    <nameField>
        <label>Ryder Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ryder Branches</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <fields>
        <fullName>CUSTOMER_BRANCH__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field for Customer Branch</description>
        <label>Customer Branch</label>
        <referenceTo>Customer_Branch__c</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Days_At_UTC__c</fullName>
        <label>Days At UTC</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Model_Year__c</fullName>
        <description>Year of the vehicle</description>
        <label>Model Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAM_CLASS__c</fullName>
        <description>Sam Class</description>
        <label>SAM Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/objects/VehicleSearchSetting__c.object
<CustomObject>
    <description>This object will host the pick list values used in the Vehicle Master Inventory Search page. This is a dummy object and no records should be created on this object. The Master Inventory Search page will use the Describe calls to load the pick list values from this object. &apos;Custom Object&apos; is used to store the pick list values instead of &apos;Custom Setting&apos; as there 20+ fields are pick lists in the Master Inventory Search and it is more convenient to house all of them in a custom object than creating 20+ custom settings.</description>
    <fields>
        <fullName>Days_at_UTC__c</fullName>
        <label>Days at UTC</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Year__c</fullName>
        <label>Model Year</label>
        <picklist>
            <picklistValues>
                <fullName>1987</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1989</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1990</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1992</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1995</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1996</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1997</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1998</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1999</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2001</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2002</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2003</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2004</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2005</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2006</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2007</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2008</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2009</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2010</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2011</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2012</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2013</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <picklist>
            <picklistValues>
                <fullName>a</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SAM_Tractor__c</fullName>
        <label>SAM Tractor</label>
        <picklist>
            <picklistValues>
                <fullName>130</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>131</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>132</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>140</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>141</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>150</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>170</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SAM_Trailer__c</fullName>
        <label>SAM Trailer</label>
        <picklist>
            <picklistValues>
                <fullName>180</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>181</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>190</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>200</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>210</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>211</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>220</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>230</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SAM_Truck__c</fullName>
        <label>SAM Truck</label>
        <picklist>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>100</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>110</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>120</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>121</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>122</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>31</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>51</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>61</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>81</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>90</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Vehicle Search Setting</label>
    <nameField>
        <label>VehicleSearchSettingName</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicle Search Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC Automation/src/classes/UVS_VehicleStatsController.cls
/***********************************************************************
 Class          : UVS_VehicleStatsController
 Author         : Manisha Gupta
 Descritption   : Controller class for Vehicle Stats Page on BTR Screen

 Date       Modified By         Description

 ************************************************************************/
public class UVS_VehicleStatsController {
  public String sellingAge{get;set;}
  public String country{get;set;}
  public Vehicle__c vehicle{get;set;}
  public list<SelectOption> sellingAgeList{get;set;}
  public List<SelectOption> countryList{get;set;}
  public List<CurrentInventory> currentInventoryList{get;set;}
  public List<SoldInventory> soldInventoryList{get;set;}
  public String btrId{get;set;}
  public String samClass{get;set;}

  public List<SelectOption> getListSAMClass() {
  	// create sam class picklist
    List<SelectOption> options = new List<SelectOption>();
    Schema.DescribeFieldResult fieldResult = VehicleSearchSetting__c.SAM_Truck__c.getDescribe();
    List<Schema.PicklistEntry> listPicklistEntry = fieldResult.getPicklistValues();
    for(Schema.PicklistEntry f : listPicklistEntry){
        options.add(new SelectOption(f.getLabel(), f.getValue()));
    }
    fieldResult = VehicleSearchSetting__c.SAM_Trailer__c.getDescribe();
    listPicklistEntry = fieldResult.getPicklistValues();
    for(Schema.PicklistEntry f : listPicklistEntry){
        options.add(new SelectOption(f.getLabel(), f.getValue()));
    }
    fieldResult = VehicleSearchSetting__c.SAM_Tractor__c.getDescribe();
    listPicklistEntry = fieldResult.getPicklistValues();
    for(Schema.PicklistEntry f : listPicklistEntry){
        options.add(new SelectOption(f.getLabel(), f.getValue()));
    }
    return options;
  }

  public UVS_VehicleStatsController(){
  	btrId = ApexPages.CurrentPage().getParameters().get('BTRId');
  	// get vehicle details and populate country, sam class and selling age
    for(Vehicle__c veh : [Select Sam_Class__c, Days_At_UTC__c, Customer_Branch__r.Ryder_Branch__r.Country_Name__c, Model_Year__c
               from Vehicle__c
               where Id = :ApexPages.currentPage().getParameters().get('Id')]){
      vehicle = veh;
    }
    if(vehicle <> null){
    	country = vehicle.Customer_Branch__c <> null && vehicle.Customer_Branch__r.Ryder_Branch__c <> null ?
    	             vehicle.Customer_Branch__r.Ryder_Branch__r.Country_Name__c : '';
	    samClass = vehicle.SAM_Class__c <> null ? vehicle.SAM_Class__c.split('-')[0].trim(): null;

	    if(vehicle.Days_At_UTC__c == null){
	      sellingAge = '0';
	    }
	    if(vehicle.Days_At_UTC__c <= 180){
	        sellingAge = '1';
	    }else if(vehicle.Days_At_UTC__c >= 181 && vehicle.Days_At_UTC__c <= 390){
	      sellingAge = '2';
	    }else{
	        sellingAge = '3';
	    }
    }


    // create selling age picklist
    sellingAgeList = new List<SelectOption>();
    sellingAgeList.add(new SelectOption('0', '--None--'));
    sellingAgeList.add(new SelectOption('1', '0 - 180 days'));
    sellingAgeList.add(new SelectOption('2', '181 - 390 days'));
    sellingAgeList.add(new SelectOption('3', '391 - older'));

    // create country picklist
    countryList = new List<SelectOption>();
    countryList.add(new SelectOption('CA', 'CA'));
    countryList.add(new SelectOption('US', 'US'));
    searchVehicles();

  }

  // method to search vehicles
  public Pagereference searchVehicles(){
    // query for current inventory
    String query = 'Select Make__c, Model__c, Sum(Unit_Count__c) UnitCount '+
                   ' from BTR_Stats__c ' +
                   ' Where Sam_Class__c Like \'' + samClass + '%\'' +
                   ' and Year__c = \'' + String.valueOf(vehicle.Model_Year__c) +'\''+
                   ' and Country__c = \'' + country + '\'' +
                   ' and Is_Current_Inventory__c = true ' +
                   ' group by Make__c, Model__c ';
    system.debug('==========QUERY===========' + query);
    currentInventoryList = new List<CurrentInventory>();
    for(AggregateResult agg : database.query(query)){
      currentInventoryList.add(new CurrentInventory((String)agg.get('Make__c'), (String)agg.get('Model__c'), Integer.valueOf(agg.get('UnitCount'))));
    }

    // get sold inventory
    soldInventoryList = new List<SoldInventory>();
    String samClassQueryString = samClass + '%';
    String soldInvQuery = 'Select Sum(Unit_Count__c) unitCount, Sum(Sales_Proceeds__c) salesProceeds, Make__c, Model__c, Mileage_Tier__c '+
                          'from BTR_Stats__c '+
                          'where SAM_Class__c Like :samClassQueryString '+
                          ' and Country__c = :country '+
                          ' and Year__c = \'' + String.valueOf(vehicle.Model_Year__c) + '\'' +
                          ' and Is_Current_Inventory__c = false '+
                          ' and selling_Age__c != null and Selling_Age__c = ' + Integer.valueOf(sellingAge) +
                          ' group by Make__c, Model__c, Mileage_Tier__c ' ;

    for(AggregateResult soldInv : database.query(soldInvQuery)){
      soldInventoryList.add(new SoldInventory((String)soldInv.get('Make__c'),
                                               (String)soldInv.get('Model__c'),
                                               (String)soldInv.get('Mileage_Tier__c'),
                                               Integer.valueOf(soldInv.get('salesProceeds')),
                                               Integer.valueOf(soldInv.get('unitCount'))));
    }

    return null;
  }

  // class to hold current inventory details
  public class CurrentInventory{
    public String make{get;set;}
    public String model{get;set;}
    public Integer unitCount{get;set;}

    public CurrentInventory(String make, String model, Integer unitCount){
        this.make = make;
        this.model = model;
        this.unitCount = unitCount;
    }
  }

  // class to hold sold inventory details
  public class SoldInventory{
    public String make{get;set;}
    public String model{get;set;}
    public String mileageTier{get;set;}
    public Integer salesProceeds{get;set;}
    public Integer unitCount{get;set;}

    public SoldInventory(String make, String model, String mileageTier, Integer salesProceeds, Integer unitCount){
        this.make = make;
        this.model = model;
        this.mileageTier = mileageTier;
        this.salesProceeds = salesProceeds;
        this.unitCount = unitCount;

    }

  }

}