SFDC Automation/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Ryder_Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ryder Branch</label>
        <referenceTo>Ryder_Branch__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Ryder_Branch__c.object
<CustomObject>
    <description>Branches at Ryder</description>
    <fields>
        <fullName>Branch_Code__c</fullName>
        <description>external ID</description>
        <externalId>true</externalId>
        <label>Branch Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Ryder Branch</label>
    <nameField>
        <label>Ryder Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ryder Branches</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>UTC__c</fullName>
        <description>This field will capture the location code for the user.</description>
        <label>UTC</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/UserTriggerHandlerTest.cls
/**=====================================================================
 * Appirio, Inc
 * Name: UserTriggerHandlerTest
 * Created Date: 01-12-2015
 * Created By: Hari Krishnan
 =====================================================================*/
@isTest
public class UserTriggerHandlerTest {
 
     // positive test case 1:
    static testMethod void whenUserCreatedWithValidUTCCode_CreatesUser() {
        Ryder_Branch__c ryderBranch = TestUtilUVS.createRyderBranch();
        User u = TestUtilUVS.createUser(false);
        u.UTC__c = ryderBranch.Branch_Code__c;
        insert u;
        System.assertEquals(u.UTC__c, ryderBranch.Branch_Code__c);
    }
    
    // positive test case 2:
    static testMethod void whenUserUpdatedWithValidUTCCode_UpdatesUser() {
        Ryder_Branch__c ryderBranch = TestUtilUVS.createRyderBranch();
        User u = TestUtilUVS.createUser(true);
        u.UTC__c = ryderBranch.Branch_Code__c;
        update u;
        System.assertEquals(u.UTC__c, ryderBranch.Branch_Code__c);
        
    }
    
    // negative test case 1:
    static testMethod void whenUserCreatedWithInvalidUTCode_ThrowsError() {
        String errorCode= 'FIELD_CUSTOM_VALIDATION_EXCEPTION';
        User u = TestUtilUVS.createUser(false);
        u.UTC__c = 'abcde';
        try {
            insert u;
        }
        catch(DmlException dmle) {
            System.assertEquals(errorCode, dmle.getDmlStatusCode(0));
        }
    }
    
    // negative test case 2:
    static testMethod void whenUserUpdatedWithInvalidUTCode_ThrowsError() {
        String errorCode = 'FIELD_CUSTOM_VALIDATION_EXCEPTION';
        User u = TestUtilUVS.createUser(true);
        u.UTC__c = 'abcde';
        try {
            update u;
        }
        catch(DmlException ex) {
            System.assertEquals(errorCode, ex.getDmlStatusCode(0));
        }
    }
}