SFDC Automation/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Address_Verified__c</fullName>
        <label>Address Verified?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Caller_Type__c</fullName>
        <label>Caller Type</label>
        <picklist>
            <picklistValues>
                <fullName>Internal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Use to search for an Existing Contact.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email_Address_Verified__c</fullName>
        <label>Email Address Verified?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Ryder_CSC_Surveys__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Ryder CSC Surveys</relationshipLabel>
        <relationshipName>Ryder_CSC_Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Ryder CSC Surveys</relationshipLabel>
        <relationshipName>Ryder_CSC_Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Feedback_about_the_agent__c</fullName>
        <description>used by pilot survey</description>
        <label>Feedback about the agent</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>How_satisfied_are_you_with_the_agent__c</fullName>
        <description>used by pilot survey</description>
        <label>How satisfied are you with the agent?</label>
        <picklist>
            <picklistValues>
                <fullName>Satisfied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dissatisfied</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Likelihood_of_calling_again__c</fullName>
        <description>Used by Pilot survey</description>
        <label>Likelihood of calling again</label>
        <picklist>
            <picklistValues>
                <fullName>Likely</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Likely</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Was_your_call_resolved__c</fullName>
        <label>Was your call resolved?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Was_your_issue_addressed__c</fullName>
        <description>used by pilot survey</description>
        <label>Was your issue addressed?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Ryder CSC Survey</label>
    <nameField>
        <displayFormat>RCSCS-{00000}-{mmddyy}</displayFormat>
        <label>Ryder CSC Survey Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ryder CSC Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC Automation/src/classes/Test_insertUpdateRyderCSCSurveys.cls
@isTest
private class Test_insertUpdateRyderCSCSurveys {

    static testMethod void Test_insertUpdateRyderCSCSurvey() {
        // set test data
        // create parent account
        RecordType rCase = [Select r.SobjectType, r.Name, r.DeveloperName, r.IsActive, r.Id From RecordType r where r.SobjectType='Case' and  r.Name='Sales Pilot'];
        RecordType rSurvey = [Select r.SobjectType, r.Name, r.DeveloperName, r.IsActive, r.Id From RecordType r where r.SobjectType='Ryder_CSC_Surveys__c' and  r.Name='Pilot Survey'];
        
		Account parentAcct = TestUtil.createAccount('Ryder FMS Parent Account', 'Customer');
        insert parentAcct;
        
        Contact con = TestUtil.createContact(parentAcct.Id);
         insert con;
         // neelima-03/13/2012-case insert test is not there. so including case insert in the test for coverage of insert case trigger too.
          Test.startTest();
         
         Case c= new Case();
        // c.RecordTypeId=rCase.Id;
         c.Contact__c=con.Id;
         c.Caller_Type__c='External';
         c.Status='New';
         c.Origin='Sales Pilot';
         c.Address_Verified__c='Yes';
         c.Email_Address_Verified__c='Yes';
         c.Description='Test survey pilot case';
         c.AccountId=parentAcct.Id;
         
         Insert c;
        
       
        Ryder_CSC_Surveys__C rs= new Ryder_CSC_Surveys__C();
        rs.Contact__c=con.Id;
        rs.Case__c=c.Id;
        rs.Feedback_about_the_agent__c='Test Agent Feedback';
        rs.How_satisfied_are_you_with_the_agent__c='Satisfied';
        rs.Was_your_call_resolved__c='Yes';
        rs.Was_your_issue_addressed__c='Yes';
        rs.Likelihood_of_calling_again__c='Likely';
        rs.RecordTypeId=rSurvey.Id;
        
        Insert rs;
        
        // update rs update on all fields for code coverage in if condition
        rs.Was_your_call_resolved__c='No';
        update rs;
        rs.How_satisfied_are_you_with_the_agent__c='DisSatisfied';
        update rs;
        rs.Likelihood_of_calling_again__c='Not Likely';
        update rs;
        rs.Was_your_issue_addressed__c='No';
        update rs;
        Test.stopTest();
              
        
        
    }
}