SFDC Automation/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Corrective_Action__c</fullName>
        <label>Corrective Action</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Proposal_Due_Date__c</fullName>
        <label>Proposal Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Resources_requeste__c</fullName>
        <label>Resources Requested</label>
        <picklist>
            <picklistValues>
                <fullName>Account Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alternative Fuels</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asset Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fuel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On-Boarding / Start-up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing / Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proposal Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proximity Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Safety / Compliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supply Chain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>System Integration / Reporting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical / Maintenance</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Run_Assign_Rule_From_Mobile__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Run Assign Rule From Mobile</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Solutions_Interest__c</fullName>
        <label>Solutions Interest</label>
        <picklist>
            <picklistValues>
                <fullName>FMS/SCS Cross Sell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FSL Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FSL VOSA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MMS – Comprehensive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MMS – Mobile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MMS – On Demand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MMS – On Site</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MMS – Preventive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle Sales</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Source__c</fullName>
        <description>This field tells if the contact is created by lead convesion process or manually by clicking new contact button.</description>
        <label>Contact Source</label>
        <picklist>
            <picklistValues>
                <fullName>Lead Conversion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manual</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Global_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Global Settings</label>
</CustomObject>

SFDC Automation/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Suspect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Solutions_Interest__c.object
<CustomObject>
    <label>Solutions Interest</label>
    <nameField>
        <label>Solutions Interest ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions Interests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC Automation/src/classes/CaseManagement_Helper_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class CaseManagement_Helper_Test
{
    static testMethod void myUnitTest()
    {
    	// TO DO: implement unit test
    	RSMCreateTestData.GetCustomSettingsRecord();       
        FetchCustomSettingsData();
        Account acc = new Account();
        acc.name = 'Test Account';    
        acc.ShippingState = RyderGlobalVariables.TEST_STATE_CANADA;        
        acc.ShippingCountry = RyderGlobalVariables.COUNTRIES_USA;        
        insert acc;
		
		system.assertEquals(acc.ShippingState, RyderGlobalVariables.TEST_STATE_CANADA);
        
        Contact c = New Contact (); 
        c.FirstName = 'TestFirst'; 
        c.LastName = 'TestLast'; 
        c.email = 'TestContact@test.com';
        c.accountId = acc.Id;
        c.Contact_Source__c = 'Lead Conversion';
        insert c;
        system.assertEquals(c.AccountId, acc.Id);
        
        Case case1 = new Case();
        case1.AccountId = acc.Id;
        case1.ContactId = c.id;
        case1.Resources_requeste__c = 'Credit';
        case1.Solutions_Interest__c = 'Rental';
        case1.Proposal_Due_Date__c = System.today().addDays(10);
        String CaseProposalRecordTypeId = '';
		Global_Settings__c CaseProposalRecordType = Global_Settings__c.getValues('1');
		if(CaseProposalRecordType != null)
			CaseProposalRecordTypeId = CaseProposalRecordType.Value__c;
		case1.RecordTypeId = CaseProposalRecordTypeId;
        insert case1;
        system.assertEquals(case1.RecordTypeId, CaseProposalRecordType.Value__c);
        system.assertEquals(false, case1.IsClosed);
        case1.Proposal_Due_Date__c = System.today();
        case1.Corrective_Action__c = 'Test';
        update case1;
        
        case1.Status = 'Closed';
        case1.Corrective_Action__c = 'Test';
        update case1;
        
        Case case2 = new Case();
        case2.AccountId = acc.Id;
        case2.ContactId = c.id;
        case2.Resources_requeste__c = 'Credit';
        case2.Solutions_Interest__c = 'Rental';
        case2.Proposal_Due_Date__c = System.today().addDays(10);
        case2.Run_Assign_Rule_From_Mobile__c = true;
        String CaseProposalRecordTypeId1 = '';
		Global_Settings__c CaseProposalRecordType1 = Global_Settings__c.getValues('5');
		if(CaseProposalRecordType1 != null)
			CaseProposalRecordTypeId1 = CaseProposalRecordType1.Value__c;
		case2.RecordTypeId = CaseProposalRecordTypeId1;
        insert case2;
        
    }
    public static void FetchCustomSettingsData()
    {
    	RecordType RT = [Select r.SobjectType, r.Name, r.Id From RecordType r where sObjectType = 'Case' and Name = 'Proposal Response'];
    	Global_Settings__c CaseProposalRecordType = new Global_Settings__c(Name = '1');
    	CaseProposalRecordType.IsActive__c = True;
    	CaseProposalRecordType.Comment__c = 'RecordType';
    	CaseProposalRecordType.Type__c = 'RecordType';
    	CaseProposalRecordType.Object_Name__c = 'Case';
    	CaseProposalRecordType.Value__c = RT.ID;
    	insert CaseProposalRecordType;
    	
    	Global_Settings__c CaseProposalRecordType1 = new Global_Settings__c(Name = '2');
    	CaseProposalRecordType1.IsActive__c = True;
    	CaseProposalRecordType1.Comment__c = 'Used at: CaseManagement trigger as email content';
    	CaseProposalRecordType1.Type__c = 'Email Content';
    	CaseProposalRecordType1.Object_Name__c = 'Case';
    	CaseProposalRecordType1.Value__c = 'new Case created';
    	insert CaseProposalRecordType1;
    	
    	Global_Settings__c CaseProposalRecordType2 = new Global_Settings__c(Name = '3');
    	CaseProposalRecordType2.IsActive__c = True;
    	CaseProposalRecordType2.Comment__c = 'Used at: CaseManagement trigger as email content';
    	CaseProposalRecordType2.Type__c = 'Email Content';
    	CaseProposalRecordType2.Object_Name__c = 'Case';
    	CaseProposalRecordType2.Value__c = 'Case Updated';
    	insert CaseProposalRecordType2;
    	
    	Global_Settings__c CaseProposalRecordType3 = new Global_Settings__c(Name = '4');
    	CaseProposalRecordType3.IsActive__c = True;
    	CaseProposalRecordType3.Comment__c = 'Used at: CaseManagement trigger as email content';
    	CaseProposalRecordType3.Type__c = 'Email Content';
    	CaseProposalRecordType3.Object_Name__c = 'Case';
    	CaseProposalRecordType3.Value__c = 'Case Closed';
    	insert CaseProposalRecordType3;
    	
    	RT = [Select r.SobjectType, r.Name, r.Id From RecordType r where sObjectType = 'Case' and Name = 'Legal Cases'];
    	Global_Settings__c CaseProposalRecordType4 = new Global_Settings__c(Name = '5');
    	CaseProposalRecordType4.IsActive__c = True;
    	CaseProposalRecordType4.Comment__c = 'RecordType';
    	CaseProposalRecordType4.Type__c = 'RecordType';
    	CaseProposalRecordType4.Object_Name__c = 'Case';
    	CaseProposalRecordType4.Value__c = RT.ID;
    	insert CaseProposalRecordType4;
    }
}