SFDC Automation/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Email_does_not_exist__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Does Email Exist</description>
        <label>Email does not exist</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Key_Contact__c.object
<CustomObject>
    <description>CSI and Maintenance Contacts</description>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AccountId</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Key Contacts</relationshipLabel>
        <relationshipName>Key_Contacts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <inlineHelpText>Select which role this Contact serves for this Customer/Branch.</inlineHelpText>
        <label>Contact Role</label>
        <picklist>
            <picklistValues>
                <fullName>CSI Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maintenance Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RydeSmart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RydeSmart Mktg</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IFT Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.STATUS_ACTIVE__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Related Branches</relationshipLabel>
        <relationshipName>Key_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Key Contact</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Key Contact #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Key Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup on Accounts</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RSM_Device_Status__c</fullName>
        <label>Device Status</label>
        <picklist>
            <picklistValues>
                <fullName>Removed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deactivated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installed with Repairs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ordered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Device</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RSM__c</fullName>
        <description>Displays RydeSmart contract status</description>
        <label>RS Contract Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Printed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to SSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by SSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deleted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/RSMEmailToNonKeyAcAfterInstCompleted.cls
//FR011-Batch Class to Send Email to Non-Key Ac once installation Process is complete for all the contracted vehicles
global class RSMEmailToNonKeyAcAfterInstCompleted implements Database.Batchable<SObject>{
    
    public String query;
    global Database.QueryLocator start(Database.BatchableContext BC){
        System.debug('query : '+query);
        return Database.getQueryLocator(query);
    }
   
    global void execute(Database.BatchableContext BC, List<Account> scope){
        List<Messaging.SingleEmailMessage> EmailList=new List<Messaging.SingleEmailMessage>();
        List<Account> updateAcctList=new List<Account>();
        Set<Id> accountIdSet=new Set<Id>();
        Set<Id> taskExistAccIds=new Set<Id>();
        Set<Id> accIds=new Set<Id>(); 
        List<Vehicle__c> Updatevehlist=new List<Vehicle__c>();
        for(Account acc:scope){
            accountIdSet.add(acc.Id);
        }
        
        List<Task> ltask = [select Id,whatId from Task where subject='Email: RydeSmart Installation Complete' and whatId in:accountIdSet];       
        for(Task t:ltask){
            taskExistAccIds.add(t.whatId);
        }
        accountIdSet.removeAll(taskExistAccIds);
        Map<String,String> keyContactEmailMap=new Map<String,String>();
        List<Key_Contact__c> kcont = [select Id,Contact__r.Email,AccountId__c from 
                           Key_Contact__c where AccountId__c in :accountIdSet 
                           and Contact_Role__c = 'RydeSmart' and Contact__r.Email_does_not_exist__c = false and 
                           Contact__r.Email <> '' and Contact__r.EmailBouncedReason = ''];
        for(Key_Contact__c kc:kcont)
        {
            keyContactEmailMap.put(kc.AccountId__c,kc.Contact__c);
        }
                               
        Map<Id,Boolean> conAccId=new Map<Id,Boolean>();
        Map<Id,String> accVehMap = new Map<Id,String>();
        
        List<Vehicle__c> vhcl = [select Id,Name,RSM_Device_Status__c,Account__c,RSM__c 
                        from vehicle__c where Account__c  in :accountIdSet 
                        and RSM__c = 'Approved' and 
                        (RSM_Device_Status__c = 'Installed' or RSM_Device_Status__c = 'Installed with Repairs')];
        for(Vehicle__c v:vhcl)
        {
            if(accVehMap != null && accVehMap.get(v.Account__c) != null)
            {
                String sValue = accVehMap.get(v.Account__c);
                accVehMap.put(v.Account__c, sValue + ',' + v.Name);
            }
            else
            {
                accVehMap.put(v.Account__c,v.Name);
            }         
        }
        
        
        //String etId=[select Id from EmailTemplate where developerName='RSMEmailToNonKeyAcAfterInstCompleted'].Id;
        String sHTMLEmail = '<p> Hi, </p>';
        sHTMLEmail += '<p> RydeSmart Installation completed for all contracted vehicles. </p>';
        List<Task> lTasks = new List<Task>();
        List<Account> acnt = [select Id from Account where Id in:accountIdSet];
        for(Account acc: acnt)
        {
            sHTMLEmail = '<p> Hi, </p>';
            sHTMLEmail += '<p> RydeSmart Installation completed for all contracted vehicles. </p>';
            if(keyContactEmailMap.get(acc.Id) != null && accVehMap.get(acc.Id) != null)
            {
                sHTMLEmail += accVehMap.get(acc.Id);
                sHTMLEmail += '<p> Regards</p>';
                sHTMLEmail += '<p> RideSmart Support </p>';
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                mail.setTargetObjectId(keyContactEmailMap.get(acc.Id));                 
                //mail.setTemplateId(etId);
                mail.setHtmlBody(sHTMLEmail);
                mail.setSubject('RydeSmart Installation Complete');
                mail.setBccSender(true);
                mail.setUseSignature(false);
                mail.setSaveAsActivity(false);
                mail.setWhatId(acc.Id);             
                EmailList.add(mail);
                
                
                Task TaskObj = new Task();
                TaskObj.Subject = 'Email: RydeSmart Installation Complete';
                TaskObj.whatId = acc.Id;
                TaskObj.Description = sHTMLEmail;
                TaskObj.WhoId = keyContactEmailMap.get(acc.Id);
                TaskObj.ActivityDate = System.today();
                TaskObj.Status = 'Completed';
                TaskObj.Priority = 'Normal';
                TaskObj.OwnerId = UserInfo.getUserId();                
                lTasks.add(TaskObj);
            }
        } 
        if(EmailList.size() > 0 && !Test.isRunningTest())
            Messaging.sendEmail(EmailList);
        if(lTasks.size() > 0)
            insert lTasks;
    }

    global void finish(Database.BatchableContext BC){
    }
}