SFDC Automation/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Available_24_7__c</fullName>
        <description>Indicate if this Contact is available to contact at all hours of the day.</description>
        <inlineHelpText>Indicate if this Contact is available to contact at all hours of the day.</inlineHelpText>
        <label>Available 24/7?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CSI_Contact_Type__c</fullName>
        <label>CSI Contact - All Branches</label>
        <picklist>
            <picklistValues>
                <fullName>Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tertiary</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <label>Post Sales Contact Role</label>
        <picklist>
            <picklistValues>
                <fullName>After Hours</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P.O. Authorization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RCRC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Target Marketing Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executive Sponsorship Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RydeSmart</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>HQ_Account_ID__c</fullName>
        <description>Used to place the approrpriate account ID to allow for Key Contact Filter contraint</description>
        <formula>BLANKVALUE(Account.Parent.Id, Account.Id)</formula>
        <label>HQ Account ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Duplicate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Duplicate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Maintenance_Contact_Type__c</fullName>
        <label>Maintenance Contact - All Branches</label>
        <picklist>
            <picklistValues>
                <fullName>Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tertiary</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Primary</fullName>
        <active>true</active>
        <label>Primary</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Customer_Branch__c.object
<CustomObject>
    <description>Customer Branches at Ryder</description>
    <fields>
        <fullName>Customer_Branch_Status__c</fullName>
        <description>Indicates whether a Customer/Branch has active vehicles.</description>
        <inlineHelpText>Indicates whether a Customer/Branch has active vehicles.</inlineHelpText>
        <label>Customer Branch Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Ryder_HQ_Account__c</fullName>
        <description>M/D field between Customer Branch and HQ Accounts</description>
        <label>Ryder HQ Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer / Branch</relationshipLabel>
        <relationshipName>Customer_Branches</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Customer / Branch</label>
    <nameField>
        <label>Customer Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer / Branch</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Key_Contact__c.object
<CustomObject>
    <description>CSI and Maintenance Contacts</description>
    <fields>
        <fullName>Available_24_7__c</fullName>
        <inlineHelpText>Indicate if this Contact is available to contact at all hours of the day.</inlineHelpText>
        <label>Available 24/7?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <inlineHelpText>Select which role this Contact serves for this Customer/Branch.</inlineHelpText>
        <label>Contact Role</label>
        <picklist>
            <picklistValues>
                <fullName>CSI Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maintenance Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RydeSmart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RydeSmart Mktg</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IFT Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <inlineHelpText>Select the Contact Type.  Only one contact can be listed as Primary for a Customer/Branch.</inlineHelpText>
        <label>Contact Type</label>
        <picklist>
            <picklistValues>
                <fullName>Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tertiary</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.STATUS_ACTIVE__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Related Branches</relationshipLabel>
        <relationshipName>Key_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Branch__c</fullName>
        <description>Joiner object used for CSI and Maintenance Contacts</description>
        <label>Customer / Branch</label>
        <referenceTo>Customer_Branch__c</referenceTo>
        <relationshipLabel>Key Contacts</relationshipLabel>
        <relationshipName>Key_Contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>HQ_Account_ID__c</fullName>
        <formula>IF(ISBLANK(Contact__r.Account.Parent.Id ) , Contact__r.Account.Id , Contact__r.Account.Parent.Id )</formula>
        <label>HQ Account ID</label>
        <type>Text</type>
    </fields>
    <label>Key Contact</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Key Contact #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Key Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/classes/Test_Contacts_KeyContacts.cls
@isTest
private class Test_Contacts_KeyContacts {
    
    static testMethod void testContactKeyContactOperations()
    {
        // create parent account
        Account parentAcct = TestUtil.createAccount('Ryder FMS Parent Account', 'Customer');
        insert parentAcct;
        
        // create child account
        Account childAcct= new Account();
        childAcct.ParentId=parentAcct.Id;
        childAcct.Name='Child-Abc Group Inc';
        childAcct.Type='Customer';
        childAcct.BillingStreet='5401 Flagler street';
        childAcct.BillingCity='Miami';
        childAcct.BillingCity='FL';
        childAcct.BillingCountry='US';
        childAcct.BillingPostalCode = RyderGlobalVariables.TEST_POST_CODE;
        RecordType rt=[Select r.SobjectType, r.Name, r.IsActive, r.Id From RecordType r where  r.SobjectType='Account'  AND r.IsActive=true and r.Name='Ryder FMS Branch Account'];
        if (rt!=null) childAcct.RecordTypeId=rt.Id;
        insert childAcct;
            
        // create all branch contact for child
        /*
        Contact allbranchContact = new Contact();
        allbranchContact.accountId = childAcct.Id;
        allbranchContact.FirstName = 'Test All Branch contact';
        allbranchContact.LastName = 'Smith';
        allbranchContact.Email = 'abc123456789@abc999888.com';
        allbranchContact.Phone = '(123) 456-8789';
        allbranchContact.CSI_Contact_Type__c='Secondary';
        allbranchContact.Maintenance_Contact_Type__c = 'Primary';
        allbranchContact.Available_24_7__c='Yes';
        allbranchContact.Is_Duplicate__c=true;
        insert allbranchContact;
         
         
        // update an all branch contact
           
        allbranchContact.CSI_Contact_Type__c='Tertiary';
        allbranchContact.Maintenance_Contact_Type__c = 'Tertiary';
        
        // delete all branch contact
        if(allbranchContact.Is_Duplicate__c==true)
        	delete allbranchContact;
         */
        // create a regular contact and update to all branch
        Contact regularContact = TestUtil.createContact(childAcct.Id, 'test989898@test123.com');
        insert regularContact;
        test.startTest();
          /*  neelima-08/23 code moved to test_contacts_allbranchContact 
        // update regular contact to all branch
        System.debug(LoggingLevel.INFO, 'update regular contact to all branch');
        regularContact.CSI_Contact_Type__c = 'Primary';
        regularContact.Maintenance_Contact_Type__c = 'Secondary';
        regularContact.Available_24_7__c='Yes';
        update regularContact;
                
        // undo the all branch contact
        System.debug(LoggingLevel.INFO, 'undo the all branch contact');
        regularContact.CSI_Contact_Type__c=null;
        regularContact.Maintenance_Contact_Type__c = null;
                
        update regularContact; 
        */
                
        // create a customer branch
        Customer_Branch__c cb = new Customer_Branch__c();
        cb.Name = 'test branch';
        cb.Ryder_HQ_Account__c = parentAcct.Id;
        cb.Customer_Branch_Status__c='Active';
        insert cb;
        
        Contact con= [Select c.HQ_Account_ID__c from Contact c  where id =:regularContact.Id] ;
        
        // insert key contact1.
       System.debug(LoggingLevel.INFO, 'insert key contact1');
        Key_Contact__c kc= new Key_Contact__c();
        kc.Customer_Branch__c= cb.Id;
        kc.Available_24_7__c='Yes';
        kc.Contact__c= con.Id;
        kc.Contact_Role__c='CSI Contact';
        kc.Contact_Type__c='Secondary';
        insert kc;
        
               
        // update key contact
        kc.Contact_Type__c='Tertiary';
        update kc;
        
        // create another contact to test contact update on key contact
        Contact regularContact2 = TestUtil.createContact(childAcct.Id, 'test85678@test321.com');
        insert regularContact2;
        
         Contact con2= [Select c.HQ_Account_ID__c from Contact c  where id =:regularContact2.Id] ;
        kc.Contact__c=con2.Id;
          System.debug(LoggingLevel.INFO, 'updating key contact2');
        update kc;
        
           System.debug(LoggingLevel.INFO, 'deleting key contact');      
        // delete key contact
        delete kc;
        
        // insert key contact2.
         Key_Contact__c kc2= new Key_Contact__c();
        kc2.Customer_Branch__c= cb.Id;
        kc2.Available_24_7__c='Yes';
        kc2.Contact__c= regularContact.Id;
        kc2.Contact_Role__c='CSI Contact';
        kc2.Contact_Type__c='Primary';
        insert kc2;
        
       
        
      regularContact2.Maintenance_Contact_Type__c='Tertiary';
       // update regularContact2;
        // test createnewkeycontact function
       //Key_Contact__c kc3= contactUtil.CreateNewKeyContact(regularContact2, cb, RyderGlobalVariables.CSI_ROLE_TEXT, true);
       //insert kc3;
       
       
         System.debug(LoggingLevel.INFO, 'updating cust branch');
        // update customer branch from active to inactive
        cb.Customer_Branch_Status__c='Inactive';
        update cb;
        
        // update customer branch from Inactive to active
        cb.Customer_Branch_Status__c='Active';
        update cb;
        
        //delete customer branch
         System.debug(LoggingLevel.INFO, 'deleting cust branch');
        delete cb;  
        
         System.debug(LoggingLevel.INFO, 'deleting regular contact');
         // delete a regular contact
         if(regularContact.Is_Duplicate__c==true)
            delete regularContact;
        // delete an all branch contact
         System.debug(LoggingLevel.INFO, 'deleting contact 2');
         if(regularContact2.Is_Duplicate__c==true)
            delete regularContact2;
        test.stopTest();
    }
    

}