SFDC Automation/src/objects/ContractPackage__c.object
<CustomObject>
    <fields>
        <fullName>Cs_no__c</fullName>
        <label>Cs_no</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>ContractPackage</label>
    <nameField>
        <label>ContractPackage</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ContractPackages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC Automation/src/classes/ContractPackage_trigger_test.cls
@isTest
public class ContractPackage_trigger_test {

    

    static testMethod void getOpportunityId() {
    
        ContractPackage__c testCntPkg = new ContractPackage__c(Cs_no__c = '0008891456', Id='a0n60000002dRnV');
        update testCntPkg;
    
        Map<String, String> rateSheet = new Map<String, String>();
        rateSheet.put(String.ValueOf(12345), '000615784236');
        
    }
}