SFDC Automation/src/objects/Customer_Branch__c.object
<CustomObject>
    <description>Customer Branches at Ryder</description>
    <label>Customer / Branch</label>
    <nameField>
        <label>Customer Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer / Branch</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Ryder_Surveys__c.object
<CustomObject>
    <description>This object will store the high-level results of Click Tools surveys, including the CSI, Follow up and Closed Case Surveys.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Ryder Surveys</relationshipLabel>
        <relationshipName>Ryder_Surveys1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Branch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer/branch the survey corresponds.</description>
        <inlineHelpText>The customer/branch of the key contact that responded to this survey.</inlineHelpText>
        <label>Customer Branch</label>
        <referenceTo>Customer_Branch__c</referenceTo>
        <relationshipLabel>Ryder Surveys</relationshipLabel>
        <relationshipName>Ryder_Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Survey_Submission_Date__c</fullName>
        <description>The date the survey was submitted with the responses.</description>
        <inlineHelpText>The survey was submitted on this date with the responses that can be viewed in the url.</inlineHelpText>
        <label>Survey Submission Date</label>
        <type>DateTime</type>
    </fields>
    <label>Ryder Survey</label>
    <nameField>
        <displayFormat>RS-{00000}-{mmddyy}</displayFormat>
        <label>Ryder Survey Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ryder Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Care360</fullName>
        <active>true</active>
        <description>This record type is used for failed surveys</description>
        <label>Care360</label>
    </recordTypes>
    <recordTypes>
        <fullName>Survey</fullName>
        <active>true</active>
        <description>Task only used to capture the workload for surveys</description>
        <label>Survey</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/classes/CreateTask.cls
public with sharing class CreateTask {
//This class is used to create the task for failed surveys & unresolved follow up task
//Created on 04/03/2012 Saad Wali Jaan.
    
    Public static Task Care360Task(String surveyId)
    {
        date myDate = System.Today();
        system.debug('Saad - myDate + 60Days = ' + myDate.addDays(60));
        Map<String, Id> surveyRecordTypes= CommonFunctions.getRecordTypeMap('Task');
        List<Ryder_Surveys__c> rs = [Select r.Id, r.Name, r.Customer_Branch__c, r.Contact__c, r.CreatedDate from Ryder_Surveys__c r WHERE r.Id = :surveyId];
        system.debug('Saad - RyderSurvey = ' + rs);
        //Create a new Task           
        Task T = new Task();
        
        for(Ryder_Surveys__c r : rs)
        {
            T.OwnerId = RyderGlobalVariables.FOLLOWSURVEYUSER;//Assigned To
            T.WhatId = r.Customer_Branch__c;//Related To
            T.WhoId = r.Contact__c;//
            T.Orignal_Task_Date__c = r.CreatedDate;//Date on which survey was done
            //T.Survey_Submission_Date__c = r.CreatedDate;//Date on which survey was done
            T.Type = 'Phone Call';
            T.Subject = 'Follow up task for Dissatisfied CSI survey';
            T.ActivityDate = myDate.addDays(60);
            T.Description = 'Follow up task for Dissatisfied CSI survey';
            T.Status = 'Not Started';
            T.Priority = 'Normal';
            T.RecordTypeId = surveyRecordTypes.get('Care360');
            T.SurveyID__c = r.Id;//To store the Id of the Ryder Survey for which this task is created.
            T.Survey_Name__c = r.Name;//To store the Name of the Ryder Survey for which this task is created.
        }
        return T;
    }
    static testMethod void test_taskcreation(){
        Ryder_Surveys__c rs = new Ryder_Surveys__c();
        insert rs;
        Care360Task(rs.Id);
    }
}