SFDC Automation/src/objects/Deal_Summary__c.object
<CustomObject>
    <label>Deal Summary</label>
    <nameField>
        <label>Deal Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Opportunity_Split__c.object
<CustomObject>
    <description>Used to display the National/Coordinated Account and Local Account splits on an opportunity.  This object will be used to perform pipeline reports.</description>
    <label>Opportunity Split</label>
    <nameField>
        <displayFormat>SPLIT-{000000}</displayFormat>
        <label>Opportunity Split #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Splits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Pipeline_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Split__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity Split</label>
        <referenceTo>Opportunity_Split__c</referenceTo>
        <relationshipLabel>Pipeline Details</relationshipLabel>
        <relationshipName>Pipeline_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate_Sheet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rate Sheet</label>
        <referenceTo>Rate_Sheet__c</referenceTo>
        <relationshipLabel>Pipeline Details</relationshipLabel>
        <relationshipName>Pipeline_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pipeline Detail</label>
    <nameField>
        <label>Pipeline Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pipeline Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Rate_Sheet__c.object
<CustomObject>
    <description>Will be populated with data from Radar</description>
    <fields>
        <fullName>Deal_Summary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal Summary</label>
        <referenceTo>Deal_Summary__c</referenceTo>
        <relationshipLabel>Rate Sheets</relationshipLabel>
        <relationshipName>Rate_Sheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Rate Sheet</label>
    <nameField>
        <label>Rate Sheet #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Sheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/classes/OpportunityDSAndRSVO.cls
public with sharing class OpportunityDSAndRSVO {
    public List<Deal_Summary__c> dealSummariesList {get; set;}
    public List<Rate_Sheet__c> rateSheetsList {get; set;}
    public List<Pipeline_Detail__c> pipelineDetailsList {get; set;}
    public List<Opportunity_Split__c> opportunitySplitsListCUSTOM {get; set;}
    public List<OpportunityLineItem> opportunityProductLineItem {get; set;}    
    
    static testMethod void test_OpportunityDSAndRSVO(){
        OpportunityDSAndRSVO temp = new OpportunityDSAndRSVO();
        temp.dealSummariesList = new List<Deal_Summary__c>();
        temp.rateSheetsList = new List<Rate_Sheet__c>();
        List<Deal_Summary__c> resultDS = temp.dealSummariesList;
        List<Rate_Sheet__c> resultRS = temp.rateSheetsList;
        system.assertEquals(resultDS, temp.dealSummariesList);
        system.assertEquals(resultRS, temp.rateSheetsList);
    }
}