SFDC Automation/src/objects/Deal_Summary__c.object
<CustomObject>
    <fields>
        <fullName>EVA__c</fullName>
        <label>EVA</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gross_Revenue__c</fullName>
        <label>Gross Revenue</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Include_In_Quote__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Include In Quote</label>
        <type>Checkbox</type>
    </fields>
    <label>Deal Summary</label>
    <nameField>
        <label>Deal Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deal Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>EVA__c</fullName>
        <label>Average EVA</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gross_Revenue__c</fullName>
        <label>Gross Revenue</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NET_REVENUE__c</fullName>
        <label>Net Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Num_of_vehicles__c</fullName>
        <inlineHelpText># of Vehicles must be entered on the Opportunity Line Item, or they will roll-up from Rate Sheets/Deal Summaries.</inlineHelpText>
        <label>Total Number of Vehicles</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rate_Sheet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rate Sheet</label>
        <referenceTo>Rate_Sheet__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Rate_Sheet__c.object
<CustomObject>
    <description>Will be populated with data from Radar</description>
    <fields>
        <fullName>Deal_Summary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Deal Summary</label>
        <referenceTo>Deal_Summary__c</referenceTo>
        <relationshipLabel>Rate Sheets</relationshipLabel>
        <relationshipName>Rate_Sheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EVA__c</fullName>
        <label>EVA</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gross_Revenue__c</fullName>
        <label>Gross Revenue</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Include_In_Quote__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Include In Quote</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Package_Type__c</fullName>
        <label>Package Type</label>
        <picklist>
            <picklistValues>
                <fullName>Regular</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Regular</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <label>Product Line</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Rate Sheet</label>
    <nameField>
        <label>Rate Sheet #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Sheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/classes/test_insertUpdateDealSummary.cls
@isTest
private class test_insertUpdateDealSummary {

    static testMethod void testDealSummary() {
    	
    	Account a = TestUtil.createAccount('Ryder FMS Parent Account', 'FMS');
    	a.billingstate = 'IL';
    	a.BillingPostalCode = '12347';
    	a.BillingCountry = 'US';
    	insert a;
    	System.debug('Account - '+a);
    	System.assert(a.Id!=null);
    	
    	Contact c = New Contact (FirstName = 'TestFirst', LastName = 'TestLast', email = 'TestContact@test.com', accountId = a.Id);
    	insert c;
    	
    	List<Opportunity> opptyList = new List<Opportunity>();
    	for(Integer i=0; i<3; i++){
    		Opportunity o = TestUtil.createOppty(a, c, 'Standard Opportunity');
    		opptyList.add(o);
    	}
    	//Opportunity o = TestUtil.createOppty(a, 'Parent Opportunity');
    	insert opptyList;
    	System.assert(opptyList.size()>0);
    	System.debug('Opportunity - '+opptyList);
    	
    	//o = [Select VEH_NO__c, Type, Num_of_vehicles__c, NET_REVENUE__c, Id, Gross_Revenue__c, EVA__c, CloseDate From Opportunity  where Id=:o.id];
    	//System.debug(o);
    	
    	List<Deal_Summary__c> dsList = new List<Deal_Summary__c>();
    	for(Integer j=0; j<3; j++){
    		Deal_Summary__c d = TestUtil.createDealSummary(opptyList[j]);
    		d.Include_In_Quote__c=true;
    		dsList.add(d);
    	}
    	insert dsList;
    	System.debug(dsList.size()>0);
    	System.debug('Deal Summary - '+dsList);
    }
    
    static testMethod void testRateSheet() {
    	
    	Account a = TestUtil.createAccount('Ryder FMS Parent Account', 'FMS');
    	a.billingstate = 'IL';
    	a.BillingPostalCode = '12347';
    	a.BillingCountry = 'US';
    	insert a;
    	System.debug('Account - '+a);
    	System.assert(a.Id!=null);
    	
    	Contact c = New Contact (FirstName = 'TestFirst', LastName = 'TestLast', email = 'TestContact@test.com', accountId = a.Id);
    	insert c;
    	
    	List<Opportunity> opptyList = new List<Opportunity>();
    	for(Integer i=0; i<3; i++){
    		Opportunity o = TestUtil.createOppty(a, c, 'Standard Opportunity');
    		opptyList.add(o);
    	}
    	
    	//Opportunity o = TestUtil.createOppty(a, 'Parent Opportunity');
    	insert opptyList;
    	System.assert(opptyList.size()>0);
    	System.debug('Opportunity - '+opptyList);
    	//o = [Select VEH_NO__c, Type, Num_of_vehicles__c, NET_REVENUE__c, Id, Gross_Revenue__c, EVA__c, CloseDate From Opportunity  where Id=:o.id];
    	//System.debug(o);
		
		
		List<Rate_Sheet__c> rtList = new List<Rate_Sheet__c>();
    	for(Integer k =0; k<3; k++){
    		Rate_Sheet__c rs = TestUtil.createRateSheet(null, opptyList[k]);
    		rs.Include_In_Quote__c=true;
    		rs.Package_Type__c='Regular';
    		rs.Product_Line__c='Full Service Lease 11 (FMS)';
    		rtList.add(rs);
    	}

    	insert rtList;
    	System.assert(rtList.size()>0);
    	System.debug('RateSheet List is - '+rtList);

    }
}