SFDC Automation/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Employee_Zipcode__c</fullName>
        <description>The zip code of the employee for employee leads</description>
        <label>Employee Zipcode</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_UVS__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The flag use to identify UVS Lead created through Eloqua</description>
        <inlineHelpText>The flag use to identify UVS Lead created through Eloqua</inlineHelpText>
        <label>Is UVS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PRODUCT_LINE__c</fullName>
        <label>Product Line</label>
        <picklist>
            <picklistValues>
                <fullName>FSL VOSA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FSL Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FSL Choice Lease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FSL Flex Lease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FSL Fast Track</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RPM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RydeSmart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MMS On Demand</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Send_Email_to_VSR_VSM__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send Email to VSR VSM</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UTC_Assigned__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UTC Assigned</label>
        <referenceTo>Ryder_Branch__c</referenceTo>
        <relationshipLabel>Leads (UTC Assigned)</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <description>The field use for Vehicle Unit sent from Eloqua as UVS Lead and will be used to autopopulate Customer Needs at the time of creation</description>
        <label>Unit #</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Postal_Code__c.object
<CustomObject>
    <description>Holds the mapping between zip code and timezone. Source data is PostalCodes table in AMDATA.</description>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <externalId>true</externalId>
        <label>Postal Code</label>
        <length>7</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>UTC__c</fullName>
        <label>UTC</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UVS_Assignee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>UVS Assignee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Postal_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Postal Code</label>
    <nameField>
        <label>Postal Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Postal Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Profile_Default_Products__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Default_Product__c</fullName>
        <label>Default Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Profile Default Products</label>
</CustomObject>

SFDC Automation/src/objects/Ryder_Branch__c.object
<CustomObject>
    <description>Branches at Ryder</description>
    <fields>
        <fullName>Branch_Code__c</fullName>
        <description>external ID</description>
        <externalId>true</externalId>
        <label>Branch Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Ryder Branch</label>
    <nameField>
        <label>Ryder Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ryder Branches</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Solution_Interest_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Solutions_Interest__c</fullName>
        <label>Solutions Interest</label>
        <referenceTo>Solutions_Interest__c</referenceTo>
        <relationshipLabel>Solution Interest Details</relationshipLabel>
        <relationshipName>Solution_Interest_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Vehicle_Name__c</fullName>
        <label>Vehicle Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Solution Interest Detail</label>
    <nameField>
        <label>Solution Interest Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solution Interest Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Solutions_Interest__c.object
<CustomObject>
    <fields>
        <fullName>Latest_Source__c</fullName>
        <label>Latest Source</label>
        <picklist>
            <picklistValues>
                <fullName>BDM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blitz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cold Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concentrix</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DBD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>F&amp;B Local Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rental Counter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NRM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National Tag Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CDM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DNA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COMBO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Lead_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead Id</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Solutions Interests</relationshipLabel>
        <relationshipName>Solutions_Interests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Original_Source__c</fullName>
        <label>Original Source</label>
        <picklist>
            <picklistValues>
                <fullName>BDM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blitz</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cold Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concentrix</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DBD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>F&amp;B Local Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rental Counter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NRM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National Tag Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CDM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DNA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COMBO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <label>Product Line</label>
        <picklist>
            <picklistValues>
                <fullName>Lease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RydeSmart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Used Vehicles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ryder Fleet Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dedicated Carrier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fuel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supply Chain &amp; Logistics</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>-- None --</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unread</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renurture</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Solutions Interest</label>
    <nameField>
        <label>Solutions Interest ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions Interests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC Automation/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>UTC__c</fullName>
        <description>This field will capture the location code for the user.</description>
        <label>UTC</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/objects/UVS_Profiles__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Profile_Name__c</fullName>
        <label>Profile Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>UVS Profiles</label>
</CustomObject>

SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <fields>
        <fullName>Branch_Code__c</fullName>
        <label>Branch Code</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PRODUCT_LINE__c</fullName>
        <description>Product Line</description>
        <label>Product Line</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAM_CLASS__c</fullName>
        <description>Sam Class</description>
        <label>SAM Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <externalId>true</externalId>
        <label>Unit Number</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <recordTypes>
        <fullName>UVS</fullName>
        <active>true</active>
        <description>Record Type for UVS Vehicles</description>
        <label>UVS</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Vehicle_List__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of vehicles with their types</description>
    <fields>
        <fullName>Vehicle_Name__c</fullName>
        <label>Vehicle Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Vehicle List</label>
</CustomObject>

SFDC Automation/src/classes/LeadTriggerHandler.cls
/*************************************************************************************************
Created By:    Sunil Gupta
Date:          August 25, 2014
Description  : Handler class for Lead Trigger
**************************************************************************************************/
public class LeadTriggerHandler {
  private static final String UVS_QUEUE = 'UVS Lead Assignment';
  // Create Solution Interest record.
  public static void createSolutionInterest(Map<Id, Lead> mapNew) { 
    
    // prepare map for profile names.
    Set<Id> ownerIds = new Set<Id>();
    Map<Id, String> mapProfiles = new Map<Id, String>();
    for(Lead l :mapNew.values()){
        if(String.valueOf(l.OwnerId).startsWith('005')){
        ownerIds.add(l.OwnerId);
        }
    }

    Map<Id, String> mapProfileNames = new Map<Id, String>();
    for(User u :[SELECT Profile.Name FROM User WHERE Id IN :ownerIds]){
      mapProfileNames.put(u.Id, u.Profile.Name);
    }

    Map<String, Profile_Default_Products__c> mapPDP = Profile_Default_Products__c.getAll();



    // create solution interest record.
    List<Solutions_Interest__c> lstSI = new List<Solutions_Interest__c>();
    
    for(Lead l :mapNew.values()){
    	//AAK 04/10/2015 Start QC 891 - excluded lead coming from eloqua
	    Solutions_Interest__c si = new Solutions_Interest__c();
		if(!l.Is_UVS__c){
		//AAK 04/10/2015 End
	        si.Lead_Id__c = l.Id;
	        si.Latest_Source__c = l.LeadSource;
	        si.Original_Source__c = l.LeadSource;
	        si.Stage__c = 'Qualified';
	        //AAK 04/10/2015 Start QC 891 - defaulting to Lease 
	        si.Product_Line__c = 'Lease';
	        //AAK 04/10/2015 End
	        if(String.valueOf(l.OwnerId).startsWith('005')){
	          
	            if(mapProfileNames.get(l.OwnerId) != null){
	                if(mapPDP.get(mapProfileNames.get(l.OwnerId)) != null){
	                  si.Product_Line__c = mapPDP.get(mapProfileNames.get(l.OwnerId)).Default_Product__c;
	                }
	            }
	        }
		}
        lstSI.add(si);
    }
    
   
    
    System.debug('@@@' + lstSI);
    if(!lstSI.isEmpty()){
      insert lstSI;
    }
    
    
  }

  // RA: Please provide Comenting in below method for each block

  // Create Solution Interest record When Lead Owner Profile is changed.
  public static void createSolutionInterestOnProfileChanged(Map<Id, Lead> mapOld, List<Lead> lstNew, Map<Id, Lead> mapNew) {
    Set<Id> setOwnerIds = new Set<Id>();
    for(Lead l :lstNew){
        if(mapOld.get(l.Id).OwnerId != l.OwnerId){
            setOwnerIds.add(l.OwnerId);
        }
    }
    System.debug('@@@' + setOwnerIds);

    Map<Id, String> mapProfileNames = new Map<Id, String>();
    for(User u :[SELECT Profile.Name FROM User WHERE Id IN :setOwnerIds]){
      mapProfileNames.put(u.Id, u.Profile.Name);
    }

    Map<String, Profile_Default_Products__c> mapPDP = Profile_Default_Products__c.getAll();


    // prepare map for  Lead Id vs Product Line
    Map<Id, String> mapProductLine = new Map<Id, String>();
  
    for(Lead l :lstNew){
      if(mapOld.get(l.Id).OwnerId != l.OwnerId){
        String newProductLine;
        if(String.valueOf(l.OwnerId).startsWith('005')){
          if(mapProfileNames.get(l.OwnerId) != null){
            if(mapPDP.get(mapProfileNames.get(l.OwnerId)) != null){
              newProductLine = mapPDP.get(mapProfileNames.get(l.OwnerId)).Default_Product__c;
            }
          }
        }
         //AAK 04/10/2015 Start QC 891 - defaulting to Lease
        //if(newProductLine == null){
        //	mapProductLine.put(l.Id, 'Lease');
        //} else { //AAK 04/10/2015 End
        	mapProductLine.put(l.Id, newProductLine);
       // }
      }
    }
    System.debug('@@@' + mapProductLine);
	System.debug('@@@' + mapProductLine.keySet());
    Map<Id, List<Solutions_Interest__c>> mapExistingSI = new Map<Id, List<Solutions_Interest__c>>();
    for(Solutions_Interest__c si : [SELECT Id, Stage__c, Lead_Id__c, Product_Line__c
                                                 FROM Solutions_Interest__c
                                                 WHERE Lead_Id__c IN :mapProductLine.KeySet()]){
      if(si.Lead_Id__c != null){
      	  system.debug('enter');
          if(mapExistingSI.containsKey(si.Lead_Id__c) == false){
            mapExistingSI.put(si.Lead_Id__c, new List<Solutions_Interest__c>());
          }
          mapExistingSI.get(si.Lead_Id__c).add(si);
      }
    }
    System.debug('@@@' + mapExistingSI);


    Set<Id> eligibleLeadIds = new Set<Id>();
    for(Id leadId :mapProductLine.keySet()){
        List<Solutions_Interest__c> lst = mapExistingSI.get(leadId);
        String newProductLine = mapProductLine.get(leadId);
        if(newProductLine != null){
            Boolean isMatched = false;
         if(lst!=null && lst.size()>0) {
              for(Solutions_Interest__c si :lst){
                if(si.Product_Line__c == newProductLine){
                  isMatched = true;
                }
              }
          }
          if(isMatched == false){
            eligibleLeadIds.add(leadId);
          }
        }
    }
    System.debug('@@@' + eligibleLeadIds);


    List<Solutions_Interest__c> lstSI = new List<Solutions_Interest__c>();
    for(Id leadId :eligibleLeadIds){ 
        Solutions_Interest__c si = new Solutions_Interest__c();
          si.Lead_Id__c = leadId;
          si.Latest_Source__c = mapNew.get(leadId).LeadSource;
          si.Original_Source__c = mapNew.get(leadId).LeadSource;
          if(mapProductLine.get(leadId) != null){
            si.Product_Line__c = mapProductLine.get(leadId);
          }
          lstSI.add(si);
        }

    System.debug('@@@' + lstSI);
   
    if(!lstSI.isEmpty()){
      insert lstSI;
      createSolutionInterestDetail(lstSI);
    }
   
  }
  
  
    // Sunil: Appirio 10/11/2014: Assign UVS Lead T-323926
    // If Lead is from Employee then fetch Postal Code from Postal Code 
    // and assign it to the user of that postal code object
  public static void assignEmployeeLeads(List<Lead> newList){
    System.debug('@@@' + newList);  
    Set<String> postalCodeSet = new Set<String>();
    for(Lead lead :newList){
        if(lead.OwnerId != null && (lead.LeadSource == 'Employee Referral')){
         if(lead.Employee_Zipcode__c !=null)
          {
           System.debug('@@@Zip code : ' + lead.Employee_Zipcode__c);
           postalCodeSet.add(lead.Employee_Zipcode__c);           
          }
        }
      }        
       System.debug('@@@' + postalCodeSet);   
      map<String,Postal_Code__c> postalCodeSelfMap = new map<String,Postal_Code__c>();
      for(Postal_Code__c postCode : [SELECT Postal_Code__c,UVS_Assignee__c FROM Postal_Code__c WHERE Postal_Code__c IN : postalCodeSet]){
        if(postCode.UVS_Assignee__c !=null){
            if(postCode.Postal_Code__c != null){
            postalCodeSelfMap.put(postCode.Postal_Code__c ,postCode);
            }            
        }
      }
      System.debug('@@@' + postalCodeSelfMap);
     
      List<Lead> leadsToUpdate = new List<Lead>();
      
      for(lead lead :newList){   
        if(postalCodeSelfMap.containskey(lead.Employee_Zipcode__c))     
         {
          lead.OwnerId = postalCodeSelfMap.get(lead.Employee_Zipcode__c).UVS_Assignee__c;
        //  setNewLeadOwners.add(lead.OwnerId);
          lead.Send_Email_to_VSR_VSM__c = true; // to send the notification email.        
           }}
         
        }
    
    
  
    // Hari Krishnan (12/29/2014): This method populates the UTC_Assigned__c field.
    //Update By Virendra to populate UTC Assigned Field For I-148716 on 18 Feb 2015
    public static void updateUTC(List<Lead> listLeads,Map<Id, Lead> mapOld,boolean isInsert) {
        String utcId = null;
        map<id,id> leadOweners = new map<id,id>();
        map<Id,User> ownersUTCs = new map<Id,User>();
     
        for(lead ld:listLeads){
            leadOweners.put(ld.id,ld.ownerId);
        }
        
        map<id,String> ownersRelatedBranchCode = new map<id,String>();
        for(User u:[SELECT id,UTC__c,Profile.Name, Profile.Id, ProfileId  FROM USER WHERE Id in :leadOweners.values()] ){
            ownersUTCs.put(u.id,u);
            ownersRelatedBranchCode.put(u.id,u.UTC__c);
        }
        
        Set<String> uvsProfiles = new Set<String>();
        
        if(UVS_Profiles__c.getOrgDefaults() != null && UVS_Profiles__c.getOrgDefaults().Profile_Name__c != null)
        {
            for(String str : UVS_Profiles__c.getOrgDefaults().Profile_Name__c.split(';')){
              uvsProfiles.add(str);
            }
        }
        Map<String,id> mapRB = new Map<String,id>();
        for(Ryder_Branch__c rb:[SELECT Id,Branch_Code__c FROM Ryder_Branch__c WHERE Branch_Code__c in : ownersRelatedBranchCode.values()]){
            mapRB.put(rb.Branch_Code__c,rb.Id);
        }
        
        // Update or Assigned UTC Assigned Field only if Owner belongs to UVS Profiles 
        for(lead ld:listLeads){
            if(ownersUTCs.containsKey(ld.ownerId)){ 
               String leadOwenerProfile = ownersUTCs.get(ld.ownerId).Profile.Name;
               if((uvsProfiles.contains(leadOwenerProfile) &&  ownersRelatedBranchCode.containsKey(ld.ownerId))
                  &&(isInsert || (!isInsert && ld.ownerId != mapOld.get(ld.id).ownerId))){
                 String  ownerUTC = ownersRelatedBranchCode.get(ld.ownerId);
                 if(mapRB.containsKey(ownerUTC)){
                   ld.UTC_Assigned__c = mapRB.get(ownerUTC);
                 }
               }else {
                   ld.UTC_Assigned__c = null;
               }
           }
        }
        
    }
    
  	//AAK 04/09/2015 QC 891 Ryder.com Lead to Salesforce (Web to Lead Part 1)   
	public static void createSolutionInterestDetail(List<Solutions_Interest__c> paramlstSI) { 
	
		//Preparing Map for the LeadIds and SolutionInterests. It will be used to pull SI for a lead
		Map<Id, Solutions_Interest__c> mapleadIds = new Map<Id, Solutions_Interest__c>();
	    for(Solutions_Interest__c SI : paramlstSI){
			mapleadIds.put(SI.Lead_Id__c, SI);
	    }
	    system.debug('LeadTriggerHandler --> mapleadIds ' + mapleadIds);	    
	    
	    //Preparing Map for VehicleListType
		Map<Integer, Vehicle_List__c> mapVehicleTypeVehicleList = new Map<Integer, Vehicle_List__c>();
	    for(Vehicle_List__c vehicle : Vehicle_List__c.getAll().values()){
	    	//if (integer.valueOf(vehicle.Vehicle_Name__c.substring(0,3).trim()) < 100)
	        //	mapVehicleTypeVehicleList.put(vehicle.Vehicle_Name__c.substring(0,2),vehicle);
	        //else
	        	mapVehicleTypeVehicleList.put(integer.valueOf(vehicle.Vehicle_Name__c.substring(0,3).trim()),vehicle);	        
	    }
		system.debug('LeadTriggerHandler --> mapVehicleTypeVehicleList ' + mapVehicleTypeVehicleList);	    


		List<String> lstLeadOwnerIds = new List<String>();
	    for(Lead l : [SELECT id, OwnerId  FROM Lead WHERE Id in :mapleadIds.KeySet()]){
			lstLeadOwnerIds.add(l.OwnerId);
	    }
	    system.debug('LeadTriggerHandler --> lstLeadOwnerIds ' + lstLeadOwnerIds);	    

		//To set the profile for a leadowner. The profile will be used to identify UVS related user
		map<id,User> mapleadownersProfile = new map<id,User>();
        for(User u:[SELECT id,UTC__c,Profile.Name, Profile.Id, ProfileId  FROM USER WHERE Id in :lstLeadOwnerIds] ){
            mapleadownersProfile.put(u.id,u);
        }
		system.debug('LeadTriggerHandler --> mapleadownersProfile ' + mapleadownersProfile);		

		//To get the profile exists in the system stored in the Custom Settings for UVS. It will be used to match with the user profile
        Set<String> uvsProfiles = new Set<String>();
        if(UVS_Profiles__c.getOrgDefaults() != null && UVS_Profiles__c.getOrgDefaults().Profile_Name__c != null){
            for(String str : UVS_Profiles__c.getOrgDefaults().Profile_Name__c.split(';')){
              uvsProfiles.add(str);
            }
        }
		system.debug('LeadTriggerHandler --> uvsProfiles ' + uvsProfiles);
		
/*		//Map the information of the lead per unit
		Map<String, Lead> mapLeadUnit = new Map<String, Lead>();
		for(Lead l : [SELECT Id, Is_UVS__c, Unit__c, OwnerId FROM Lead WHERE Id IN :mapleadIds.KeySet()]){
			//system.debug('LeadTriggerHandler --> uvsProfiles contains' + uvsProfiles.contains(mapleadownersProfile.get(l.ownerId).Profile.Name));
			if(mapleadownersProfile.get(l.ownerId).Profile.Name != null)
			{
				if((l.Is_UVS__c == true) && (l.Unit__c != null) && (uvsProfiles.contains(mapleadownersProfile.get(l.ownerId).Profile.Name))){
					mapLeadUnit.put(l.Unit__c, l);
				}
			}
		}
		system.debug('LeadTriggerHandler --> mapLeadUnit ' + mapLeadUnit);
*/

		//Map the information of the lead per unit
		Set<String> setUnits = new Set<String>();
		for(Lead l : [SELECT Id, Is_UVS__c, Unit__c, OwnerId FROM Lead WHERE Id IN :mapleadIds.KeySet()]){
			if(l.Unit__c != null && !setUnits.contains(l.Unit__c)){
				setUnits.add(l.Unit__c);
			}
		}
		system.debug('LeadTriggerHandler --> setUnits ' + setUnits);
		
		//Map the vehicle informatio per unit, the SAM Class info will used to generated SI Detail
		Map<String,Vehicle__c> mapVehList = new Map<String,Vehicle__c>();
		for (Vehicle__c Veh :[SELECT Id, unit__c, SAM_CLASS__c FROM Vehicle__c WHERE Unit__c IN :setUnits]){
			mapVehList.put(Veh.unit__c, Veh);
		}
		system.debug('mapVehList --> mapVehList ' + mapVehList);		
		
		List<Solution_Interest_Detail__c> lstSIDetToBeInsert = new List<Solution_Interest_Detail__c>();
		for(Lead l : [SELECT Id, Is_UVS__c, Unit__c, OwnerId FROM Lead WHERE Id IN :mapleadIds.KeySet() And Is_UVS__c = true AND unit__c != null]){
			Solutions_Interest__c SI =  mapleadIds.get(l.Id);
			integer samClass;
			if(mapVehList.get(l.unit__c).SAM_CLASS__c.isNumeric())
				samClass = integer.valueOf(mapVehList.get(l.unit__c).SAM_CLASS__c);
			else
				samClass = integer.valueOf(mapVehList.get(l.unit__c).SAM_CLASS__c.substring(0,3).trim());			
			system.debug('samClass : ' + samClass);
			Vehicle_List__c vehList = mapVehicleTypeVehicleList.get(samClass);
	        
	        Solution_Interest_Detail__c detailObj = new Solution_Interest_Detail__c();
	        detailObj.Vehicle_Type__c = vehList.Vehicle_Type__c;
	        detailObj.Vehicle_Name__c = vehList.Vehicle_Name__c;
	        detailObj.Solutions_Interest__c = SI.Id;
	        lstSIDetToBeInsert.add(detailObj);		
		}
		system.debug('LeadTriggerHandler --> lstSIDetToBeInsert ' + lstSIDetToBeInsert);		
		
		if(lstSIDetToBeInsert.size() > 0)
			insert lstSIDetToBeInsert;

	}
    
}