SFDC Automation/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>PRODUCT_LINE__c</fullName>
        <label>Product Line</label>
        <picklist>
            <picklistValues>
                <fullName>FSL VOSA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FSL Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FSL Choice Lease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FSL Flex Lease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FSL Fast Track</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RPM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RydeSmart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MMS On Demand</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Web_Lead_Owner__c</fullName>
        <label>Web Lead Owner</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Web_initiated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Web initiated</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/classes/test_LeadManagement_Helper.cls
@isTest (seeAllData=true)
private with sharing class test_LeadManagement_Helper{
    static testMethod void test_LeadManagement_Helper()
    {
        User users = [select Id from User where Name = 'Eloqua Integration' limit 1];
        System.runAs(users)
        {
            Lead l= new Lead();
            l.ownerId = users.Id;
            l.FirstName='Jessica';
            l.LastName='Galindez';
            //l.Web_initiated__c=true;
            l.LeadSource='Cold Call';
            l.Country='US';
            l.State='FL';
            l.Status='Unread';
            //l.RecordTypeId='012P00000008Wbh';
            l.recordtypeid = [select id from recordtype where name = 'Marketing Automation Lead'][0].id;
            l.Company='Home Depot -test method ';
            //l.Web_Lead_Owner__c='11539';
            l.PRODUCT_LINE__c='Rental';
            l.PostalCode = '33144';
            insert(l);
        } 
    }

}