SFDC Automation/src/objects/Lead_Referral__c.object
<CustomObject>
    <description>This object is a SF2SF shared object with the SCS org.</description>
    <fields>
        <fullName>Close_Date__c</fullName>
        <description>Close date of opportunity</description>
        <label>Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FMS_Opportunity_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Lead_Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FMS_Oppty_Amount__c</fullName>
        <label>FMS Oppty Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FMS_Oppty_Created_Date__c</fullName>
        <label>FMS Oppty Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>FMS_Oppty_Name__c</fullName>
        <label>FMS Oppty Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FMS_Oppty_Owner__c</fullName>
        <label>FMS Oppty Owner</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FMS_Oppty_Reason_Won_Lost__c</fullName>
        <label>FMS Oppty Reason/Won/Lost</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FMS_Oppty_Stage__c</fullName>
        <label>FMS Oppty Stage</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FMS_Oppty_Total_Vehicles__c</fullName>
        <label>FMS Oppty Total Vehicles</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FMS_Oppty_Win_Loss_Notes__c</fullName>
        <label>FMS Oppty Win/Loss Notes</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Next_Steps__c</fullName>
        <label>Next Steps</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Referral</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Lead Referral Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>EST_DEAL_VAL__c</fullName>
        <label>Estimated Deal Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Win/Loss Notes</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Num_of_vehicles__c</fullName>
        <inlineHelpText># of Vehicles must be entered on the Opportunity Line Item, or they will roll-up from Rate Sheets/Deal Summaries.</inlineHelpText>
        <label>Total Number of Vehicles</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reason_Won_Lost__c</fullName>
        <inlineHelpText>UVS: Reason Lost Only.</inlineHelpText>
        <label>Reason Won/Lost</label>
        <picklist>
            <controllingField>StageName</controllingField>
            <picklistValues>
                <fullName>Less expensive option available</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsatisfactory maintenance quality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fleet downsizing by a split fleet customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsatisfactory breakdown service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unable to meet business needs/ provide flexibility/ act as partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsatisfactory billing and invoicing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsatisfactory account management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Company declined due to credit- Customer unwilling to agree to credit-related stipulations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insufficient proximity/ convenience of service locations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ryder closed location</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fleet downsizing by a 100% Ryder Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer closed location</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change in transportation model to common carrier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Company declined due to credit-not credit worthy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bankruptcy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Company acquisition or Management change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RIL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Lost - Duplicate Pipeline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Declined due to credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ability to Extend Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change in Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Company out of business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Economic Conditions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fleet Downsize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>I Don&apos;t Know</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>I Don&apos;t Remember</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Issue with Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Length of lease</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/classes/UpdOppDataOnLeadReferralHelper.cls
/*
* 
*   Helper class for the trigger UpdOppDataOnLeadReferral that updates the values of Opp Name, Opp
*   Owner on the Lead Referral record when Opportunity is linked with the Lead Referral record.
*
*   Author                     |Date               |Comment
*   -------------------------|------------------|--------------------------------------------------
*   Saad Wali Jaan    |05.18.2015   |First draft
*
*/
public with sharing class UpdOppDataOnLeadReferralHelper {

    public static void UpdateLeadReferral(List<Lead_Referral__c> lLeadRef, Map<Id, Lead_Referral__c> mapOld, Map<Id, Lead_Referral__c> mapNew) {
        
        system.debug('UODOLRH 1 lLeadRef = ' + lLeadRef);
        system.debug('UODOLRH 2 mapOld = ' + mapOld);
        system.debug('UODOLRH 3 mapNew = ' + mapNew);

        map<id, id> mapLeadRefOpp = new map<id, id>();
        list<id> lstOppId = new list<id>();
        list<Lead_Referral__c> lstLeadRefToUpdate = new list<Lead_Referral__c>(); 
        
        for(Lead_Referral__c lstLeadRef: lLeadRef)
        {
            if(!mapLeadRefOpp.containskey(lstLeadRef.id)) mapLeadRefOpp.put(lstLeadRef.id, mapNew.get(lstLeadRef.id).FMS_Opportunity_Name__c);
            if(mapNew.get(lstLeadRef.id).FMS_Opportunity_Name__c <> null) lstOppId.add(mapNew.get(lstLeadRef.id).FMS_Opportunity_Name__c);            
        }   
        system.debug('UODOLRH 4 - mapLeadRefOpp = ' + mapLeadRefOpp);
        system.debug('UODOLRH 5 - lstOppId = ' + lstOppId);
        
        //list<opportunity> lstOpportunity = [select id, Name, Owner.Name, StageName, EST_DEAL_VAL__c from Opportunity where id in :lstOppId];
        list<opportunity> lstOpportunity = [select id, Name, Owner.Name, StageName, EST_DEAL_VAL__c, CloseDate, NextStep, Num_of_vehicles__c, CreatedDate, Reason_Won_Lost__c, Notes__c from Opportunity where id in :lstOppId];
        system.debug('UODOLRH 6 - lstOpportunity = ' + lstOpportunity);
        
        for(Lead_Referral__c lstLR: lLeadRef)
        {
            system.debug('UODOLRH 7.1 - mapLeadRefOpp.get(lstLR.id) = ' + mapLeadRefOpp.get(lstLR.id));
            if (mapLeadRefOpp.get(lstLR.id)== null)
            {
                system.debug('UODOLRH 7.2');
                //lstLeadRefToUpdate.add(new Lead_Referral__c(id=lstLR.id, FMS_Oppty_Name__c=NULL, FMS_Oppty_Amount__c=NULL, FMS_Oppty_Stage__c=NULL, FMS_Oppty_Owner__c=NULL));
                lstLeadRefToUpdate.add(new Lead_Referral__c(id=lstLR.id, FMS_Oppty_Name__c=NULL, FMS_Oppty_Amount__c=NULL, FMS_Oppty_Stage__c=NULL, FMS_Oppty_Owner__c=NULL, Close_Date__c=NULL, Next_Steps__c=NULL, FMS_Oppty_Total_Vehicles__c=NULL, FMS_Oppty_Created_Date__c=NULL, FMS_Oppty_Reason_Won_Lost__c=NULL, FMS_Oppty_Win_Loss_Notes__c=NULL));                      
            }
            else
            {
                system.debug('UODOLRH 7.3');
                for(Opportunity Opp: lstOpportunity)
                {
                    system.debug('UODOLRH 8 - mapLeadRefOpp.get(lstLR.id) = ' + mapLeadRefOpp.get(lstLR.id) + ' Opp.id = ' + Opp.id);
                    if(mapLeadRefOpp.get(lstLR.id) == Opp.id)
                    {
                        //lstLeadRefToUpdate.add(new Lead_Referral__c(id=lstLR.id, FMS_Oppty_Name__c=Opp.Name, FMS_Oppty_Amount__c=Opp.EST_DEAL_VAL__c, FMS_Oppty_Stage__c=Opp.StageName, FMS_Oppty_Owner__c=Opp.Owner.Name));
                        lstLeadRefToUpdate.add(new Lead_Referral__c(id=lstLR.id, FMS_Oppty_Name__c=Opp.Name, FMS_Oppty_Amount__c=Opp.EST_DEAL_VAL__c, FMS_Oppty_Stage__c=Opp.StageName, FMS_Oppty_Owner__c=Opp.Owner.Name, Close_Date__c=Opp.CloseDate, Next_Steps__c=Opp.NextStep, FMS_Oppty_Total_Vehicles__c=Opp.Num_of_vehicles__c, FMS_Oppty_Created_Date__c=Opp.CreatedDate, FMS_Oppty_Reason_Won_Lost__c=Opp.Reason_Won_Lost__c, FMS_Oppty_Win_Loss_Notes__c=Opp.Notes__c));  
                        system.debug('UODOLRH 9 - lstLeadRefToUpdate = ' + lstLeadRefToUpdate);
                    }
                }
            }
        }
        if (lstLeadRefToUpdate.size() > 0) update lstLeadRefToUpdate; 
    }
    
    public static void UpdateLeadReferralFromOpp(List<Id> lstOppId, Map<Id, Opportunity> mapOld, Map<Id, Opportunity> mapNew, Map<id, Id> mapLeadRefOpp) {
    
        system.debug('UODOLRH 10 lstOppId = ' + lstOppId);
        system.debug('UODOLRH 11 mapOld = ' + mapOld);
        system.debug('UODOLRH 12 mapNew = ' + mapNew);
        system.debug('UODOLRH 13 mapLeadRefOpp = ' + mapLeadRefOpp);
        
        //list<id> lstLeadRefId = new list<id>(mapLeadRefOpp.keyset());
        list<Lead_Referral__c > lstLeadRefId = [Select id from Lead_Referral__c where id in: mapLeadRefOpp.keyset()];
        system.debug('UODOLRH 14 - lstLeadRefId = ' + lstLeadRefId);
        
        list<Lead_Referral__c> lstLeadRefToUpdate = new list<Lead_Referral__c>(); 
        
        list<opportunity> lstOpportunity = [select id, Name, Owner.Name, StageName, EST_DEAL_VAL__c, CloseDate, NextStep, Num_of_vehicles__c, CreatedDate, Reason_Won_Lost__c, Notes__c from Opportunity where id in :lstOppId];
        system.debug('UODOLRH 15 - lstOpportunity = ' + lstOpportunity);
        
        for(Lead_Referral__c lstLR: lstLeadRefId)
        {
            system.debug('UODOLRH 16 - lstLR.id = ' + lstLR.id);
            for(Opportunity Opp: lstOpportunity)
            {
                system.debug('UODOLRH 17 - mapLeadRefOpp.get(lstLR.id) = ' + mapLeadRefOpp.get(lstLR.id) + ' Opp.id = ' + Opp.id);
                if(mapLeadRefOpp.get(lstLR.id) == Opp.id)
                {
                    lstLeadRefToUpdate.add(new Lead_Referral__c(id=lstLR.id, FMS_Oppty_Name__c=Opp.Name, FMS_Oppty_Amount__c=Opp.EST_DEAL_VAL__c, FMS_Oppty_Stage__c=Opp.StageName, FMS_Oppty_Owner__c=Opp.Owner.Name, Close_Date__c=Opp.CloseDate, Next_Steps__c=Opp.NextStep, FMS_Oppty_Total_Vehicles__c=Opp.Num_of_vehicles__c, FMS_Oppty_Created_Date__c=Opp.CreatedDate, FMS_Oppty_Reason_Won_Lost__c=Opp.Reason_Won_Lost__c, FMS_Oppty_Win_Loss_Notes__c=Opp.Notes__c));
                    system.debug('UODOLRH 18 - lstLeadRefToUpdate = ' + lstLeadRefToUpdate);
                }
            }
        }
        if (lstLeadRefToUpdate.size() > 0) update lstLeadRefToUpdate; 
    }
}