SFDC Automation/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Actual_Close_Date__c</fullName>
        <description>Populated with the current date when the Opportunity is marked Signed / Booked / Lost</description>
        <label>Actual Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CMPT_ID__c</fullName>
        <label>Competitor</label>
        <picklist>
            <controllingField>Deal_lost_to_Won_from_whom__c</controllingField>
            <picklistValues>
                <fullName>ComCar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dixie</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enterprise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gatorlease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hogan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hunt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IdealLease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>I don&apos;t know</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interstate Natn&apos;l</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lily</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NationalLease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OEM (pls specify)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other (pls specify)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ownership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PacLease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Penske</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rollins</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ryder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>We need the values here</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Customer_100_Ownership__c</fullName>
        <description>Select Yes if this company owned their entire fleet when we got them, regardless of who was providing maintenance services, or they went to 100% ownership if we lost them. Select No if this company had any portion of their fleet under a lease contract</description>
        <inlineHelpText>Select Yes if this company owned their entire fleet when we got them, regardless of who was providing maintenance services, or they went to 100% ownership if we lost them. Select No if this company had any portion of their fleet under a lease contract</inlineHelpText>
        <label>Customer 100% Ownership</label>
        <picklist>
            <controllingField>Deal_lost_to_Won_from_whom__c</controllingField>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Deal_lost_to_Won_from_whom__c</fullName>
        <label>Deal lost to/ Won from whom</label>
        <picklist>
            <controllingField>Reason_Won_Lost__c</controllingField>
            <picklistValues>
                <fullName>Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ownership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pipeline inactive cleanup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Common Carrier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Competition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not lost. Duplicate pipeline</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Local_Provider_Name__c</fullName>
        <inlineHelpText>Please complete ONLY when selecting &quot;Local Provider&quot; from the Competitor field.</inlineHelpText>
        <label>Local Provider Name</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Win/Loss Notes</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Reason_Won_Lost__c</fullName>
        <inlineHelpText>UVS: Reason Lost Only.</inlineHelpText>
        <label>Reason Won/Lost</label>
        <picklist>
            <controllingField>StageName</controllingField>
            <picklistValues>
                <fullName>Less expensive option available</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsatisfactory maintenance quality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fleet downsizing by a split fleet customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsatisfactory breakdown service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unable to meet business needs/ provide flexibility/ act as partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsatisfactory billing and invoicing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsatisfactory account management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Company declined due to credit- Customer unwilling to agree to credit-related stipulations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insufficient proximity/ convenience of service locations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ryder closed location</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fleet downsizing by a 100% Ryder Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer closed location</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change in transportation model to common carrier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Company declined due to credit-not credit worthy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bankruptcy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Company acquisition or Management change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RIL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Lost - Duplicate Pipeline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Declined due to credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ability to Extend Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change in Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Company out of business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Economic Conditions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fleet Downsize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>I Don&apos;t Know</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>I Don&apos;t Remember</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Issue with Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Length of lease</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Was_this_competitor_the_incumbent__c</fullName>
        <label>Was this competitor the incumbent?</label>
        <picklist>
            <controllingField>CMPT_ID__c</controllingField>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Who_is_the_main_incumbent__c</fullName>
        <label>Who is the Main Incumbent</label>
        <picklist>
            <controllingField>Reason_Won_Lost__c</controllingField>
            <picklistValues>
                <fullName>Ideal Lease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National Lease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ownership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pac Lease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Penske</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ryder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None – Net Fleet Growth</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/classes/OppMultiEdit_Controller.cls
public with sharing class OppMultiEdit_Controller
{
	private Set<ID> sOppIds = new Set<ID>();
	public List<Opportunity> lOpp {get; set;}
	public String sRetURL = '';
	public OppMultiEdit_Controller(ApexPages.StandardSetController Control)
	{
		sRetURL = ApexPages.currentPage().getParameters().get('retURL');		
		system.debug('Nitin-------------->'+Control.getRecords());
		List<Opportunity> lSelectedOpp = Control.getSelected();
		if(lSelectedOpp != null && lSelectedOpp.size() > 0)
		{
			for(Opportunity Opp : lSelectedOpp)
			{
				sOppIds.add(Opp.Id);
			}
			if(sOppIds.size() > 0)
			{
				lOpp = [select Id, Name, Actual_Close_Date__c, AccountId, Account.Name, 
						Reason_Won_Lost__c, Deal_lost_to_Won_from_whom__c, 
						Customer_100_Ownership__c, CMPT_ID__c, StageName, 
						Was_this_competitor_the_incumbent__c, Local_Provider_Name__c, 
						Notes__c, Who_is_the_main_incumbent__c from Opportunity where Id in : sOppIds];
			}
		}
		else
		{
			apexpages.Message msg = new Apexpages.Message(ApexPages.Severity.Info,'Please select at-least one record from List view!');
			apexpages.addmessage(msg);
		}
	}
	public void UpdateData()
	{
		try
		{
			update lOpp;
			apexpages.Message msg = new Apexpages.Message(ApexPages.Severity.Info, 'Records Updated!');
			apexpages.addmessage(msg);
		}
		catch(exception ex)
		{
			apexpages.Message msg = new Apexpages.Message(ApexPages.Severity.Error, ex.getMessage());
			apexpages.addmessage(msg);
		}
	}
}