SFDC Automation/src/objects/Opportunity_Split__c.object
<CustomObject>
    <description>Used to display the National/Coordinated Account and Local Account splits on an opportunity.  This object will be used to perform pipeline reports.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Opportunity for which the Split is valid</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Splits</relationshipLabel>
        <relationshipName>Opportunity_Splits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sales_Team_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Team Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunity_Splits</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Opportunity Split</label>
    <nameField>
        <displayFormat>SPLIT-{000000}</displayFormat>
        <label>Opportunity Split #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Splits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/classes/updateOpportunityTrigger.cls
public with sharing class updateOpportunityTrigger {
    // piyush -- this is not being used see the trigger for comments by mph
	/*
	public static void updateSplitOwnership(map<id,opportunity> newmap, map<id, opportunity> oldmap){
		
		list<id> listIds = new list<id>();
		Opportunity oldopp = null;
		//determine which opportunities need to have their opportunitysplits updated
		for (Opportunity o : newmap.values()){
			oldopp = oldmap.get(o.id);
			if ( !o.isclosed && (oldopp.ownerid != o.ownerid) ){
				listIds.add( o.id );
			}
		}

		list<Opportunity_Split__c> listos = new list<Opportunity_Split__c>();		
		for (Opportunity_Split__c os : [select id, opportunity__c, sales_team_member__c from Opportunity_Split__c where opportunity__c in :listIds]){
			if (os.Sales_Team_Member__c == oldmap.get(os.opportunity__c).ownerid){
				os.sales_team_member__c = newmap.get(os.opportunity__c).ownerid;
				listos.add(os);
			}
		}
		update listos;
	}
*/
}