SFDC Automation/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Actual_Close_Date__c</fullName>
        <description>Populated with the current date when the Opportunity is marked Signed / Booked / Lost</description>
        <label>Actual Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Approved_Date__c</fullName>
        <label>Approved Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Approved__c</fullName>
        <label>Approved</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CMPT_ID__c</fullName>
        <label>Competitor</label>
        <picklist>
            <controllingField>Deal_lost_to_Won_from_whom__c</controllingField>
            <picklistValues>
                <fullName>ComCar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dixie</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enterprise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gatorlease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hogan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hunt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IdealLease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>I don&apos;t know</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interstate Natn&apos;l</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lily</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NationalLease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OEM (pls specify)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other (pls specify)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ownership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PacLease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Penske</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rollins</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ryder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>We need the values here</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Deal_lost_to_Won_from_whom__c</fullName>
        <label>Deal lost to/ Won from whom</label>
        <picklist>
            <controllingField>Reason_Won_Lost__c</controllingField>
            <picklistValues>
                <fullName>Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ownership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pipeline inactive cleanup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Common Carrier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Competition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not lost. Duplicate pipeline</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Local_Provider_Name__c</fullName>
        <inlineHelpText>Please complete ONLY when selecting &quot;Local Provider&quot; from the Competitor field.</inlineHelpText>
        <label>Local Provider Name</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Num_of_vehicles__c</fullName>
        <inlineHelpText># of Vehicles must be entered on the Opportunity Line Item, or they will roll-up from Rate Sheets/Deal Summaries.</inlineHelpText>
        <label>Total Number of Vehicles</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reason_Won_Lost__c</fullName>
        <inlineHelpText>UVS: Reason Lost Only.</inlineHelpText>
        <label>Reason Won/Lost</label>
        <picklist>
            <controllingField>StageName</controllingField>
            <picklistValues>
                <fullName>Less expensive option available</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsatisfactory maintenance quality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fleet downsizing by a split fleet customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsatisfactory breakdown service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unable to meet business needs/ provide flexibility/ act as partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsatisfactory billing and invoicing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsatisfactory account management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Company declined due to credit- Customer unwilling to agree to credit-related stipulations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insufficient proximity/ convenience of service locations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ryder closed location</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fleet downsizing by a 100% Ryder Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer closed location</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change in transportation model to common carrier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Company declined due to credit-not credit worthy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bankruptcy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Company acquisition or Management change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RIL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Lost - Duplicate Pipeline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Declined due to credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ability to Extend Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change in Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Company out of business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Economic Conditions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fleet Downsize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>I Don&apos;t Know</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>I Don&apos;t Remember</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Issue with Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Length of lease</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Who_is_the_main_incumbent__c</fullName>
        <label>Who is the Main Incumbent</label>
        <picklist>
            <controllingField>Reason_Won_Lost__c</controllingField>
            <picklistValues>
                <fullName>Ideal Lease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Provider</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National Lease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ownership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pac Lease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Penske</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ryder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None – Net Fleet Growth</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ext_pipeline_id__c</fullName>
        <externalId>true</externalId>
        <label>Opportunity Number</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/classes/ApproveLargeOppPageController.cls
/****************************************************************************
 *   Date            Name                 Description
 * --------        --------------       ----------------
 * 6/10/2015       Saad Wali Jaan       For displaying Booked Opportunities with More than 10 Units    
 ****************************************************************************/
/*This class is defined to be a controller to the page ApproveLargeOppPage page*/
public with sharing class ApproveLargeOppPageController
{
    private String userId;
    integer intApproveLargeOppCount = integer.valueof(LABEL.ApproveLargeOppCount);
    date dtApproveLargeOppDate = Date.valueOf(LABEL.ApproveLargeOppDate); 

    string strApproveLargeOppStage = LABEL.ApproveLargeOppStage;

    List<string> lstApproveLargeOppStage = new List<string>(strApproveLargeOppStage.remove('\'').split(','));

    //List<string> lstApproveLargeOppStage = new List<string>(strApproveLargeOppStage.split(','));    
        
    public List<Opportunity> lstOpportunity {get;set;}
    
    public ApproveLargeOppPageController(ApexPages.StandardController stdController) 
    {
        System.debug('ALOPC0.0 = ' + strApproveLargeOppStage);
        system.debug('ALOPC0.1 - lstApproveLargeOppStage = ' + lstApproveLargeOppStage );
        system.debug('ALOPC0.2');    
        this.userId = ApexPages.currentPage().getParameters().get('id');
        GetOpportunities();
    }
    
    public void GetOpportunities()
    {
        system.debug('ALOPC0.3');
        lstOpportunity = [select o.Id, o.Name, o.Actual_Close_Date__c, o.AccountId, o.Account.Name, o.Approved__c, o.Approved_Date__c, o.ext_pipeline_id__c, 
                          o.Reason_Won_Lost__c, o.Deal_lost_to_Won_from_whom__c, o.Who_is_the_main_incumbent__c, o.CMPT_ID__c, o.Local_Provider_Name__c,                            
                          o.StageName, o.Num_of_vehicles__c, o.Owner.Name, o.Owner.ManagerId from Opportunity o where o.Owner.ManagerId =:userId and 
                          StageName in: lstApproveLargeOppStage and Num_of_vehicles__c >=: intApproveLargeOppCount and Actual_Close_Date__c >: dtApproveLargeOppDate  
                          and Approved__c = NULL order by Actual_Close_Date__c];
    }
    public void updateOpportunity()
    {
        system.debug('ALOPC0.4');
        List<Opportunity> lstOpportunityUpdate = new List<Opportunity>();
        try
        {
            system.debug('ALOPC5');
            for(Opportunity ops: lstOpportunity )
            {
                if(ops.Approved__c != null)
                {
                    system.debug('ALOPC6');
                    ops.Approved_Date__c = system.today();
                    lstOpportunityUpdate.add(ops);
                }            
            }
            if(lstOpportunityUpdate.size() > 0)
            {
                system.debug('ALOPC7');
                update lstOpportunityUpdate;
                GetOpportunities();                
            }
            else
            {
                system.debug('ALOPC8');
                apexpages.Message msg = new Apexpages.Message(ApexPages.Severity.Info,'Please select at-least one record from List view!');
                apexpages.addmessage(msg);
            }
        }
        catch(exception ex)
        {
            
        }
    }
}