SFDC Automation/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Actual_Close_Date__c</fullName>
        <description>Populated with the current date when the Opportunity is marked Signed / Booked / Lost</description>
        <label>Actual Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Approved_Date__c</fullName>
        <label>Approved Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Approved__c</fullName>
        <label>Approved</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Num_of_vehicles__c</fullName>
        <inlineHelpText># of Vehicles must be entered on the Opportunity Line Item, or they will roll-up from Rate Sheets/Deal Summaries.</inlineHelpText>
        <label>Total Number of Vehicles</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

SFDC Automation/src/classes/ApproveLargeOppSchedule.cls
global class ApproveLargeOppSchedule implements Schedulable {
        global void execute(SchedulableContext sc) {
        
        //Batchable class to create task for Approving Large Opportunities 
        ApproveLargeOppBatch OppBatch = new ApproveLargeOppBatch(); 
        //OppBatch.query='select Id, Name, Actual_Close_Date__c, AccountId, Account.Name, Approved__c, Approved_Date__c, StageName, Num_of_vehicles__c, Owner.Name, Owner.ManagerId from Opportunity where StageName = \'Booked\' and Num_of_vehicles__c >= ' + LABEL.ApproveLargeOppCount + ' and Actual_Close_Date__c > ' + LABEL.ApproveLargeOppDate + ' and Approved__c = NULL Order by Actual_Close_Date__c';
        OppBatch.query='select Id, Name, Actual_Close_Date__c, AccountId, Account.Name, Approved__c, Approved_Date__c, StageName, Num_of_vehicles__c, Owner.Name, Owner.ManagerId from Opportunity where Num_of_vehicles__c >= ' + LABEL.ApproveLargeOppCount + ' and Actual_Close_Date__c > ' + LABEL.ApproveLargeOppDate + ' and StageName in (' + LABEL.ApproveLargeOppStage + ') and Approved__c = NULL Order by Actual_Close_Date__c';        
        database.executebatch(OppBatch,100);
      }
}