SFDC Automation/src/objects/PartialWinRateSheet__c.object
<CustomObject>
    <description>Contains the list of Rate Sheets which were not booked</description>
    <fields>
        <fullName>IsProcessed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To mark the records as processed once user submit button</description>
        <label>IsProcessed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>PartialWinRateSheets</relationshipLabel>
        <relationshipName>PartialWinRateSheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>PartialWinRateSheet</label>
    <nameField>
        <label>PartialWinRateSheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PartialWinRateSheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/classes/test_PW_CreateTask_Scheduled.cls
@isTest
Private Class test_PW_CreateTask_Scheduled{
    static testmethod void unitTest(){
    Test.startTest();
    
    PW_CreateTask ruvb = new PW_CreateTask();
    //ruvb.query='SELECT Opportunity__c FROM PartialWinRateSheet__c WHERE CreatedDate = TODAY AND IsProcessed__c = false GROUP BY Opportunity__c';  
    Database.executeBatch(ruvb);
        
    PW_CreateTask_Scheduled Sb1 = new PW_CreateTask_Scheduled();
    SchedulableContext scq;
    Sb1.execute(scq);  
    
    Test.StopTest();
    }
}