SFDC Automation/src/objects/Profile_Default_Products__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Default_Product__c</fullName>
        <label>Default Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Profile Default Products</label>
</CustomObject>

SFDC Automation/src/objects/Solutions_Interest__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Id</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Solutions Interests</relationshipLabel>
        <relationshipName>Solutions_Interests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead Id</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Solutions Interests</relationshipLabel>
        <relationshipName>Solutions_Interests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <label>Product Line</label>
        <picklist>
            <picklistValues>
                <fullName>Lease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RydeSmart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Used Vehicles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ryder Fleet Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dedicated Carrier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fuel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supply Chain &amp; Logistics</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>-- None --</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unread</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renurture</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Solutions Interest</label>
    <nameField>
        <label>Solutions Interest ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions Interests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC Automation/src/classes/ContactTriggerHandler.cls
/*************************************************************************************************
Created By:    Sunil Gupta
Date:          August 28, 2014
Description  : Handler class for Contact Trigger
**************************************************************************************************/
public class ContactTriggerHandler {

  // Create Solution Interest record.
  public static void createSolutionInterest(Map<Id, Contact> mapNew) {
    // prepare map for profile names.
    Set<Id> ownerIds = new Set<Id>();
    Map<Id, String> mapProfiles = new Map<Id, String>();
    for(Contact c :mapNew.values()){
      if(String.valueOf(c.OwnerId).startsWith('005')){
        ownerIds.add(c.OwnerId);
      }
    }

    Map<Id, String> mapProfileNames = new Map<Id, String>();
    for(User u :[SELECT Profile.Name FROM User WHERE Id IN :ownerIds]){
      mapProfileNames.put(u.Id, u.Profile.Name);
    }

    Map<String, Profile_Default_Products__c> mapPDP = Profile_Default_Products__c.getAll();


    // Existing Solution Interest record for available contacts.
    Set<Id> existingContacts = new Set<Id>();
    for(Solutions_Interest__c si :[SELECT Id, Lead_Id__c, Product_Line__c
                                                 FROM Solutions_Interest__c
                                                 WHERE Contact_Id__c IN :mapNew.keySet()]){
      if(si.Contact_Id__c != null){
      	existingContacts.add(si.Contact_Id__c);
      }
    }
    System.debug('@@@' + existingContacts);



    // create solution interest record.
    List<Solutions_Interest__c> lstSI = new List<Solutions_Interest__c>();
    for(Contact c :mapNew.values()){
    	if(existingContacts.contains(c.Id) == false){
        	Solutions_Interest__c si = new Solutions_Interest__c();
        	si.Contact_Id__c = c.Id;
        	si.Stage__c = 'Qualified';
        	if(String.valueOf(c.OwnerId).startsWith('005')){ // RA: We can ignore this condition
          		if(mapProfileNames.get(c.OwnerId) != null){
            		if(mapPDP.get(mapProfileNames.get(c.OwnerId)) != null){
              			si.Product_Line__c = mapPDP.get(mapProfileNames.get(c.OwnerId)).Default_Product__c;
            		}
          		}
        	}
        	lstSI.add(si);
      	}

    }
    System.debug('@@@' + lstSI);
    insert lstSI;
  }



}