SFDC Automation/src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Base__c</fullName>
        <label>Base</label>
        <precision>18</precision>
        <scale>8</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Interest_Rate__c</fullName>
        <label>Interest Rate</label>
        <picklist>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5.5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <label>Term</label>
        <picklist>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>36</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>42</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>48</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>54</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/QuoteLineItemHistory__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <length>8000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Field__c</fullName>
        <label>Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NewValue__c</fullName>
        <label>NewValue</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OldValue__c</fullName>
        <label>OldValue</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Line Item</label>
        <referenceTo>QuoteLineItem</referenceTo>
        <relationshipLabel>Quote Line Item History</relationshipLabel>
        <relationshipName>QuoteLineItemHistorys</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>QuoteLineItemHistory</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>QuoteLineItemHistory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QuoteLineItemHistorys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC Automation/src/classes/QuoteLineItemTriggerHandler.cls
/*************************************************************************************************
Created By:    Sunil Gupta
Date:          September 11, 2014
Description  : Handler class for QuoteLineItem Trigger
**************************************************************************************************/

public class QuoteLineItemTriggerHandler {

  // Create Quote Line Item History Records.
  public static void createHistoryRecords(Map<Id, QuoteLineItem> newMap ,Map<Id, QuoteLineItem> oldMap) {

    List<QuoteLineItemHistory__c> lstItems = new List<QuoteLineItemHistory__c>();
    for(QuoteLineItem item :newMap.values()){
        if(oldMap == null || oldMap.get(item.Id).UnitPrice != item.UnitPrice){
            QuoteLineItemHistory__c obj = new QuoteLineItemHistory__c();
        obj.Field__c = 'UnitPrice__c';
        if(oldmap == null){
          obj.OldValue__c = '0.00';
        }
        else{
            obj.OldValue__c = String.valueOf(oldMap.get(item.Id).UnitPrice);
        }
        obj.NewValue__c = String.valueOf(item.UnitPrice);
        obj.Action__c = 'Changed from ' + obj.OldValue__c + ' to ' + obj.NewValue__c;
        obj.Quote_Line_Item__c = item.Id;
        lstItems.add(obj);
        }
    }

    try{
        System.debug('@@@' + lstItems);
        insert lstItems;
    }
    catch(Exception ex){
        System.debug(ex.getMessage());
    }
  }

  public static void calculateBase(List<QuoteLineItem> listQli){
    for(QuoteLineItem qli : listQli){
        if(qli.Interest_Rate__c <> null && qli.Term__c <> null){
          qli.Base__c = calculateBaseValue(qli.Interest_Rate__c, qli.Term__c);
        }
    }
  }

  public static double calculateBaseValue(String InterestRate, String term){
      Double base = 1.0000000000;
      Double mbase = 1.0000000000 + (Decimal.ValueOf(InterestRate )/ 1200);
      system.debug('********mbase***'+mbase);
      for(integer i=0; i < Integer.ValueOf(term); i++){
        base = base * mbase;
        system.debug('********base***'+base);
      }
      return base;
  }
}