SFDC Automation/src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Approved_Price__c</fullName>
        <label>Approved Price</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Approved_to_take__c</fullName>
        <formula>Approved_Price__c/Take_Price2__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Approved % to take</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>As_Is_Vehicle__c</fullName>
        <description>Vehicle&apos;s AsIs field value</description>
        <formula>Vehicle__r.AS_IS_Vehicle__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>As Is Vehicle</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BankOfAmerica__c</fullName>
        <formula>Vehicle__r.BankOfAmerica__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BankOfAmerica</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Book_Value__c</fullName>
        <formula>Vehicle__r.NBV__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Book Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Branch_Name__c</fullName>
        <description>Vehicle Branch Name</description>
        <formula>Vehicle__r.Branch_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Branch Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Offer_Price__c</fullName>
        <label>Customer Offer Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Days_held__c</fullName>
        <formula>Vehicle__r.Days_At_UTC__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days held</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Display_Code__c</fullName>
        <formula>Vehicle__r.display_code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Display Code</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Eng_Mdl__c</fullName>
        <description>Vehicle Engine Model</description>
        <formula>Vehicle__r.ENG_MDL__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Engine Model</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gain_Loss__c</fullName>
        <formula>UnitPrice - Book_Value__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Gain (Loss)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Make_Model__c</fullName>
        <description>Concatenation of Vehicle.Manufacturer__c and Vehicle.Model__c</description>
        <formula>Vehicle__r.Manufacturer__c &amp; &apos; &apos; &amp; Vehicle__r.Model__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Make/Model</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Meq_sale_prc_am__c</fullName>
        <formula>Vehicle__r.meq_sale_prc_am__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Meq sale prc am</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Model_Year__c</fullName>
        <formula>TEXT(Vehicle__r.Model_Year__c)</formula>
        <label>Model Year</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NVI_Percent__c</fullName>
        <description>NVI Percentage</description>
        <formula>(UnitPrice* 10000) / Vehicle__r.NVI__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NVI %</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>NVI__c</fullName>
        <description>Vehicle NVI</description>
        <formula>Vehicle__r.NVI__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NVI</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NonCompliantCAUnits__c</fullName>
        <formula>Vehicle__r.NonCompliantCAUnits__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NonCompliantCAUnits</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Overstock__c</fullName>
        <formula>Vehicle__r.Overstock__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Overstock</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SAM_Class__c</fullName>
        <formula>Vehicle__r.SAM_CLASS__c &amp; &apos; &apos; &amp; Vehicle__r.VEH_CLS_SAM_DS__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SAM Class</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SpecialPrice__c</fullName>
        <formula>Vehicle__r.SpecialPrice__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SpecialPrice</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Take_Price2__c</fullName>
        <label>Take Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Take_Price_percent__c</fullName>
        <formula>UnitPrice/Take_Price2__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Take Price (%)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vosa__c</fullName>
        <formula>Vehicle__r.VOSA__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Vosa</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <fields>
        <fullName>AS_IS_Vehicle__c</fullName>
        <defaultValue>false</defaultValue>
        <label>AS IS Vehicle</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Approved_Price__c</fullName>
        <label>Approved Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Ask_Price__c</fullName>
        <label>Ask Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BankOfAmerica__c</fullName>
        <defaultValue>false</defaultValue>
        <label>BankOfAmerica</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Branch_Name__c</fullName>
        <label>Branch Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ENG_MDL__c</fullName>
        <label>Engine Model</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gain_Loss__c</fullName>
        <label>Gain Loss</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Model_Year__c</fullName>
        <description>Year of the vehicle</description>
        <label>Model Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NBV__c</fullName>
        <label>Book Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NVI__c</fullName>
        <description>Net Vehicle Investment</description>
        <label>NVI</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NonCompliantCAUnits__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NonCompliantCAUnits</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Odometer__c</fullName>
        <label>Odometer</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Overstock__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Overstock</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SAM_CLASS__c</fullName>
        <description>Sam Class</description>
        <label>SAM Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAM_Odom__c</fullName>
        <label>SAM Odom</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sold_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field to indicate whether a vehicle has been sold and not available in the inventory.</description>
        <inlineHelpText>Field to indicate whether a vehicle has been sold and not available in the inventory.</inlineHelpText>
        <label>Sold Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SpecialPrice__c</fullName>
        <label>SpecialPrice</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Take_Price_Percent__c</fullName>
        <formula>IF(Ask_Price__c &gt; 0, Take_Price__c / Ask_Price__c, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Take Price (%)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>VOSA__c</fullName>
        <defaultValue>false</defaultValue>
        <label>VOSA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>display_code__c</fullName>
        <defaultValue>false</defaultValue>
        <label>display_code</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>meq_sale_prc_am__c</fullName>
        <defaultValue>0</defaultValue>
        <description>sold</description>
        <label>meq_sale_prc_am</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/UVS_QLIRelatedList.cls
/**=============================================================================
 * Created By: Nimisha (Appirio, Inc)
 * Created Date: [09/24/2014]
 * Description: Controller for inLine VF Page in Quote related list. (T-321414)


==============================================================================*/
public with sharing class UVS_QLIRelatedList {

  public ApexPages.StandardSetController sc {get; set;}
  public Id deleteRecordId{get;set;}
  public Quote quote{get;set;}
  public List<QuoteLineItem> qliList{get;set;}
  public list<QliColorCode> qliColorList{get;set;}
  public UAT_Total uatTotal{get;set;}
  public QuoteLineItem totalOfAllItems{get;set;}
  public Vehicle__c vehicleTemp{get;set;}

  public UVS_QLIRelatedList(ApexPages.StandardController sc) {
    this.quote = (Quote)sc.getRecord();
    uatTotal = new UAT_Total();
    vehicleTemp = new Vehicle__c();
    totalOfAllItems = new QuoteLineItem();
    fetchRecords(quote);
  }
  private void fetchRecords(Quote quote){
    qliColorList = new list<QliColorCode>();
    //AAK 03/10/2015 Start - updated the odometer__c to SAM_Odom__c
    for(QuoteLineItem qli:[Select ServiceDate, NVI_Percent__c, Make_Model__c, Eng_Mdl__c, Quantity, ListPrice, Description, Vosa__c,
                            UnitPrice, Take_Price2__c, SAM_Class__c,
                            Model_Year__c, Gain_Loss__c, Days_held__c, Book_Value__c, Approved_to_take__c, Approved_Price__c, BankOfAmerica__c,
                            SpecialPrice__c, Display_Code__c, NonCompliantCAUnits__c, Overstock__c, Meq_sale_prc_am__c, Vehicle__c, Vehicle__r.Name,
                            Vehicle__r.NVI__c, Vehicle__r.Branch_Name__c, Vehicle__r.SAM_Odom__c, Take_Price_percent__c, Vehicle__r.AS_IS_Vehicle__c,
                            NVI__c, Vehicle__r.Sold_Flag__c, AS_IS_Vehicle__c 
                           From QuoteLineItem
                           WHERE QuoteId = :quote.Id]) {
      qliColorList.add(new QliColorCode(qli,false));
      
      if(qli.NVI_Percent__c != null){
        uatTotal.total_NVI += qli.NVI__c;
      }
      if(qli.Book_Value__c != null){
        uatTotal.total_BookValue += qli.Book_Value__c;
      }
      if(qli.UnitPrice != null){
        uatTotal.total_SalesPrice += qli.UnitPrice;
      }
      
      if(qli.Take_Price2__c != null){
        uatTotal.total_TakePrice += qli.Take_Price2__c;
      }
      
      
      if(qli.Gain_Loss__c != null){
        uatTotal.total_GainLoss += qli.Gain_Loss__c;
      }
      
      if(qli.Approved_Price__c != null){
        uatTotal.total_ApprovedPrice += qli.Approved_Price__c;
      }
      
    }
    
    QuoteLineItem lastRowDummyItem = new QuoteLineItem();
    qliColorList.add(new QliColorCode(lastRowDummyItem,true));
    
    vehicleTemp.NBV__c = uatTotal.total_BookValue;
    vehicleTemp.Ask_Price__c = uatTotal.total_SalesPrice;
    totalOfAllItems.Take_Price2__c =  uatTotal.total_TakePrice;
    totalOfAllItems.Customer_Offer_Price__c = uatTotal.total_GainLoss;
    totalOfAllItems.Approved_Price__c = uatTotal.total_ApprovedPrice;
    
    
    Decimal d= 0.0;
    
    if(uatTotal.total_NVI != 0){
      d = (uatTotal.total_SalesPrice/uatTotal.total_NVI)*100;
      uatTotal.total_NVIPer = d.setScale(2);
    }
    
    if(uatTotal.total_TakePrice != 0){
      d = (uatTotal.total_SalesPrice/uatTotal.total_TakePrice)*100;
      uatTotal.total_TakePricePer = d.setScale(2);
    }
    
    if(uatTotal.total_TakePrice != 0){
      d = (uatTotal.total_ApprovedPrice/uatTotal.total_TakePrice)*100;
      uatTotal.total_ApprovedPerofTake = d.setScale(2);
    }


  }

  public PageReference deleteRecord(){
    list <QuoteLineItem> qlidel = [SELECT Id
                                   FROM QuoteLineItem
                                   WHERE id = :deleteRecordId] ;
    if(!qlidel.isEmpty()) {
        delete qlidel;
    }
    return null;
  }

 // Wrapper class used in visualforce page to display Totals
  public class UAT_Total{
    public Double total_NVI{get;set;}
    public Double total_NVIPer{get;set;}
    public Double total_BookValue{get;set;}
    public Double total_SalesPrice{get;set;}
    public Double total_TakePrice{get;set;}
    public Double total_TakePricePer{get;set;}
    public Double total_GainLoss{get;set;}
    public Double total_ApprovedPrice{get;set;}
    public Double total_ApprovedPerofTake{get;set;}
    
    public UAT_Total(){
      this.total_NVI=0.0;
      this.total_NVIPer = 0.0;
      this.total_BookValue = 0.0;
      this.total_SalesPrice = 0.0;
      this.total_TakePrice = 0.0;
      this.total_TakePricePer = 0.0;
      this.total_GainLoss = 0.0;
      this.total_ApprovedPrice = 0.0;
      this.total_ApprovedPerofTake = 0.0;
    }
  }

  // Wrapper class used in visualforce page to display result
  public class QliColorCode {
    public QuoteLineItem qliWrap{get;set;}
    public String color{get;set;}
    public boolean isLastRow{get;set;}
    public QliColorCode(QuoteLineItem qli,Boolean isLastRow) {
      qliWrap = qli;
      color = getColorCode(qli,isLastRow);
      this.isLastRow = isLastRow;
    }

    // helper method to get color code
     private String getColorCode(QuoteLineItem q,boolean isLastRow) {
      String colorCode = '#E0E0E0';
      if(isLastRow){
        colorCode = 'cadetblue';
        return colorCode;
      }
      
      if(q.OverStock__c <> false) {
        colorCode = '#00cc00';
      }
      
      if(q.SpecialPrice__c <> null && q.SpecialPrice__c <> 0.00) {
        colorCode = '#ccffff';
      }

      //if(q.Display_Code__c == true) {
        //colorCode = '#ffff99';
      //}
      
      if(q.AS_IS_Vehicle__c == true) {
        colorCode = '#ffff99';
      }

      if(q.Vehicle__r.Sold_Flag__c != NULL && q.Vehicle__r.Sold_Flag__c) {
        colorCode = '#FF3333';
      }

      if(q.BankOfAmerica__c == true) {
        colorCode = '#FF8040';
      }

      if(q.NonCompliantCAUnits__c  == true) {
        colorCode = '#7fe57f';
      }
      
      return colorCode ;
    }
  }
}