SFDC Automation/src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Selected_Image1__c</fullName>
        <label>Selected Image1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Selected_Image2__c</fullName>
        <label>Selected Image2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Selected_Image3__c</fullName>
        <label>Selected Image3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Selected_Image4__c</fullName>
        <label>Selected Image4</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Selected_Image5__c</fullName>
        <label>Selected Image5</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>UVS</fullName>
        <active>true</active>
        <description>Used vehicle Sales</description>
        <label>UVS</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Approval_Level__c</fullName>
        <description>0 (No approval required), 1 (FAM), 2 (DAM) and 3 (VP AM )</description>
        <label>Approval Level</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Display_Code__c</fullName>
        <formula>Vehicle__r.display_code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Display Code</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Interest_Rate__c</fullName>
        <label>Interest Rate</label>
        <picklist>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16.5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5.5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Overstock__c</fullName>
        <formula>Vehicle__r.Overstock__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Overstock</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SpecialPrice__c</fullName>
        <formula>Vehicle__r.SpecialPrice__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SpecialPrice</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <label>Term</label>
        <picklist>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>36</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>42</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>48</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>54</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>VehicleImage1__c</fullName>
        <label>VehicleImage1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VehicleImage2__c</fullName>
        <label>VehicleImage2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VehicleImage3__c</fullName>
        <label>VehicleImage3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/RyderConfig__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Provides configuration information for Ryder</description>
    <label>Ryder Config</label>
</CustomObject>

SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup on Accounts</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Overstock__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Overstock</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SpecialPrice__c</fullName>
        <label>SpecialPrice</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>display_code__c</fullName>
        <defaultValue>false</defaultValue>
        <label>display_code</label>
        <type>Checkbox</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <recordTypes>
        <fullName>UVS</fullName>
        <active>true</active>
        <description>Record Type for UVS Vehicles</description>
        <label>UVS</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/ImageSelectorController_V1Test.cls
/**=====================================================================
 * Appirio, Inc
 * Name: ImageSelectorController_V1Test
 * Description: Test class for controller class ImageSelectorController_V1
 * Created Date: [12/26/2014]
 * Created By: [Rajeev Arya] (Appirio)
 * Date Modified                Modified By                  Description of the update
 
 =====================================================================*/
@isTest
private class ImageSelectorController_V1Test {

    static Quote quo = new Quote();
    
    private static void createTestData(){
        
        RyderConfig__c rdc = TestUtilUVS.createRyderConfig(true);
        
        Product2 prod = new Product2();
        prod.Name = 'testUVS123';
        prod.CurrencyIsoCode = 'USD';
        prod.IsActive = true;
        insert prod;
        
        PriceBookEntry pbe = [SELECT Id, Pricebook2Id
            FROM PriceBookEntry
            WHERE Product2Id = : prod.Id
            LIMIT 1
        ];
        pbe.isActive = true;
        update pbe;
        
        quo = TestUtilUVS.createQuote('UVS', false);
        quo.Selected_Image1__c = 'http://vehicleimages.ryder.com//images/300294.jpg';
        quo.Selected_Image2__c = 'http://vehicleimages.ryder.com//images/300294-1.jpg';
        quo.Selected_Image3__c = 'http://vehicleimages.ryder.com//images/300294-2.jpg';
        quo.Selected_Image4__c = 'http://vehicleimages.ryder.com//images/300294-3.jpg';
        quo.Selected_Image5__c = 'http://vehicleimages.ryder.com//images/300044.jpg';
        quo.Pricebook2Id = pbe.Pricebook2Id;
        insert quo;
        
        
        list < Vehicle__c > veh1 = TestUtilUVS.createVehList(false);
        //veh1[0].Account__c = acc.id;
        veh1[0].Overstock__c = false;
        veh1[0].SpecialPrice__c = null;
        veh1[0].Display_Code__c = false;
        insert veh1[0];
        
        QuoteLineItem q = new QuoteLineItem();
        q.Interest_Rate__c = '12';
        q.Term__c = '12';
        q.PriceBookEntryId = pbe.Id;
        q.Quantity = 1;
        q.UnitPrice = 123;
        q.Vehicle__c = veh1[0].Id;
        q.Approval_Level__c = 3;
        q.QuoteId = quo.Id;
        q.VehicleImage1__c = 'http://vehicleimages.ryder.com//images/300294-4.jpg';
        q.VehicleImage2__c = 'http://vehicleimages.ryder.com//images/300294-5.jpg';
        q.VehicleImage3__c = 'http://vehicleimages.ryder.com//images/300294-6.jpg';
        insert q;
    }
    
    static testMethod void ControllerTest(){
       
        createTestData();
        Test.startTest();
                    
        RyderGlobalVariables.IS_TEST = true;
       
        PageReference quotePage = Page.QuoteVehicleImages_V1;
        Test.setCurrentPage(quotePage);
                    
        // Set the model action
        ApexPages.currentPage().getParameters().put('quoteId', quo.Id);

        // Create a standard controller 
        ApexPages.Standardcontroller controller = new ApexPages.Standardcontroller(quo); 
        
        //create instance of pages controller
        ImageSelectorController_V1 ImageSelector = new ImageSelectorController_V1(controller);
        //ImageSelectorController_V1.init();
        Test.stopTest();
        
        ImageSelectorController_V1.VehImageWrapper wrap=new ImageSelectorController_V1.VehImageWrapper();
        wrap.imageSelect=true;
        ImageSelector.getorderOptions();
        ImageSelector.removeOpt();
        ImageSelector.validateImageUrl();
        ImageSelector.saveImageUrl();
        ImageSelector.vehMap.put('Test1','1');
        List<String> vehPaths = new List<String>();
        vehPaths.add('Test1');
        ImageSelector.allVehPaths.addall(vehPaths);
        ImageSelector.vehPathsMap.put('1',vehPaths);
        wrap.imageSelect = false;
        wrap.imageURL = 'Test1';
        wrap.vehNo = 'Test1';
        ImageSelector.vehImageWrap.add(wrap);
        ImageSelector.saveImageUrl();
        ImageSelector.closePopup();
        ImageSelector.showPopup();
        ImageSelector.cancel();
          
        ImageSelector.vehiclePaths();
    
    }
}