SFDC Automation/src/objects/RSM_PO__c.object
<CustomObject>
    <description>Object to store Purchase Order header data</description>
    <fields>
        <fullName>DateOrdered__c</fullName>
        <label>DateOrdered</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DateReceived__c</fullName>
        <label>DateReceived</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DateShipped__c</fullName>
        <label>DateShipped</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Unit_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit #</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>RSM POs</relationshipLabel>
        <relationshipName>RSM_POs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RSM PO</label>
    <nameField>
        <label>Customer Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RSM POs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <fields>
        <fullName>RSM_Order_Status__c</fullName>
        <description>Field to store RydeSmart order information</description>
        <label>Order Status</label>
        <picklist>
            <picklistValues>
                <fullName>Ordered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/RSMUpdateOrderStatusBatch.cls
//Batch Class to update order Status in Account from PO
global class RSMUpdateOrderStatusBatch implements Database.Batchable<SObject>{

  public String query;
  global Database.QueryLocator start(Database.BatchableContext BC){
      System.debug('query : '+query);
      return Database.getQueryLocator(query);
   }
   
   global void execute(Database.BatchableContext BC, List<RSM_PO__c> scope){
      Map<Id,Vehicle__c> updateVehicleMap=new Map<Id,Vehicle__c>();
      
      for(RSM_PO__c po:scope){
          if(po.Unit_Number__c!=null){
              Vehicle__c v=new Vehicle__c(Id=po.Unit_Number__c);  
              if(po.DateReceived__c!=null){
                  v.RSM_Order_Status__c='Received';
              }else if(po.DateShipped__c!=null){
                  v.RSM_Order_Status__c='Shipped';
              }else if(po.DateOrdered__c!=null){
                  v.RSM_Order_Status__c='Ordered';
              }  
              updateVehicleMap.put(po.Unit_Number__c,v); 
          }
      }
      if(updateVehicleMap!=null && updateVehicleMap.values().size()>0){
          update updateVehicleMap.values();
      }
 
    }

   global void finish(Database.BatchableContext BC){
   }
}