SFDC Automation/src/objects/RSM_Contract__c.object
<CustomObject>
    <description>Object to store RydeSmart Contract details</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to store the ID of the Account with which the Contract is related. This field will be populated from database based on the Lessee No in the contract</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>RSM Contracts</relationshipLabel>
        <relationshipName>RSM_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Number__c</fullName>
        <externalId>true</externalId>
        <label>Contract Number</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status_Name__c</fullName>
        <label>Status Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>RSM Contract</label>
    <nameField>
        <label>RSM Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RSM Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC Automation/src/objects/RSM_ContractDetail__c.object
<CustomObject>
    <description>The object stores the details of the contract</description>
    <fields>
        <fullName>Action_Name__c</fullName>
        <label>Action Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract_Number__c</fullName>
        <label>Contract Number</label>
        <referenceTo>RSM_Contract__c</referenceTo>
        <relationshipName>ContractNumber</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Current__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Current</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Name__c</fullName>
        <label>Service Name</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Number</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipName>RSContractDetails</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RSM ContractDetail</label>
    <nameField>
        <label>RSM ContractDetailID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RSM ContractDetails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup on Accounts</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RSM_Addition_Service_prior_count__c</fullName>
        <label>RSM Addition Service prior count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RSM_Additional_Services__c</fullName>
        <label>Additional Services</label>
        <picklist>
            <picklistValues>
                <fullName>Business Intelligence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Safety Analytics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Navigation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Speed gauge</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>RSM_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>RSM Service field will let you know whether the vehicle is using RydeSmart service or not.</description>
        <label>RydeSmart Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RSM_Service_Level_Change__c</fullName>
        <description>Field to capture if the vehicle is Upgraded or Downgraded (The logic is calculated based on Service level and Additional Service level)</description>
        <label>RSM Service Level Change</label>
        <picklist>
            <picklistValues>
                <fullName>Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Downgrade</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RSM_Service_Level_Prior_value__c</fullName>
        <label>RSM Service Level Prior value</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RSM_Service_Level__c</fullName>
        <description>Displays Service Level of the vehicle</description>
        <label>Service Level</label>
        <picklist>
            <picklistValues>
                <fullName>Plus 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>STD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RSM_Service_level_Change_Date__c</fullName>
        <description>Field to capture the date when RSM Service level changed</description>
        <label>RSM Service level Change Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RSM__c</fullName>
        <description>Displays RydeSmart contract status</description>
        <label>RS Contract Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Printed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to SSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by SSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deleted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <externalId>true</externalId>
        <label>Unit Number</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/RSMUpdateVehicleBatch.cls
//Batch Class to update fields RS Customer, Service level & RS contract Status in vehicle page
global class RSMUpdateVehicleBatch implements Database.Batchable<SObject>{

  public String query;
  global Database.QueryLocator start(Database.BatchableContext BC){
      return Database.getQueryLocator(query);
   }
   
   global void execute(Database.BatchableContext BC, List<RSM_ContractDetail__c> scope){

      boolean clearVal = false;
      Set<String> vehicleSet=new Set<String>();
      Map<String,Vehicle__c> vehicleMap=new Map<String,Vehicle__c>();
      Map<String,Vehicle__c> updateVehicleMap=new Map<String,Vehicle__c>();
      for(RSM_ContractDetail__c cd:scope){    
          vehicleSet.add(cd.Unit_Number__c); 
      }
      List<Vehicle__c> lstVehicle=[select Id,Unit__c from Vehicle__c where Id in:vehicleSet ];
      for(Vehicle__c  v: lstVehicle){     
          vehicleMap.put(v.Id,v);
      }    
     
      for(RSM_ContractDetail__c cd:scope){
          clearVal = false;
          system.debug('Saad 1 cd.Unit_Number__r.id = ' + cd.Unit_Number__c);
          if(cd.Action_Name__c != 'Cancel'){
            system.debug('Saad 2');          
              if(cd.Unit_Number__r.Account__c == cd.Contract_Number__r.Account__c)
              {
                  system.debug('Saad 3');
                  If(cd.Is_Current__c == true)
                  {
                      system.debug('Saad 4 cd.Service_Name__c = '+cd.Service_Name__c);
                      //Vehicle__c v=new Vehicle__c(Id=vehicleMap.get(cd.Unit_Number__c).Id,RSM_Customer__c=true,RSM_Service_Level__c=cd.Service_Name__c,RSM__c=cd.Contract_Number__r.Status_Name__c);
                      Vehicle__c v=new Vehicle__c(Id=cd.Unit_Number__r.id, RSM_Customer__c=true, RSM_Service_Level__c=cd.Service_Name__c,RSM__c=cd.Contract_Number__r.Status_Name__c);
                      updateVehicleMap.put(v.Id,v);
                  }
              }
              else
              {
                  system.debug('Saad 5');
                  clearVal = true;
              }
          } 
          else
          {
              system.debug('Saad 6');
              If(cd.Is_Current__c == true)
              {
                  system.debug('Saad 7');              
                  clearVal = true;
              }
          }
          if (clearVal == true)
          {
              system.debug('Saad 8');
              //Vehicle__c v=new Vehicle__c(Id=vehicleMap.get(cd.Unit_Number__c).Id,RSM_Customer__c=false,RSM_Service_Level__c='',RSM_Service_Level_Prior_value__c='',RSM__c=cd.Contract_Number__r.Status_Name__c,RSM_Additional_Services__c='',RSM_Service_Level_Change__c='',RSM_Service_level_Change_Date__c=NULL,RSM_Addition_Service_prior_count__c=0);
              Vehicle__c v=new Vehicle__c(Id=cd.Unit_Number__r.id,RSM_Customer__c=false,RSM_Service_Level__c='',RSM_Service_Level_Prior_value__c='',RSM__c=cd.Contract_Number__r.Status_Name__c,RSM_Additional_Services__c='',RSM_Service_Level_Change__c='',RSM_Service_level_Change_Date__c=NULL,RSM_Addition_Service_prior_count__c=0);
              
              updateVehicleMap.put(v.Id,v);
          }
     }
     system.debug('Saad 9');
     update updateVehicleMap.values();
     system.debug('Saad 10');     
   }

   global void finish(Database.BatchableContext BC){
   }
}