SFDC Automation/src/objects/RSM_Contract__c.object
<CustomObject>
    <description>Object to store RydeSmart Contract details</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to store the ID of the Account with which the Contract is related. This field will be populated from database based on the Lessee No in the contract</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>RSM Contracts</relationshipLabel>
        <relationshipName>RSM_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Number__c</fullName>
        <externalId>true</externalId>
        <label>Contract Number</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>RSM Contract</label>
    <nameField>
        <label>RSM Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RSM Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC Automation/src/objects/RSM_ContractDetail__c.object
<CustomObject>
    <description>The object stores the details of the contract</description>
    <fields>
        <fullName>Action_Name__c</fullName>
        <label>Action Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract_Number__c</fullName>
        <label>Contract Number</label>
        <referenceTo>RSM_Contract__c</referenceTo>
        <relationshipName>ContractNumber</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Unit_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Number</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipName>RSContractDetails</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RSM ContractDetail</label>
    <nameField>
        <label>RSM ContractDetailID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RSM ContractDetails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup on Accounts</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RSM_Add_Service_current_count__c</fullName>
        <formula>IF(INCLUDES(RSM_Additional_Services__c , &apos;Business Intelligence&apos;),1,0 )+ IF(INCLUDES(RSM_Additional_Services__c, &apos;Safety Analytics&apos;),1,0 ) + IF(INCLUDES(RSM_Additional_Services__c, &apos;Navigation&apos;),1,0 )+ IF(INCLUDES(RSM_Additional_Services__c, &apos;Speed gauge&apos;),1,0 )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RSM Add Service current count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RSM_Addition_Service_prior_count__c</fullName>
        <label>RSM Addition Service prior count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RSM_Additional_Services__c</fullName>
        <label>Additional Services</label>
        <picklist>
            <picklistValues>
                <fullName>Business Intelligence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Safety Analytics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Navigation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Speed gauge</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>RSM_Service_Level_Change__c</fullName>
        <description>Field to capture if the vehicle is Upgraded or Downgraded (The logic is calculated based on Service level and Additional Service level)</description>
        <label>RSM Service Level Change</label>
        <picklist>
            <picklistValues>
                <fullName>Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Downgrade</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RSM_Service_Level_Prior_value__c</fullName>
        <label>RSM Service Level Prior value</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RSM_Service_Level__c</fullName>
        <description>Displays Service Level of the vehicle</description>
        <label>Service Level</label>
        <picklist>
            <picklistValues>
                <fullName>Plus 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>STD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RSM_Service_level_Change_Date__c</fullName>
        <description>Field to capture the date when RSM Service level changed</description>
        <label>RSM Service level Change Date</label>
        <type>Date</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/RSMServiceLevelChangeStatus.cls
//Batch class to calculate the vehicle is Upgraded or Downgraded based on the Service level change and Additional service level
global class RSMServiceLevelChangeStatus implements Database.Batchable<SObject>{
    
    public String query;
    global Database.QueryLocator start(Database.BatchableContext BC){
          return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<RSM_ContractDetail__c> scope){
        
        Map<id,Vehicle__c> updateVehicleMap=new Map<id,Vehicle__c>();
        boolean clearVal = false;
             
        for(RSM_ContractDetail__c cd:scope){
        
            clearVal = false;
        
            if(cd.Action_Name__c != 'Cancel'){

                if(cd.Unit_Number__r.Account__c == cd.Contract_Number__r.Account__c){
    
                    if(cd.Unit_Number__r.RSM_Service_Level_Prior_value__c!=null && cd.Unit_Number__r.RSM_Service_Level__c!=cd.Unit_Number__r.RSM_Service_Level_Prior_value__c){
    
                        if(cd.Unit_Number__r.RSM_Service_Level__c=='Plus 1' && cd.Unit_Number__r.RSM_Service_Level_Prior_value__c=='Plus'){
    
                            Vehicle__c v = new Vehicle__c(Id=cd.Unit_Number__r.id,RSM_Service_Level_Change__c='Upgrade',RSM_Service_level_Change_Date__c=System.today());
                            updateVehicleMap.put(cd.Unit_Number__r.id,v);       
                            
                        }else if(cd.Unit_Number__r.RSM_Service_Level__c=='Plus 1' && cd.Unit_Number__r.RSM_Service_Level_Prior_value__c=='STD'){
    
                            Vehicle__c v = new Vehicle__c(Id=cd.Unit_Number__r.id,RSM_Service_Level_Change__c='Upgrade',RSM_Service_level_Change_Date__c=System.today());
                            updateVehicleMap.put(cd.Unit_Number__r.id,v);
                            
                        }else if(cd.Unit_Number__r.RSM_Service_Level__c=='Plus' && cd.Unit_Number__r.RSM_Service_Level_Prior_value__c=='STD'){
    
                            Vehicle__c v = new Vehicle__c(Id=cd.Unit_Number__r.id,RSM_Service_Level_Change__c='Upgrade',RSM_Service_level_Change_Date__c=System.today());
                            updateVehicleMap.put(cd.Unit_Number__r.id,v);
                            
                        }else if(cd.Unit_Number__r.RSM_Service_Level__c=='Plus' && cd.Unit_Number__r.RSM_Service_Level_Prior_value__c=='Plus 1'){
    
                            Vehicle__c v = new Vehicle__c(Id=cd.Unit_Number__r.id,RSM_Service_Level_Change__c='Downgrade',RSM_Service_level_Change_Date__c=System.today());
                            updateVehicleMap.put(cd.Unit_Number__r.id,v);
                            
                        }else if(cd.Unit_Number__r.RSM_Service_Level__c=='STD' && cd.Unit_Number__r.RSM_Service_Level_Prior_value__c=='Plus'){
    
                            Vehicle__c v = new Vehicle__c(Id=cd.Unit_Number__r.id,RSM_Service_Level_Change__c='Downgrade',RSM_Service_level_Change_Date__c=System.today());
                            updateVehicleMap.put(cd.Unit_Number__r.id,v);
                            
                        } else if(cd.Unit_Number__r.RSM_Service_Level__c=='STD' && cd.Unit_Number__r.RSM_Service_Level_Prior_value__c=='Plus 1'){
    
                            Vehicle__c v = new Vehicle__c(Id=cd.Unit_Number__r.id,RSM_Service_Level_Change__c='Downgrade',RSM_Service_level_Change_Date__c=System.today());
                            updateVehicleMap.put(cd.Unit_Number__r.id,v);
                        }     
                    }
                    else if(cd.Unit_Number__r.RSM_Add_Service_current_count__c>=0 && cd.Unit_Number__r.RSM_Addition_Service_prior_count__c>=0 && cd.Unit_Number__r.RSM_Add_Service_current_count__c!=cd.Unit_Number__r.RSM_Addition_Service_prior_count__c){
    
                        if(cd.Unit_Number__r.RSM_Add_Service_current_count__c > cd.Unit_Number__r.RSM_Addition_Service_prior_count__c){
    
                            Vehicle__c v = new Vehicle__c(Id=cd.Unit_Number__r.id,RSM_Service_Level_Change__c='Upgrade',RSM_Service_level_Change_Date__c=System.today());
                            updateVehicleMap.put(cd.Unit_Number__r.id,v);                               
                        }
                        else if(cd.Unit_Number__r.RSM_Add_Service_current_count__c < cd.Unit_Number__r.RSM_Addition_Service_prior_count__c){
    
                            Vehicle__c v = new Vehicle__c(Id=cd.Unit_Number__r.id,RSM_Service_Level_Change__c='Downgrade',RSM_Service_level_Change_Date__c=System.today());
                            updateVehicleMap.put(cd.Unit_Number__r.id,v);
                        }
                    }
                }
                else
                {
                    clearVal = true;
                }
            }
            else
            {
                clearVal = true;
            }
            if (clearVal == true)
            {
                //Note: Not able to update the RSM_Add_Service_current_count__c count as it is a formula field. Either we should upload 
                Vehicle__c v = new Vehicle__c(Id=cd.Unit_Number__r.id,RSM_Additional_Services__c='',RSM_Service_Level_Change__c='',RSM_Service_level_Change_Date__c=NULL,RSM_Addition_Service_prior_count__c=0);
                updateVehicleMap.put(cd.Unit_Number__r.id,v);       
            }         
        }
        update updateVehicleMap.values();
    }
    
    global void finish(Database.BatchableContext BC){
    }
}