SFDC Automation/src/objects/RSM_Contract__c.object
<CustomObject>
    <description>Object to store RydeSmart Contract details</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to store the ID of the Account with which the Contract is related. This field will be populated from database based on the Lessee No in the contract</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>RSM Contracts</relationshipLabel>
        <relationshipName>RSM_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Number__c</fullName>
        <externalId>true</externalId>
        <label>Contract Number</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status_Name__c</fullName>
        <label>Status Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>RSM Contract</label>
    <nameField>
        <label>RSM Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RSM Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC Automation/src/objects/RSM_ContractDetail__c.object
<CustomObject>
    <description>The object stores the details of the contract</description>
    <fields>
        <fullName>Action_Name__c</fullName>
        <label>Action Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract_Number__c</fullName>
        <label>Contract Number</label>
        <referenceTo>RSM_Contract__c</referenceTo>
        <relationshipName>ContractNumber</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Current__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Current</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Service_Name__c</fullName>
        <label>Service Name</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Number</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipName>RSContractDetails</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RSM ContractDetail</label>
    <nameField>
        <label>RSM ContractDetailID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RSM ContractDetails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup on Accounts</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/RSMUpdateVehicleBatch_Test.cls
@isTest
private class RSMUpdateVehicleBatch_Test{

static testmethod void unitTest(){
    Test.startTest();
    List<Vehicle__c> vList=new List<Vehicle__c>();
    for(integer i=0;i<2;i++){
            Vehicle__c v=new Vehicle__c();
            v.Name=i+'';
            vList.add(v);
    }
    insert vList;
    
    RSM_Contract__c rCon=new RSM_Contract__c();    
    rCon.Name='12345';    
    insert rCon;
    
    RSM_ContractDetail__c rc=new RSM_ContractDetail__c();
    rc.Name='test1';
    rc.Unit_Number__c=vList[0].Id;
    rc.Contract_Number__c=rCon.Id;
    rc.Action_Name__c='Add';
    rc.Is_Current__c = true;
    insert rc;
    
    RSM_ContractDetail__c rc1=new RSM_ContractDetail__c();
    rc1.Name='test1';
    rc1.Unit_Number__c=vList[1].Id;
    rc1.Contract_Number__c=rCon.Id;
    rc1.Action_Name__c='Cancel';
    rc1.Is_Current__c = true;
    insert rc1;
    
    RSMUpdateVehicleBatch rvb=new RSMUpdateVehicleBatch();
    rvb.query='select Is_Current__c, Contract_Number__r.Account__c, Id,Unit_Number__c,'
    			+'Service_Name__c,Contract_Number__r.Status_Name__c, '
    			+'RSM_ContractDetail__c.Unit_Number__r.Account__c,Action_Name__c from RSM_ContractDetail__c';
    Database.executeBatch(rvb);
    
    Test.stopTest();

}
}