SFDC Automation/src/objects/RSM_Contract__c.object
<CustomObject>
    <description>Object to store RydeSmart Contract details</description>
    <fields>
        <fullName>Contract_Number__c</fullName>
        <externalId>true</externalId>
        <label>Contract Number</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CreatedBy__c</fullName>
        <description>To store the Created by of the Contract in the Telemetry</description>
        <label>CreatedBy</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CreatedDate__c</fullName>
        <description>To store the Created Date of the Contract in the Telemetry</description>
        <label>CreatedDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Document_Type_Name__c</fullName>
        <label>Document Type Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Lessee_Email__c</fullName>
        <label>Lessee Email</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lessee__c</fullName>
        <label>Lessee</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status_Name__c</fullName>
        <label>Status Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>RSM Contract</label>
    <nameField>
        <label>RSM Contract Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RSM Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC Automation/src/objects/RSM_ContractDetail__c.object
<CustomObject>
    <description>The object stores the details of the contract</description>
    <fields>
        <fullName>Contract_Number__c</fullName>
        <label>Contract Number</label>
        <referenceTo>RSM_Contract__c</referenceTo>
        <relationshipName>ContractNumber</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Current__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Current</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unit_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit Number</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipName>RSContractDetails</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RSM ContractDetail</label>
    <nameField>
        <label>RSM ContractDetailID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RSM ContractDetails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/RSMVehicleContract.cls
/************************************************************************************
 *  Date            Name          Description
 * --------   --------------    ----------------
 * 1/24/2014    Saad Wali Jaan    RydeSmart Contracts Data Visibility on Vehicle page        
 *************************************************************************************/

/*
* This class is defined to be a controller to the page RydeSmartContract page
*/

public with sharing class RSMVehicleContract
{
    public List<RSM_Contract__c> vehicleRelatedActiveContracts {get;set;}
    public List<RSM_ContractDetail__c> vehicleRelatedContractDetails {get;set;}
    public Vehicle__c vehicleInfo {set; get;}
    public id ContractId {set; get;}
    
    public String sortOrder {get;set;}
    public String sortField {get;set;}
    
    public ApexPages.StandardSetController stdActiveContractController {get;set;}
    
    public List<RSM_Contract__c> getPageActiveContracts()
    {
        return stdActiveContractController.getRecords();
    }
    
    public RSMVehicleContract(ApexPages.StandardController stdController) 
    {
        this.vehicleInfo = (Vehicle__c)stdController.getRecord();
        system.debug('Saad - vehicleInfo = ' + vehicleInfo); 
        init();
    }
       
    public void init()
    {
        if(vehicleInfo.Id!=null)
        {
        	vehicleRelatedContractDetails = new List<RSM_ContractDetail__c>();
            vehicleRelatedContractDetails = [select Contract_Number__c from RSM_ContractDetail__c where Unit_Number__c=: vehicleInfo.id and Is_Current__c = true limit 1];
            system.debug('Saad - vehicleRelatedContractDetails = ' + vehicleRelatedContractDetails);
            ContractId = vehicleRelatedContractDetails[0].Contract_Number__c;
            system.debug('Saad - ContractId = ' + ContractId);
        }
        searchActiveContracts();
    }
    
    public void searchActiveContracts()
    {
        vehicleRelatedActiveContracts = new List<RSM_Contract__c>();
        stdActiveContractController = new ApexPages.StandardSetController(new List<RSM_Contract__c>());
        stdActiveContractController = new ApexPages.StandardSetController(Database.getQueryLocator(
        [Select r.Contract_Number__c, r.CreatedBy__c, r.CreatedDate__c, r.Document_Type_Name__c, r.Effective_Date__c, r.Id, r.Lessee__c, r.Lessee_Email__c, r.Name, r.Status_Name__c from RSM_Contract__c r WHERE id =:ContractId order by Effective_Date__c desc]));
        stdActiveContractController.setpageSize(10);
    }
}