SFDC Automation/src/objects/RyderConfig__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Provides configuration information for Ryder</description>
    <fields>
        <fullName>ETL_Username__c</fullName>
        <label>ETL Username</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Ryder Config</label>
</CustomObject>

SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup on Accounts</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RSM_Billing_Email_Date__c</fullName>
        <description>Date when Email was sent to activate billing</description>
        <label>Billing Email Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RSM_Billing_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Billing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RSM_Device_Status__c</fullName>
        <label>Device Status</label>
        <picklist>
            <picklistValues>
                <fullName>Removed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deactivated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installed with Repairs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ordered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Device</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RSM_Health_Status__c</fullName>
        <label>Health Status</label>
        <picklist>
            <picklistValues>
                <fullName>Requires Shop Repair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Has Ticket(s) Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Reporting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No issues reported</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Device</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RSM_Request_for_Billing__c</fullName>
        <label>Request for Billing</label>
        <picklist>
            <picklistValues>
                <fullName>Send to Activate Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent to Activate Billing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/RSMInstallationFlowBatch2.cls
//Batch Class to Send Email to RSS Team when "Request for Billing=Send to Billing" in Vehicle object
//Note: should add RSS Team users to emailreceipent list
global class RSMInstallationFlowBatch2 implements Database.Batchable<SObject>{

  public String query;
  global Database.QueryLocator start(Database.BatchableContext BC){
      System.debug('query : '+query);
      return Database.getQueryLocator(query);
   }
   
   global void execute(Database.BatchableContext BC, List<Account> scope){
      List<Messaging.SingleEmailMessage> EmailList=new List<Messaging.SingleEmailMessage>();
      List<Vehicle__c> updateVehList=new List<Vehicle__c>();
      Set<Id> accountIdSet=new Set<Id>();
      for(Account acc:scope){
          accountIdSet.add(acc.Id);
      }
      String[] userIds=new String[]{};
      
      //User u=[select Id from User where userName=RyderGlobalVariables.ETLUSER];
      //User u=[select Id from User where userName=RyderConfig__c.getOrgDefaults().ETL_Username__c];
      User u=[select Id from User where userName=: RyderGlobalVariables.RyderSmart_RSS];
      String etId=[select Id from EmailTemplate where developerName='RSM_Activate_Billing'].Id;
      Set<Id> conAccId=new Set<Id>();
      for(Vehicle__c v:[select Id,Name,RSM_Device_Status__c,Account__c,RSM_Request_for_Billing__c,RSM_Health_Status__c,RSM_Billing_Status__c,RSM_Billing_Email_Date__c from vehicle__c where RSM_Request_for_Billing__c='Send to Activate Billing' and RSM_Billing_Status__c=false and Account__c  in :accountIdSet]){
          v.RSM_Request_for_Billing__c='Sent to Activate Billing';
          v.RSM_Billing_Email_Date__c=System.Today();
          updateVehList.add(v);
          conAccId.add(v.Account__c);
      }
      for(Id ac:conAccId){
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setTargetObjectId(u.Id);
        mail.setTemplateId(etId);
        mail.setBccSender(true);
        mail.setUseSignature(false);
        mail.setSaveAsActivity(false);
        mail.setWhatId(ac);
        
        EmailList.add(mail);   
        
       
      } 
      
      If (EmailList.size() > 0 && !Test.isRunningTest())
      	Messaging.sendEmail(EmailList);
     
      update updateVehList;
   }

   global void finish(Database.BatchableContext BC){
   }
}