SFDC Automation/src/objects/Sales_Territory__c.object
<CustomObject>
    <fields>
        <fullName>Sales_Territory_Code__c</fullName>
        <externalId>true</externalId>
        <label>Sales Territory Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Territory_Desc__c</fullName>
        <label>Sales Territory Desc</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Sales Territory</label>
    <nameField>
        <label>Sales Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC Automation/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Sales_Territory_Code__c</fullName>
        <label>Sales Territory Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Territory__c</fullName>
        <label>Sales Territory</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/test_insertUpdateUser.cls
@isTest
public class test_insertUpdateUser {

    static testMethod void insertUpdateUser() 
    {
    Sales_Territory__c t= new Sales_Territory__c(Sales_Territory_Desc__c='test territory',Sales_Territory_code__c='99999');
    insert t;
    user u= testutil.createUser();
    u.Sales_Territory__c='test territory';
    system.debug('User*****' + u);
    test.starttest();
    insert u;
    test.stoptest();
    }
}