SFDC Automation/src/objects/Solution_Interest_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Solutions_Interest__c</fullName>
        <label>Solutions Interest</label>
        <referenceTo>Solutions_Interest__c</referenceTo>
        <relationshipLabel>Solution Interest Details</relationshipLabel>
        <relationshipName>Solution_Interest_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Vehicle_Name__c</fullName>
        <label>Vehicle Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle_Type__c</fullName>
        <label>Vehicle Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Solution Interest Detail</label>
    <nameField>
        <label>Solution Interest Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solution Interest Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFDC Automation/src/objects/Solutions_Interest__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Id</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Solutions Interests</relationshipLabel>
        <relationshipName>Solutions_Interests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Solutions Interest</label>
    <nameField>
        <label>Solutions Interest ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solutions Interests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC Automation/src/classes/UVSAccountLatestCustomerNeedController.cls
/*************************************************************************************************
Created By:    Manisha Gupta
Date:          September 27, 2014
Description:   Get Latest Customer Need for Account(T-323089)
**************************************************************************************************/
public class UVSAccountLatestCustomerNeedController {
  public List<Solution_Interest_Detail__c> custNeed{get;set;}
  public UVSAccountLatestCustomerNeedController(ApexPages.StandardController sc){
    custNeed = new List<Solution_Interest_Detail__c>();
    Id latestContactId;
    for(Contact c : [Select Id from Contact where AccountId=:sc.getId() order by LastModifiedDate DESC LIMIT 1]){
      latestContactId = c.Id;
    }
    if(latestContactId == null){
      ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.INFO, 'No Contact exists.'));
      return;
    }
    for(Solution_Interest_Detail__c sID : [Select Id, Name, Vehicle_Name__c, Vehicle_Type__c, Solutions_Interest__r.Contact_Id__c,
                                           Solutions_Interest__c, Solutions_Interest__r.Name, Solutions_Interest__r.Contact_Id__r.Name
                                           from Solution_Interest_Detail__c
                                           where Solutions_Interest__r.Contact_Id__c = :latestContactId
                                           order by Id desc]){
      custNeed.add(sId);
    }
    system.debug('===================' + custNeed);
    if(custNeed.isEmpty()){
      ApexPages.addMessage(new Apexpages.Message(ApexPages.Severity.INFO, 'No Customer Need exists.'));
    }

  }
}