SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <fields>
        <fullName>RSM_Request_for_Billing__c</fullName>
        <label>Request for Billing</label>
        <picklist>
            <picklistValues>
                <fullName>Send to Activate Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent to Activate Billing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/RSMInstallationFlowBatch.cls
//Batchable Class to update 'Request for Billing' field in vehicle as part of Installation flow
global class RSMInstallationFlowBatch implements Database.Batchable<SObject>{
    
    public String query;
    global Database.QueryLocator start(Database.BatchableContext BC){
        System.debug('query : '+query);
        return Database.getQueryLocator(query);
    }
   
    global void execute(Database.BatchableContext BC, List<Vehicle__c> scope){
        List<Vehicle__c> vehicleList=new List<Vehicle__c>();
        Set<String> vehicleSet=new Set<String>();
      
        for(Vehicle__c veh:scope){
            veh.RSM_Request_for_Billing__c='Send to Activate Billing';
            vehicleList.add(veh);          
        } 
 
        update vehicleList;
    }

    global void finish(Database.BatchableContext BC){
    }
}