SFDC Automation/src/objects/VehicleSearchSetting__c.object
<CustomObject>
    <description>This object will host the pick list values used in the Vehicle Master Inventory Search page. This is a dummy object and no records should be created on this object. The Master Inventory Search page will use the Describe calls to load the pick list values from this object. &apos;Custom Object&apos; is used to store the pick list values instead of &apos;Custom Setting&apos; as there 20+ fields are pick lists in the Master Inventory Search and it is more convenient to house all of them in a custom object than creating 20+ custom settings.</description>
    <fields>
        <fullName>Availability__c</fullName>
        <label>Availability</label>
        <picklist>
            <picklistValues>
                <fullName>Available for Sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OS in Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sale in Process</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Body_Height__c</fullName>
        <label>Body Height</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>54</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>55</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>63</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>65</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>66</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>72</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>73</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>76</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>77</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>78</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>79</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>81</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>82</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>83</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>84</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>85</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>86</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>87</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>88</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>89</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>90</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>91</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>92</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>93</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Body_Length__c</fullName>
        <label>Body Length</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>29</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>31</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>32</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>34</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>35</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>36</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Body_Width__c</fullName>
        <label>Body Width</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>72</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>78</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>82</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>84</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>85</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>86</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>88</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>89</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>90</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>91</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>92</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>93</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>95</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>96</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>97</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>98</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>99</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>100</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>101</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>102</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <picklist>
            <picklistValues>
                <fullName>a</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SAM_Truck__c</fullName>
        <label>SAM Truck</label>
        <picklist>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>100</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>110</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>120</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>121</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>122</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>31</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>51</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>61</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>81</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>90</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Vehicle Search Setting</label>
    <nameField>
        <label>VehicleSearchSettingName</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicle Search Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFDC Automation/src/classes/VehicleUtilClass.cls
/******************************************************************************************
 *  Name    : VehicleUtilClass
 *  Purpose : Contains utility methods for vehicle.
 *  Author  : Hari Krishnan
 *  Date    : 2014-10-09
 *  Version : 1.0
 *
 *  Modification History
 *  Date  Who   Description
 *
 ********************************************************************************************/
public with sharing class VehicleUtilClass {

    /**
    * @author Hari Krishnan
    * @date 2014/10/09
    * @description This method returns a list of SAM Class.
    * @return List<SelectOption> A list of SelectOption that contains all applicable SAM Class codes.
    */
    public static List<SelectOption> getSAMClassList(boolean enableNoneOption) {
        List<SelectOption> options = new List<SelectOption>();
        if(enableNoneOption == true)
            options.add(new SelectOption('--None--', '--None--'));
        Schema.DescribeFieldResult fieldResult = VehicleSearchSetting__c.SAM_Truck__c.getDescribe();
        List<Schema.PicklistEntry> listPicklistEntry = fieldResult.getPicklistValues();
        for(Schema.PicklistEntry f : listPicklistEntry)
            options.add(new SelectOption(f.getLabel(), f.getValue()));
        return options;
    }
    
    /**
    * @author Hari Krishnan
    * @date 2014/10/09
    * @description This method returns a list of 'availability' values.
    * @return List<SelectOption> A list of SelectOption that contains all applicable 'availability' values.
    */
    public static List<SelectOption> getAvailabilityList(boolean enableNoneOption) {
        List<SelectOption> options = new List<SelectOption>();
        if(enableNoneOption == true)
            options.add(new SelectOption('--None--', '--None--'));
        Schema.DescribeFieldResult fieldResult = VehicleSearchSetting__c.Availability__c.getDescribe();
        List<Schema.PicklistEntry> listPicklistEntry = fieldResult.getPicklistValues();
        for(Schema.PicklistEntry f : listPicklistEntry)
            options.add(new SelectOption(f.getLabel(), f.getValue()));
        return options;
    }
    
    /**
    * @author Hari Krishnan
    * @date 2014/10/09
    * @description This method returns a list of body height values.
    * @return List<SelectOption> A list of SelectOption that contains all applicable body height values.
    */
    public static List<SelectOption> getBodyHeightList(boolean enableNoneOption) {
        List<SelectOption> options = new List<SelectOption>();
        if(enableNoneOption == true)
            options.add(new SelectOption('--None--', '--None--'));
        Schema.DescribeFieldResult fieldResult = VehicleSearchSetting__c.Body_Height__c.getDescribe();
        List<Schema.PicklistEntry> listPicklistEntry = fieldResult.getPicklistValues();
        for(Schema.PicklistEntry f : listPicklistEntry)
            options.add(new SelectOption(f.getLabel(), f.getValue()));
        return options;
    }
    
    /**
    * @author Hari Krishnan
    * @date 2014/10/09
    * @description This method returns a list of body length values.
    * @return List<SelectOption> A list of SelectOption that contains all applicable body length values.
    */
    public static List<SelectOption> getBodyLengthList(boolean enableNoneOption) {
        List<SelectOption> options = new List<SelectOption>();
        if(enableNoneOption == true)
            options.add(new SelectOption('--None--', '--None--'));
        Schema.DescribeFieldResult fieldResult = VehicleSearchSetting__c.Body_Length__c.getDescribe();
        List<Schema.PicklistEntry> listPicklistEntry = fieldResult.getPicklistValues();
        for(Schema.PicklistEntry f : listPicklistEntry)
            options.add(new SelectOption(f.getLabel(), f.getValue()));
        return options;
    }
    
    /**
    * @author Hari Krishnan
    * @date 2014/10/09
    * @description This method returns a list of body width values.
    * @return List<SelectOption> A list of SelectOption that contains all applicable body width values.
    */
    public static List<SelectOption> getBodyWidthList(boolean enableNoneOption) {
        List<SelectOption> options = new List<SelectOption>();
        if(enableNoneOption == true)
            options.add(new SelectOption('--None--', '--None--'));
        Schema.DescribeFieldResult fieldResult = VehicleSearchSetting__c.Body_Width__c.getDescribe();
        List<Schema.PicklistEntry> listPicklistEntry = fieldResult.getPicklistValues();
        for(Schema.PicklistEntry f : listPicklistEntry)
            options.add(new SelectOption(f.getLabel(), f.getValue()));
        return options;
    }
      
    /**
    * @author Hari Krishnan
    * @date 2014/10/09
    * @description This method returns a list of vehicle models.
    * @return List<SelectOption> A list of SelectOption that contains all applicable vehicle model values.
    */
    public static List<SelectOption> getVehicleModelList(boolean enableNoneOption) {
        List<SelectOption> options = new List<SelectOption>();
        if(enableNoneOption == true)
            options.add(new SelectOption('--None--', '--None--'));
        Schema.DescribeFieldResult fieldResult = VehicleSearchSetting__c.Model__c.getDescribe();
        List<Schema.PicklistEntry> listPicklistEntry = fieldResult.getPicklistValues();
        for(Schema.PicklistEntry f : listPicklistEntry)
            options.add(new SelectOption(f.getLabel(), f.getValue()));
        return options;
    }

}