SFDC Automation/src/objects/Vehicle__c.object
<CustomObject>
    <description>Ryder Vehicles</description>
    <fields>
        <fullName>RSM_Billing_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Billing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RSM_Device_Status__c</fullName>
        <label>Device Status</label>
        <picklist>
            <picklistValues>
                <fullName>Removed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deactivated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installed with Repairs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ordered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Device</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RSM_Health_Status__c</fullName>
        <label>Health Status</label>
        <picklist>
            <picklistValues>
                <fullName>Requires Shop Repair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Has Ticket(s) Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Reporting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No issues reported</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Device</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RSM_Request_for_Billing__c</fullName>
        <label>Request for Billing</label>
        <picklist>
            <picklistValues>
                <fullName>Send to Activate Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent to Activate Billing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <label>Unit #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

SFDC Automation/src/classes/RSMInstallationFlowBatch_Test.cls
@isTest
private class RSMInstallationFlowBatch_Test{

    static testmethod void unitTest(){
    Test.startTest();
  	RSMCreateTestData.GetCustomSettingsRecord();
    
    RSMInstallationFlowBatch rif= new RSMInstallationFlowBatch ();
    rif.query='select Id,RSM_Device_Status__c,RSM_Request_for_Billing__c,RSM_Health_Status__c,RSM_Billing_Status__c from vehicle__c where RSM_Device_Status__c=\'Installed\' and RSM_Health_Status__c=\'No issues reported\' and RSM_Billing_Status__c=false LIMIT 10'; 
    database.executebatch(rif);
    
    Test.stopTest();

}
}